package main

import (
	"fmt"
	"github.com/PHPCraftdream/HotamSpec/internal/docbundle"
	"github.com/PHPCraftdream/HotamSpec/internal/evidence"
	"github.com/PHPCraftdream/HotamSpec/internal/gate"
	"github.com/PHPCraftdream/HotamSpec/internal/generator"
	"github.com/PHPCraftdream/HotamSpec/internal/invariants"
	"github.com/PHPCraftdream/HotamSpec/internal/loader"
	"github.com/PHPCraftdream/HotamSpec/internal/localization"
	"github.com/PHPCraftdream/HotamSpec/internal/ontology"
	"github.com/PHPCraftdream/HotamSpec/internal/selfspec"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

func cmdGenSpec(args []string) error {
	// Compile-cache cleanup (gate.CleanupCompileCache) is centralized in
	// main() -- reachable from every subcommand, not just this one (land,
	// init-project, and others also drive genSpec/allViolations
	// transitively). See main()'s own doc comment for why.
	fs := newFlagSet("gen-spec")
	domain := fs.String("domain", "", "domain directory (default: "+defaultDomainRel+")")
	claudeMD := fs.String("claude-md", "", "path to CLAUDE.md for rune count")
	todayFlag := fs.String("today", "", "date in YYYY-MM-DD format (default: system date) — embedded in freshness/status lines of the generated docs and root crystal; pin this for reproducible/byte-identical regeneration")
	profile := fs.String("profile", "", "output profile: consumer|full (default: resolve from the domain's manifest.json, falling back to full)")
	spec := fs.Bool("spec", false, "render the SPEC bundle (one shared test snapshot); optional for legacy/single-language domains, automatic for multilingual bundles")
	fs.Parse(args)

	// Validate --profile: only "consumer", "full", or empty (resolve from
	// manifest) are accepted. A garbage value is a usage error, not silently
	// ignored — a typo like "consmer" must not silently degrade to "full"
	// and surprise the user with ~90 files instead of ~30.
	switch *profile {
	case "", loader.GenProfileConsumer, loader.GenProfileFull:
		// ok
	default:
		return fmt.Errorf("--profile must be %q, %q, or empty (resolve from manifest), got %q", loader.GenProfileConsumer, loader.GenProfileFull, *profile)
	}

	domainDir, err := resolveDomain(*domain)
	if err != nil {
		return err
	}
	today := *todayFlag
	if today == "" {
		today = time.Now().Format("2006-01-02")
	}
	// Resolve the effective crystal path the SAME way `hotam land` does
	// (resolveClaudeMDPath): an explicit --claude-md wins; absent that, a
	// convention-carrying project auto-writes the root crystal (active
	// domain) OR the local <domainDir>/CLAUDE.md (non-active consumer domain,
	// task A2). Wiring this into gen-spec too — not only land — closes the
	// asymmetry where `hotam gen-spec` against a consumer domain left its
	// local crystal stale unless the operator remembered --claude-md every
	// time, even though docs/gen/* was already regenerated by default.
	claudeMDPath := resolveClaudeMDPath(domainDir, *claudeMD)
	written, removed, err := genSpec(domainDir, claudeMDPath, today, *profile, *spec)
	if err != nil {
		return err
	}
	for _, p := range written {
		fmt.Println(relPathForDisplay(p))
	}
	if len(removed) > 0 {
		fmt.Printf("removed %d stale file(s):\n", len(removed))
		for _, p := range removed {
			fmt.Println(relPathForDisplay(p))
		}
	}
	return nil
}

// includeSpec (--spec) opts legacy/single-language domains into SPEC.md
// rendering. BuildSpec executes verified_by tests to record their scenario
// narrative, so the opt-in preserves their prior cost behavior. An explicitly
// multilingual domain owns a complete per-language SPEC bundle, so genSpec
// renders every locale from one collected SPEC row set.
func genSpec(domainDir, claudeMDPath, today, profile string, includeSpec bool) ([]string, []string, error) {
	var written, removed []string
	var renderErr error
	err := localization.SafeRender(func() error {
		written, removed, renderErr = genSpecStaged(domainDir, claudeMDPath, today, profile, includeSpec)
		return renderErr
	})
	if err != nil {
		return written, removed, err
	}
	return written, removed, renderErr
}

func genSpecStaged(domainDir, claudeMDPath, today, profile string, includeSpec bool) ([]string, []string, error) {
	// Profile resolution (R-gen-spec-profile): an explicit non-empty profile
	// (only cmdGenSpec's --profile flag passes one) overrides the domain's
	// manifest for THIS invocation without rewriting it. An empty profile
	// (every other caller — land, init-project, tests) resolves from the
	// domain's manifest.json gen_profile field, defaulting to "full" when
	// absent — so consumer-profile domains stay consumer on every subsequent
	// hotam land, and every pre-existing domain (no gen_profile field) keeps
	// the full output set byte-identical.
	resolvedProfile := profile
	if resolvedProfile == "" {
		resolvedProfile = loader.ResolveGenProfile(graphPathForDomain(domainDir))
	}
	consumer := resolvedProfile == loader.GenProfileConsumer

	// R-empty-content-gen-notice: a MISSING graph.json (os.IsNotExist — a
	// freshly cloned framework with no domain populated yet) is treated as an
	// empty graph, not a hard error. Every generator already handles
	// g.IsEmpty() by rendering the calm EmptyNotice into docs/gen/*.md, so the
	// missing-file case produces output identical to the empty-but-present
	// case (the two are indistinguishable to an adopter with nothing modeled
	// yet). Any OTHER read error (decode failure, permissions) still surfaces
	// as a real error via loadGraphOrEmpty.
	g, err := loadGraphForGenSpec(domainDir)
	if err != nil {
		return nil, nil, err
	}
	layout, err := docbundle.NewLayout(g.Languages, g.DefaultLanguage)
	if err != nil {
		return nil, nil, fmt.Errorf("gen-spec: output languages: %w", err)
	}
	localizedConfigured := len(g.Languages) > 0
	if layout.Multilingual() {
		// A multilingual declaration owns the full normative bundle and one
		// shared execution snapshot, so it cannot silently omit SPEC views.
		includeSpec = true
	}
	genDir := filepath.Join(domainDir, "docs", "gen")
	domainName := domainNameFromDir(domainDir)

	reportPresent := false
	if localizedConfigured {
		reportPresent, _, err = evidenceReportBundleState(genDir)
		if err != nil {
			return nil, nil, fmt.Errorf("gen-spec: inspect evidence report bundle: %w", err)
		}
	}
	refreshReportViews := localizedConfigured && reportPresent
	shareEvidenceSnapshot := refreshReportViews || invariants.ConformanceAuditRequired(g)
	needExecutionSnapshot := g.SelfExecutingAtoms || shareEvidenceSnapshot
	var atomSnapshot *gate.AtomExecutionSnapshot
	if needExecutionSnapshot {
		g, atomSnapshot, err = invariants.InvocationExecutionSnapshot(g)
		if err != nil {
			return nil, nil, fmt.Errorf("gen-spec: collect one atom execution snapshot: %w", err)
		}
	}
	if g.SelfExecutingAtoms && len(g.Requirements) > 0 {
		overrides, err := atomOverrides(g, domainDir)
		if err != nil {
			return nil, nil, fmt.Errorf("gen-spec: atom registry: %w", err)
		}
		discovered, err := selfspec.DiscoverAtomsFromSnapshot(gate.SpecRootForGraph(g), g.DomainDir, overrides, atomSnapshot)
		if err != nil {
			return nil, nil, fmt.Errorf("gen-spec: discover atoms: %w", err)
		}
		for _, req := range g.Requirements {
			if req.Status == ontology.StatusREJECTED || !requiresAtomDiscovered(req, g.SelfExecutingAtomPackages) {
				continue
			}
			if _, ok := discovered.Get(req.ID); !ok {
				return nil, nil, fmt.Errorf("gen-spec: atom %s vanished; run sync-domain to resolve lifecycle changes", req.ID)
			}
		}
		// Self-hosting mirrors sync-self's projection (SyncGraph: appends
		// atom-derived requirements the on-disk graph does not have yet);
		// consumer domains keep the mirror-only merge.
		if g.SelfHosting {
			if _, err := selfspec.SyncGraph(g, discovered, today); err != nil {
				return nil, nil, fmt.Errorf("gen-spec: merge atoms: %w", err)
			}
		} else if err := selfspec.MergeIntoGraph(g, discovered); err != nil {
			return nil, nil, fmt.Errorf("gen-spec: merge atoms: %w", err)
		}
	}
	if g.SelfExecutingAtoms {
		if err := loader.ValidateGraph(g); err != nil {
			return nil, nil, fmt.Errorf("gen-spec: validate projected graph: %w", err)
		}
	}

	var evidenceSnapshot evidence.Report
	var activeViolations []invariants.Violation
	if shareEvidenceSnapshot {
		activeViolations, evidenceSnapshot, err = invariants.PriorToPostProcessViolationsForPublicationWithEvidence(g, includeSpec)
		if err != nil {
			return nil, nil, fmt.Errorf("gen-spec: collect shared evidence snapshot: %w", err)
		}
		if (reportPresent || includeSpec) && evidenceSnapshot.SchemaVersion <= 0 {
			return nil, nil, fmt.Errorf("gen-spec: evidence collector returned no valid report schema (schema_version=%d)", evidenceSnapshot.SchemaVersion)
		}
	} else {
		activeViolations = invariants.PriorToPostProcessViolationsForPublication(g, includeSpec)
	}

	// Resident-crystal char count (CRYSTAL_CHARS budget measure,
	// R-context-budget-rule): a fixpoint computed at generation time, NOT a
	// read of a stale pre-existing CLAUDE.md. The crystal's LIVE-STATE block
	// embeds its own rune count, so the measurement must converge
	// (render→measure→re-render until the embedded number stops changing);
	// the converged value feeds BOTH the root crystal (CLAUDE.md/AGENTS.md/
	// GEMINI.md) AND docs/gen/AGENT-CONTEXT.md + live-state.md, which carry
	// the same LIVE-STATE block via BuildLiveState. The --claude-md flag
	// below gates only whether the root crystal is written to disk, not
	// whether the measurement is computed — so a gen-spec run WITHOUT
	// --claude-md still embeds the correct fixpoint count into AGENT-CONTEXT.md
	// (closing the former mode-dependent "0 chars" disagreement).
	repoRoot := repoRootForDomain(domainDir)
	// projectFrameworkDir (task #357): GLOSSARY.md and tools/*.md are PROJECT-
	// shared — a single framework/ directory at the repository root (sibling of
	// domains/), byte-identical regardless of which domain's gen-spec
	// regenerated it. Every domain writes the same bytes to the same paths
	// (idempotent overwrite), so a multi-domain project carries exactly ONE
	// copy of this engine self-documentation.
	projectFrameworkDir := filepath.Join(repoRoot, "framework")
	// domainFrameworkDir: the OLD per-domain framework/ directory (task #355's
	// layout, now retired by #357). Kept only as the cleanup target — every
	// generator-owned file that #355 wrote here has moved (FRAMEWORK-
	// INVARIANTS.md back to docs/gen/, tools/*.md up to projectFrameworkDir),
	// so cleanupStaleDomainFrameworkDir removes the lot and prunes the empty dir.
	domainFrameworkDir := filepath.Join(domainDir, "framework")
	domainGraphs := map[string]*ontology.Graph{domainName: g}

	// activeViolations/activeOverride/charCount are computed LATER in this
	// function (right before live-state.md/AGENT-CONTEXT.md/the crystal are
	// rendered), NOT here at the top — see that later computation's own doc
	// comment for why: a real ordering bug (found while implementing
	// check_domain_claude_md_current, E4) meant computing them here, before
	// SPEC.md (and every other doc) is actually written to disk, embedded a
	// STALE violation snapshot into LIVE-STATE -- e.g. check_spec_md_current
	// correctly reporting "SPEC.md does not exist" because, at THIS point in
	// the function, it genuinely does not exist yet even on a `--spec` run
	// that is about to create it moments later in the SAME genSpec call. A
	// separate, independent `hotam all-violations` process running
	// immediately afterward would then see SPEC.md already on disk and
	// disagree with the just-written CLAUDE.md, producing a permanent,
	// non-regenerable check_domain_claude_md_current false positive
	// (observed directly via TestExternal_InitProjectBornObligated, whose
	// `hotam init-project` + `hotam all-violations` two-subprocess sequence
	// caught exactly this gap).

	var written []string

	type docEntry struct {
		filename string
		content  string
	}

	decisionsWritten := generator.DecisionsMDHasContent(g)
	entitiesWritten := generator.EntitiesMDHasContent(g)
	tensionsWritten := generator.TensionsMDHasContent(g)
	pipelineWritten := generator.PipelineMDHasContent(g)
	modelsWritten := generator.ModelsMDHasContent(g)
	// requirementsWritten..graphJSONWritten (task #364): the remaining
	// docs/gen/*.md projections that used to be written UNCONDITIONALLY, now
	// gated the SAME way DECISIONS/ENTITIES/TENSIONS/PIPELINE/MODELS already
	// are — withheld entirely when the domain graph is genuinely empty (0
	// axes/stakeholders/requirements/conflicts/assumptions/operators/
	// processes/goals/entity_types/entities), so a freshly-scaffolded,
	// unmodeled domain now produces ZERO files under docs/gen/ instead of a
	// directory full of calm-but-empty placeholders. See each
	// generator.XxxMDHasContent's own doc comment (internal/generator) for
	// why the predicate is graph-emptiness: every one of these files'
	// EmptyNotice fallback is keyed off the SAME g.IsEmpty() check already.
	requirementsWritten := generator.RequirementsMDWritten(g, consumer)
	openWritten := generator.OpenMDHasContent(g)
	unenforcedWritten := generator.UnenforcedMDHasContent(g)
	frameworkInvariantsWritten := generator.FrameworkInvariantsMDHasContent(g)
	historyWritten := generator.HistoryMDHasContent(g)
	constitutionWritten := generator.ConstitutionMDHasContent(g)
	traceabilityWritten := generator.TraceabilityMDHasContent(g)
	coverageWritten := generator.CoverageMDHasContent(g)
	repoMapWritten := generator.RepoMapMDHasContent(g)
	agentContextWritten := generator.AgentContextMDHasContent(g)
	liveStateWritten := generator.LiveStateMDHasContent(g)
	graphJSONWritten := generator.GraphJSONHasContent(g)
	if consumer {
		// Lightweight consumer profile: HISTORY/OPEN/UNENFORCED only with
		// their own data; engine self-documentation and derived indexes are
		// not written (`gen-spec --profile full` renders them one-shot).
		openWritten = openWritten && generator.ConsumerOpenMDHasContent(g)
		unenforcedWritten = unenforcedWritten && generator.ConsumerUnenforcedMDHasContent(g)
		modelsWritten = modelsWritten && !g.IsEmpty()
		historyWritten = historyWritten && generator.ConsumerHistoryMDHasContent(g)
		frameworkInvariantsWritten = false
		constitutionWritten = false
		traceabilityWritten = false
		coverageWritten = false
		repoMapWritten = false
		agentContextWritten = false
		liveStateWritten = false
		graphJSONWritten = false
	}

	// requirementsMD..coverageMD hold the rendered content for the 8
	// previously-unconditional top-level docs/gen/ projections
	// (REQUIREMENTS/OPEN/UNENFORCED/FRAMEWORK-INVARIANTS/HISTORY/
	// CONSTITUTION/TRACEABILITY/COVERAGE.md), computed ONLY when their own
	// *MDHasContent(g) predicate above is true. Both repoMapDocs (REPO-MAP.md's
	// own "Generated docs" listing, via fullRepoMapDocs below) and mdDocs (the
	// actual docs/gen/ write set, below) read from these SAME named variables
	// — no positional indexing into a shared slice, which broke once each
	// entry's PRESENCE, not just its content, became conditional.
	var requirementsMD, openMD, unenforcedMD, frameworkInvariantsMD, historyMD, constitutionMD, traceabilityMD, coverageMD string
	if requirementsWritten {
		requirementsMD = generator.BuildRequirements(g, domainName, consumer)
	}
	if openWritten {
		openMD = generator.BuildOpen(g)
	}
	if unenforcedWritten {
		unenforcedMD = generator.BuildUnenforced(g)
	}
	if frameworkInvariantsWritten {
		// FRAMEWORK-INVARIANTS.md is a PER-DOMAIN projection (which framework-
		// plumbing SETTLED atoms THIS domain carries) — it grows with the
		// domain's own content, exactly like REQUIREMENTS.md. Task #357
		// returned it to docs/gen/ (where it lived before #355's short-lived
		// relocation).
		frameworkInvariantsMD = generator.BuildFrameworkInvariants(g, domainName)
	}
	if historyWritten {
		historyMD = generator.BuildHistory(g)
	}
	if constitutionWritten {
		constitutionMD = generator.BuildConstitution(g, domainName, consumer)
	}
	if traceabilityWritten {
		traceabilityMD = generator.BuildTraceability(g)
	}
	if coverageWritten {
		coverageMD = generator.BuildCoverage(g)
	}

	// repoMapDocs is the CONDITIONAL set of docs written into
	// domains/<name>/docs/gen/ (REQUIREMENTS/OPEN/UNENFORCED/
	// FRAMEWORK-INVARIANTS/HISTORY/CONSTITUTION/TRACEABILITY/COVERAGE.md) —
	// task #364 extended the SAME conditional-write pattern
	// TENSIONS/PIPELINE/MODELS/DECISIONS/ENTITIES already used to this
	// remaining, previously-unconditional set: each entry is appended only
	// when its own *MDHasContent(g) predicate is true, in the SAME declared
	// order the old fixed literal used.
	// promoted it (and tools/*.md) to the PROJECT-root framework/ directory
	// (frameworkDocs below) — engine self-documentation that is byte-identical
	// for every domain, kept out of the per-domain business-projection tree.
	// FRAMEWORK-INVARIANTS.md, by contrast, IS here — it is per-domain (which
	// plumbing atoms THIS domain carries), so it stays in docs/gen/. REPO-MAP.md's
	// own "Generated docs" section lists exactly this docs/gen/ set, and a
	// separate "Framework reference (project-shared)" section lists framework/ —
	// it deliberately excludes atoms-*.md and live-state.md, which are only
	// ever materialized at the repo-root docs/methodology/atoms/ (and inside
	// root CLAUDE.md's LIVE-STATE block) for the single active domain, never
	// per-domain under docs/gen/. REPO-MAP.md's own "Generated docs" section
	// must list exactly this set to stay byte-identical, even though
	// atoms-*.md/live-state.md are additionally written alongside them on
	// disk (see mdDocs below).
	// SPEC rows are projected from the one gate.AtomExecutionSnapshot collected
	// above for discovery, explicit conformance/reporting, or --spec. Every
	// locale consumes these same rows; languages never rerun a test package.
	var specRows map[string]gate.SpecRow
	if includeSpec {
		if shareEvidenceSnapshot {
			specRows = evidenceSnapshot.SpecRows
		} else if atomSnapshot != nil {
			specRows = gate.CollectSpecRowsFromSnapshot(g, atomSnapshot)
		} else {
			specRows = gate.CollectSpecRows(g)
		}
	}

	// gateOrder (task #331, R4-process-why): the domain's declared
	// gate_stage_order, threaded into BuildPipeline so PIPELINE.md's
	// generated "Live state" section can render a live SIGNED/DEFERRED
	// tally per stage — the SAME resolver DOMAIN-MAP's sibling-pulse gate
	// line already consults (see internal/generator/claudemd.go). nil for a
	// domain that has not declared gate_stage_order (hotam-spec-self,
	// hotam-dev) is the honest no-op BuildPipeline already handles.
	gateOrder := loader.ResolveGateStageOrder(graphPathForDomain(domainDir))

	// glossaryMD is PROJECT-shared (task #357): the methodology controlled
	// vocabulary, byte-identical for every domain. Written to the repo-root
	// framework/ directory and listed under REPO-MAP.md's "Framework reference
	// (project-shared)" section (frameworkDocs below).
	var glossaryMD string
	var frameworkDocs []generator.GenDocEntry
	if !consumer {
		glossaryMD = generator.BuildGlossary(g, consumer)
		frameworkDocs = []generator.GenDocEntry{
			{Filename: "GLOSSARY.md", Content: glossaryMD},
		}
	}
	var repoMapDocs []generator.GenDocEntry
	if requirementsWritten {
		repoMapDocs = append(repoMapDocs, generator.GenDocEntry{Filename: "REQUIREMENTS.md", Content: requirementsMD})
	}
	if openWritten {
		repoMapDocs = append(repoMapDocs, generator.GenDocEntry{Filename: "OPEN.md", Content: openMD})
	}
	if unenforcedWritten {
		repoMapDocs = append(repoMapDocs, generator.GenDocEntry{Filename: "UNENFORCED.md", Content: unenforcedMD})
	}
	if frameworkInvariantsWritten {
		repoMapDocs = append(repoMapDocs, generator.GenDocEntry{Filename: "FRAMEWORK-INVARIANTS.md", Content: frameworkInvariantsMD})
	}
	if historyWritten {
		repoMapDocs = append(repoMapDocs, generator.GenDocEntry{Filename: "HISTORY.md", Content: historyMD})
	}
	if constitutionWritten {
		repoMapDocs = append(repoMapDocs, generator.GenDocEntry{Filename: "CONSTITUTION.md", Content: constitutionMD})
	}
	if traceabilityWritten {
		repoMapDocs = append(repoMapDocs, generator.GenDocEntry{Filename: "TRACEABILITY.md", Content: traceabilityMD})
	}
	if coverageWritten {
		repoMapDocs = append(repoMapDocs, generator.GenDocEntry{Filename: "COVERAGE.md", Content: coverageMD})
	}
	// SPEC.md (BuildSpec, W1.3) is the one docs/gen/ projection that EXECUTES
	// real `go test` subprocesses (one per verified_by entry) rather than
	// reading the graph/filesystem alone — see includeSpec's own doc comment
	// above. Appended conditionally, at the end, so every existing index into
	// repoMapDocs/mdDocs by position (below) stays valid whether or not it is
	// present, and every caller that does not request SPEC.md never
	// pays this cost or sees SPEC.md in its written/removed lists.
	specDocs := map[string]string{}
	var specNames []string
	if includeSpec {
		specDocs, err = gate.BuildSpecDocumentsFromRows(g, specRows)
		if err != nil {
			return nil, nil, fmt.Errorf("gen-spec: render SPEC bundle: %w", err)
		}
		if err := validateSpecOutputTargets(genDir, specDocs); err != nil {
			return nil, nil, fmt.Errorf("gen-spec: refusing SPEC output collision: %w", err)
		}
	}
	if includeSpec {
		for name := range specDocs {
			specNames = append(specNames, name)
		}
		sort.Strings(specNames)
		for _, name := range specNames {
			repoMapDocs = append(repoMapDocs, generator.GenDocEntry{Filename: name, Content: specDocs[name]})
		}
	}
	// REPO-MAP.md lists itself too (the repo-map scan globs docs/gen/*.md
	// including the file it is about to (re)write); its own title is fixed by
	// the H1 line BuildRepoMap always emits, so a placeholder with just that
	// heading is enough for mdTitle() to extract "Repository file index".
	// Only appended when REPO-MAP.md itself will actually be written this run
	// (repoMapWritten, task #364) — an empty domain that withholds every
	// OTHER doc must not list itself as a phantom "Generated doc" either.
	fullRepoMapDocs := append([]generator.GenDocEntry{}, repoMapDocs...)
	if repoMapWritten {
		fullRepoMapDocs = append(fullRepoMapDocs, generator.GenDocEntry{Filename: "REPO-MAP.md", Content: "# REPO-MAP.md — Repository file index (Hotam-Spec)"})
	}
	// SPEC.md acknowledgment on a plain run (mode-independence fix,
	// continuing task #317): when this run did NOT render SPEC.md
	// (!includeSpec), but a SPEC.md already exists on disk from a prior
	// `--spec` run, REPO-MAP.md must still list it — cleanupStaleGenFiles's
	// exemptFromCleanup below already guarantees a plain run never DELETES
	// an existing SPEC.md (see that call's own doc comment), so REPO-MAP.md
	// omitting its bullet would be a stale, self-contradictory listing
	// (files on disk that REPO-MAP.md's own "Generated docs" section does
	// not mention). Reading the real on-disk content (rather than a
	// placeholder) lets mdTitle() extract SPEC.md's actual H1 exactly like
	// every other entry — this ONLY feeds fullRepoMapDocs (REPO-MAP.md's
	// own listing); it is deliberately never added to repoMapDocs/mdDocs,
	// so a plain run never rewrites SPEC.md's own content, only
	// acknowledges its presence. A missing or unreadable file is silently
	// skipped (nothing to acknowledge — the honest "not written yet" case
	// every fresh domain starts in).
	if !includeSpec {
		if existing, err := os.ReadFile(filepath.Join(genDir, "SPEC.md")); err == nil {
			fullRepoMapDocs = append(fullRepoMapDocs, generator.GenDocEntry{Filename: "SPEC.md", Content: string(existing)})
		}
	}
	var decisionsMD, entitiesMD, tensionsMD, pipelineMD, modelsMD string
	if decisionsWritten {
		decisionsMD = generator.BuildDecisions(g)
		fullRepoMapDocs = append(fullRepoMapDocs, generator.GenDocEntry{Filename: "DECISIONS.md", Content: decisionsMD})
	}
	if entitiesWritten {
		entitiesMD = generator.BuildEntities(g, domainName)
		fullRepoMapDocs = append(fullRepoMapDocs, generator.GenDocEntry{Filename: "ENTITIES.md", Content: entitiesMD})
	}
	if tensionsWritten {
		tensionsMD = generator.BuildTensions(g)
		fullRepoMapDocs = append(fullRepoMapDocs, generator.GenDocEntry{Filename: "TENSIONS.md", Content: tensionsMD})
	}
	if pipelineWritten {
		pipelineMD = generator.BuildPipeline(g, domainName, gateOrder)
		fullRepoMapDocs = append(fullRepoMapDocs, generator.GenDocEntry{Filename: "PIPELINE.md", Content: pipelineMD})
	}
	if modelsWritten {
		modelsMD = generator.BuildModels(g)
		fullRepoMapDocs = append(fullRepoMapDocs, generator.GenDocEntry{Filename: "MODELS.md", Content: modelsMD})
	}
	// BuildRepoMap is only ever CALLED when repoMapWritten (task #364) — a
	// fully-empty graph withholds REPO-MAP.md itself (see mdDocs below), so
	// there is no reason to render a string nothing will ever write.
	var repoMapMD string
	if repoMapWritten {
		repoMapMD = generator.BuildRepoMap(g, domainName, fullRepoMapDocs, frameworkDocs, decisionsWritten, entitiesWritten, tensionsWritten, pipelineWritten, modelsWritten, consumer)
	}

	// Atoms docs: under the consumer profile, each of the four atoms-*.md
	// files is rendered first (unchanged Build* behavior), then WRITTEN only
	// if it carries real content — i.e. NOT the empty-notice case. An external
	// business domain's own requirements (e.g. R-invoice-approval-flow) will
	// essentially never match the framework-internal prefixes the four
	// selectSettled filters use (R-operator-*, R-claude-md-*, R-anchor-*,
	// R-check-*, …), so all four render the SAME calm empty notice for virtually
	// every external consumer domain — genuinely empty, pure noise. This is a
	// WRITE-time filter in genSpec; BuildAtomsOperator/etc.'s rendering is
	// unchanged. The emptyNotice marker is read from renderAtoms's exact
	// literal (internal/generator/atoms.go) so a future drift in that string
	// stays in sync.
	const emptyAtomsNotice = "_No atomic requirements in this topic yet._"
	atomsOperator := generator.BuildAtomsOperator(g)
	atomsSubstrate := generator.BuildAtomsSubstrate(g)
	atomsDiscipline := generator.BuildAtomsDiscipline(g)
	atomsCheck := generator.BuildAtomsCheck(g)
	shouldWriteAtoms := func(content string) bool {
		return !consumer || !strings.Contains(content, emptyAtomsNotice)
	}

	// mdDocs (task #364): each of the 8 previously-fixed top-level entries,
	// plus REPO-MAP.md, is now conditional on its own *Written flag computed
	// above — reading from the SAME named *MD variables repoMapDocs/
	// fullRepoMapDocs used, rather than indexing into repoMapDocs by fixed
	// position (which is no longer valid once every entry's PRESENCE, not
	// just its content, varies with domain emptiness).
	var mdDocs []docEntry
	if requirementsWritten {
		mdDocs = append(mdDocs, docEntry{"REQUIREMENTS.md", requirementsMD})
	}
	if openWritten {
		mdDocs = append(mdDocs, docEntry{"OPEN.md", openMD})
	}
	if unenforcedWritten {
		mdDocs = append(mdDocs, docEntry{"UNENFORCED.md", unenforcedMD})
	}
	if frameworkInvariantsWritten {
		mdDocs = append(mdDocs, docEntry{"FRAMEWORK-INVARIANTS.md", frameworkInvariantsMD})
	}
	if historyWritten {
		mdDocs = append(mdDocs, docEntry{"HISTORY.md", historyMD})
	}
	if constitutionWritten {
		mdDocs = append(mdDocs, docEntry{"CONSTITUTION.md", constitutionMD})
	}
	if traceabilityWritten {
		mdDocs = append(mdDocs, docEntry{"TRACEABILITY.md", traceabilityMD})
	}
	if coverageWritten {
		mdDocs = append(mdDocs, docEntry{"COVERAGE.md", coverageMD})
	}
	if repoMapWritten {
		mdDocs = append(mdDocs, docEntry{"REPO-MAP.md", repoMapMD})
	}
	if includeSpec {
		for _, name := range specNames {
			mdDocs = append(mdDocs, docEntry{name, specDocs[name]})
		}
	}
	if shouldWriteAtoms(atomsOperator) {
		mdDocs = append(mdDocs, docEntry{"atoms-operator.md", atomsOperator})
	}
	if shouldWriteAtoms(atomsSubstrate) {
		mdDocs = append(mdDocs, docEntry{"atoms-substrate.md", atomsSubstrate})
	}
	if shouldWriteAtoms(atomsDiscipline) {
		mdDocs = append(mdDocs, docEntry{"atoms-discipline.md", atomsDiscipline})
	}
	if shouldWriteAtoms(atomsCheck) {
		mdDocs = append(mdDocs, docEntry{"atoms-check.md", atomsCheck})
	}
	// live-state.md and AGENT-CONTEXT.md are BOTH rendered from the SAME
	// phase-one publication snapshot (activeViolations). AGENT-CONTEXT must
	// not self-compute invariants.AllViolations at render time: the full set
	// includes disk-projection checks evaluated against the STALE pre-write
	// disk, and the staged bundle's publication below makes those signals
	// false in the same run — embedding them would leave STRUCTURE signals in
	// the written file that the run itself has already invalidated (review
	// finding P3-11).
	if decisionsWritten {
		mdDocs = append(mdDocs, docEntry{"DECISIONS.md", decisionsMD})
	}
	if entitiesWritten {
		mdDocs = append(mdDocs, docEntry{"ENTITIES.md", entitiesMD})
	}
	if tensionsWritten {
		mdDocs = append(mdDocs, docEntry{"TENSIONS.md", tensionsMD})
	}
	if pipelineWritten {
		mdDocs = append(mdDocs, docEntry{"PIPELINE.md", pipelineMD})
	}
	if modelsWritten {
		mdDocs = append(mdDocs, docEntry{"MODELS.md", modelsMD})
	}
	// ENGINE-VERSION.md (task #400, W2.3): engine identity fingerprint —
	// always written (unconditional, not content-gated) because every domain
	// has an engine fingerprint regardless of graph content. Content depends
	// only on the engine's own source packages (internal/generator,
	// internal/ontology, internal/loader), not the domain graph at all — it
	// is engine metadata, not a graph-derived projection. NOT added to
	// repoMapDocs/fullRepoMapDocs (REPO-MAP.md lists graph-derived docs, and
	// this file is not one), and NOT gated by any *MDHasContent predicate.
	// If the fingerprint cannot be computed (the three engine packages are
	// absent from the resolved module root — e.g. a temp/test domain created
	// in os.TempDir() by an e2e test, or a consumer repo whose engine is a
	// compiled binary without source), the write is SKIPPED silently: a
	// domain without engine source has no meaningful fingerprint to stamp,
	// and the freshness check (check_engine_docs_fingerprint_current)
	// degrades to an honest no-op for the identical reason, mirroring
	// check_spec_md_current's own honest-no-op-when-absent shape.
	engineVersionMD, engineVersionErr := generator.BuildEngineVersionMD(repoRoot)
	if engineVersionErr == nil {
		mdDocs = append(mdDocs, docEntry{"ENGINE-VERSION.md", engineVersionMD})
	}

	if localizedConfigured {
		// The localized renderer owns every human-readable projection for an
		// explicitly configured language set; never also publish the legacy
		// unsuffixed view set.
		mdDocs = nil
	}
	mdPaths := make([]string, len(mdDocs))
	mdContents := make([][]byte, len(mdDocs))
	for i, d := range mdDocs {
		mdPaths[i] = filepath.Join(genDir, d.filename)
		mdContents[i] = []byte(d.content)
	}

	var stagedPaths []string
	var stagedContents [][]byte
	stagedSet := make(map[string]bool)
	addStagedFiles := func(paths []string, contents [][]byte) error {
		if len(paths) != len(contents) {
			return fmt.Errorf("generated bundle has %d paths but %d contents", len(paths), len(contents))
		}
		for i, path := range paths {
			clean := filepath.Clean(path)
			if stagedSet[clean] {
				return fmt.Errorf("generated bundle contains duplicate output path %s", clean)
			}
			stagedSet[clean] = true
			stagedPaths = append(stagedPaths, clean)
			stagedContents = append(stagedContents, contents[i])
		}
		return nil
	}
	if err := addStagedFiles(mdPaths, mdContents); err != nil {
		return nil, nil, err
	}
	// The phase-one violation/evidence snapshot was computed before rendering
	// and is shared by SPEC, every localized view, and the boot crystal.
	activeOverride := &generator.ViolationsOverride{For: g, Violations: activeViolations}

	// selfCrystalPath == claudeMDPath: when this genSpec run IS writing a
	// crystal (claudeMDPath != ""), that path is exactly the one
	// renderDomainMapBlockWithViolations's SELF-ENTRY SPECIAL CASE needs —
	// see that function's doc comment for the real, found-in-practice
	// os.Stat time-of-check/time-of-write race this avoids (a domain's own
	// first-ever local-crystal write would otherwise omit its own
	// DOMAIN-MAP crystal-link line, since the file does not exist YET at
	// render time, producing a non-deterministic render that disagreed with
	// a LATER re-render of the identical, unchanged graph). When
	// claudeMDPath == "" (this run is not writing a crystal at all — e.g.
	// most test/library callers), selfCrystalPath stays "" too, so every
	// DOMAIN-MAP entry falls through to the real (unaffected, correct)
	// os.Stat check, exactly as before this fix.
	charCount, err := generator.ComputeCrystalCharCountFixpointWithViolations(g, domainName, repoRoot, domainGraphs, today, consumer, activeOverride, claudeMDPath)
	if err != nil {
		return written, nil, err
	}

	if localizedConfigured {
		specDocsForRepoMap := specDocs
		if !includeSpec {
			specDocsForRepoMap = make(map[string]string)
			candidates, err := docbundle.DomainCandidates(genDir)
			if err != nil {
				return nil, nil, err
			}
			for _, path := range candidates {
				if !layout.IsSpecPath(genDir, path) {
					continue
				}
				content, err := os.ReadFile(path)
				if err != nil {
					if os.IsNotExist(err) {
						continue
					}
					return nil, nil, fmt.Errorf("read existing SPEC view %s: %w", path, err)
				}
				if !gate.IsGeneratedSpecDocument(string(content)) {
					continue
				}
				relative, err := filepath.Rel(genDir, path)
				if err != nil {
					return nil, nil, err
				}
				specDocsForRepoMap[filepath.ToSlash(relative)] = string(content)
			}
		}
		crystalPaths := make(map[string]string, len(layout.LanguagesForViews()))
		defaultLanguage := layout.DefaultLanguage
		if len(layout.Languages) == 1 && defaultLanguage == "" {
			defaultLanguage = layout.Languages[0]
		}
		for _, language := range layout.LanguagesForViews() {
			crystalPath := claudeMDPath
			if claudeMDPath != "" && layout.Multilingual() && language != defaultLanguage {
				name, err := layout.CrystalPath(language)
				if err != nil {
					return nil, nil, err
				}
				crystalPath = filepath.Join(filepath.Dir(claudeMDPath), name)
			}
			crystalPaths[language] = crystalPath
		}
		localizedDocuments, err := generator.BuildLocalizedDocumentsWithSnapshotAndCrystalPathsForProfile(g, domainName, repoRoot, today, activeViolations, specDocsForRepoMap, crystalPaths, resolvedProfile)
		if err != nil {
			return nil, nil, fmt.Errorf("gen-spec: render localized documents: %w", err)
		}
		localizedKeys := make([]string, 0, len(localizedDocuments))
		for key := range localizedDocuments {
			localizedKeys = append(localizedKeys, key)
		}
		sort.Strings(localizedKeys)
		localizedPaths := make([]string, 0, len(localizedKeys))
		localizedContents := make([][]byte, 0, len(localizedKeys))
		for _, key := range localizedKeys {
			path, err := docbundle.ResolveOutputPath(repoRoot, domainDir, key)
			if err != nil {
				return nil, nil, fmt.Errorf("gen-spec: localized output %q: %w", key, err)
			}
			language, localized := docbundle.LocalizedOutputLanguage(key)
			if !localized && !layout.Multilingual() {
				language, localized = localizedLayoutBaseLanguage(layout)
			}
			if localized {
				if err := validateLocalizedRendererTarget(path, language); err != nil {
					return nil, nil, err
				}
			}
			localizedPaths = append(localizedPaths, path)
			localizedContents = append(localizedContents, []byte(localizedDocuments[key]))
		}
		if err := addStagedFiles(localizedPaths, localizedContents); err != nil {
			return nil, nil, err
		}
		specKeys := make([]string, 0, len(specDocs))
		for key := range specDocs {
			specKeys = append(specKeys, key)
		}
		sort.Strings(specKeys)
		specPaths := make([]string, 0, len(specKeys))
		specContents := make([][]byte, 0, len(specKeys))
		for _, key := range specKeys {
			specPaths = append(specPaths, filepath.Join(genDir, filepath.FromSlash(key)))
			specContents = append(specContents, []byte(specDocs[key]))
		}
		if err := addStagedFiles(specPaths, specContents); err != nil {
			return nil, nil, err
		}
		if reportPresent {
			reportDocuments, _, err := buildEvidenceDocuments(g, evidenceSnapshot)
			if err != nil {
				return nil, nil, fmt.Errorf("gen-spec: render localized evidence reports: %w", err)
			}
			if err := validateEvidenceDocumentTargets(domainDir, reportDocuments); err != nil {
				return nil, nil, fmt.Errorf("gen-spec: refusing evidence report collision: %w", err)
			}
			reportKeys := make([]string, 0, len(reportDocuments))
			for key := range reportDocuments {
				reportKeys = append(reportKeys, key)
			}
			sort.Strings(reportKeys)
			reportPaths := make([]string, 0, len(reportKeys))
			reportContents := make([][]byte, 0, len(reportKeys))
			for _, key := range reportKeys {
				reportPaths = append(reportPaths, filepath.Join(domainDir, filepath.FromSlash(key)))
				reportContents = append(reportContents, []byte(reportDocuments[key]))
			}
			if err := addStagedFiles(reportPaths, reportContents); err != nil {
				return nil, nil, err
			}
			machine, err := encodeEvidenceReport(evidenceSnapshot)
			if err != nil {
				return nil, nil, fmt.Errorf("gen-spec: encode evidence report: %w", err)
			}
			evidencePath := filepath.Join(genDir, "evidence.json")
			if err := addStagedFiles([]string{evidencePath}, [][]byte{machine}); err != nil {
				return nil, nil, err
			}
		}
	}

	// live-state.md/AGENT-CONTEXT.md (task #364): withheld like every other
	// docs/gen/ projection this task gates when the domain graph is
	// genuinely empty (agentContextWritten/liveStateWritten, computed
	// above). charCount/activeViolations above are STILL computed
	// unconditionally regardless of this gate — they also feed the root/
	// local crystal render below, which is written whenever claudeMDPath is
	// set, independent of domain content.
	var liveStateAndAgentContextPaths []string
	var liveStateAndAgentContextContents [][]byte
	if liveStateWritten && !localizedConfigured {
		liveStateAndAgentContextPaths = append(liveStateAndAgentContextPaths, filepath.Join(genDir, "live-state.md"))
		liveStateAndAgentContextContents = append(liveStateAndAgentContextContents, []byte(generator.BuildStandaloneLiveStateRoot(g, domainName, charCount, today, activeViolations, repoRoot)))
	}
	if agentContextWritten && !localizedConfigured {
		liveStateAndAgentContextPaths = append(liveStateAndAgentContextPaths, filepath.Join(genDir, "AGENT-CONTEXT.md"))
		liveStateAndAgentContextContents = append(liveStateAndAgentContextContents, []byte(generator.BuildAgentContextRootWithViolations(g, domainName, charCount, today, consumer, activeViolations, repoRoot)))
	}
	if err := addStagedFiles(liveStateAndAgentContextPaths, liveStateAndAgentContextContents); err != nil {
		return nil, nil, err
	}

	// graph.json archival copy (task #364): withheld like every other
	// docs/gen/ projection this task gates when the domain graph is
	// genuinely empty (graphJSONWritten, computed above) — BuildGraphJSON
	// itself still succeeds and would render a well-formed, empty-arrays
	// payload, but there is nothing to archive for a domain with no content.
	var graphJSON string
	if graphJSONWritten {
		graphJSON, err = generator.BuildGraphJSON(g)
		if err != nil {
			return nil, nil, fmt.Errorf("build graph.json: %w", err)
		}
		graphPath := filepath.Join(genDir, "graph.json")
		if err := addStagedFiles([]string{graphPath}, [][]byte{[]byte(graphJSON)}); err != nil {
			return nil, nil, err
		}
	}

	// framework/GLOSSARY.md (task #357): the methodology controlled vocabulary
	// is PROJECT-shared — written to the repo-root framework/ directory (single
	// copy, byte-identical across domains). Written here (after the docs/gen/
	// batch above) so it lands at projectFrameworkDir, and appended to `written`
	// so cleanupStaleProjectFrameworkFiles treats it as current rather than
	// stale. FRAMEWORK-INVARIANTS.md, by contrast, is per-domain and now writes
	// through mdDocs into docs/gen/ (where it was before task #355).
	if !consumer && !localizedConfigured {
		glossaryPath := filepath.Join(projectFrameworkDir, "GLOSSARY.md")
		if err := addStagedFiles([]string{glossaryPath}, [][]byte{[]byte(glossaryMD)}); err != nil {
			return nil, nil, err
		}
	}

	// thinking/*.md and tools/*.md: BuildThinkingDocs/BuildToolDocs return
	// maps (Go randomizes map iteration order per run), so the filenames are
	// sorted before writing/appending — this makes `written`'s order for
	// these two groups deterministic run-to-run, which the sequential
	// version never actually guaranteed either. File contents (and thus
	// byte-identity against git) are unaffected either way: only console
	// listing order is at stake here, not what lands on disk.
	//
	// Consumer profile: thinking/*.md (the full Canon/Narrative/Why prose for
	// every §-section of the METHODOLOGY ITSELF) is framework
	// self-documentation, not domain content — skipped entirely for an
	// external business consumer who just uses the tool.
	if !consumer && !localizedConfigured {
		thinkingDocs := generator.BuildThinkingDocs()
		thinkingKeys := make([]string, 0, len(thinkingDocs))
		for key := range thinkingDocs {
			thinkingKeys = append(thinkingKeys, key)
		}
		sort.Strings(thinkingKeys)
		thinkingPaths := make([]string, len(thinkingKeys))
		thinkingContents := make([][]byte, len(thinkingKeys))
		for i, key := range thinkingKeys {
			thinkingPaths[i] = filepath.Join(genDir, "thinking", key+".md")
			thinkingContents[i] = []byte(thinkingDocs[key])
		}
		if err := addStagedFiles(thinkingPaths, thinkingContents); err != nil {
			return nil, nil, err
		}
	}

	// Consumer profile: write tools/*.md pages ONLY for Implemented tools
	// (skip the 27 Planned tools whose page is entirely historical/aspirational
	// prose for a command that doesn't exist yet). tools/INDEX.md is written
	// unconditionally below regardless of profile (cheap, useful, and already
	// the recommended pointer per the crystal-trim philosophy). Task #357:
	// both land under the PROJECT-root framework/tools/ (sibling of domains/),
	// NOT docs/gen/tools/ — engine self-documentation shared across all domains,
	// byte-identical regardless of which domain regenerated it.
	if !consumer && !localizedConfigured {
		toolDocs := generator.BuildToolDocs(consumer)
		toolKeys := make([]string, 0, len(toolDocs))
		for cmd := range toolDocs {
			if consumer && !toolIsImplemented(cmd) {
				continue
			}
			toolKeys = append(toolKeys, cmd)
		}
		sort.Strings(toolKeys)
		toolPaths := make([]string, len(toolKeys))
		toolContents := make([][]byte, len(toolKeys))
		for i, cmd := range toolKeys {
			toolPaths[i] = filepath.Join(projectFrameworkDir, "tools", cmd+".md")
			toolContents[i] = []byte(toolDocs[cmd])
		}
		if err := addStagedFiles(toolPaths, toolContents); err != nil {
			return nil, nil, err
		}
		toolIndexPath := filepath.Join(projectFrameworkDir, "tools", "INDEX.md")
		if err := addStagedFiles([]string{toolIndexPath}, [][]byte{[]byte(generator.BuildToolDocsIndex(consumer))}); err != nil {
			return nil, nil, err
		}
	}

	if claudeMDPath != "" {
		defaultLanguage := layout.DefaultLanguage
		if len(layout.Languages) == 1 && defaultLanguage == "" {
			defaultLanguage = layout.Languages[0]
		}
		for _, language := range layout.LanguagesForViews() {
			view := *g
			view.RenderLanguage = language
			viewGraphs := map[string]*ontology.Graph{domainName: &view}
			viewOverride := &generator.ViolationsOverride{For: &view, Violations: activeViolations}
			crystalPath := claudeMDPath
			if localizedConfigured && language != defaultLanguage {
				name, err := layout.CrystalPath(language)
				if err != nil {
					return nil, nil, err
				}
				crystalPath = filepath.Join(filepath.Dir(claudeMDPath), name)
				if err := validateLocalizedCrystalTarget(crystalPath); err != nil {
					return nil, nil, err
				}
			}
			viewCharCount, err := generator.ComputeCrystalCharCountFixpointWithViolations(&view, domainName, repoRoot, viewGraphs, today, consumer, viewOverride, crystalPath)
			if err != nil {
				return nil, nil, err
			}
			claudeMD := generator.RenderClaudeMDFromTemplateWithViolations(&view, domainName, repoRoot, viewCharCount, viewGraphs, today, consumer, viewOverride, crystalPath)
			claudeMD += preserveDurableNotesTail(crystalPath)
			crystalBytes := []byte(claudeMD)
			crystalPaths := []string{crystalPath}
			crystalContents := [][]byte{crystalBytes}
			if !localizedConfigured || language == defaultLanguage {
				crystalDir := filepath.Dir(claudeMDPath)
				crystalPaths = append(crystalPaths, filepath.Join(crystalDir, "AGENTS.md"), filepath.Join(crystalDir, "GEMINI.md"))
				crystalContents = append(crystalContents, crystalBytes, crystalBytes)
			}
			if err := addStagedFiles(crystalPaths, crystalContents); err != nil {
				return nil, nil, err
			}
		}
	}

	// All renderers and locale validation have completed. Publish the staged
	// content through the existing fsio parallel writer. Files are staged
	// together before writes, but publication is not a multi-file transaction.
	if err := writeFilesParallel(stagedPaths, stagedContents); err != nil {
		return nil, nil, err
	}
	written = append(written, stagedPaths...)
	extraPaths, err := convergeCrystalReaders(g, domainName, domainDir, repoRoot, genDir, today, consumer, claudeMDPath, localizedConfigured, liveStateWritten, agentContextWritten, resolvedProfile, activeViolations)
	if err != nil {
		return nil, nil, err
	}
	written = append(written, extraPaths...)

	var removedCrystals []string
	var crystalDirs []string
	if claudeMDPath != "" {
		// A resolved boot path owns locale cleanup only in its sibling
		// directory; never disturb a separate project crystal.
		crystalDirs = []string{filepath.Dir(claudeMDPath)}
	} else if !crystalConventionExists(repoRoot) {
		crystalDirs = []string{repoRoot, domainDir}
	}
	seenCrystalDirs := make(map[string]bool)
	for _, directory := range crystalDirs {
		directory = filepath.Clean(directory)
		if seenCrystalDirs[directory] {
			continue
		}
		seenCrystalDirs[directory] = true
		removed, err := cleanupStaleLocalizedCrystals(directory, written)
		if err != nil {
			return written, nil, err
		}
		removedCrystals = append(removedCrystals, removed...)
	}

	// R-profile-switch-cleanup: genSpec only ever WRITES files, never
	// deletes — so switching a domain's profile from full to consumer (via
	// --profile, or a manifest gen_profile change landed through `hotam land`)
	// would leave the now-unwanted thinking/*.md and Planned-tool pages on disk
	// even though the printed written list shrank. A single cleanup pass at the
	// end removes any generator-owned file under docs/gen/ that is NOT in this
	// run's written list — correct in BOTH directions (full→consumer deletes;
	// consumer→full is a no-op since written only grows). The comparison is
	// against written, not the profile flag directly, so it stays correct for
	// any future variance in the written set (e.g. conditional DECISIONS/
	// ENTITIES), not just the profile switch.
	//
	// SPEC.md (W2.3 lifecycle fix): unlike every other top-level docs/gen/
	// projection, SPEC.md is a KNOWN, first-class projection whose
	// regeneration is gated behind --spec (includeSpec above) for cost
	// reasons alone (BuildSpecFromRows executes a real `go test` per
	// verified_by entry — see includeSpec's own doc comment) — it is never
	// an orphan just because a cheap default `gen-spec` run did not
	// regenerate it. Passing exemptFromCleanup here tells
	// cleanupStaleGenFiles to leave an existing SPEC.md alone whenever this
	// run did NOT render it (includeSpec == false), instead of treating its
	// absence from `written` as staleness the way it would for any other
	// top-level file. When includeSpec IS true, SPEC.md is already inside
	// `written` (repoMapDocs/mdDocs above), so it is never a cleanup
	// candidate in that run regardless of this exemption — the exemption
	// only matters for the includeSpec==false path, and even there it is a
	// pure "leave present file alone" rule: it never fabricates or deletes
	// content, it only stops the DEFAULT run from mistaking "not
	// regenerated this run" for "orphaned".
	var exemptFromCleanup []string
	if !includeSpec {
		candidates, err := docbundle.DomainCandidates(genDir)
		if err != nil {
			return written, nil, err
		}
		for _, path := range candidates {
			if !layout.IsSpecPath(genDir, path) {
				continue
			}
			relative, err := filepath.Rel(genDir, path)
			if err != nil {
				return written, nil, err
			}
			exemptFromCleanup = append(exemptFromCleanup, filepath.ToSlash(relative))
		}
	}
	// Evidence/finding views and their one raw JSON store are owned by
	// `hotam evidence --write`, not this graph-document generation run.
	for _, path := range docbundle.ReportCandidates(genDir) {
		relative, err := filepath.Rel(genDir, path)
		if err != nil {
			return written, nil, err
		}
		exemptFromCleanup = append(exemptFromCleanup, filepath.ToSlash(relative))
	}
	var removedSpec []string
	if includeSpec {
		err := filepath.WalkDir(filepath.Join(genDir, "spec"), func(path string, entry os.DirEntry, walkErr error) error {
			if os.IsNotExist(walkErr) {
				return nil
			}
			if walkErr != nil {
				return walkErr
			}
			if entry.IsDir() || filepath.Ext(path) != ".md" {
				return nil
			}
			rel, err := filepath.Rel(genDir, path)
			if err != nil {
				return err
			}
			if _, keep := specDocs[filepath.ToSlash(rel)]; keep {
				return nil
			}
			exists, owned, err := inspectGeneratedOutput(path, gate.IsGeneratedSpecDocument)
			if err != nil {
				return err
			}
			if !exists || !owned {
				return nil
			}
			if err := os.Remove(path); err != nil {
				return err
			}
			removedSpec = append(removedSpec, path)
			return nil
		})
		if err != nil {
			return written, removedSpec, err
		}
	}
	removedGen, err := cleanupStaleGenFiles(genDir, written, exemptFromCleanup, layout)
	if err != nil {
		return written, nil, err
	}
	// Project-root framework/ cleanup pass (task #357): symmetric to the
	// docs/gen/ pass above — deletes generator-owned files under the shared
	// project-root framework/ that are NOT in this run's written list (e.g. a
	// full→consumer profile switch drops the Planned-tool pages). The docs/gen/
	// pass above ALSO deletes stale leftovers from the pre-#357 layout
	// (docs/gen/GLOSSARY.md, docs/gen/tools/*.md): those closed-list entries are
	// no longer written to docs/gen/, so they register as stale and get removed
	// — that is the migration path from the old location to the new one.
	// Shared framework outputs are reconciled when this is the only full
	// profile owner, or when a consumer run observes that no full domain still
	// owns the directory. A sibling full domain can retain another locale set.
	var removedProjectFW []string
	cleanupProjectFW := false
	if consumer {
		cleanupProjectFW = !projectUsesFullProfile(repoRoot, true)
	} else {
		cleanupProjectFW = !projectHasOtherFullProfile(repoRoot, domainDir)
	}
	if cleanupProjectFW {
		removedProjectFW, err = cleanupStaleProjectFrameworkFiles(projectFrameworkDir, written, layout)
		if err != nil {
			return written, nil, err
		}
	}
	removedEvidence, err := cleanupStaleEvidenceLocaleViews(genDir, layout)
	if err != nil {
		return written, nil, err
	}
	var removedDomainFW []string
	if filepath.Clean(domainFrameworkDir) != filepath.Clean(projectFrameworkDir) {
		removedDomainFW, err = cleanupStaleDomainFrameworkDir(domainFrameworkDir)
		if err != nil {
			return written, nil, err
		}
	}
	removed := append(append(append(append(append(append([]string{}, removedCrystals...), removedEvidence...), removedSpec...), removedGen...), removedProjectFW...), removedDomainFW...)
	sort.Strings(removed)
	return written, removed, nil
}

// preserveDurableNotesTail reads the pre-existing file at path (if any) and
// returns whatever content sits AFTER its generator.DurableNotesMarkerLine —
// the operator's own durable notes, per the template's own promise (see that
// const's doc comment). Returns "" for every case that means "nothing to
// carry forward": the file does not exist yet, it exists but cannot be read
// (permissions, etc. — genSpec's crystal write already tolerates a from-
// scratch write in these cases, so a read failure here degrades the same
// way rather than aborting the whole gen-spec run over a best-effort
// preservation step), or it exists but carries no marker line at all (not
// template-shaped — e.g. a hand-authored file some project already had at
// that path before adopting the crystal convention; overwriting it wholesale
// on first adoption is the existing, unchanged behavior).
