package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// cmdScaffoldRegistrydump implements `hotam scaffold-registrydump --domain
// <dir>`: it writes <domainDir>/spec/registrydump/main.go, a minimal Go
// program that imports the domain's own spec/ module root package (expected
// to declare `var Requirements = hotamontology.New[hotamontology.Requirement]()`,
// mirroring internal/selfspec.Requirements' shape one-for-one — see
// R-domain-founded-in-wave-order step 6 in the root CLAUDE.md) plus the
// vendored spec/hotamontology package, and prints
// `json.Marshal(Requirements.All())` to stdout.
//
// This is the domain-side half of the module-boundary bridge `hotam
// sync-domain` (task #366) needs: sync-domain itself lives in the ENGINE's
// own Go module and can never import a consumer domain's spec/ module
// directly (NEW-2-bis — no cross-module `replace`), so it instead spawns
// `go run ./registrydump` INSIDE the domain's own spec/ module (the same
// module-boundary-crossing principle internal/gate/test_exec.go already uses
// to execute a domain's verified_by tests) and reads the JSON it prints back
// on stdout.
//
// Modeled directly on `hotam vendor-ontology` (cmd/hotam/vendor_ontology.go)
// for its two hard requirements: (1) spec/go.mod must already exist — this
// command never mints a new Go module on the caller's behalf; (2)
// spec/hotamontology/ must already be vendored (`hotam vendor-ontology` run
// first) — registrydump's own generated source imports it directly, so
// scaffolding it before the ontology mirror exists would produce a Go file
// that cannot compile. Idempotent: re-running always overwrites
// spec/registrydump/main.go unconditionally with the current template.
func cmdScaffoldRegistrydump(args []string) error {
	fs := newFlagSet("scaffold-registrydump")
	domain := fs.String("domain", "", "domain directory (default: "+defaultDomainRel+")")
	fs.Parse(args)

	domainDir, err := resolveDomain(*domain)
	if err != nil {
		return err
	}

	written, err := scaffoldRegistrydump(domainDir)
	if err != nil {
		return err
	}
	fmt.Println(relPathForDisplay(written))
	return nil
}

// scaffoldRegistrydump does the actual write and returns the path written,
// so tests can call it directly without going through flag parsing / stdout.
//
// Requires <domainDir>/spec/go.mod (the domain's own spec/ Go module must
// already exist — same hard requirement as vendorOntology/vendorRecorder)
// AND <domainDir>/spec/hotamontology/requirement.go (the vendored ontology
// mirror `hotam vendor-ontology` writes — registrydump's generated source
// imports this package by its module-relative path, so scaffolding it first
// would leave a non-compiling stub).
func scaffoldRegistrydump(domainDir string) (string, error) {
	specDir := filepath.Join(domainDir, "spec")
	specGoMod := filepath.Join(specDir, "go.mod")
	modulePath, err := readGoModModulePath(specGoMod)
	if err != nil {
		if os.IsNotExist(err) {
			return "", fmt.Errorf("scaffold-registrydump: %s does not exist -- the domain's spec/ tree must already be its own Go module (its own go.mod) before registrydump can be scaffolded into it; see PLAN-authored-spec-discipline.md §3", specGoMod)
		}
		return "", fmt.Errorf("scaffold-registrydump: %w", err)
	}

	vendoredOntology := filepath.Join(specDir, "hotamontology", "requirement.go")
	if _, err := os.Stat(vendoredOntology); err != nil {
		if os.IsNotExist(err) {
			return "", fmt.Errorf("scaffold-registrydump: %s does not exist -- run `hotam vendor-ontology --domain %s` first so registrydump's generated source has a spec/hotamontology package to import", vendoredOntology, domainDir)
		}
		return "", fmt.Errorf("scaffold-registrydump: stat %s: %w", vendoredOntology, err)
	}

	target := filepath.Join(specDir, "registrydump", "main.go")
	content := []byte(registrydumpSource(modulePath))
	if err := writeFileMkdir(target, content); err != nil {
		return "", fmt.Errorf("scaffold-registrydump: %w", err)
	}
	return target, nil
}

// registrydumpBanner is the do-not-edit banner prepended to the generated
// spec/registrydump/main.go, the same rhetorical shape as
// internal/ontology/vendor.Banner / internal/recorder/vendor.Banner applied
// to a GENERATED (not vendored-from-canon) file: hand-editing it will be
// silently discarded the next time `hotam scaffold-registrydump` runs.
const registrydumpBanner = `// Code generated by ` + "`hotam scaffold-registrydump`" + `. DO NOT EDIT.
//
// This program is the domain-side half of the module-boundary bridge
// ` + "`hotam sync-domain`" + ` uses to read this domain's own Go-authored Requirement
// registry (declared in this spec/ module's root package, conventionally
// spec/requirements.go, as ` + "`var Requirements = hotamontology.New[hotamontology.Requirement]()`" + `,
// mirroring internal/selfspec.Requirements' shape in the HotamSpec engine
// itself) without the engine ever needing a cross-module Go import into this
// domain's separate spec/ module (forbidden -- see
// internal/gate/test_exec.go's module-boundary doc comments for the
// identical constraint applied to verified_by test execution).
//
// ` + "`hotam sync-domain`" + ` spawns this program via ` + "`go run ./registrydump`" + ` inside this
// module and reads its stdout as JSON.
`

// registrydumpTemplate is the generated main.go body, minus the banner.
// {{MODULE}} is substituted with the domain's spec/ module's own declared
// module path (read from spec/go.mod) so the import statement resolves
// regardless of what name the domain author chose for their module.
const registrydumpTemplate = `package main

import (
	"encoding/json"
	"fmt"
	"os"

	spec "{{MODULE}}"
)

// main prints json.Marshal(spec.Requirements.All()) to stdout -- the exact
// []hotamontology.Requirement slice ` + "`hotam sync-domain`" + ` reads back and
// projects onto this domain's graph.json.
func main() {
	data, err := json.Marshal(spec.Requirements.All())
	if err != nil {
		fmt.Fprintf(os.Stderr, "registrydump: marshal Requirements.All(): %v\n", err)
		os.Exit(1)
	}
	os.Stdout.Write(data)
}
`

// registrydumpSource returns the full byte-for-byte content
// spec/registrydump/main.go should hold for a domain whose spec/ module's
// own go.mod declares modulePath.
func registrydumpSource(modulePath string) string {
	return registrydumpBanner + "\n" + strings.ReplaceAll(registrydumpTemplate, "{{MODULE}}", modulePath)
}

// readGoModModulePath reads the `module <path>` directive out of the go.mod
// at path, returning just <path>. Returns an os.IsNotExist-satisfying error
// when path itself does not exist (propagated to the caller unchanged so it
// can distinguish "no go.mod yet" from "go.mod exists but has no module
// directive" / other read errors).
func readGoModModulePath(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if strings.HasPrefix(line, "module ") {
			return strings.TrimSpace(strings.TrimPrefix(line, "module ")), nil
		}
	}
	if err := scanner.Err(); err != nil {
		return "", fmt.Errorf("scan %s: %w", path, err)
	}
	return "", fmt.Errorf("%s has no `module <path>` directive", path)
}
