"""Canon: §Agent — scaffolds spec/agents/<name>/ as a self-contained sub-operator directory with its own CLAUDE.md, scope.py, tools/, agents/, and README.md.

WHY: Spinning up a new sub-agent by hand is error-prone (forgotten sentinels,
wrong scope.py shape, missing __init__.py). This tool guarantees a deterministic,
gen_spec-ready scaffold from one command, keeping the operator-as-directory
pattern (`R-operator-crystal-is-claude-md`) structurally consistent across all
sub-agents.

Created files and their roles:
  CLAUDE.md   — placeholder operator crystal; carries CONSTITUTION sentinels so
                 gen_spec (task #57) can fill the CONSTITUTION block on next run.
  scope.py    — declares which R-id prefixes this agent's CONSTITUTION includes;
                 the Canon: §Agent marker makes it machine-readable.
  tools/      — private tools directory for this agent (starts empty).
  agents/     — empty subdir for recursive sub-agents (R-agent-is-recursive-director).
  README.md   — human-readable rationale; what this agent stewards and why it
                 exists as a separate operator.

R-prefer-tool-over-hand: scaffolding belongs here because the files must satisfy
exact structural contracts (sentinel placement, scope.py shape). A hand-crafted
directory will drift; this tool cannot.

Exit codes:
  0 — success (directory + files created).
  1 — failure (name invalid, directory already exists, or write error).
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

_SPEC_ROOT = Path(__file__).resolve().parents[1]
_AGENTS_ROOT = _SPEC_ROOT / "agents"

# Sentinel used in tests to override the agents root
_DEFAULT_AGENTS_ROOT = _AGENTS_ROOT

_NAME_RE = re.compile(r"^[a-z][a-z0-9-]*$")

_CLAUDE_MD_TEMPLATE = """\
# {name}

> This file is the operator crystal for the `{name}` sub-agent.
> It is a PLACEHOLDER — run `uv run python tools/gen_spec.py` to populate
> the CONSTITUTION block below from the live graph.

## Purpose

{purpose}

## Scope

This agent's CONSTITUTION block is filtered by the R-id prefixes declared
in `scope.py`. Only requirements whose id starts with one of those prefixes
are included.

<!-- CONSTITUTION:BEGIN -->
<!-- CONSTITUTION:END -->
"""

_SCOPE_PY_TEMPLATE = '''\
"""Canon: §Agent — declares the scope of agent \'{name}\'.

SCOPE is a tuple of R-id prefixes; the agent\'s CONSTITUTION block
filters g.requirements where id.startswith(any of these).

PURPOSE is a one-line machine-readable rationale used by AGENT-MAP.
"""

PURPOSE = "{purpose}"

SCOPE = {scope_tuple}
'''

_README_TEMPLATE = """\
# {name}

{purpose}

## Agent-as-directory pattern

Each sub-agent in `spec/agents/` is a self-contained operator directory
following the `R-operator-crystal-is-claude-md` convention. The directory
bundles everything the agent needs to operate without referencing the parent
operator's crystal: its own `CLAUDE.md` (the operator crystal, carrying the
CONSTITUTION block generated by `gen_spec.py`), a `scope.py` declaring which
R-id prefixes it stewards, and a `tools/` directory for private tooling.

To regenerate the CONSTITUTION block after graph changes, run:

    uv run python tools/gen_spec.py

from the `spec/` directory. The sentinels `<!-- CONSTITUTION:BEGIN -->` and
`<!-- CONSTITUTION:END -->` in `CLAUDE.md` mark where gen_spec writes.
"""


def _validate_name(name: str) -> str | None:
    """Return an error message if name is invalid, else None."""
    if not _NAME_RE.match(name):
        return (
            f"Invalid agent name '{name}'. "
            "Must be lowercase letters, digits, and hyphens only, "
            "starting with a letter (e.g. 'framework-agent')."
        )
    return None


def _build_scope_tuple(prefixes: list[str]) -> str:
    """Render a Python tuple literal from a list of prefix strings."""
    if not prefixes:
        return "()"
    items = ", ".join(f'"{p}"' for p in prefixes)
    if len(prefixes) == 1:
        return f'("{prefixes[0]}",)'
    return f"({items})"


def scaffold(
    name: str,
    scope_prefixes: list[str],
    purpose: str,
    agents_root: Path,
) -> int:
    """Create the agent directory and its four files. Returns exit code."""
    err = _validate_name(name)
    if err:
        print(f"ERROR: {err}", file=sys.stderr)
        return 1

    agent_dir = agents_root / name
    if agent_dir.exists():
        print(
            f"ERROR: '{agent_dir}' already exists. "
            "Delete it manually before re-running.",
            file=sys.stderr,
        )
        return 1

    agent_dir.mkdir(parents=True)

    # CLAUDE.md
    claude_md = _CLAUDE_MD_TEMPLATE.format(name=name, purpose=purpose)
    (agent_dir / "CLAUDE.md").write_text(claude_md, encoding="utf-8")

    # scope.py
    scope_tuple = _build_scope_tuple(scope_prefixes)
    scope_py = _SCOPE_PY_TEMPLATE.format(
        name=name, purpose=purpose, scope_tuple=scope_tuple
    )
    (agent_dir / "scope.py").write_text(scope_py, encoding="utf-8")

    # tools/__init__.py
    tools_dir = agent_dir / "tools"
    tools_dir.mkdir()
    (tools_dir / "__init__.py").write_text("", encoding="utf-8")

    # agents/ — recursive sub-agents subdir (R-agent-is-recursive-director)
    agents_subdir = agent_dir / "agents"
    agents_subdir.mkdir()
    (agents_subdir / "__init__.py").write_text("", encoding="utf-8")

    # docs/ — private notes/checkpoints for this agent (R-agent-has-docs-dir)
    docs_dir = agent_dir / "docs"
    docs_dir.mkdir()
    (docs_dir / ".gitkeep").write_text("", encoding="utf-8")

    # README.md
    readme = _README_TEMPLATE.format(name=name, purpose=purpose)
    (agent_dir / "README.md").write_text(readme, encoding="utf-8")

    print(f"Created agent scaffold at {agent_dir}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Scaffold a new sub-agent directory under spec/agents/<name>/."
    )
    parser.add_argument(
        "name",
        help="Kebab-case agent name (e.g. framework-agent). "
        "Lowercase letters, digits, hyphens only.",
    )
    parser.add_argument(
        "--scope",
        default="",
        help="Comma-separated R-id prefixes for this agent's CONSTITUTION filter "
        "(e.g. R-check-,R-bijection-). Defaults to empty.",
    )
    parser.add_argument(
        "--purpose",
        default="",
        help="One-line rationale written into scope.py, README.md and CLAUDE.md (required).",
    )
    parser.add_argument(
        "--parent",
        default=None,
        help="Path to the parent agents/ directory. "
        "If given, the new agent is created at <parent>/<name>/. "
        "Defaults to spec/agents/ (top-level).",
    )
    args = parser.parse_args(argv)

    if not args.purpose.strip():
        print(
            "ERROR: `--purpose` is required (R-agent-declares-purpose); "
            "pass a one-line rationale describing what this agent stewards",
            file=sys.stderr,
        )
        return 1

    scope_prefixes = [p.strip() for p in args.scope.split(",") if p.strip()]

    if args.parent is not None:
        agents_root = Path(args.parent)
    else:
        agents_root = _AGENTS_ROOT

    return scaffold(
        name=args.name,
        scope_prefixes=scope_prefixes,
        purpose=args.purpose,
        agents_root=agents_root,
    )


if __name__ == "__main__":
    sys.exit(main())
