"""Generator: the human layer + structural anti-drift (docs-as-code, layer 9).

The single source of truth is the executable model:
  - `spec/src/tensio/*.py` docstrings (the methodology narrative: RULE + Canon:§
    + WHY) — they ship with the framework and are content-free;
  - `spec/content/graph.py:build_graph()` (the domain's tension graph) — populated
    by the user; empty in a fresh framework.

The normative human layer is GENERATED, never hand-written; drift is structurally
impossible because the meta-test (tests/test_docs_gen.py) demands regeneration ==
committed, byte-for-byte.

Pipeline (mirrors dev-coin's gen_spec, purpose inverted from "prove no conflict"
to "render the tensions visibly"):

    tensio docstrings (narrative)            --gen-->  REQUIREMENTS.md
    content graph (Requirements + ...)       --gen-->  REQUIREMENTS.md (roster)
    Conflict clusters by axis + Mermaid      --gen-->  TENSIONS.md
    OPEN requirements + unresolved conflicts --gen-->  OPEN.md

Outputs (committed under docs/gen/, banner-marked, LF):
    REQUIREMENTS.md — requirement roster + methodology narrative.
    TENSIONS.md     — tension map: conflict nodes, clusters by axis, Mermaid.
    OPEN.md         — open registry: OPEN requirements + unresolved conflicts.

Run:
  uv run python tools/gen_spec.py            # regenerate docs/gen/ from spec/content/
  uv run python tools/gen_spec.py --demo     # regenerate docs/demo/ from the fixture

Deterministic byte-for-byte: LF newlines, utf-8, no timestamps/randomness.
Narrative docstrings are read via ast (no code execution); the graph is loaded
via the framework loader (content) or the fixture import (--demo).
"""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

# --- Make the tensio package importable (model is the source of truth) ------

SPEC_ROOT = Path(__file__).resolve().parents[1]  # .../spec
REPO_ROOT = SPEC_ROOT.parent  # .../HotamSpec
SRC = SPEC_ROOT / "src" / "tensio"
GEN_DIR = REPO_ROOT / "docs" / "gen"
DEMO_DIR = REPO_ROOT / "docs" / "demo"

if str(SPEC_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(SPEC_ROOT / "src"))

from tensio.conflict import Conflict  # noqa: E402
from tensio.graph import (  # noqa: E402
    TensionGraph,
    conflicts_by_axis,
    latent_connector_suspects,
    load_content_graph,
)
from tensio.requirement import DRAFT, ENFORCED, SETTLED  # noqa: E402

REQUIREMENTS_MD = GEN_DIR / "REQUIREMENTS.md"
TENSIONS_MD = GEN_DIR / "TENSIONS.md"
OPEN_MD = GEN_DIR / "OPEN.md"
UNENFORCED_MD = GEN_DIR / "UNENFORCED.md"

BANNER = (
    "<!-- AUTOGENERATED from spec/src/tensio + spec/content — do not edit by "
    "hand. Edits: docstrings/content -> uv run python tools/gen_spec.py -->"
)

# --- Module order for the narrative section of REQUIREMENTS.md --------------
# (module name without .py, section label). The order IS the document order.

MODULE_ORDER: list[tuple[str, str]] = [
    ("__init__", "Methodology overview + the closed loop"),
    ("stakeholder", "§Stakeholder — owners and stewards"),
    ("axis", "§Axis — controlled vocabulary of tension dimensions"),
    ("assumption", "§Assumption — beliefs with a lifecycle"),
    ("requirement", "§Requirement — the requirement node"),
    ("conflict", "§Conflict — the connector node"),
    ("graph", "§Graph — the store, the loader, and traversal"),
    ("invariants", "§Invariants — structural form"),
]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _read(path: Path) -> str:
    """Read source as utf-8, normalizing newlines to LF."""
    return path.read_text(encoding="utf-8").replace("\r\n", "\n").replace("\r", "\n")


def _module_docstring(mod: str) -> str:
    """Top-level docstring of src/tensio/<mod>.py via ast (no code execution)."""
    tree = ast.parse(_read(SRC / f"{mod}.py"))
    return ast.get_docstring(tree) or ""


def _cell(text: str) -> str:
    """Escape text for a markdown table cell (LF -> space, | -> \\|)."""
    return text.replace("\n", " ").replace("|", "\\|")


def _mermaid_id(node_id: str) -> str:
    """Sanitize an object id into a Mermaid-safe node identifier."""
    return node_id.replace("-", "_").replace("~", "_").replace(".", "_")


_EMPTY_NOTICE = (
    "_No domain content loaded — `spec/content/graph.py` is absent or empty. "
    "See CLAUDE.md §How to populate to drop in a domain. The methodology "
    "narrative below is the framework itself and is always present._"
)


# ---------------------------------------------------------------------------
# REQUIREMENTS.md — the roster + the methodology narrative
# ---------------------------------------------------------------------------


def build_requirements(g: TensionGraph) -> str:
    """Build REQUIREMENTS.md (roster table + generated narrative) as an LF string."""
    lines: list[str] = [BANNER, ""]
    lines.append("# REQUIREMENTS.md — Requirement roster & methodology (Tensio)")
    lines.append("")
    lines.append(
        "Generated from the executable model: the methodology narrative comes from "
        "`spec/src/tensio` docstrings (RULE + `Canon:§` + WHY); the roster below "
        "comes from `spec/content/graph.py:build_graph()`. Source of truth is the "
        "code; this text is generated, so it cannot drift from the model."
    )
    lines.append("")
    lines.append("---")
    lines.append("")

    # Roster: requirements.
    lines.append("## Requirement roster")
    lines.append("")
    if g.is_empty():
        lines.append(_EMPTY_NOTICE)
        lines.append("")
    elif not g.requirements:
        lines.append("_No requirements declared in this domain yet._")
        lines.append("")
    else:
        lines.append("| id | status | owner | assumptions | claim |")
        lines.append("|---|---|---|---|---|")
        for r in g.requirements:
            assn = ", ".join(r.assumptions) if r.assumptions else "—"
            lines.append(
                f"| `{r.id}` | {_cell(r.status)} | `{r.owner}` | {_cell(assn)} | "
                f"{_cell(r.claim)} |"
            )
        lines.append("")

    # Roster: stakeholders.
    if g.stakeholders:
        lines.append("## Stakeholders")
        lines.append("")
        lines.append("| id | name | domain |")
        lines.append("|---|---|---|")
        for s in g.stakeholders:
            lines.append(f"| `{s.id}` | {_cell(s.name)} | {_cell(s.domain)} |")
        lines.append("")

    # Roster: assumptions.
    if g.assumptions:
        lines.append("## Assumptions")
        lines.append("")
        lines.append("| id | status | owner | statement |")
        lines.append("|---|---|---|---|")
        for a in g.assumptions:
            lines.append(
                f"| `{a.id}` | {a.status} | `{a.owner}` | {_cell(a.statement)} |"
            )
        lines.append("")

    # Narrative: module docstrings in order.
    lines.append("---")
    lines.append("")
    lines.append("## Methodology (generated from module docstrings)")
    lines.append("")
    for ordinal, (mod, label) in enumerate(MODULE_ORDER, start=1):
        doc = _module_docstring(mod)
        lines.append(f"### {ordinal}. {label} — `tensio.{mod}`")
        lines.append("")
        if doc:
            lines.append(doc.rstrip())
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# TENSIONS.md — the tension map (nodes, clusters by axis, Mermaid)
# ---------------------------------------------------------------------------


def _conflict_block(c: Conflict) -> list[str]:
    """Render one Conflict node as a markdown sub-block."""
    lines: list[str] = []
    lines.append(f"#### `{c.id}` — {c.axis}")
    lines.append("")
    lines.append(f"- **context:** {c.context}")
    lines.append(f"- **members:** {', '.join(f'`{m}`' for m in c.members)}")
    lines.append(f"- **steward:** `{c.steward}`")
    lines.append(f"- **lifecycle:** {c.lifecycle}")
    if c.shared_assumption:
        lines.append(f"- **shared assumption:** `{c.shared_assumption}`")
    if c.derived:
        lines.append(
            f"- **spawned (lineage):** {', '.join(f'`{d}`' for d in c.derived)}"
        )
    if c.revisit_marker:
        lines.append(f"- **revisit marker:** {c.revisit_marker}")
    lines.append("")
    return lines


def _mermaid(g: TensionGraph) -> list[str]:
    """Render the tension map as a Mermaid graph: R-nodes -> C-nodes <- R-nodes."""
    lines: list[str] = ["```mermaid", "graph TD"]
    # Requirement nodes referenced by any conflict (members + derived).
    referenced: list[str] = []
    seen: set[str] = set()
    for c in g.conflicts:
        for rid in list(c.members) + list(c.derived):
            if rid not in seen:
                seen.add(rid)
                referenced.append(rid)
    for rid in referenced:
        lines.append(f'    {_mermaid_id(rid)}["{rid}"]')
    # Conflict nodes + edges.
    for c in g.conflicts:
        cid = _mermaid_id(c.id)
        lines.append(f'    {cid}{{"{c.id}\\n{c.axis}"}}')
        for m in c.members:
            lines.append(f"    {_mermaid_id(m)} --> {cid}")
        for d in c.derived:
            lines.append(f"    {cid} -.spawns.-> {_mermaid_id(d)}")
    lines.append("```")
    return lines


def build_tensions(g: TensionGraph) -> str:
    """Build TENSIONS.md (the tension map) as an LF string."""
    lines: list[str] = [BANNER, ""]
    lines.append("# TENSIONS.md — The tension map (Tensio)")
    lines.append("")
    lines.append(
        "Generated from `spec/content/graph.py` (the domain's tension graph). A "
        "**Conflict** is a first-class connector NODE — `R-a -> C <- R-b` — "
        "carrying the tension axis, the colliding context, and the shared "
        "assumption that belong to neither requirement. Conflicts CLUSTER by axis: "
        "a cluster of size > 1 is one unresolved architectural choice, not N local "
        "disputes."
    )
    lines.append("")
    lines.append("---")
    lines.append("")

    if g.is_empty():
        lines.append(_EMPTY_NOTICE)
        lines.append("")
        return "\n".join(lines).rstrip() + "\n"

    # Clusters by axis.
    clusters = conflicts_by_axis(g)
    lines.append("## Clusters by axis")
    lines.append("")
    if not clusters:
        lines.append("_No conflict nodes yet._")
        lines.append("")
    for axis, cons in clusters.items():
        kind = "ARCHITECTURAL CHOICE (cluster)" if len(cons) > 1 else "single tension"
        lines.append(f"### Axis `{axis}` — {len(cons)} conflict(s), {kind}")
        lines.append("")
        for c in cons:
            lines.extend(_conflict_block(c))

    # Mermaid map.
    lines.append("## Tension map (Mermaid)")
    lines.append("")
    if g.conflicts:
        lines.extend(_mermaid(g))
    else:
        lines.append("_No conflict nodes to render._")
    lines.append("")

    # Controlled vocabulary reference (per-domain).
    lines.append("## Controlled vocabulary of axes (this domain)")
    lines.append("")
    if not g.axes:
        lines.append("_No axes declared in this domain yet._")
        lines.append("")
    else:
        lines.append("| axis slug | description |")
        lines.append("|---|---|")
        for ax in g.axes:
            lines.append(f"| `{ax.slug}` | {_cell(ax.description)} |")
        lines.append("")

    # Latent-connector suspicions (heuristic).
    suspects = latent_connector_suspects(g)
    lines.append("## Latent-connector suspicions (heuristic, for AI review)")
    lines.append("")
    lines.append(
        "Requirement pairs that SHOULD perhaps have a connector node but do not. "
        "This is a heuristic stub for the deferred detector — a suspicion to judge, "
        "never an auto-materialized conflict."
    )
    lines.append("")
    if not suspects:
        lines.append("_None flagged._")
        lines.append("")
    else:
        lines.append("| left | right | hint |")
        lines.append("|---|---|---|")
        for s in suspects:
            lines.append(f"| `{s.left}` | `{s.right}` | {_cell(s.hint)} |")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# OPEN.md — the open registry (OPEN requirements + unresolved conflicts)
# ---------------------------------------------------------------------------


def build_open(g: TensionGraph) -> str:
    """Build OPEN.md (open registry) as an LF string."""
    open_reqs = [r for r in g.requirements if r.is_open()]
    unresolved = [c for c in g.conflicts if c.is_unresolved()]

    lines: list[str] = [BANNER, ""]
    lines.append("# OPEN.md — Open registry (Tensio)")
    lines.append("")
    lines.append(
        "Generated mirror of what is still open: OPEN(question) requirements and "
        "conflicts not yet resolved by a steward (DETECTED / ACKNOWLEDGED). This is "
        "the visibility-of-the-open layer; run `tools/what_now.py` for the "
        "prioritized next actions that close these."
    )
    lines.append("")
    if g.is_empty():
        lines.append(_EMPTY_NOTICE)
        lines.append("")
        return "\n".join(lines).rstrip() + "\n"

    lines.append(
        f"Open requirements: **{len(open_reqs)}**. "
        f"Unresolved conflicts: **{len(unresolved)}**."
    )
    lines.append("")
    lines.append("---")
    lines.append("")

    lines.append("## OPEN requirements")
    lines.append("")
    if not open_reqs:
        lines.append("_None._")
        lines.append("")
    else:
        lines.append("| id | owner | question |")
        lines.append("|---|---|---|")
        for r in open_reqs:
            question = r.status[len("OPEN") :].strip().strip("()").strip()
            lines.append(f"| `{r.id}` | `{r.owner}` | {_cell(question)} |")
        lines.append("")

    lines.append("## Unresolved conflicts (no steward resolution yet)")
    lines.append("")
    if not unresolved:
        lines.append("_None._")
        lines.append("")
    else:
        lines.append("| id | axis | lifecycle | steward | members |")
        lines.append("|---|---|---|---|---|")
        for c in unresolved:
            mem = ", ".join(c.members)
            lines.append(
                f"| `{c.id}` | `{c.axis}` | {c.lifecycle} | `{c.steward}` | "
                f"{_cell(mem)} |"
            )
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# UNENFORCED.md — burn-down meter (enforcement gradient)
# ---------------------------------------------------------------------------


def build_unenforced(g: TensionGraph) -> str:
    """Build UNENFORCED.md (burn-down meter for the enforcement gradient) as an LF string.

    Canon: §Requirement — UNENFORCED.md is the generated mirror of the
    enforcement gradient (R-enforcement-gradient / R-requirement-enforced).
    It lists every SETTLED requirement whose enforcement is NOT yet ENFORCED,
    the ENFORCED ones (the substrate's reflexes), and a brief DRAFT roster.
    The burn-down ratio line IS the meter: a healthy direction is SETTLED-ENFORCED
    growing while UNENFORCED shrinks.
    """
    settled = [r for r in g.requirements if r.status == SETTLED]
    draft = [r for r in g.requirements if r.status == DRAFT]
    open_reqs = [r for r in g.requirements if r.is_open()]
    rejected = [r for r in g.requirements if r.status == "REJECTED"]

    settled_enforced = [r for r in settled if r.enforcement == ENFORCED]
    settled_unenforced = [r for r in settled if r.enforcement != ENFORCED]

    lines: list[str] = [BANNER, ""]
    lines.append("# UNENFORCED.md — Burn-down meter (Tensio)")
    lines.append("")
    lines.append(
        "Generated mirror of the enforcement gradient. Every requirement carries\n"
        "`enforcement: PROSE | STRUCTURAL | ENFORCED` (R-enforcement-gradient). This\n"
        "report lists every SETTLED requirement whose enforcement is NOT yet ENFORCED —\n"
        "i.e. claimed but not guaranteed, soft context-debt (R-requirement-enforced)."
    )
    lines.append("")
    lines.append(
        "The ratio line below IS the burn-down meter: a healthy direction is SETTLED-ENFORCED\n"
        "growing while UNENFORCED (PROSE+STRUCTURAL of SETTLED) shrinks."
    )
    lines.append("")

    if g.is_empty():
        lines.append(_EMPTY_NOTICE)
        lines.append("")
        return "\n".join(lines).rstrip() + "\n"

    lines.append(
        f"**Burn-down: SETTLED-ENFORCED {len(settled_enforced)} / SETTLED {len(settled)}; "
        f"DRAFT {len(draft)}; OPEN {len(open_reqs)}; REJECTED {len(rejected)}.**"
    )
    lines.append("")
    lines.append("---")
    lines.append("")

    lines.append("## SETTLED but UNENFORCED")
    lines.append("")
    if not settled_unenforced:
        lines.append("_None — all SETTLED requirements are ENFORCED._")
        lines.append("")
    else:
        lines.append("| id | enforcement | owner | claim |")
        lines.append("|---|---|---|---|")
        for r in settled_unenforced:
            lines.append(
                f"| `{r.id}` | {r.enforcement} | `{r.owner}` | {_cell(r.claim)} |"
            )
        lines.append("")

    lines.append("## SETTLED and ENFORCED (the substrate's automatic reflexes)")
    lines.append("")
    if not settled_enforced:
        lines.append("_None yet._")
        lines.append("")
    else:
        lines.append("| id | enforced_by | claim |")
        lines.append("|---|---|---|")
        for r in settled_enforced:
            by = ", ".join(r.enforced_by) if r.enforced_by else "—"
            lines.append(f"| `{r.id}` | {_cell(by)} | {_cell(r.claim)} |")
        lines.append("")

    lines.append("## DRAFT (not yet promoted)")
    lines.append("")
    if not draft:
        lines.append("_No DRAFT requirements._")
        lines.append("")
    else:
        lines.append("| id | owner |")
        lines.append("|---|---|")
        for r in draft:
            lines.append(f"| `{r.id}` | `{r.owner}` |")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------


def _write(path: Path, text: str) -> None:
    """Write a file as utf-8 with LF newlines (deterministic)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)


def _load_graph(*, demo: bool) -> TensionGraph:
    """Return the graph to render: demo fixture or domain content."""
    if demo:
        tests_dir = str(SPEC_ROOT / "tests")
        if tests_dir not in sys.path:
            sys.path.insert(0, tests_dir)
        from fixtures.seed import seed_graph  # noqa: PLC0415

        return seed_graph()
    return load_content_graph()


def main(argv: list[str] | None = None) -> None:
    """Regenerate the human layer.

    Default: write docs/gen/{REQUIREMENTS,TENSIONS,OPEN}.md from spec/content/.
    --demo: write docs/demo/{REQUIREMENTS,TENSIONS,OPEN}.md from the fixture seed
            (committed docs/gen/ stays untouched, so the anti-drift meta-test
            keeps measuring the content state).
    """
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--demo",
        action="store_true",
        help="render the fixture demo graph into docs/demo/ (not docs/gen/).",
    )
    args = parser.parse_args(argv)
    g = _load_graph(demo=args.demo)
    out_dir = DEMO_DIR if args.demo else GEN_DIR
    targets = {
        out_dir / "REQUIREMENTS.md": build_requirements(g),
        out_dir / "TENSIONS.md": build_tensions(g),
        out_dir / "OPEN.md": build_open(g),
        out_dir / "UNENFORCED.md": build_unenforced(g),
    }
    for path, text in targets.items():
        _write(path, text)
        print(f"written: {path}")


if __name__ == "__main__":
    main()
