"""Anti-drift meta-test (docs-as-code layer 9): generated text cannot drift.

Guarantees, mirroring dev-coin's test_docs_gen but pointed at CONTENT, not at a
hardcoded seed:
  1. Regeneration of docs/gen/{REQUIREMENTS,TENSIONS,OPEN}.md from the CURRENT
     spec/content/ (which is empty in a freshly-shipped framework) matches the
     committed files, byte-for-byte. CRLF normalized on read, generator writes
     LF — the human layer cannot be hand-edited; only the model can.
  2. Generated files are LF-only and carry the AUTOGENERATED banner.
  3. Canon coverage: every public object in tensio (module + top-level class /
     function) carries a docstring with a `Canon:§` / `§` label.
  4. Structural fidelity: running the generators against the DEMO fixture
     actually renders the conflict nodes, the Mermaid map, and the open registry
     (a populated graph proves the generator is not a phantom that always passes
     the empty-equality check).
  5. The empty graph yields a calm "no content yet" notice (not an awkward
     empty-table).
"""

from __future__ import annotations

import ast
import sys
from pathlib import Path

import pytest

# gen_spec lives in spec/tools (not a package) — add to path.
_TOOLS = Path(__file__).resolve().parents[1] / "tools"
_TESTS = Path(__file__).resolve().parent
for _p in (_TOOLS, _TESTS):
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

import gen_spec  # noqa: E402

from fixtures.seed import seed_graph  # noqa: E402


def _read_normalized(path: Path) -> str:
    """Read utf-8 and normalize newlines to LF (as the generator writes)."""
    return path.read_text(encoding="utf-8").replace("\r\n", "\n").replace("\r", "\n")


# ---------------------------------------------------------------------------
# 1. Regeneration of CONTENT == committed files (byte-for-byte, LF)
# ---------------------------------------------------------------------------


def test_requirements_md_up_to_date() -> None:
    """docs/gen/REQUIREMENTS.md matches regeneration from spec/content/."""
    g = gen_spec.load_content_graph()
    assert gen_spec.build_requirements(g) == _read_normalized(
        gen_spec.REQUIREMENTS_MD
    ), "REQUIREMENTS.md is stale: run `uv run python tools/gen_spec.py`."


def test_tensions_md_up_to_date() -> None:
    """docs/gen/TENSIONS.md matches regeneration from spec/content/."""
    g = gen_spec.load_content_graph()
    assert gen_spec.build_tensions(g) == _read_normalized(gen_spec.TENSIONS_MD), (
        "TENSIONS.md is stale: run `uv run python tools/gen_spec.py`."
    )


def test_open_md_up_to_date() -> None:
    """docs/gen/OPEN.md matches regeneration from spec/content/."""
    g = gen_spec.load_content_graph()
    assert gen_spec.build_open(g) == _read_normalized(gen_spec.OPEN_MD), (
        "OPEN.md is stale: run `uv run python tools/gen_spec.py`."
    )


def test_unenforced_md_up_to_date() -> None:
    """docs/gen/UNENFORCED.md matches regeneration from spec/content/."""
    g = gen_spec.load_content_graph()
    assert gen_spec.build_unenforced(g) == _read_normalized(gen_spec.UNENFORCED_MD), (
        "UNENFORCED.md is stale: run `uv run python tools/gen_spec.py`."
    )


def test_glossary_md_up_to_date() -> None:
    """docs/gen/GLOSSARY.md matches regeneration from spec/src/tensio/glossary.py."""
    g = gen_spec.load_content_graph()
    assert gen_spec.build_glossary(g) == _read_normalized(gen_spec.GLOSSARY_MD), (
        "GLOSSARY.md is stale: run `uv run python tools/gen_spec.py`."
    )


def test_history_md_up_to_date() -> None:
    """docs/gen/HISTORY.md matches regeneration from spec/content/."""
    g = gen_spec.load_content_graph()
    assert gen_spec.build_history(g) == _read_normalized(gen_spec.HISTORY_MD), (
        "HISTORY.md is stale: run `uv run python tools/gen_spec.py`."
    )


def test_decisions_md_up_to_date() -> None:
    """docs/gen/DECISIONS.md matches regeneration from spec/content/."""
    g = gen_spec.load_content_graph()
    assert gen_spec.build_decisions(g) == _read_normalized(gen_spec.DECISIONS_MD), (
        "DECISIONS.md is stale: run `uv run python tools/gen_spec.py`."
    )


def test_generated_files_are_lf_and_banner(tmp_path: Path) -> None:
    """Generator writes LF without CR and stamps the AUTOGENERATED banner."""
    g = gen_spec.load_content_graph()
    outputs = {
        "REQUIREMENTS.md": gen_spec.build_requirements(g),
        "TENSIONS.md": gen_spec.build_tensions(g),
        "OPEN.md": gen_spec.build_open(g),
        "UNENFORCED.md": gen_spec.build_unenforced(g),
        "GLOSSARY.md": gen_spec.build_glossary(g),
        "HISTORY.md": gen_spec.build_history(g),
        "DECISIONS.md": gen_spec.build_decisions(g),
    }
    for name, text in outputs.items():
        p = tmp_path / name
        gen_spec._write(p, text)
        raw = p.read_bytes()
        assert b"\r\n" not in raw, f"{name}: CRLF found — must be LF"
        assert raw.decode("utf-8").startswith(gen_spec.BANNER), (
            f"{name}: missing AUTOGENERATED banner"
        )


def test_generator_is_deterministic() -> None:
    """Building twice yields identical bytes (no timestamps/ordering nondeterminism)."""
    g = gen_spec.load_content_graph()
    assert gen_spec.build_requirements(g) == gen_spec.build_requirements(g)
    assert gen_spec.build_tensions(g) == gen_spec.build_tensions(g)
    assert gen_spec.build_open(g) == gen_spec.build_open(g)
    assert gen_spec.build_unenforced(g) == gen_spec.build_unenforced(g)
    assert gen_spec.build_glossary(g) == gen_spec.build_glossary(g)
    assert gen_spec.build_history(g) == gen_spec.build_history(g)
    assert gen_spec.build_decisions(g) == gen_spec.build_decisions(g)


# ---------------------------------------------------------------------------
# 3. Canon coverage: every public object carries a §-label
# ---------------------------------------------------------------------------


def _public_objects() -> list[tuple[str, str]]:
    """All public tensio objects: (qualified name, docstring).

    Objects = module docstrings + top-level public classes/functions. Methods
    are covered by their class docstring and excluded.
    """
    objects: list[tuple[str, str]] = []
    for path in sorted(gen_spec.SRC.glob("*.py")):
        tree = ast.parse(_read_normalized(path))
        mod = path.stem
        objects.append((f"tensio.{mod}", ast.get_docstring(tree) or ""))
        for node in tree.body:
            if isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
                objects.append(
                    (f"tensio.{mod}.{node.name}", ast.get_docstring(node) or "")
                )
            elif isinstance(
                node, (ast.FunctionDef, ast.AsyncFunctionDef)
            ) and not node.name.startswith("_"):
                objects.append(
                    (f"tensio.{mod}.{node.name}", ast.get_docstring(node) or "")
                )
    return objects


# Explicit list of canon sections that MUST appear across the docstrings.
REQUIRED_SECTIONS = [
    "§Requirement",
    "§Conflict",
    "§Assumption",
    "§Axis",
    "§Stakeholder",
    "§Invariants",
    "§Graph",
]


def test_all_sections_covered_in_docstrings() -> None:
    """Each required §-section appears somewhere in the tensio docstrings."""
    blob = "\n".join(doc for _name, doc in _public_objects())
    missing = [s for s in REQUIRED_SECTIONS if s not in blob]
    assert not missing, f"§-sections not covered by docstrings: {missing}"


@pytest.mark.parametrize("name,doc", _public_objects())
def test_public_object_has_section_label(name: str, doc: str) -> None:
    """Every public object has a non-empty docstring carrying a `Canon:§` label."""
    assert doc.strip(), f"{name}: empty docstring"
    assert "§" in doc, f"{name}: docstring missing a `Canon:§N` label"


# ---------------------------------------------------------------------------
# 4. Structural fidelity: a POPULATED graph (demo fixture) actually renders
# ---------------------------------------------------------------------------


def test_tensions_md_contains_conflict_nodes_and_mermaid_on_demo() -> None:
    """TENSIONS.md against the demo renders every fixture conflict + Mermaid."""
    g = seed_graph()
    text = gen_spec.build_tensions(g)
    assert "```mermaid" in text, "TENSIONS.md missing Mermaid diagram"
    for c in g.conflicts:
        assert c.id in text, f"TENSIONS.md missing conflict node {c.id}"
        assert c.axis in text, f"TENSIONS.md missing axis {c.axis}"


def test_requirements_md_contains_every_requirement_on_demo() -> None:
    """REQUIREMENTS.md against the demo lists every fixture requirement id."""
    g = seed_graph()
    text = gen_spec.build_requirements(g)
    for r in g.requirements:
        assert r.id in text, f"REQUIREMENTS.md missing requirement {r.id}"


def test_open_md_lists_open_items_on_demo() -> None:
    """OPEN.md against the demo lists every OPEN req + every unresolved conflict."""
    g = seed_graph()
    text = gen_spec.build_open(g)
    for r in g.requirements:
        if r.is_open():
            assert r.id in text, f"OPEN.md missing open requirement {r.id}"
    for c in g.conflicts:
        if c.is_unresolved():
            assert c.id in text, f"OPEN.md missing unresolved conflict {c.id}"


# ---------------------------------------------------------------------------
# 5. Empty content -> calm "no content yet" notice, not an awkward empty table
# ---------------------------------------------------------------------------


def test_empty_graph_renders_no_content_notice() -> None:
    """An empty graph yields a calm "no content yet" notice in each doc.

    This is what the committed docs/gen/ files should read on a freshly-shipped
    framework — a calm "load a domain" prompt, not an empty roster.
    """
    from tensio.graph import TensionGraph  # noqa: PLC0415

    g = TensionGraph()
    assert g.is_empty()
    for build in (
        gen_spec.build_requirements,
        gen_spec.build_tensions,
        gen_spec.build_open,
        gen_spec.build_unenforced,
        gen_spec.build_history,
        gen_spec.build_decisions,
    ):
        text = build(g)
        assert "No domain content loaded" in text, (
            f"{build.__name__} must render the empty-content notice"
        )
