"""Tests for spec/tools/audit_atomicity.py — the atomicity audit tool.

Enforcer for R-audit-atomicity-tool (the audit is performed by a deterministic
TOOL, not a one-off hand invocation) and the lift for the projected
R-tool-audit-atomicity (R-tool-is-its-own-requirement machinery: this file's
existence flips the projected requirement's enforcer).

Covers:
  1. Claim heuristics: compound conjunctions/semicolons flagged; atomic passes.
  2. Invariant audit runs over ALL_INVARIANTS without error.
  3. main(--demo) is deterministic (two runs, byte-identical AUDIT.md) and
     writes to GEN_DIR (monkeypatched to tmp so the real docs are untouched).
"""

from __future__ import annotations

import sys
from pathlib import Path

_SRC = Path(__file__).resolve().parents[1] / "src"
_TOOLS = Path(__file__).resolve().parents[1] / "tools"
for _p in (_SRC, _TOOLS):
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

import audit_atomicity  # noqa: E402
from hotam_spec.invariants import ALL_INVARIANTS  # noqa: E402


def test_audit_claim_flags_compound_conjunction() -> None:
    """A claim joining two obligations with ', and shall' is COMPOUND."""
    verdict, reason = audit_atomicity._audit_claim(
        "The system shall write the file, and shall verify the checksum."
    )
    assert verdict == "COMPOUND"
    assert reason


def test_audit_claim_flags_semicolon() -> None:
    """A claim carrying two clauses split by '; ' is COMPOUND."""
    verdict, _ = audit_atomicity._audit_claim(
        "The system shall write the file; the checksum shall be verified."
    )
    assert verdict == "COMPOUND"


def test_audit_claim_atomic_passes() -> None:
    """A single-concern claim is ATOMIC with no reason."""
    verdict, reason = audit_atomicity._audit_claim(
        "The system shall write the file."
    )
    assert verdict == "ATOMIC"
    assert reason == ""


def test_audit_invariant_runs_over_all_invariants() -> None:
    """_audit_invariant yields a (verdict, reason) for every registered check_*."""
    for fn in ALL_INVARIANTS:
        verdict, _reason = audit_atomicity._audit_invariant(fn)
        assert verdict in ("ATOMIC", "COMPOUND"), (
            f"{fn.__name__}: unexpected verdict {verdict!r}"
        )


def test_main_demo_is_deterministic_and_writes_audit_md(
    tmp_path: Path, monkeypatch, capsys
) -> None:
    """Two --demo runs produce byte-identical AUDIT.md (deterministic tool)."""
    monkeypatch.setattr(audit_atomicity, "GEN_DIR", tmp_path)

    audit_atomicity.main(["--demo"])
    first = (tmp_path / "AUDIT.md").read_text(encoding="utf-8")
    audit_atomicity.main(["--demo"])
    second = (tmp_path / "AUDIT.md").read_text(encoding="utf-8")

    assert first == second, "audit_atomicity output must be byte-deterministic"
    assert first.startswith("<!-- Generated by tools/audit_atomicity.py")
    assert "# Atomicity Audit" in first
    out = capsys.readouterr().out
    assert "Atomicity Audit" in out
