// audit.go renders requirements_audit.md: the markdown artifact that carries
// the verbatim (Cyrillic-legal) `why` text the .go files may no longer
// contain, per GEN-CODE-CONTRACT.md §1.1's zero-Cyrillic rule. Every .go
// comment this package emits as an "// Atom: <slug>...  — see
// requirements_audit.md" anchor has a matching heading in this file, keyed
// by the same translated (ToKebabCase) entity-slug/state/event values, so a
// human/LLM auditor can jump from the anchor straight to the original
// requirement text (contract §0 mirror principle) — markdown is not code,
// so R-speak-by-reference (quoting the source claim verbatim) is legitimate
// here even though it is forbidden in the .go layer.
//
// RenderAuditFile takes the already-built []*entityModel (the same models
// RenderEntitiesFile/RenderLifecycleFile/RenderLifecycleTestFile render
// from), not raw []ontology.EntityType — entitySlug and every state/event
// value are computed exactly once in BuildEntityModel and threaded through
// here, so the anchors this file's headings carry can never independently
// drift from the ones the .go comments reference (same discipline as the
// eventConst threading in models.go/lifecycle.go).
package gocode

import (
	"fmt"
	"sort"
	"strings"

	"github.com/PHPCraftdream/HotamSpec/internal/ontology"
)

// RenderAuditFile renders requirements_audit.md for a domain: one section
// per EntityType (sorted by slug for determinism, contract §5), heading
// anchored on the same translated entity-slug the .go layer's "// Atom:
// ..." comments reference, followed by the EntityType's own verbatim `why`
// (if any) and one sub-entry per lifecycle state/transition that carries a
// non-empty `why`, followed by a "## Requirements" section (stage 4) with
// one entry per SETTLED requirement — heading anchored on the same
// lowercased requirement id requirements_test.go's "// Atom: ..." comments
// reference, the requirement's full verbatim claim (Cyrillic-legal here,
// markdown, not .go — contract §1.1/§3), and a line naming which atoms were
// found and where they mirror to. EntityTypes with no `why` anywhere
// (struct, states, or transitions) are skipped entirely — an empty section
// would be a dangling anchor target nothing points at, since the .go layer
// only emits an "// Atom: ..." comment when `why` is non-empty
// (models.go/lifecycle.go). The Requirements section, by contrast, always
// renders one entry per requirement passed in (even a "no structural atom"
// one) — requirements_test.go unconditionally emits a Test_<id> function
// with an "// Atom: ..." comment for every SETTLED requirement, so every
// requirement has a live anchor pointing here, unlike the EntityType why-only
// gating above.
func RenderAuditFile(models []*entityModel, reqModels []*requirementModel) ([]byte, error) {
	sorted := make([]*entityModel, len(models))
	copy(sorted, models)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].src.Slug < sorted[j].src.Slug })

	sortedReqs := make([]*requirementModel, len(reqModels))
	copy(sortedReqs, reqModels)
	sort.Slice(sortedReqs, func(i, j int) bool { return sortedReqs[i].src.ID < sortedReqs[j].src.ID })

	var b strings.Builder
	b.WriteString("# requirements_audit.md\n\n")
	b.WriteString("AUTOGENERATED from the domain graph.json — do not edit by hand. Edits: methodology/graph -> hotam gen-code\n\n")
	b.WriteString("Verbatim (original-language) `why` text for every EntityType/state/transition the generated .go layer\n")
	b.WriteString("anchors to via `// Atom: ...` comments (GEN-CODE-CONTRACT.md §1.1). Markdown, not code — the zero-Cyrillic\n")
	b.WriteString("rule applies only to `.go` files; this file is where the original requirement text legitimately lives.\n\n")

	for _, m := range sorted {
		et := m.src
		hasAnyWhy := et.Why != ""
		for _, s := range m.states {
			if s.src.Why != "" {
				hasAnyWhy = true
			}
		}
		for _, tr := range m.transitions {
			if tr.src.Why != "" {
				hasAnyWhy = true
			}
		}
		if !hasAnyWhy {
			continue
		}

		fmt.Fprintf(&b, "## %s {#%s}\n\n", et.Slug, m.entitySlug)

		if et.Why != "" {
			fmt.Fprintf(&b, "%s\n\n", et.Why)
		}

		for _, s := range m.states {
			if s.src.Why == "" {
				continue
			}
			fmt.Fprintf(&b, "### %s.lifecycle.state.%s {#%s-lifecycle-state-%s}\n\n", et.Slug, s.src.Name, m.entitySlug, s.value)
			fmt.Fprintf(&b, "%s\n\n", s.src.Why)
		}

		for _, tr := range m.transitions {
			if tr.src.Why == "" {
				continue
			}
			fmt.Fprintf(&b, "### %s.lifecycle.transition.%s {#%s-lifecycle-transition-%s}\n\n", et.Slug, tr.src.Event, m.entitySlug, tr.eventValue)
			fmt.Fprintf(&b, "%s\n\n", tr.src.Why)
		}
	}

	if len(sortedReqs) > 0 {
		b.WriteString("## Requirements\n\n")
		for _, rm := range sortedReqs {
			renderRequirementAuditEntry(&b, rm)
		}
	}

	return []byte(b.String()), nil
}

// renderRequirementAuditEntry renders one SETTLED requirement's stage-4
// audit entry: heading anchored on the requirement id (matching
// requirements_test.go's "// Atom: <id> - see requirements_audit.md#<anchor>"
// comment), the full verbatim claim, and a line per found atom naming where
// it mirrors to in requirements_test.go (file:function/sub-test) — or, for a
// requirement with no structural atom, an explicit statement of that fact.
func renderRequirementAuditEntry(b *strings.Builder, rm *requirementModel) {
	fmt.Fprintf(b, "### %s {#%s}\n\n", rm.src.ID, rm.anchorSlug)
	fmt.Fprintf(b, "%s\n\n", rm.src.Claim)
	b.WriteString("Atoms:\n\n")

	switch rm.kind {
	case atomKindField:
		for _, fa := range rm.fields {
			subName := fa.entity.structName + "_" + fa.field.fieldName
			fmt.Fprintf(b, "- entity/field: `%s.%s` -> `requirements_test.go:%s/%s`\n",
				fa.entity.structName, fa.field.fieldName, rm.funcName, subName)
		}
	case atomKindStatePair:
		sp := rm.statePair
		names := make([]string, len(sp.states))
		for i, s := range sp.states {
			names[i] = s.constant
		}
		fmt.Fprintf(b, "- state/transition: `%s` states {%s} -> `requirements_test.go:%s/%s_state_pair`\n",
			sp.entity.structName, strings.Join(names, ", "), rm.funcName, sp.entity.structName)
	case atomKindGate:
		for _, c := range rm.gate.correlates {
			switch c.kind {
			case gateAnchorCorrelateState:
				subName := "gate_order_anchor_" + c.stateEntity.structName + "_" + c.state.constant
				fmt.Fprintf(b, "- gate/order: anchor `%s` -> lifecycle state `%s.%s` (%s) -> `requirements_test.go:%s/%s`\n",
					c.anchor, c.stateEntity.structName, c.state.constant, c.state.src.Name, rm.funcName, subName)
			case gateAnchorCorrelateRequirement:
				subName := "gate_order_anchor_" + requirementFuncNameBody(c.requirementID)
				fmt.Fprintf(b, "- gate/order: anchor `%s` -> requirement `%s` -> `requirements_test.go:%s/%s`\n",
					c.anchor, c.requirementID, rm.funcName, subName)
			case gateAnchorCorrelateWhy:
				fmt.Fprintf(b, "- gate/order: anchor `%s` -> found only in an EntityType `why` text (textual, not structural) -> no .go assertion rendered (see this requirement's own why/claim text above)\n", c.anchor)
			default:
				fmt.Fprintf(b, "- gate/order: anchor `%s` -> no correlate found anywhere in the domain graph -> no .go assertion rendered\n", c.anchor)
			}
		}
	case atomKindInterEntity:
		names := make([]string, len(rm.interEntity))
		for i, em := range rm.interEntity {
			names[i] = em.structName
		}
		fmt.Fprintf(b, "- inter-entity invariant: {%s} -> `requirements_test.go:%s/inter_entity_%s` (compile-time link only - both constructors must resolve to build; New<Entity>() can never return nil, so no runtime nil-check is rendered)\n",
			strings.Join(names, ", "), rm.funcName, strings.Join(names, "_"))
	default:
		if len(rm.gate.anchors) > 0 {
			// This requirement matched row 3's meta-token + anchor shape,
			// but every anchor's correlate search (resolveGateAnchorCorrelate,
			// requirements.go) came back empty or why-text-only - contract §3
			// row 3 does not apply, and it honestly fell through to the
			// closing row instead of being classified as a vacuous gate/order
			// check (see the anchor-by-anchor detail this loop prints).
			fmt.Fprintf(b, "- gate/order anchors {%s} found in claim text, but none resolve to a runtime-comparable graph correlate (lifecycle.state.name or another requirement id) -> reclassified as no structural atom, per-anchor detail:\n",
				strings.Join(rm.gate.anchors, ", "))
			for _, c := range rm.gate.correlates {
				switch c.kind {
				case gateAnchorCorrelateWhy:
					fmt.Fprintf(b, "  - anchor `%s`: found only in an EntityType `why` text (textual, not structural)\n", c.anchor)
				default:
					fmt.Fprintf(b, "  - anchor `%s`: no correlate found anywhere in the domain graph\n", c.anchor)
				}
			}
		}
		fmt.Fprintf(b, "- no structural atom -> `requirements_test.go:%s` (t.Log only)\n", rm.funcName)
	}

	b.WriteString("\n")
}

// GenerateAuditFromGraph builds the []*entityModel for entityTypes and
// renders requirements_audit.md from it (with an empty Requirements
// section), in the same map[filename][]byte shape
// GenerateModelsFromGraph/GenerateLifecycleFromGraph use, so callers (the
// future CLI stage) can merge all three into one file set. Callers that also
// have SETTLED requirements to atomize should use
// GenerateRequirementsFromGraph instead, which renders the same file with
// the Requirements section populated (contract §0: this package renders
// requirements_audit.md in exactly one place, RenderAuditFile — this
// function and GenerateRequirementsFromGraph are two callers of it, not two
// independent renderers).
func GenerateAuditFromGraph(entityTypes []ontology.EntityType) (map[string][]byte, error) {
	models := make([]*entityModel, 0, len(entityTypes))
	for _, et := range entityTypes {
		m, err := BuildEntityModel(et)
		if err != nil {
			return nil, fmt.Errorf("gocode: GenerateAuditFromGraph: %w", err)
		}
		models = append(models, m)
	}

	auditSrc, err := RenderAuditFile(models, nil)
	if err != nil {
		return nil, fmt.Errorf("gocode: GenerateAuditFromGraph: %w", err)
	}
	return map[string][]byte{
		"requirements_audit.md": auditSrc,
	}, nil
}
