// audit.go renders requirements_audit.md: the markdown artifact that carries
// the verbatim (Cyrillic-legal) `why` text the .go files may no longer
// contain, per GEN-CODE-CONTRACT.md §1.1's zero-Cyrillic rule. Every .go
// comment this package emits as an "// Atom: <slug>...  — see
// requirements_audit.md" anchor has a matching heading in this file, keyed
// by the same translated (ToKebabCase) entity-slug/state/event values, so a
// human/LLM auditor can jump from the anchor straight to the original
// requirement text (contract §0 mirror principle) — markdown is not code,
// so R-speak-by-reference (quoting the source claim verbatim) is legitimate
// here even though it is forbidden in the .go layer.
//
// RenderAuditFile takes the already-built []*entityModel (the same models
// RenderEntitiesFile/RenderLifecycleFile/RenderLifecycleTestFile render
// from), not raw []ontology.EntityType — entitySlug and every state/event
// value are computed exactly once in BuildEntityModel and threaded through
// here, so the anchors this file's headings carry can never independently
// drift from the ones the .go comments reference (same discipline as the
// eventConst threading in models.go/lifecycle.go).
package gocode

import (
	"fmt"
	"sort"
	"strings"

	"github.com/PHPCraftdream/HotamSpec/internal/ontology"
)

// RenderAuditFile renders requirements_audit.md for a domain: one section
// per EntityType (sorted by slug for determinism, contract §5), heading
// anchored on the same translated entity-slug the .go layer's "// Atom:
// ..." comments reference, followed by the EntityType's own verbatim `why`
// (if any) and one sub-entry per lifecycle state/transition that carries a
// non-empty `why`. EntityTypes with no `why` anywhere (struct, states, or
// transitions) are skipped entirely — an empty section would be a
// dangling anchor target nothing points at, since the .go layer only emits
// an "// Atom: ..." comment when `why` is non-empty (models.go/lifecycle.go).
func RenderAuditFile(models []*entityModel) ([]byte, error) {
	sorted := make([]*entityModel, len(models))
	copy(sorted, models)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].src.Slug < sorted[j].src.Slug })

	var b strings.Builder
	b.WriteString("# requirements_audit.md\n\n")
	b.WriteString("AUTOGENERATED from the domain graph.json — do not edit by hand. Edits: methodology/graph -> hotam gen-code\n\n")
	b.WriteString("Verbatim (original-language) `why` text for every EntityType/state/transition the generated .go layer\n")
	b.WriteString("anchors to via `// Atom: ...` comments (GEN-CODE-CONTRACT.md §1.1). Markdown, not code — the zero-Cyrillic\n")
	b.WriteString("rule applies only to `.go` files; this file is where the original requirement text legitimately lives.\n\n")

	for _, m := range sorted {
		et := m.src
		hasAnyWhy := et.Why != ""
		for _, s := range m.states {
			if s.src.Why != "" {
				hasAnyWhy = true
			}
		}
		for _, tr := range m.transitions {
			if tr.src.Why != "" {
				hasAnyWhy = true
			}
		}
		if !hasAnyWhy {
			continue
		}

		fmt.Fprintf(&b, "## %s {#%s}\n\n", et.Slug, m.entitySlug)

		if et.Why != "" {
			fmt.Fprintf(&b, "%s\n\n", et.Why)
		}

		for _, s := range m.states {
			if s.src.Why == "" {
				continue
			}
			fmt.Fprintf(&b, "### %s.lifecycle.state.%s {#%s-lifecycle-state-%s}\n\n", et.Slug, s.src.Name, m.entitySlug, s.value)
			fmt.Fprintf(&b, "%s\n\n", s.src.Why)
		}

		for _, tr := range m.transitions {
			if tr.src.Why == "" {
				continue
			}
			fmt.Fprintf(&b, "### %s.lifecycle.transition.%s {#%s-lifecycle-transition-%s}\n\n", et.Slug, tr.src.Event, m.entitySlug, tr.eventValue)
			fmt.Fprintf(&b, "%s\n\n", tr.src.Why)
		}
	}

	return []byte(b.String()), nil
}

// GenerateAuditFromGraph builds the []*entityModel for entityTypes and
// renders requirements_audit.md from it, in the same map[filename][]byte
// shape GenerateModelsFromGraph/GenerateLifecycleFromGraph use, so callers
// (the future CLI stage) can merge all three into one file set.
func GenerateAuditFromGraph(entityTypes []ontology.EntityType) (map[string][]byte, error) {
	models := make([]*entityModel, 0, len(entityTypes))
	for _, et := range entityTypes {
		m, err := BuildEntityModel(et)
		if err != nil {
			return nil, fmt.Errorf("gocode: GenerateAuditFromGraph: %w", err)
		}
		models = append(models, m)
	}

	auditSrc, err := RenderAuditFile(models)
	if err != nil {
		return nil, fmt.Errorf("gocode: GenerateAuditFromGraph: %w", err)
	}
	return map[string][]byte{
		"requirements_audit.md": auditSrc,
	}, nil
}
