// audit.go renders requirements_audit.md: the markdown artifact that carries
// the verbatim (Cyrillic-legal) `why` text the .go files may no longer
// contain, per GEN-CODE-CONTRACT.md §1.1's zero-Cyrillic rule. Every .go
// comment this package emits as an "// Atom: <slug>...  — see
// requirements_audit.md" anchor has a matching heading in this file, keyed
// by the same translated (ToKebabCase) entity-slug/state/event values, so a
// human/LLM auditor can jump from the anchor straight to the original
// requirement text (contract §0 mirror principle) — markdown is not code,
// so R-speak-by-reference (quoting the source claim verbatim) is legitimate
// here even though it is forbidden in the .go layer.
//
// RenderAuditFile takes the already-built []*entityModel (the same models
// RenderEntitiesFile/RenderLifecycleFile/RenderLifecycleTestFile render
// from), not raw []ontology.EntityType — entitySlug and every state/event
// value are computed exactly once in BuildEntityModel and threaded through
// here, so the anchors this file's headings carry can never independently
// drift from the ones the .go comments reference (same discipline as the
// eventConst threading in models.go/lifecycle.go).
package gocode

import (
	"fmt"
	"sort"
	"strings"

	"github.com/PHPCraftdream/HotamSpec/internal/ontology"
)

// RenderAuditFile renders requirements_audit.md for a domain: one section
// per EntityType (sorted by slug for determinism, contract §5), heading
// anchored on the same translated entity-slug the .go layer's "// Atom:
// ..." comments reference, followed by the EntityType's own verbatim `why`
// (if any) and one sub-entry per lifecycle state/transition that carries a
// non-empty `why`, followed by a "## Requirements" section (stage 4) with
// one entry per SETTLED requirement — heading anchored on the same
// lowercased requirement id requirements_test.go's "// Atom: ..." comments
// reference, the requirement's full verbatim claim (Cyrillic-legal here,
// markdown, not .go — contract §1.1/§3), and a line naming which atoms were
// found and where they mirror to. EntityTypes with no `why` anywhere
// (struct, states, or transitions) are skipped entirely — an empty section
// would be a dangling anchor target nothing points at, since the .go layer
// only emits an "// Atom: ..." comment when `why` is non-empty
// (models.go/lifecycle.go). The Requirements section, by contrast, always
// renders one entry per requirement passed in (even a "no structural atom"
// one) — requirements_test.go unconditionally emits a Test_<id> function
// with an "// Atom: ..." comment for every SETTLED requirement, so every
// requirement has a live anchor pointing here, unlike the EntityType why-only
// gating above. A final "## Pipeline Gates" section (stage 5) lists every
// pipelineGateModel passed in — one entry per generated Gate<...>Terminal
// function, naming the referencer field, the referenced EntityType, and the
// referenced entity's terminal state(s) the gate accepts — mirroring
// pipeline_test.go's own "// Atom: ..." comments (pipeline_test_gen.go).
// gates may be nil (callers that have not yet built pipeline gates, e.g.
// GenerateAuditFromGraph/GenerateLifecycleFromGraph/GenerateRequirementsFromGraph),
// in which case the section is simply omitted.
func RenderAuditFile(models []*entityModel, reqModels []*requirementModel, gates []*pipelineGateModel) ([]byte, error) {
	sorted := make([]*entityModel, len(models))
	copy(sorted, models)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].src.Slug < sorted[j].src.Slug })

	sortedReqs := make([]*requirementModel, len(reqModels))
	copy(sortedReqs, reqModels)
	sort.Slice(sortedReqs, func(i, j int) bool { return sortedReqs[i].src.ID < sortedReqs[j].src.ID })

	sortedGates := make([]*pipelineGateModel, len(gates))
	copy(sortedGates, gates)
	sort.Slice(sortedGates, func(i, j int) bool { return sortedGates[i].funcName < sortedGates[j].funcName })

	var b strings.Builder
	b.WriteString("# requirements_audit.md\n\n")
	b.WriteString("AUTOGENERATED from the domain graph.json — do not edit by hand. Edits: methodology/graph -> hotam gen-code\n\n")
	b.WriteString("Verbatim (original-language) `why` text for every EntityType/state/transition the generated .go layer\n")
	b.WriteString("anchors to via `// Atom: ...` comments (GEN-CODE-CONTRACT.md §1.1). Markdown, not code — the zero-Cyrillic\n")
	b.WriteString("rule applies only to `.go` files; this file is where the original requirement text legitimately lives.\n\n")

	for _, m := range sorted {
		et := m.src
		hasAnyWhy := et.Why != ""
		for _, s := range m.states {
			if s.src.Why != "" {
				hasAnyWhy = true
			}
		}
		for _, tr := range m.transitions {
			if tr.src.Why != "" {
				hasAnyWhy = true
			}
		}
		if !hasAnyWhy {
			continue
		}

		fmt.Fprintf(&b, "## %s {#%s}\n\n", et.Slug, m.entitySlug)

		if et.Why != "" {
			fmt.Fprintf(&b, "%s\n\n", et.Why)
		}

		for _, s := range m.states {
			if s.src.Why == "" {
				continue
			}
			fmt.Fprintf(&b, "### %s.lifecycle.state.%s {#%s-lifecycle-state-%s}\n\n", et.Slug, s.src.Name, m.entitySlug, s.value)
			fmt.Fprintf(&b, "%s\n\n", s.src.Why)
		}

		for _, tr := range m.transitions {
			if tr.src.Why == "" {
				continue
			}
			fmt.Fprintf(&b, "### %s.lifecycle.transition.%s {#%s-lifecycle-transition-%s}\n\n", et.Slug, tr.src.Event, m.entitySlug, tr.eventValue)
			fmt.Fprintf(&b, "%s\n\n", tr.src.Why)
		}
	}

	if len(sortedReqs) > 0 {
		// otherSettled (contract §3.1's coverage report needs the same
		// "search the whole SETTLED corpus" access resolveGateAnchorCorrelate
		// already uses for gate/order atoms) is every requirement's own src,
		// unfiltered by SETTLED status here: sortedReqs is already the
		// SETTLED-only requirementModel set BuildRequirementModels produced
		// (non-SETTLED requirements never reach requirementModel at all), so
		// this is exactly the otherSettled slice BuildRequirementModel itself
		// was given.
		otherSettled := make([]ontology.Requirement, len(sortedReqs))
		for i, rm := range sortedReqs {
			otherSettled[i] = rm.src
		}

		b.WriteString("## Requirements\n\n")
		for _, rm := range sortedReqs {
			cov := BuildCoverageReport(rm, sorted, otherSettled)
			renderRequirementAuditEntry(&b, rm, cov)
		}
	}

	if len(sortedGates) > 0 {
		b.WriteString("## Pipeline Gates\n\n")
		b.WriteString("Stage 5: one gate per `kind:reference` field whose `ref_target` resolves to another\n")
		b.WriteString("EntityType of this domain (GEN-CODE-CONTRACT.md §0 - \"artifact not accepted until\n")
		b.WriteString("predecessor terminal\"). See `pipeline_test.go` for the generated `Gate<...>Terminal`\n")
		b.WriteString("function and its `Test<...>` table-driven proof.\n\n")
		for _, gm := range sortedGates {
			renderPipelineGateAuditEntry(&b, gm)
		}
	}

	return []byte(b.String()), nil
}

// renderRequirementAuditEntry renders one SETTLED requirement's stage-4
// audit entry: heading anchored on the requirement id (matching
// requirements_test.go's "// Atom: <id> - see requirements_audit.md#<anchor>"
// comment), the full verbatim claim, a line per found atom naming where
// it mirrors to in requirements_test.go (file:function/sub-test) — or, for a
// requirement with no structural atom, an explicit statement of that fact —
// and finally the contract §3.1 coverage-completeness line: "Coverage: N/M
// candidate terms resolved", plus an explicit per-gap listing of every
// candidate term that did NOT resolve to one of this requirement's own atoms
// (either unresolved anywhere in the graph, or resolved to a DIFFERENT graph
// element — the "partial coverage gap" case §3.1 requires never be silently
// invisible behind an "atom found" appearance of completeness).
func renderRequirementAuditEntry(b *strings.Builder, rm *requirementModel, cov coverageReport) {
	fmt.Fprintf(b, "### %s {#%s}\n\n", rm.src.ID, rm.anchorSlug)
	fmt.Fprintf(b, "%s\n\n", rm.src.Claim)
	b.WriteString("Atoms:\n\n")

	switch rm.kind {
	case atomKindField:
		for _, fa := range rm.fields {
			subName := fa.entity.structName + "_" + fa.field.fieldName
			fmt.Fprintf(b, "- entity/field: `%s.%s` -> `requirements_test.go:%s/%s`\n",
				fa.entity.structName, fa.field.fieldName, rm.funcName, subName)
		}
	case atomKindStatePair:
		sp := rm.statePair
		names := make([]string, len(sp.states))
		for i, s := range sp.states {
			names[i] = s.constant
		}
		fmt.Fprintf(b, "- state/transition: `%s` states {%s} -> `requirements_test.go:%s/%s_state_pair`\n",
			sp.entity.structName, strings.Join(names, ", "), rm.funcName, sp.entity.structName)
	case atomKindGate:
		for _, c := range rm.gate.correlates {
			switch c.kind {
			case gateAnchorCorrelateState:
				subName := "gate_order_anchor_" + c.stateEntity.structName + "_" + c.state.constant
				fmt.Fprintf(b, "- gate/order: anchor `%s` -> lifecycle state `%s.%s` (%s) -> `requirements_test.go:%s/%s`\n",
					c.anchor, c.stateEntity.structName, c.state.constant, c.state.src.Name, rm.funcName, subName)
			case gateAnchorCorrelateRequirement:
				subName := "gate_order_anchor_" + requirementFuncNameBody(c.requirementID)
				fmt.Fprintf(b, "- gate/order: anchor `%s` -> requirement `%s` -> `requirements_test.go:%s/%s`\n",
					c.anchor, c.requirementID, rm.funcName, subName)
			case gateAnchorCorrelateWhy:
				fmt.Fprintf(b, "- gate/order: anchor `%s` -> found only in an EntityType `why` text (textual, not structural) -> no .go assertion rendered (see this requirement's own why/claim text above)\n", c.anchor)
			default:
				fmt.Fprintf(b, "- gate/order: anchor `%s` -> no correlate found anywhere in the domain graph -> no .go assertion rendered\n", c.anchor)
			}
		}
	case atomKindInterEntity:
		names := make([]string, len(rm.interEntity))
		for i, em := range rm.interEntity {
			names[i] = em.structName
		}
		fmt.Fprintf(b, "- inter-entity invariant: {%s} -> `requirements_test.go:%s/inter_entity_%s` (compile-time link only - both constructors must resolve to build; New<Entity>() can never return nil, so no runtime nil-check is rendered)\n",
			strings.Join(names, ", "), rm.funcName, strings.Join(names, "_"))
	default:
		if len(rm.gate.anchors) > 0 {
			// This requirement matched row 3's meta-token + anchor shape,
			// but every anchor's correlate search (resolveGateAnchorCorrelate,
			// requirements.go) came back empty or why-text-only - contract §3
			// row 3 does not apply, and it honestly fell through to the
			// closing row instead of being classified as a vacuous gate/order
			// check (see the anchor-by-anchor detail this loop prints).
			fmt.Fprintf(b, "- gate/order anchors {%s} found in claim text, but none resolve to a runtime-comparable graph correlate (lifecycle.state.name or another requirement id) -> reclassified as no structural atom, per-anchor detail:\n",
				strings.Join(rm.gate.anchors, ", "))
			for _, c := range rm.gate.correlates {
				switch c.kind {
				case gateAnchorCorrelateWhy:
					fmt.Fprintf(b, "  - anchor `%s`: found only in an EntityType `why` text (textual, not structural)\n", c.anchor)
				default:
					fmt.Fprintf(b, "  - anchor `%s`: no correlate found anywhere in the domain graph\n", c.anchor)
				}
			}
		}
		fmt.Fprintf(b, "- no structural atom -> `requirements_test.go:%s` (t.Log only)\n", rm.funcName)
	}

	b.WriteString("\n")
	renderCoverageSection(b, cov)
}

// renderCoverageSection renders GEN-CODE-CONTRACT.md §3.1's mandatory
// "Coverage: N/M candidate terms resolved" line for one requirement, plus an
// explicit listing of every unresolved/partial-coverage-gap candidate term,
// each tagged with WHERE (if anywhere) it looks like a graph concept — so a
// steward reading requirements_audit.md never sees bare "atom found"
// completeness without also seeing what the claim mentions that the atoms
// above did not capture.
func renderCoverageSection(b *strings.Builder, cov coverageReport) {
	total := len(cov.candidates)
	resolved := cov.resolvedCount()
	fmt.Fprintf(b, "Coverage: %d/%d candidate terms resolved\n\n", resolved, total)

	gaps := cov.gaps()
	if len(gaps) == 0 {
		if total > 0 {
			b.WriteString("All candidate terms resolved into this requirement's own atoms above.\n\n")
		}
		return
	}

	b.WriteString("Unresolved / partial-coverage-gap candidate terms:\n\n")
	for _, g := range gaps {
		fmt.Fprintf(b, "- `%s` (%s): %s\n", g.text, candidateKindLabel(g.kind), candidateGapDetail(g))
	}
	b.WriteString("\n")
}

// candidateKindLabel names the contract §3.1 extraction rule that produced
// one candidate term, for the audit line's "(...)" tag.
func candidateKindLabel(k candidateTermKind) string {
	switch k {
	case candidateKindCapitalized:
		return "capitalized token/abbreviation"
	case candidateKindGraphName:
		return "graph field/state name"
	case candidateKindQuoted:
		return "quoted term"
	default:
		return "unknown"
	}
}

// candidateGapDetail renders the "-> resembles graph concept X, not used by
// this requirement's atoms (candidate for graph/heuristic follow-up)" OR
// "-> no graph correlate found (out of model)" detail contract §3.1 requires
// for every unresolved candidate: a candidate that resembles an existing
// graph element (field/state/entity/requirement id) but was not captured by
// this requirement's own atoms is a follow-up candidate (graph enrichment or
// matching-heuristic gap); a candidate with no correlate anywhere is
// honestly out of the current model.
func candidateGapDetail(g candidateTerm) string {
	switch {
	case g.resolvedField != nil && g.resolvedEntity != nil:
		return fmt.Sprintf("resembles graph field `%s.%s`, not captured by this requirement's own atoms above (candidate for graph/heuristic follow-up)", g.resolvedEntity.structName, g.resolvedField.fieldName)
	case g.resolvedState != nil && g.resolvedEntity != nil:
		return fmt.Sprintf("resembles graph state `%s.%s` (%s), not captured by this requirement's own atoms above (candidate for graph/heuristic follow-up)", g.resolvedEntity.structName, g.resolvedState.constant, g.resolvedState.src.Name)
	case g.resolvedRequirementID != "":
		return fmt.Sprintf("resembles requirement id `%s`, not captured by this requirement's own atoms above (candidate for graph/heuristic follow-up)", g.resolvedRequirementID)
	case g.resolvedEntity != nil:
		return fmt.Sprintf("resembles EntityType `%s`, not captured by this requirement's own atoms above (candidate for graph/heuristic follow-up)", g.resolvedEntity.structName)
	default:
		return "no graph correlate found anywhere in the domain (out of model, or genuinely ambiguous between multiple EntityTypes with no binding signal)"
	}
}

// renderPipelineGateAuditEntry renders one stage-5 pipeline gate's audit
// entry: heading anchored on the gate function name (matching
// pipeline_test.go's own "// Atom: ... - see requirements_audit.md" comment,
// pipeline_test_gen.go's renderPipelineGateTest), the referencer field, the
// referenced EntityType, and where the gate function + its test live.
//
// Contract §2.1: when gm.preciseState is set, the entry names the EXACT
// state the gate requires (never "terminal") and the referencer's own why
// text is the anchor's cited justification (the referencer-binding signal
// resolvePreciseGateState uses, GEN-CODE-CONTRACT.md §2.1) - a human/LLM
// auditor reading this entry can see WHY this gate is precise, not merely
// THAT it is. Otherwise (preciseState nil) the entry documents the general
// RequiresTerminal gate exactly as before this stage.
func renderPipelineGateAuditEntry(b *strings.Builder, gm *pipelineGateModel) {
	anchor := strings.ToLower(gm.funcName)
	fmt.Fprintf(b, "### %s {#%s}\n\n", gm.funcName, anchor)
	fmt.Fprintf(b, "`%s.%s` references `%s` (kind:reference, ref_target=%q).\n\n",
		gm.referencer.structName, gm.field.fieldName, gm.referenced.structName, gm.referenced.src.Slug)

	if gm.preciseState != nil {
		fmt.Fprintf(b, "**Precise gate** (GEN-CODE-CONTRACT.md section 2.1): requires `%s` to be in EXACTLY state `%s` (%s) -\n",
			gm.referenced.structName, gm.preciseState.constant, gm.preciseState.src.Name)
		fmt.Fprintf(b, "a later terminal state of `%s` does NOT satisfy this gate.\n\n", gm.referenced.structName)
		fmt.Fprintf(b, "Basis: the SETTLED requirement corpus names `%s_%s` (or the `-`-separated spelling) in a\n",
			strings.ToLower(gm.referenced.src.Slug), strings.ToLower(gm.preciseState.src.Name))
		fmt.Fprintf(b, "claim, AND `%s`'s own `why` text quotes that same token - the referencer-bound correlate\n", gm.referencer.structName)
		b.WriteString("resolvePreciseGateState (pipeline.go) requires before preferring a precise gate over the general\n")
		b.WriteString("RequiresTerminal one. See this domain's EntityType why-text section above for the verbatim quote.\n\n")
	} else {
		names := make([]string, len(gm.terminalStates))
		for i, s := range gm.terminalStates {
			names[i] = s.constant
		}
		fmt.Fprintf(b, "**General gate**: accepts any of `%s`'s own terminal (or quiescent) state(s): %s.\n", gm.referenced.structName, strings.Join(names, ", "))
		b.WriteString("No SETTLED requirement in this domain names one specific state of this referenced EntityType\n")
		b.WriteString("tied to this specific referencer (GEN-CODE-CONTRACT.md section 2.1), so terminal-ness remains\n")
		b.WriteString("the only available structural signal.\n\n")
	}

	fmt.Fprintf(b, "- gate function: `pipeline_test.go:%s`\n", gm.funcName)
	fmt.Fprintf(b, "- gate test: `pipeline_test.go:Test%s`\n\n", gm.funcName)
}

// GenerateAuditFromGraph builds the []*entityModel for entityTypes and
// renders requirements_audit.md from it (with an empty Requirements
// section), in the same map[filename][]byte shape
// GenerateModelsFromGraph/GenerateLifecycleFromGraph use, so callers (the
// future CLI stage) can merge all three into one file set. Callers that also
// have SETTLED requirements to atomize should use
// GenerateRequirementsFromGraph instead, which renders the same file with
// the Requirements section populated (contract §0: this package renders
// requirements_audit.md in exactly one place, RenderAuditFile — this
// function and GenerateRequirementsFromGraph are two callers of it, not two
// independent renderers).
func GenerateAuditFromGraph(entityTypes []ontology.EntityType) (map[string][]byte, error) {
	models := make([]*entityModel, 0, len(entityTypes))
	for _, et := range entityTypes {
		m, err := BuildEntityModel(et)
		if err != nil {
			return nil, fmt.Errorf("gocode: GenerateAuditFromGraph: %w", err)
		}
		models = append(models, m)
	}

	auditSrc, err := RenderAuditFile(models, nil, nil)
	if err != nil {
		return nil, fmt.Errorf("gocode: GenerateAuditFromGraph: %w", err)
	}
	return map[string][]byte{
		"requirements_audit.md": auditSrc,
	}, nil
}
