package gocode

import (
	"fmt"
	"sort"
	"strings"

	"github.com/PHPCraftdream/HotamSpec/internal/ontology"
)

// OwnershipMarker is the exact first line GEN-CODE-CONTRACT.md §1 mandates
// for every generated .go file under domains/<d>/gen/go/. Hand edits inside
// that tree are forbidden, symmetric with the docs/gen/ rule.
const OwnershipMarker = "// AUTOGENERATED from the domain graph.json — do not edit by hand. Edits: methodology/graph -> hotam gen-code"

// knownFieldKinds mirrors GEN-CODE-CONTRACT.md §2's EntityType.fields[]
// row: only "string" and "enum" have a defined Go mapping today. Any other
// kind (e.g. ontology.EntityFieldKinds also allows "number", "reference",
// "state") must make the generator refuse loudly rather than silently
// coerce to string, per the contract's closing paragraph in §2.
var knownFieldKinds = map[string]struct{}{
	"string": {},
	"enum":   {},
}

// UnknownFieldKindError is returned when an EntityType field carries a kind
// this generator does not yet have a Go mapping for (contract §2, final
// paragraph: "генератор обязан явно отказать с именем неизвестного
// элемента").
type UnknownFieldKindError struct {
	EntityType string
	Field      string
	Kind       string
}

func (e *UnknownFieldKindError) Error() string {
	return fmt.Sprintf("gocode: EntityType %q field %q has kind %q, which has no §2 Go mapping in GEN-CODE-CONTRACT.md", e.EntityType, e.Field, e.Kind)
}

// UnknownStateKindError is returned when a lifecycle state carries a kind
// this generator does not recognize (contract §2 only maps "initial" and
// "terminal" explicitly; ontology.StateKinds also defines "normal" and
// "quiescent", both handled below as ordinary/terminal-like states, but any
// future addition must fail loudly, not silently).
type UnknownStateKindError struct {
	EntityType string
	State      string
	Kind       string
}

func (e *UnknownStateKindError) Error() string {
	return fmt.Sprintf("gocode: EntityType %q state %q has kind %q, which has no §2 Go mapping in GEN-CODE-CONTRACT.md", e.EntityType, e.State, e.Kind)
}

// UnknownTransitionStateError is returned when a lifecycle transition's
// `src` or `dst` names a state that is not declared in the same
// EntityType's `lifecycle.states[]` — the graph would be internally
// inconsistent, so the generator refuses rather than emit a Go constant
// reference that does not exist (contract §0: refuse loudly, never guess).
type UnknownTransitionStateError struct {
	EntityType string
	Event      string
	State      string
	Which      string // "src" or "dst"
}

func (e *UnknownTransitionStateError) Error() string {
	return fmt.Sprintf("gocode: EntityType %q transition %q: %s state %q is not declared in lifecycle.states[]", e.EntityType, e.Event, e.Which, e.State)
}

// DuplicateTransitionEventError is returned when two transitions on the same
// EntityType share the same `event` name. Contract §2 maps one Go method per
// `event` ("по одному методу ... на event"); two transitions with the same
// event would collide on the same Go method name, which is exactly the kind
// of unresolvable ambiguity §0 requires the generator to refuse loudly on,
// rather than silently emit one method that only reflects one of the two
// transitions (or invalid duplicate-method Go source).
type DuplicateTransitionEventError struct {
	EntityType string
	Event      string
}

func (e *DuplicateTransitionEventError) Error() string {
	return fmt.Sprintf("gocode: EntityType %q has more than one lifecycle transition with event %q — cannot map to a single Go method (GEN-CODE-CONTRACT.md §2)", e.EntityType, e.Event)
}

// entityModel is the resolved, Go-identifier-shaped view of one
// ontology.EntityType, built once so struct/enum/Validate rendering never
// re-derives identifiers (and thus can never disagree with each other).
type entityModel struct {
	src         ontology.EntityType
	structName  string
	stateType   string
	states      []stateModel
	fields      []fieldModel
	transitions []transitionModel
}

type stateModel struct {
	src      ontology.State
	constant string // e.g. StateNameDraft
	value    string // original graph state name, used as the string value
}

// transitionModel is the resolved, Go-identifier-shaped view of one
// ontology.Transition: the event's Go method name plus the already-resolved
// src/dst state constants it references (contract §2: "lifecycle.transitions[]
// -> по одному методу ... на event").
type transitionModel struct {
	src        ontology.Transition
	methodName string     // e.g. ApprovePM (event, PascalCase)
	srcState   stateModel // resolved lifecycle.states[] entry for src
	dstState   stateModel // resolved lifecycle.states[] entry for dst
}

type fieldModel struct {
	src       ontology.EntityField
	fieldName string // exported Go field name
	goType    string // "string" or "<Entity><Field>Kind"
	isEnum    bool
	enumType  string // set when isEnum
}

// BuildEntityModel resolves one EntityType's identifiers and validates its
// field/state kinds against the contract's known mapping. It performs no
// rendering — callers use it to produce Go source (RenderEntityType) or to
// inspect the resolved shape in tests.
func BuildEntityModel(et ontology.EntityType) (*entityModel, error) {
	structName, err := ToPascalCase(et.Slug)
	if err != nil {
		return nil, fmt.Errorf("EntityType %q: struct name: %w", et.Slug, err)
	}

	m := &entityModel{
		src:        et,
		structName: structName,
		stateType:  structName + "State",
	}

	for _, s := range et.Lifecycle.States {
		switch s.Kind {
		case ontology.StateKindInitial, ontology.StateKindNormal, ontology.StateKindTerminal, ontology.StateKindQuiescent:
			// recognized — contract §2 explicitly maps initial/terminal;
			// normal/quiescent are ordinary named states with no special
			// generation behavior beyond "a state that exists".
		default:
			return nil, &UnknownStateKindError{EntityType: et.Slug, State: s.Name, Kind: s.Kind}
		}
		stateIdent, err := ToPascalCase(s.Name)
		if err != nil {
			return nil, fmt.Errorf("EntityType %q: lifecycle state %q: %w", et.Slug, s.Name, err)
		}
		m.states = append(m.states, stateModel{
			src:      s,
			constant: m.stateType + stateIdent,
			value:    s.Name,
		})
	}

	for _, f := range et.Fields {
		if _, ok := knownFieldKinds[f.Kind]; !ok {
			return nil, &UnknownFieldKindError{EntityType: et.Slug, Field: f.Name, Kind: f.Kind}
		}
		fieldIdent, err := ToPascalCase(f.Name)
		if err != nil {
			return nil, fmt.Errorf("EntityType %q: field %q: %w", et.Slug, f.Name, err)
		}
		fm := fieldModel{src: f, fieldName: fieldIdent}
		if f.Kind == "enum" {
			fm.isEnum = true
			fm.enumType = structName + fieldIdent + "Kind"
			fm.goType = fm.enumType
		} else {
			fm.goType = "string"
		}
		m.fields = append(m.fields, fm)
	}

	statesByName := make(map[string]stateModel, len(m.states))
	for _, s := range m.states {
		statesByName[s.value] = s
	}

	seenEvents := make(map[string]struct{}, len(et.Lifecycle.Transitions))
	for _, tr := range et.Lifecycle.Transitions {
		if _, dup := seenEvents[tr.Event]; dup {
			return nil, &DuplicateTransitionEventError{EntityType: et.Slug, Event: tr.Event}
		}
		seenEvents[tr.Event] = struct{}{}

		srcState, ok := statesByName[tr.Src]
		if !ok {
			return nil, &UnknownTransitionStateError{EntityType: et.Slug, Event: tr.Event, State: tr.Src, Which: "src"}
		}
		dstState, ok := statesByName[tr.Dst]
		if !ok {
			return nil, &UnknownTransitionStateError{EntityType: et.Slug, Event: tr.Event, State: tr.Dst, Which: "dst"}
		}
		methodName, err := ToPascalCase(tr.Event)
		if err != nil {
			return nil, fmt.Errorf("EntityType %q: lifecycle transition event %q: %w", et.Slug, tr.Event, err)
		}
		m.transitions = append(m.transitions, transitionModel{
			src:        tr,
			methodName: methodName,
			srcState:   srcState,
			dstState:   dstState,
		})
	}

	return m, nil
}

// initialState returns the model's initial lifecycle state, per contract
// §2 ("kind: initial -> значение по умолчанию конструктора"). An EntityType
// with no initial state is a graph-shape error the loader's own
// check_entity_type_lifecycle_wellformed should already have caught
// upstream, but this generator refuses explicitly rather than emit a
// constructor with an undefined starting state.
func (m *entityModel) initialState() (stateModel, error) {
	for _, s := range m.states {
		if s.src.IsInitial() {
			return s, nil
		}
	}
	return stateModel{}, fmt.Errorf("gocode: EntityType %q has no initial lifecycle state", m.src.Slug)
}

// RenderEntityType renders one EntityType as Go source: a doc-commented
// struct (comment verbatim from EntityType.why, contract §2), a state enum
// type + constants (if the EntityType has a lifecycle), one enum type per
// enum-kind field, a constructor starting in the initial state, and a
// Validate() method with one branch per required field (contract §2).
func RenderEntityType(m *entityModel) (string, error) {
	var b strings.Builder

	// --- doc comment + struct ---
	if m.src.Why != "" {
		writeDocComment(&b, m.structName, m.src.Why)
	}
	fmt.Fprintf(&b, "type %s struct {\n", m.structName)
	fmt.Fprintf(&b, "\tState %s\n", m.stateType)
	for _, f := range m.fields {
		if f.src.RefTarget != "" {
			fmt.Fprintf(&b, "\t// %s references %s (ref_target). Real inter-entity resolution\n", f.fieldName, f.src.RefTarget)
			fmt.Fprintf(&b, "\t// is a TODO until this generator resolves ref_target against the\n")
			fmt.Fprintf(&b, "\t// domain's other EntityTypes (GEN-CODE-CONTRACT.md §2, §6).\n")
		}
		fmt.Fprintf(&b, "\t%s %s\n", f.fieldName, f.goType)
	}
	b.WriteString("}\n\n")

	// --- state enum ---
	if len(m.states) > 0 {
		fmt.Fprintf(&b, "type %s string\n\n", m.stateType)
		b.WriteString("const (\n")
		for _, s := range m.states {
			if s.src.Why != "" {
				writeConstComment(&b, s.src.Why)
			}
			fmt.Fprintf(&b, "\t%s %s = %q\n", s.constant, m.stateType, s.value)
		}
		b.WriteString(")\n\n")
	}

	// --- enum-kind fields ---
	for _, f := range m.fields {
		if !f.isEnum {
			continue
		}
		fmt.Fprintf(&b, "// %s is the enum type for %s.%s (kind: enum). The graph does not yet\n", f.enumType, m.structName, f.fieldName)
		fmt.Fprintf(&b, "// enumerate this field's legal values, so no constants are generated —\n")
		fmt.Fprintf(&b, "// this is a named string type standing in for a future closed set.\n")
		fmt.Fprintf(&b, "type %s string\n\n", f.enumType)
	}

	// --- constructor ---
	initial, err := m.initialState()
	if err != nil {
		return "", err
	}
	fmt.Fprintf(&b, "// New%s constructs a %s in its initial lifecycle state (%s).\n", m.structName, m.structName, initial.value)
	fmt.Fprintf(&b, "func New%s() *%s {\n", m.structName, m.structName)
	fmt.Fprintf(&b, "\treturn &%s{State: %s}\n", m.structName, initial.constant)
	b.WriteString("}\n\n")

	// --- Validate() ---
	recv := strings.ToLower(m.structName[:1])
	fmt.Fprintf(&b, "// Validate reports the first missing required field, per GEN-CODE-CONTRACT.md\n")
	fmt.Fprintf(&b, "// §2 (field.required -> a branch in Validate()).\n")
	fmt.Fprintf(&b, "func (%s *%s) Validate() error {\n", recv, m.structName)
	any := false
	for _, f := range m.fields {
		if !f.src.Required {
			continue
		}
		any = true
		fmt.Fprintf(&b, "\tif %s.%s == \"\" {\n", recv, f.fieldName)
		fmt.Fprintf(&b, "\t\treturn fmt.Errorf(\"%s: %s is required\")\n", m.structName, f.fieldName)
		b.WriteString("\t}\n")
	}
	if !any {
		b.WriteString("\t_ = " + recv + "\n")
	}
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n")

	return b.String(), nil
}

func writeDocComment(b *strings.Builder, name, text string) {
	fmt.Fprintf(b, "// %s: ", name)
	writeWrappedCommentBody(b, text, false)
}

func writeConstComment(b *strings.Builder, text string) {
	writeWrappedCommentBody(b, text, true)
}

// writeWrappedCommentBody writes text as one or more "// "-prefixed comment
// lines, verbatim (contract §2: struct doc-comment and transition `why` are
// copied "дословно, не перефразируется") — no truncation, no summarization,
// only line-wrapping so `gofmt`/`go vet` stay happy with source line length.
// Embedded newlines in text are preserved as separate comment lines.
func writeWrappedCommentBody(b *strings.Builder, text string, indent bool) {
	prefix := "// "
	if indent {
		prefix = "\t// "
	}
	for _, line := range strings.Split(text, "\n") {
		b.WriteString(prefix)
		b.WriteString(line)
		b.WriteString("\n")
	}
}

// RenderEntitiesFile renders the full entities.go body for a domain: the
// ownership marker, package clause, imports, then one rendered EntityType
// per graph entity type, sorted by slug for determinism (contract §5).
func RenderEntitiesFile(packageName string, entityTypes []ontology.EntityType) ([]byte, error) {
	sorted := make([]ontology.EntityType, len(entityTypes))
	copy(sorted, entityTypes)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Slug < sorted[j].Slug })

	var b strings.Builder
	b.WriteString(OwnershipMarker)
	b.WriteString("\n\n")
	fmt.Fprintf(&b, "package %s\n\n", packageName)
	b.WriteString("import \"fmt\"\n\n")

	for i, et := range sorted {
		m, err := BuildEntityModel(et)
		if err != nil {
			return nil, err
		}
		rendered, err := RenderEntityType(m)
		if err != nil {
			return nil, err
		}
		b.WriteString(rendered)
		if i != len(sorted)-1 {
			b.WriteString("\n")
		}
	}

	return []byte(b.String()), nil
}
