"""Canon: §Entity — domain-declared business concept with its own lifecycle.

A domain (e.g. a finance app) declares EntityType('customer', lifecycle=…, fields=…)
in its build_graph(); the framework accepts it as first-class and the
check_entity_* family covers every declared type by iteration. No new code per
entity — coverage is generated by iterating g.entity_types and g.entities.

Reuses the §Lifecycle keystone (R-entity-reuses-lifecycle): EntityType.lifecycle
is a Lifecycle, validated by check_lifecycle_wellformed. No parallel state
machinery for entity states.

References:
  M12 — Entity deferred → ships here as the first opt-in domain-declarative aspect.
  R-process-aspect-first — Process landed first, declared drives_entities as
    forward-compat; this module activates that seam.
  R-statemachine-wellformedness — EntityType.lifecycle reuses the same keystone.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from hotam_spec.lifecycle import Lifecycle

ENTITY_FIELD_KINDS: frozenset[str] = frozenset(
    {"string", "number", "enum", "reference", "state"}
)
# state-kind field stores a state name; reference field's ref_target names what it
# points to ("stakeholder", "requirement", "<entity-slug>", etc.).


@dataclass(frozen=True)
class EntityField:
    """Canon: §Entity — one named typed field on an EntityType."""

    name: str
    kind: str  # ∈ ENTITY_FIELD_KINDS
    required: bool = True
    ref_target: str = (
        ""  # for kind=reference: target collection ("stakeholder", "<slug>", …)
    )


@dataclass(frozen=True)
class EntityType:
    """Canon: §Entity — declarative business concept (domain-supplied, not framework-supplied)."""

    slug: str  # kebab-case ("customer", "order", "invoice")
    description: str
    lifecycle: Lifecycle  # ← keystone reuse
    fields: tuple[EntityField, ...] = field(default_factory=tuple)
    why: str = ""


@dataclass(frozen=True)
class EntityInstance:
    """Canon: §Entity — one concrete instance carried by the domain graph.

    RULE: id MUST start with 'ENT-<slug>-' (typed-anchor discipline).
    state MUST be a state in the corresponding EntityType.lifecycle.
    """

    id: str  # 'ENT-<slug>-<name>'
    entity_type: str  # slug of EntityType
    state: str  # value matched by Lifecycle.matches
    field_values: tuple[tuple[str, str], ...] = field(
        default_factory=tuple
    )  # frozen dict-equivalent

    def field_value(self, name: str) -> str | None:
        """Canon: §Entity — lookup a field value by name, or None."""
        for n, v in self.field_values:
            if n == name:
                return v
        return None
