// Origin: one-time bulk extraction by .scratch/selfspec-codegen (task #345, RAC-A) from
// domains/hotam-spec-self/graph.json. That program was a THROWAWAY (run once, never
// committed to git) and is NOT a regeneration path -- it went graph->Go, the OPPOSITE of
// today's sync direction. These literals are HAND-MAINTAINED Go source: edit them directly,
// then mirror Go->graph via `hotam sync-self` (dry-run by default; --confirm-hash to write).
// The "generated" framing describes this file's ORIGIN (task #345's one-time bulk pull from
// the pre-existing JSON graph), not an ongoing regeneration workflow.
//
// Topic: Determinism, Drift, and Store.
//
// STRUCTURAL fields only: Claim, Why, Owner, Status, Relations, Assumptions,
// Enforcement, EnforcedBy, Enforceability, MTag, Summary, CreatedAt, SettledAt,
// BlockedOn, ImplementedBy, VerifiedBy, SourceRefs, DeclOrder. EVENT fields
// (History, GateSignoffs, LastReviewedAt, ReviewAfter, Evidence) are
// deliberately absent — MergeIntoGraph passes them through from the graph's
// existing node untouched.
package selfspec

import "github.com/PHPCraftdream/HotamSpec/internal/ontology"

var _ = Requirements.MustRegister("R-constituting-requirements-converge", ontology.Requirement{
	ID:             "R-constituting-requirements-converge",
	Claim:          "The set of SETTLED requirements composing the operator-prompt shall be pairwise consistent on declared axes, with structural contradictions between constituting atoms forbidden.",
	Owner:          "framework-reviewer",
	Status:         "SETTLED",
	Why:            "SETTLED (BUILD-TRIGGER fired): R-operator-prompt-from-substrate has landed -- gen_spec generates the CONSTITUTION block from SETTLED requirements, making the constituting set explicit and machine-known. PROMOTED STRUCTURAL->ENFORCED (Wave 10, closeable->0): check_constituting_not_in_unresolved_conflict is the machine-checkable face of pairwise consistency -- no unresolved Conflict (DETECTED/ACKNOWLEDGED) may hold two SETTLED constituting atoms while the CONSTITUTION presents both as settled truth. Scoped to the self-host graph (the one that DEFINES this atom): a business domain's DETECTED conflict with SETTLED members is a NORMAL held tension awaiting its resolver (e.g. hotam-dev C-ec1ec532), NOT incoherence, and those atoms do not compose the operator-prompt -- so the demand binds only to the self-host constitution index (honest scope per this atom's own claim 'composing the operator-prompt').",
	Assumptions:    []string{"A-bootstrap-self-applies"},
	Relations:      []ontology.Relation{},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"check_constituting_not_in_unresolved_conflict"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-07-12",
	SourceRefs:     []string{},
	DeclOrder:      83,
})

var _ = Requirements.MustRegister("R-constitution-is-index", ontology.Requirement{
	ID:             "R-constitution-is-index",
	Claim:          "The CONSTITUTION block in root CLAUDE.md shall render each SETTLED requirement as id + enforcement flag [E/S/P] grouped by category, with a pointer to docs/gen/REQUIREMENTS.md for full claims.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "The crystal is a seed plus indexes, not a catalog (R-crystal-reload-by-reference): full claims already live in the generated roster (docs/gen/REQUIREMENTS.md) and enforcement detail in docs/gen/UNENFORCED.md, so carrying them verbatim doubled the block (~38k chars of the 85k crystal). The index keeps every SETTLED anchor resident for the CONFRONT scan while cutting ~16k chars, and is orthogonal to Phase 3: relocating framework-plumbing atoms changes WHICH ids are listed, not the line format. R-operator-prompt-from-substrate stays true — all SETTLED requirements, grouped by category, generated deterministically. Phase 2.2b: claim text removed from index lines — the claim was truncated to 96 chars with ellipsis, contradicting R-crystal-carries-short-form; short_form(claim, summary) is the correct mechanism and lives in REQUIREMENTS.md.",
	Assumptions:    []string{"A-finite-context-operators", "A-compaction-loses-working"},
	Relations:      []ontology.Relation{},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"TestBuildConstitution_ByteIdenticalToFixture"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-07-02",
	SettledAt:      "2026-07-12",
	SourceRefs:     []string{},
	DeclOrder:      198,
})

var _ = Requirements.MustRegister("R-constitution-separates-plumbing", ontology.Requirement{
	ID:             "R-constitution-separates-plumbing",
	Claim:          "The CONSTITUTION index in root CLAUDE.md shall render only business and discipline atoms, relocating framework-plumbing atoms to a generated docs/gen/FRAMEWORK-INVARIANTS.md named by an in-block pointer, with the partition total equal to all SETTLED atoms.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "hotam-spec-self is the framework modeling itself, so a majority of its SETTLED requirements are internal guarantees of the framework's own machinery (Entity/Agent/Domain/Process/Operator-internals/Lifecycle-keystone/Generator/bijection/anchor mechanics/CLAUDE.md machinery) rather than business claims the operator mediates as reality. Phase 3 (task #9) relocates those atoms out of the resident CONSTITUTION index into a generated FRAMEWORK-INVARIANTS.md, reachable by pointer, so the operator's resident index reflects what it actually mediates. This is presentational only: no atom's status changes and no atom is dropped from the full REQUIREMENTS.md roster (kept, not deleted, mirroring R-rejected-preserved-not-deleted's anti-loss discipline).",
	Assumptions:    []string{},
	Relations:      []ontology.Relation{},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"TestBuildFrameworkInvariants_ByteIdenticalToFixture"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-07-02",
	SettledAt:      "2026-07-12",
	SourceRefs:     []string{},
	DeclOrder:      199,
})

var _ = Requirements.MustRegister("R-deterministic-generation", ontology.Requirement{
	ID:             "R-deterministic-generation",
	Claim:          "The Go generator (internal/generator, surfaced as `hotam gen-spec`) shall produce byte-stable LF utf-8 output with no timestamps or randomness — two runs over an unchanged graph yield identical bytes.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Determinism is what makes the anti-drift meta-test possible. Without it, regeneration would never equal the committed file. ENFORCED by TestGenerator_DoubleRegenerateIsIdentical and TestGenerator_GraphJSONDoubleRegenerateIsIdentical (internal/generator/determinism_test.go), which rebuild every generated doc (Requirements, Tensions, Open, Unenforced, Glossary, History, Decisions, Constitution, Entities, RepoMap, FrameworkInvariants, LiveState, Atoms*) plus graph.json twice and assert byte-equality. The Go generators use sorted iteration (internal/loader/sort.go sortedCopy) and no time/random sources, so the output is a pure function of the graph.",
	Assumptions:    []string{"A-python-stack"},
	Relations:      []ontology.Relation{},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"TestGenerator_DoubleRegenerateIsIdentical"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-07-12",
	SourceRefs:     []string{"internal/generator/determinism_test.go", "internal/loader/sort.go"},
	DeclOrder:      4,
})

var _ = Requirements.MustRegister("R-drift-structurally-impossible", ontology.Requirement{
	ID:             "R-drift-structurally-impossible",
	Claim:          "The generated docs/gen/*.md and graph.json shall equal the regeneration of the current graph, byte-for-byte.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Anti-drift meta-test — direct lift of dev-coin's pattern. The human layer (docs/gen) cannot be hand-edited without regeneration catching the drift. ENFORCED by TestGenerator_GraphJSONDoubleRegenerateIsIdentical (internal/generator/determinism_test.go), which rebuilds graph.json twice from the same in-memory graph and asserts byte-identity; its sibling TestGenerator_DoubleRegenerateIsIdentical covers every generated doc (Requirements, Tensions, Open, Unenforced, Glossary, History, Decisions, Constitution, Entities, RepoMap, FrameworkInvariants, LiveState, Atoms*). The generators are pure functions of (graph, today) — sorted iteration via internal/loader/sort.go, no hidden time/random sources — so regeneration over an unchanged graph AND an unchanged explicit today value always reproduces the committed bytes. UPDATED 2026-07-13 (task #96, external-review P0): BuildLiveState/BuildAgentContext/RenderClaudeMDFromTemplate and their transitive callees (diagnose.DiagnoseSignals, diagnose.FreshnessSignals) formerly called time.Now() internally to compute today's date embedded in freshness/status text, which made two regenerations on different calendar days non-identical even with zero graph changes — a hole in this requirement's byte-identity guarantee that let the committed root CLAUDE.md/AGENTS.md/GEMINI.md drift (233/116/91 vs the graph's real 236/160/43) without CI's regen-idempotency check reliably catching it, since a same-day local regen looked clean while the next day's regen would show date-only noise. Fixed by threading today as an explicit parameter through every affected generator/diagnose function (`hotam gen-spec` gained a `--today YYYY-MM-DD` flag, defaulting to time.Now() only at the CLI edge when omitted, matching the existing hotam status/due/land/apply-proposal convention) — see TestBuildLiveState_TodayIsInjectable, TestBuildLiveState_SameTodayIsByteIdentical, TestBuildAgentContext_TodayIsInjectable, TestBuildAgentContext_SameTodayIsByteIdentical, TestRenderClaudeMDFromTemplate_SameTodayIsByteIdentical, TestDiagnoseSignals_TodayIsInjectable, TestDiagnoseSignals_SameTodayIsByteIdentical, and the CLI-level TestGenSpec_SameTodayIsByteIdenticalIncludingCrystal. The byte-identity claim now holds precisely as originally stated once today is held fixed — CI's regen-idempotency step regenerates the root crystals from the committed graph and diffs against the committed tree in one pipeline run (same real-world moment, hence same --today), so it is unaffected by this fix in the common case, but the injectability closes the previously-impossible 'pin a golden fixture and compare byte-for-byte on any day' path and eliminates the class of same-day-only false negatives. UPDATED 2026-07-13 (task #102): a SECOND byte-identity hole, independent of today-threading, lived in the SAME \"resident crystal N chars\" LIVE-STATE line: cmd/hotam/gen_spec.go computed the embedded count by reading the PRE-EXISTING CLAUDE.md on disk (written by the previous run) BEFORE regenerating it, so pass 2 embedded pass 1's file size into a differently-sized file — the line changed every gen-spec pass and never converged, which is exactly why CI's regen-idempotency check (regen twice, diff) was permanently red. The AGENT-CONTEXT.md code path never computed a real count at all (stuck at \"0 chars\" when --claude-md was omitted). Fixed by making the measurement a fixpoint (generator.ComputeCrystalCharCountFixpoint) computed unconditionally per pass and shared by every LIVE-STATE carrier — see TestComputeCrystalCharCountFixpoint_RealDomainGraph, TestGenSpec_CrystalFixpointConvergesAcrossRuns, TestGenSpec_CrystalCharCountIsRenderedFixpoint. The byte-identity claim now holds for two consecutive gen-spec passes over the same tree, which is precisely what CI checks.",
	Assumptions:    []string{"A-python-stack"},
	Relations:      []ontology.Relation{},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"TestGenerator_GraphJSONDoubleRegenerateIsIdentical"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-07-12",
	SourceRefs:     []string{"internal/generator/determinism_test.go", "internal/loader/sort.go"},
	DeclOrder:      1,
})

var _ = Requirements.MustRegister("R-engine-docs-fingerprint-current", ontology.Requirement{
	ID:             "R-engine-docs-fingerprint-current",
	Claim:          "A domain's committed docs/gen/ENGINE-VERSION.md, if present, SHALL carry a stamped engine content fingerprint matching the current engine's own fingerprint (gate.EngineDocsFingerprint), so that a domain whose generated docs were produced by a different engine build is mechanically surfaced as stale.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Consumer-generated documentation can silently lag behind engine evolution: the engine changes in its own commits, the consumer's generated docs sit in a separate repository, and no mechanism told the consumer's resolver 'the engine that produced these docs is not the engine you have now.' This exact class of problem caused the W0.1 regression (task #369's engine upgrade retroactively broke domains in another repository with zero warning). Task #400 closes that gap: gate.EngineDocsFingerprint computes a deterministic sha256 content-hash over internal/generator, internal/ontology, internal/loader (the packages whose changes affect generated-doc shape/content) -- deliberately NOT a raw git commit SHA (too noisy, invalidates on every unrelated commit) NOR a manually-bumped version number (defaults to 'dev' for local builds). generator.BuildEngineVersionMD stamps the short 16-char fingerprint into every domain's docs/gen/ENGINE-VERSION.md on genSpec; check_engine_docs_fingerprint_current fires one violation when the stamped fingerprint disagrees with the current engine's own. ENFORCED by check_engine_docs_fingerprint_current (internal/invariants/engine_version_current.go): unconditional for every domain, honest no-op when the file is absent (same class as check_spec_md_current) or when the current engine's fingerprint cannot be computed (a consumer repo whose engine is a compiled binary without source). No opt-in trigger needed: this is NOT a new obligation riding an already-spent trigger, it is the same class of unconditional staleness check check_spec_md_current/check_domain_claude_md_current already are.",
	Assumptions:    []string{"A-finite-context-operators", "A-compaction-loses-working"},
	Relations:      []ontology.Relation{},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"check_engine_docs_fingerprint_current"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-07-31",
	SettledAt:      "2026-07-31",
	SourceRefs:     []string{"internal/gate/engine_fingerprint.go", "internal/generator/engine_version.go", "internal/invariants/engine_version_current.go"},
	DeclOrder:      275,
})

var _ = Requirements.MustRegister("R-enforceability-kind-declared", ontology.Requirement{
	ID:             "R-enforceability-kind-declared",
	Claim:          "A requirement shall carry an enforceability kind from the set ENFORCEABLE or INHERENTLY_PROSE, distinguishing real closeable debt from permanent discipline.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "The enforcement-gradient P0 REFLECTION conflated two categories: requirements that could have a check_* but don't yet (real debt) and requirements that are fundamentally judgment calls no check_* could ever verify (permanent discipline). Without this distinction the debt metric never converges -- inherent-prose rules were counted as debt forever. Splitting the two makes the P0 REFLECTION an honest, closeable signal.",
	Assumptions:    []string{"A-python-stack"},
	Relations:      []ontology.Relation{},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"check_enforceability_kind_known"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-07-01",
	SettledAt:      "2026-07-01",
	SourceRefs:     []string{},
	DeclOrder:      186,
})

var _ = Requirements.MustRegister("R-m-tag-format-valid", ontology.Requirement{
	ID:             "R-m-tag-format-valid",
	Claim:          "Every Requirement.m_tag (when non-empty) shall match `^M[1-9][0-9]*$`, be unique across the graph, and appear only on OPEN requirements.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "The M-decision registry (DECISIONS.md) bijection depends on m_tag discipline. Was orphan policy; now claimed. Atomic — one concern (M-tag well-formedness) with three sub-rules all in one check_*; if we later split the check, this R splits with it.",
	Assumptions:    []string{"A-text-grounded-in-models"},
	Relations:      []ontology.Relation{},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"check_m_tag_valid_format", "check_m_tag_unique", "check_m_tag_open_only"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-06-30",
	SourceRefs:     []string{},
	DeclOrder:      81,
})

var _ = Requirements.MustRegister("R-no-hand-edit-graph", ontology.Requirement{
	ID:             "R-no-hand-edit-graph",
	Claim:          "Changes to domains/*/graph.json shall be made only through `hotam apply-proposal` / `hotam land` (or, for a self-hosting domain's Requirement/Rejection structural fields, through `hotam sync-self` projecting internal/selfspec.Requirements onto the graph), with direct hand-edits prohibited outside of bootstrap events.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "The closed loop's ACT half goes through the proposal writer (R-active-loop-apply-tool). The sanctioned write path is `hotam apply-proposal <file.json>` or `hotam land` (cmd/hotam/apply_proposal.go, cmd/hotam/land.go), which load a Proposed* JSON, validate it, mutate the in-memory graph, check for new invariant violations, and only then write graph.json + graph.lock (internal/proposal/apply.go). Not yet implemented as a deterministic host-hook guard: the CLI is a pure command-line tool with no PreToolUse / host-hook integration, so there is no mechanism that mechanically blocks direct Edit/Write on graph.json. (Historically the Python _graph_guard.py PreToolUse hook provided that mechanical block.) Without a guard on graph.json, a hand-edit can bypass the proposal protocol's validation+invariant-check gate -- the same self-judging-the-judge problem (Enf#3, supervector A). PROSE (not ENFORCED): no enforcer exists. ENFORCED 2026-07-13: TestNoHandEditGraph_RealDomainLocksPinCurrentGraph in internal/loader/lock_real_domains_test.go mechanically verifies this claim -- but only for THIS repo's own two domains (hotam-spec-self, hotam-dev), and only as a TEST, never as part of `hotam all-violations` itself, so a hand-edited CONSUMER domain graph.json (e.g. an adopting repo's domains/prat, domains/gpsm-sm) reported '0 violations -- graph clean' even with a stale lock (@fh adversarial review finding F6). ENFORCED_BY WIDENED 2026-07-17: check_graph_lock_pins_graph_json (internal/invariants/domain_structure.go) moves the same loader.VerifyLock machinery into the graph-generic invariant registry, keyed off g.DomainDir (populated by loader.LoadGraph for every domain, self-hosting or consumer) so it runs inside `hotam all-violations` itself for ANY domain, closing the gap the test-only enforcer left open. MECHANISM WIDENED 2026-07-24 (task #351, RAC-B4, the closing step of RAC-B/task #346's authority flip): for THIS repo's own self-hosting domain (domains/hotam-spec-self), a Requirement/Rejection node's structural fields (Claim, Owner, Status, Why, Assumptions, Relations, Enforcement, EnforcedBy, MTag, Enforceability, Summary, CreatedAt, SettledAt, SourceRefs, DeclOrder, BlockedOn, ImplementedBy, VerifiedBy) are now authored in Go (internal/selfspec's requirements_<topic>.go files) and projected onto graph.json by `hotam sync-self` (RAC-B2, task #349) -- apply-proposal/land now REFUSE Kind=Requirement/Rejection proposals on a self-hosting domain outright (RAC-B3, task #350), so `hotam sync-self` is the only sanctioned path for such an edit, never a direct graph.json write. check_self_requirements_match_registry (internal/invariants/selfspec_shadow.go), promoted from a RAC-A shadow-only advisory to a real All-registered gate in this same step, is what makes a hand-edit to those fields mechanically detectable: it fails `hotam all-violations` whenever internal/selfspec.Requirements and domains/hotam-spec-self/graph.json's Requirement nodes structurally disagree, closing the orphan-enforcer gap check_bijection_r_to_enforcer would otherwise flag for that check_* function. settled_at RESTORED 2026-07-13 from git HEAD 9af0176 (pre-corruption value) after a mutate.go bug this session silently reset it on content-only updates; see task #84.",
	Assumptions:    []string{"A-python-stack"},
	Relations:      []ontology.Relation{},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"TestNoHandEditGraph_RealDomainLocksPinCurrentGraph", "check_graph_lock_pins_graph_json", "check_self_requirements_match_registry"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-07-12",
	SourceRefs:     []string{"internal/proposal/apply.go", "internal/loader/lock_real_domains_test.go", "internal/invariants/domain_structure.go"},
	DeclOrder:      171,
	ImplementedBy:  []string{"internal/proposal/apply.go:Apply"},
	VerifiedBy:     []string{"internal/loader/lock_real_domains_test.go:TestNoHandEditGraph_RealDomainLocksPinCurrentGraph"},
})

var _ = Requirements.MustRegister("R-no-observation-type", ontology.Requirement{
	ID:             "R-no-observation-type",
	Claim:          "The ontology (internal/ontology) shall define no Observation or Evidence struct type anywhere -- Assumption remains the ontology's sole belief-carrying node type.",
	Owner:          "framework-reviewer",
	Status:         "SETTLED",
	Why:            "Wave 1 mechanical-honesty pass (2026-07-02): R-observation-evidence-scope (STRUCTURAL, M21 resolver verdict) makes a broader claim -- operator epistemics live in the working dialogue, crystallized only on request -- that is not fully machine-checkable (no static scan can verify 'lives in the dialogue'). But its NEGATIVE half -- no separate Observation/Evidence type exists -- IS mechanically checkable. Split out as its own atom (R-commit-boundary-checkable's slice-of-a-broader-claim pattern) so the mechanical slice can honestly reach ENFORCED while the parent claim (R-observation-evidence-scope) stays STRUCTURAL, undiluted by a partial enforcer. No Observation or Evidence struct is defined anywhere in internal/ontology/ -- Assumption (internal/ontology/assumption.go) is the sole belief-carrying node type. STRUCTURAL: the negative-existence guarantee is real (no such struct exists) but not machine-checked. (Historically the Python enforcement was an AST scan of spec/src/hotam_spec/*.py for a class named Observation or Evidence; an equivalent enforcer would scan internal/ontology/*.go for a struct of that name, but none is registered.) ENFORCED 2026-07-13: TestNoObservationType in internal/selfcheck/ontology_shape_test.go mechanically verifies this claim by static source scan: no type declaration named Observation or Evidence exists in non-test internal/ontology/*.go (Assumption remains the sole belief-carrying node type). settled_at RESTORED 2026-07-13 from git HEAD 9af0176 (pre-corruption value) after a mutate.go bug this session silently reset it on content-only updates; see task #84.",
	Assumptions:    []string{"A-most-knowledge-crystallizable"},
	Relations:      []ontology.Relation{{Kind: "refines", Target: "R-observation-evidence-scope"}},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"TestNoObservationType"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-07-02",
	SettledAt:      "2026-07-12",
	SourceRefs:     []string{"internal/ontology/assumption.go"},
	DeclOrder:      217,
})

var _ = Requirements.MustRegister("R-observation-evidence-scope", ontology.Requirement{
	ID:             "R-observation-evidence-scope",
	Claim:          "Operator epistemics (observations, beliefs, reasoning) shall live in the working dialogue, crystallized into the substrate only on request.",
	Owner:          "framework-reviewer",
	Status:         "SETTLED",
	Why:            "M21. Resolver verdict 2026-07-02 (verbatim): «нужно думать в чате. И по просьбе в чате записывать свои мысли» (English: 'need to think in chat. And on request in chat, write down one's thoughts'). This settles the M21 question against modeling belief-vs-reality drift as new first-class types: an operator's live reasoning stays in the session dialogue (the mediation loop's CONFRONT/TRANSLATE steps), and is crystallized into a typed node ONLY when explicitly asked to (mirrors R-crystallize-knowledge-to-code's on-demand discipline). REQUALIFIED 2026-07-02 (Wave 7 move 2 honesty pass): previously carried default enforceability=ENFORCEABLE, which listed it as closeable debt in UNENFORCED.md -- but no check_* can ever verify 'an operator kept its reasoning in the dialogue and crystallized only on request' as a property of the committed graph (it is a fact about a conversation, not the graph state). This is the same honesty class as R-initiator-supplies-domain-content: a real, permanent dialogue discipline that is INHERENTLY_PROSE, not ENFORCEABLE-but-unbuilt. RE-ATOMIZED Wave 8 move 2 (2026-07-03): the compound-claim audit (historically performed by the Python audit_atomicity tool, not yet implemented as a Go command) flagged the prior claim as COMPOUND -- it also asserted 'Assumption remains the only belief-carrying node type -- no separate Observation/Evidence types', which duplicates R-no-observation-type (SETTLED, STRUCTURAL); that mechanically-checkable half already lives there. Trimmed this claim to the dialogue-discipline half only (the genuinely INHERENTLY_PROSE half with no duplicate owner) -- R-no-observation-type remains the sole, undiluted owner of the negative-existence half. No semantic narrowing: both halves are still live exactly as before, now under two non-overlapping atoms. settled_at RESTORED 2026-07-13 from git HEAD 9af0176 (pre-corruption value) after a mutate.go bug this session silently reset it on content-only updates; see task #84.",
	Assumptions:    []string{"A-most-knowledge-crystallizable"},
	Relations:      []ontology.Relation{},
	Enforcement:    "STRUCTURAL",
	EnforcedBy:     []string{},
	MTag:           "",
	Enforceability: "INHERENTLY_PROSE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-07-12",
	SourceRefs:     []string{},
	DeclOrder:      63,
})

var _ = Requirements.MustRegister("R-parallel-mutating-agents-use-worktree", ontology.Requirement{
	ID:             "R-parallel-mutating-agents-use-worktree",
	Claim:          "Parallel agent invocations that mutate tracked repository files shall use git worktree isolation unless their target files are provably disjoint and no history-rewriting git operation is planned during their execution window.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Incident 2026-06-30/07-01: two parallel agents (P5-noise-fix and enforceability-flag tasks) both touched overlapping graph and invariants territory in one shared working tree. A subsequent git filter-repo hard-reset (run by the director to purge .idea/__pycache__ from committed history) wiped one agent's uncommitted work because it had not yet been committed and was not isolated in a worktree. The fix had to be redone from scratch. This requirement crystallizes the lesson: parallel mutating agents belong in isolated worktrees, or the director must guarantee no history-rewrite runs while their work is uncommitted. Not yet implemented as an enforced mechanism -- no spawn-log / worktree-isolation-status tooling exists (the spawn-log-isolation-status tool is Planned, not Implemented). The discipline is INHERENTLY_PROSE: it is a fact about an operating procedure (parallel agent orchestration), not a property of the committed graph that a check_* can verify. settled_at RESTORED 2026-07-13 from git HEAD 9af0176 (pre-corruption value) after a mutate.go bug this session silently reset it on content-only updates; see task #84.",
	Assumptions:    []string{"A-python-stack"},
	Relations:      []ontology.Relation{},
	Enforcement:    "STRUCTURAL",
	EnforcedBy:     []string{},
	MTag:           "",
	Enforceability: "INHERENTLY_PROSE",
	Summary:        "",
	CreatedAt:      "2026-07-01",
	SettledAt:      "2026-07-12",
	SourceRefs:     []string{},
	DeclOrder:      187,
})

var _ = Requirements.MustRegister("R-per-node-json-store", ontology.Requirement{
	ID:             "R-per-node-json-store",
	Claim:          "Each graph node (Requirement/Conflict/Assumption/...) shall be persisted in its own separate JSON file, with a schema validating each file on load, instead of living in the single graph.py.",
	Owner:          "framework-author",
	Status:         "REJECTED",
	Why:            "REJECTED — REPLACES by storage = the Python code itself. (a) Technically this is NOT R-rdf-store: no RDF triples, no SHACL shapes, no SPARQL — just one plain JSON file per node plus a load-time schema check. (b) It is rejected anyway because it violates the same underlying principle the RDF proposal violated: storage = the Python code itself. Per-node JSON would introduce a parallel source of truth (files that can drift from graph.py's build_graph()) and a schema layer duplicating the frozen-dataclass constructors — the exact anti-pattern criticized in SHACL (validation that re-states the check_* invariants / the constructors). The generated docs/gen/graph.json snapshot already gives any reader a machine-readable export, read-only, with the Python code remaining the single writer. (c) REVISIT WHEN either of two triggers appears: a SECOND legitimate writer of the graph emerges (something other than apply_proposal.py editing graph.py), OR a real non-Python consumer appears for which the generated export is insufficient and needs the store itself to be language-neutral. — (was: External product review proposed per-node JSON files as the primary store.)",
	Assumptions:    []string{},
	Relations:      []ontology.Relation{},
	Enforcement:    "PROSE",
	EnforcedBy:     []string{},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-07-10",
	SettledAt:      "",
	SourceRefs:     []string{},
	DeclOrder:      270,
})

var _ = Requirements.MustRegister("R-prefer-tool-over-hand", ontology.Requirement{
	ID:             "R-prefer-tool-over-hand",
	Claim:          "The operator shall prefer a reusable tool over performing the same action by hand, with one-off acts permitted only for genuine bootstrap or single-occurrence events.",
	Owner:          "ai-agent",
	Status:         "SETTLED",
	Why:            "Today's third architectural principle. Cannot be algorithmically enforced (no AST detection of 'you did it by hand'); STRUCTURAL via prose discipline in the operator-prompt + a generated discipline doc. Use SETTLED (not DRAFT) — the principle is now in force; the structural enforcement is the prose.",
	Assumptions:    []string{"A-stakeholders-care"},
	Relations:      []ontology.Relation{},
	Enforcement:    "STRUCTURAL",
	EnforcedBy:     []string{},
	MTag:           "",
	Enforceability: "INHERENTLY_PROSE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-07-12",
	SourceRefs:     []string{},
	DeclOrder:      75,
})

var _ = Requirements.MustRegister("R-project-name-hotam-spec", ontology.Requirement{
	ID:             "R-project-name-hotam-spec",
	Claim:          "The project's name shall be Hotam-Spec (display) and hotam-spec (kebab-case for domain-level artifacts — domain directory names like `domains/hotam-spec-self`, the `hotam` CLI binary name, and repository slug conventions), while the Go module path shall match the real git remote and is deliberately `github.com/PHPCraftdream/HotamSpec` (PascalCase suffix, per commit 4325ac8), closing M1.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "M1 (package name) was OPEN since the framework's first incarnation as 'tensio'. The rename to Hotam-Spec aligns the project with its repository name and the user's chosen identity. UPDATED 2026-07-13 (task #113, decision brief §4): the Go module-path-suffix clause was reworded to legalize the current, deliberately-chosen module path `github.com/PHPCraftdream/HotamSpec` (PascalCase suffix, matching the real git remote — set in commit 4325ac8 'chore: rename Go module to match the real git remote'). The earlier kebab-case-for-module-suffix demand was visibly drifted from reality: the actual go.mod reads 'module github.com/PHPCraftdream/HotamSpec', and renaming it back to kebab-case would be a 119-file / 178-import-occurrence mechanical change that reverses a conscious recent decision (decision brief §4 option (b) over (a), which was flagged as the highest-risk option in the whole batch of 9). Kebab-case remains the rule for domain-level artifacts that already legitimately are kebab/lowercase (directory names like domains/hotam-spec-self, the hotam CLI binary name) — only the module-path-suffix clause changed to match reality. Convention: 'Hotam-Spec' in prose (capitalized hyphen). (Historically a Python package 'hotam_spec' with a PyPI 'hotam-spec' distribution; the project is now a Go module.) Renames completed in three sequential passes (#89 package, #90 domain, #91 prose).",
	Assumptions:    []string{"A-python-stack"},
	Relations:      []ontology.Relation{},
	Enforcement:    "PROSE",
	EnforcedBy:     []string{},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-07-12",
	SourceRefs:     []string{},
	DeclOrder:      185,
})

var _ = Requirements.MustRegister("R-project-root-not-hardcoded", ontology.Requirement{
	ID:             "R-project-root-not-hardcoded",
	Claim:          "HotamSpec resolves the consumer's project root through a single function, paths.ProjectRoot() (internal/paths/project_root.go), via a documented R1-R6 priority chain, never through a raw runtime.Caller-based parents-climb guess at the consumer's files.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "paths.ProjectRoot() (internal/paths/project_root.go) resolves the project root via a six-level priority chain: R1 env HOTAM_SPEC_PROJECT_ROOT, R2 env HOTAM_SPEC_DOMAINS_ROOT (parent), R3 bottom-up search for Go-native markers (domains/, delegations/, or the SECONDARY-marker quorum), R4 .hotam-spec-project marker file, R5 legacy pyproject.toml [tool.hotam-spec].project_root fallback, R6 self-hosting fallback (repo root via go.mod). Every path that reads/writes consumer content (domains/, tickets/, CLAUDE.md, docs/gen) is derived from this resolver. FOUND ISSUE (not fixed): the historical Python claim asserted an AST-scanning enforcer (test_project_root_not_hardcoded.py) that syntactically scans every committed framework .py for a Path(__file__).resolve().parents[N] climb joined to consumer data. No such AST scanner exists -- there is no Go equivalent that syntactically scans internal/*.go for a runtime.Caller-based parents-climb to consumer data. The named enforcer TestProjectRoot_Priority_NativeMarkerBeatsPyproject (internal/paths/) tests the resolver's R3-over-R5 priority, NOT the 'no hardcoded consumer-root climb' discipline. The enforcement/enforced_by are out of scope for this content batch; enforcement is ENFORCED with a priority-chain test that does not verify the no-hardcode claim. settled_at RESTORED 2026-07-13 from git HEAD 9af0176 (pre-corruption value) after a mutate.go bug this session silently reset it on content-only updates; see task #84.",
	Assumptions:    []string{},
	Relations:      []ontology.Relation{},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"TestProjectRoot_Priority_NativeMarkerBeatsPyproject"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-07-09",
	SettledAt:      "2026-07-12",
	SourceRefs:     []string{"internal/paths/project_root.go", "internal/paths/project_root_chain_test.go"},
	DeclOrder:      269,
})

var _ = Requirements.MustRegister("R-rdf-store", ontology.Requirement{
	ID:             "R-rdf-store",
	Claim:          "The tension graph shall be persisted in an RDF triplestore with SHACL shapes and SPARQL traversal.",
	Owner:          "framework-author",
	Status:         "REJECTED",
	Why:            "REJECTED — REPLACES by storage = the Python code itself. RDF adds a heavy parallel substrate over what frozen dataclasses + plain-function traversal already do; SHACL duplicates the check_* invariants; SPARQL is unnecessary at the in-memory graph sizes we serve.",
	Assumptions:    []string{},
	Relations:      []ontology.Relation{},
	Enforcement:    "PROSE",
	EnforcedBy:     []string{},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "",
	SourceRefs:     []string{},
	DeclOrder:      102,
})

var _ = Requirements.MustRegister("R-run-speed-guarded", ontology.Requirement{
	ID:             "R-run-speed-guarded",
	Claim:          "Test-run duration shall not silently degrade: a self-calibrating guard (baseline = mean of the first 5 local runs * 1.2, stored per-machine off-git) fails the suite when a run exceeds the baseline.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Resolver's verbatim need (2026-07-05): real speed must be guarded by code-law; machines differ so no hardcoded constant — first 5 runs calibrate, +20% headroom, per-machine gitignored file. Closes the speed-vs-verification tension (C-ec1ec532 in hotam-dev) with a mediating rule: speed cannot silently regress.",
	Assumptions:    []string{},
	Relations:      []ontology.Relation{},
	Enforcement:    "PROSE",
	EnforcedBy:     []string{},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-07-05",
	SettledAt:      "2026-07-12",
	SourceRefs:     []string{},
	DeclOrder:      264,
	BlockedOn:      "blocked on a timing harness + per-machine baseline store (both absent)",
})

var _ = Requirements.MustRegister("R-sensorium-committed", ontology.Requirement{
	ID:             "R-sensorium-committed",
	Claim:          "The universal sensorium hooks (SessionStart/PostCompact gen_spec, UserPromptSubmit emit_cipher+claude_md_diff_watch+attention_hook, PreToolUse graph-guard, Stop context_producer) shall live in a committed project settings.json generated by a setup tool with commands portable via $CLAUDE_PROJECT_DIR, never only in the personal git-ignored settings.local.json.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Not yet implemented: setup-hooks is Planned in methodology.Tools, and the adapter tools it would wire (attention-hook, claude-md-diff-watch, context-producer, emit-cipher) are all Planned as well. The committed-portable-sensorium generator does not exist: a committed .claude/settings.json exists in the repo, but it is not produced by a setup tool and does not carry the full sensorium hook enumeration. (Historical note: the original generator was tools/setup_hooks.py, which produced the committed project settings.json so that a fresh clone got the pulse and the graph-guard rather than starting blind.) The original WHY stands: hooks that live only in the personal git-ignored settings.local.json leave a fresh clone with no pulse and no graph-guard. PROSE (not ENFORCED): no enforcer exists.",
	Assumptions:    []string{},
	Relations:      []ontology.Relation{},
	Enforcement:    "PROSE",
	EnforcedBy:     []string{},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-07-03",
	SettledAt:      "2026-07-12",
	SourceRefs:     []string{},
	DeclOrder:      244,
	BlockedOn:      "blocked on the setup_hooks tool (Planned in internal/methodology/tools_data.go)",
})

var _ = Requirements.MustRegister("R-setup-claude-generates-settings", ontology.Requirement{
	ID:             "R-setup-claude-generates-settings",
	Claim:          "The file `.claude/settings.json` shall be generated by `spec/tools/setup_claude.py` deterministically; hand-edits are forbidden by a meta-test.",
	Owner:          "framework-author",
	Status:         "REJECTED",
	Why:            "REJECTED — REPLACES the point-installer requirements (R-tool-setup-context-hook et al.): the envisioned single setup_claude.py that would generate settings was never built; the surgical, per-concern installers (setup_context_hook.py --patch-global and friends) won on the ground — configuration is applied one concern at a time, opt-in and user-run, not by one settings-generating entry point. — (was: Single source of truth: Python file generates the JSON; meta-test enforces equality. BUILD-TRIGGER: the prerequisite atomization (R-requirement-claim-is-atomic and R-check-method-is-atomic) has landed — without it, setup_claude.py easily slides back into compoundness.)",
	Assumptions:    []string{"A-python-stack"},
	Relations:      []ontology.Relation{},
	Enforcement:    "PROSE",
	EnforcedBy:     []string{},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "",
	SourceRefs:     []string{},
	DeclOrder:      98,
})

var _ = Requirements.MustRegister("R-smoke-test", ontology.Requirement{
	ID:             "R-smoke-test",
	Claim:          "The test suite shall provide a fast end-to-end signal that the framework is healthy on the real domain graph -- load the graph, run every generator template, and regenerate docs without panicking or empty output.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "An agent after a change should not need to remember the full test count or layout -- one signal means 'the framework did not fall over on real data'. A distributed set of tests together covers that ground: TestGenSpec_SmokeOnRealDomain (internal/generator/byteidentical_test.go) loads the real hotam-spec-self domain graph (domains/hotam-spec-self/graph.json) and runs every generator Build* template (REQUIREMENTS/TENSIONS/OPEN/UNENFORCED/GLOSSARY/HISTORY/DECISIONS/CONSTITUTION/ENTITIES/FRAMEWORK-INVARIANTS/REPO-MAP/live-state plus BuildGraphJSON), asserting non-empty output and no panic; the all-violations coverage is exercised by internal/invariants' own real-graph tests; the harness path is exercised by internal/diagnose integration tests (TestAllFindings_RealGraphNoPanic) and the cmd/hotam CLI tests. The single-test shape is split across packages because tests run per-package, but the collective signal is the same one-health-check intent. (Historical note: this role was originally one end-to-end test, spec/tests/test_smoke.py.) PROSE (not ENFORCED): no single check_* gates this; it is the test suite's role, not an invariant. ENFORCED 2026-07-13: TestSmoke_EveryBuildTemplateOnRealDomainNoPanicNoEmpty in internal/generator/byteidentical_test.go mechanically verifies this claim.",
	Assumptions:    []string{"A-python-stack"},
	Relations:      []ontology.Relation{},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"TestSmoke_EveryBuildTemplateOnRealDomainNoPanicNoEmpty"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-07-12",
	SourceRefs:     []string{"internal/generator/byteidentical_test.go", "internal/diagnose/integration_test.go"},
	DeclOrder:      25,
})

var _ = Requirements.MustRegister("R-speculative-aspects-frozen", ontology.Requirement{
	ID:             "R-speculative-aspects-frozen",
	Claim:          "The Entity aspect, multi-domain federation, and sub-agent recursion machinery shall receive no inward development while frozen, unfreezing only when a real business domain demonstrates concrete need.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Built ahead of demand -- 0 entity_types/entities, exactly 1 domain, 0 active sub-agents against the supporting machinery: classic speculative generality. Frozen by resolver 2026-07-02 after audit. The frozen surface is carried as Planned (not-implemented) methodology.Tools entries -- create-agent, spawn-agent, invoke-agent, create-domain (internal/methodology/tools_data.go) -- plus the Entity aspect substrate that exists but is inert (internal/ontology/entity.go, internal/invariants/scope_process.go Process/Entity checks that no-op when g.EntityTypes is empty). The natural home for this freeze is C-8600b1b8 (core-vs-aspect, ACKNOWLEDGED, revisit_marker reads 'REVISIT when a second opt-in behavioral aspect is proposed'); the freeze remains open pending resolver decision on when to formally move C-8600b1b8 to DECIDED, and do not confuse 'now addressable via ConflictTransition proposals' with 'already resolved.' FOUND ISSUE (not fixed): there is no frozen-aspects snapshot guard -- an inward edit to a frozen file (e.g. adding entity-machinery behavior) would not fail a test. (Historical note: the original Wave 1 guard was a sha256 hash-baseline test, tests/frozen_aspects_baseline.json + test_frozen_aspects_snapshot.py, that made an inward edit fail RED; it was not carried over.) The freeze is currently carried by review discipline + the Planned tool status, not by a structural guard; the requirement is PROSE (not ENFORCED). Unfreeze trigger remains Phase 5 (a real business domain).",
	Assumptions:    []string{},
	Relations:      []ontology.Relation{},
	Enforcement:    "PROSE",
	EnforcedBy:     []string{},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-07-02",
	SettledAt:      "2026-07-12",
	SourceRefs:     []string{"internal/methodology/tools_data.go", "internal/ontology/entity.go"},
	DeclOrder:      200,
})

var _ = Requirements.MustRegister("R-stale-substrate", ontology.Requirement{
	ID:             "R-stale-substrate",
	Claim:          "Crystallized knowledge whose enforcing assumption has died shall be surfaced as stale (enforced-but-wrong, a bad habit).",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "SETTLED (P6): the structural detection path now exists. The stale-substrate signal is produced by ReflectDeadAssumptionOnEnforcer (internal/diagnose/finding.go): for each SETTLED+ENFORCED Requirement whose Assumptions include a DEAD one, it emits a Finding (Condition=\"reflect_dead_assumption_on_enforcer\", Target=requirement id) whose Imperative names the dead assumption and the requirement resting on it -- surfacing the bad-habit case where an enforced rule's premise has quietly died. This Finding flows through AllFindings into the what-now attention signals (internal/diagnose/signal.go) via the same registry as every other reflection predicate (R-reflection-predicates-first-class). Today the hotam-spec-self domain carries zero DEAD assumptions, so no stale substrate actually fires; the structural detection path is in place for when one does. TestReflectDeadAssumptionOnEnforcer_Fires (internal/diagnose/finding_test.go) pins the firing path; TestReflectDeadAssumptionOnEnforcer_ProseNotEnforced pins that PROSE requirements do not trigger it.",
	Assumptions:    []string{"A-compaction-loses-working"},
	Relations:      []ontology.Relation{},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"TestReflectDeadAssumptionOnEnforcer_Fires"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-07-12",
	SourceRefs:     []string{"internal/diagnose/finding.go", "internal/diagnose/signal.go", "internal/diagnose/finding_test.go"},
	DeclOrder:      58,
})

var _ = Requirements.MustRegister("R-tool-is-its-own-requirement", ontology.Requirement{
	ID:             "R-tool-is-its-own-requirement",
	Claim:          "Every tool registered in the methodology.Tools registry whose entry opens with a Canon: §<topic> marker shall be projected into a STRUCTURAL tool-derived requirement R-tool-<basename> with that tool's claim text, enforced by its named enforcer test when one exists.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "The sensor-substrate inversion taken one step deeper: not only does code generate the operator's prompt, the tool IS its own requirement. The claim is the tool's purpose, the registry entry is the declaration, the enforcer test (when present) is the guard. Removing the tool removes the R; lying in the purpose is caught by the enforcer test failing (when one exists). This eliminates the prose gap between 'R written in graph' and 'tool implementing R'. The projection is realized by internal/generator/tool_reqs.go: a static data table (toolRequirementData) carries one ToolRequirement per tool (Basename, CanonSection, Claim, Enforcer); ScanToolRequirements() projects each into R-tool-<basename> (underscores→hyphens); BuildToolDerivedSection() renders them into FRAMEWORK-INVARIANTS.md under 'Tool-derived requirements', and BuildFrameworkInvariants also lists them in the constitution index. (Historical note: the original mechanism scanned spec/tools/*.py for module docstrings opening with 'Canon: §<topic> — <claim>'; that filesystem scan was replaced by the explicit data table, since tools are now CLI subcommands in cmd/hotam/, not discoverable .py modules with parseable docstrings — but the 1:1 tool→R projection discipline is preserved.) PROSE (not ENFORCED): the projection itself has no enforcer test (proven historically by test_tool_derived_requirements.py); the data table is maintained by hand alongside the methodology.Tools registry. ENFORCED 2026-07-13: TestScanToolRequirements_ProjectsEveryEntryToRequirement in internal/generator/tool_reqs_test.go mechanically verifies this claim.",
	Assumptions:    []string{"A-python-stack"},
	Relations:      []ontology.Relation{{Kind: "replaces", Target: "R-setup-claude-generates-settings"}},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"TestScanToolRequirements_ProjectsEveryEntryToRequirement"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-07-12",
	SourceRefs:     []string{"internal/generator/tool_reqs.go", "internal/generator/frameworkinvariants.go"},
	DeclOrder:      149,
})

var _ = Requirements.MustRegister("R-two-altitude-ontology", ontology.Requirement{
	ID:             "R-two-altitude-ontology",
	Claim:          "The methodology shall use ONE ontology at two altitudes: operator is to the methodology as actor is to the business (the methodology plane is the business plane applied reflexively).",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Realized in THIS meta-domain — Hotam-Spec modeling its own design IS the proof that one ontology serves both altitudes. D3 (decided by domain-user 2026-06-30): downgraded STRUCTURAL→PROSE — no structural enforcer exists; the claim is discipline, not check.",
	Assumptions:    []string{"A-bootstrap-self-applies"},
	Relations:      []ontology.Relation{},
	Enforcement:    "PROSE",
	EnforcedBy:     []string{},
	MTag:           "",
	Enforceability: "INHERENTLY_PROSE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-06-30",
	SourceRefs:     []string{},
	DeclOrder:      12,
})

var _ = Requirements.MustRegister("R-wheel-build-atomic-verified", ontology.Requirement{
	ID:             "R-wheel-build-atomic-verified",
	Claim:          "A release artifact shall be produced by a single atomic build command that fuses population + build + a self-check refusing to emit an artifact whose shipped tool-member names do not match the source-of-truth tool set on disk.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Not applicable in the current build model; the original mechanism was specific to a packaging model the framework no longer uses. (Historical note: the uv_build backend packaged only content under src/hotam_spec/; the 26 hotam-* CLI entry points imported their tool scripts from a shipped _tools/ directory populated OUT-OF-BAND just before the build by populate_tools.py; forgetting that manual step shipped a wheel that imported cleanly but had zero working CLI commands, invisible in the repo -- _tools/ was .gitignored. spec/scripts/build_wheel.py fused populate+`uv build --wheel`+verify into one atomic command comparing the SET of _tools/ member names inside the produced .whl against spec/tools/*.py on disk (Etap Y #127, upgraded from a bare member-count comparison to a name-set comparison with an explicit missing/extra diff).) This concern does not arise in the current build model: `go build ./cmd/hotam` compiles all packages natively via the import graph -- there is no out-of-band populate step, no shipped _tools/ directory, and no gap between 'imports cleanly' and 'has working CLI commands'. A release is `go build` producing a single binary; a missing tool would be a compile error, not a silently-broken artifact. The original WHY stands as a design principle (an atomic build with a self-check makes the broken-artifact failure structurally impossible to publish), but the current build model achieves this by construction (the compiler IS the self-check) rather than via a separate verification script. RECLASSIFIED 2026-07-13: enforceability ENFORCEABLE -> INHERENTLY_PROSE (agent consultation, fm) -- the only test available under the current build model would be \"go build succeeds\", which is already exercised by every other test run in CI and would be a vacuous, non-additive assertion specific to this requirement; the actual guarantee this requirement wants is structurally provided by Go's own compiler (a missing tool reference is a compile error), not by a dedicated enforcer.",
	Assumptions:    []string{"A-python-stack"},
	Relations:      []ontology.Relation{},
	Enforcement:    "PROSE",
	EnforcedBy:     []string{},
	MTag:           "",
	Enforceability: "INHERENTLY_PROSE",
	Summary:        "",
	CreatedAt:      "2026-07-10",
	SettledAt:      "2026-07-12",
	SourceRefs:     []string{},
	DeclOrder:      273,
})

var _ = Requirements.MustRegister("R-work-within-launch-dir", ontology.Requirement{
	ID:             "R-work-within-launch-dir",
	Claim:          "A live operator, executing at runtime through shell commands or tool calls, shall confine all file mutations to its launch working directory -- never touching the host harness or global configuration unless the user explicitly requests otherwise; this live-conduct discipline is not statically checkable (no committed-code test can observe a runtime shell-out) and is enforced as honest PROSE.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "SPLIT 2026-07-13 (task #115, decision brief docs/reviews/2026-07-13-category-c2-decision-brief.md section 6 option (a')): this requirement was split into two atoms because its single claim bundled two genuinely different things -- (1) committed framework CODE writing into the host home (statically, mechanically checkable) and (2) a live agent shelling out at RUNTIME to touch the home dir (not statically checkable). The structural/code half is now its own ENFORCED atom R-committed-code-no-home-writes (refines this one), enforced by a Go AST scanner (TestLaunchDirWriteScope_NoHomeWriteColocation in internal/selfcheck/launch_dir_scope_test.go) re-ported from the original Python test_launch_dir_write_scope.py. THIS atom keeps the residual live-agent-runtime-conduct half (2): an operator shelling out through bash/tool-calls at runtime and touching the home directory is not statically observable -- no committed-code test can see it -- so it is honest discipline-of-prose, the same category as R-agent-conduct-is-rules-not-tests, which it now mirrors (enforceability ENFORCEABLE -> INHERENTLY_PROSE, since the live-conduct half is the highest abstraction that code cannot verify). Resolver verdict 2026-07-05 stands verbatim: 'cah вообще нельзя трогать - он ведь обновится всё сотрет. И он в праве быть собой, без наших вмешательств' + 'нужно создать правило, что работаем строго в папке запуска, пока пользователь не попросит иного'. Trigger: the operator proposed setup_context_hook.py --patch-global --apply, which surgically patched the global host configuration -- a double fault: (1) it violates host sovereignty (the harness is a guest environment we inhabit, not own), and (2) it is futile, since a host update overwrites the patch anyway. The framework is a guest in the host's home: it lives strictly within the repository it was launched in; everything outside is sovereign and untouched absent an explicit user request. History: this ID was briefly ENFORCED 2026-07-10 via the Python AST scanner, reverted to PROSE 2026-07-12 when that scanner was not carried forward; the 2026-07-13 split moves the mechanically-checkable half to R-committed-code-no-home-writes (ENFORCED) and keeps the genuinely-unobservable live-conduct half here as INHERENTLY_PROSE -- more honest than a blanket INHERENTLY_PROSE on the original bundled claim (which would have been a regression from its ENFORCED state 3 days earlier), per decision brief section 6.",
	Assumptions:    []string{},
	Relations:      []ontology.Relation{{Kind: "replaces", Target: "R-context-hook-piggybacks-cah-stamp"}, {Kind: "replaces", Target: "R-measure-context-size"}},
	Enforcement:    "PROSE",
	EnforcedBy:     []string{},
	MTag:           "",
	Enforceability: "INHERENTLY_PROSE",
	Summary:        "",
	CreatedAt:      "2026-07-05",
	SettledAt:      "2026-07-12",
	SourceRefs:     []string{},
	DeclOrder:      257,
})
