// Origin: one-time bulk extraction by .scratch/selfspec-codegen (task #345, RAC-A) from
// domains/hotam-spec-self/graph.json. That program was a THROWAWAY (run once, never
// committed to git) and is NOT a regeneration path -- it went graph->Go, the OPPOSITE of
// today's sync direction. These literals are HAND-MAINTAINED Go source: edit them directly,
// then mirror Go->graph via `hotam sync-self` (dry-run by default; --confirm-hash to write).
// The "generated" framing describes this file's ORIGIN (task #345's one-time bulk pull from
// the pre-existing JSON graph), not an ongoing regeneration workflow.
//
// Topic: Authored Spec Layer (spec/model, spec/tests, traceability).
//
// STRUCTURAL fields only: Claim, Why, Owner, Status, Relations, Assumptions,
// Enforcement, EnforcedBy, Enforceability, MTag, Summary, CreatedAt, SettledAt,
// BlockedOn, ImplementedBy, VerifiedBy, SourceRefs, DeclOrder. EVENT fields
// (History, GateSignoffs, LastReviewedAt, ReviewAfter, Evidence) are
// deliberately absent — MergeIntoGraph passes them through from the graph's
// existing node untouched.
package selfspec

import "github.com/PHPCraftdream/HotamSpec/internal/ontology"

var _ = Requirements.MustRegister("R-authored-prose-no-live-tallies", ontology.Requirement{
	ID:             "R-authored-prose-no-live-tallies",
	Claim:          "Authored prose fields that narrate a domain's DURABLE rationale or description -- Process.Why/Step.Why and manifest.json's `goals`/`charter` -- MUST NOT carry a point-in-time status snapshot (a snapshot-marker phrase co-occurring with an ISO date, e.g. \"текущее положение\"/\"по состоянию на\"/\"as of\"/\"current status\" plus a dated claim; or a live \"N из/of M\" tally co-occurring with a stage token from the domain's OWN declared `gate_stage_order`). A live count or dated status claim belongs to a generated projection instead -- PIPELINE.md's generated \"Live state\" section, DOMAIN-MAP's gates line, or an assert-checked orientation_faq phrase template -- never frozen into prose that nothing regenerates. Requirement.Claim and Conflict.Context are DELIBERATELY OUT of this claim's scope for now: they carry more legitimate risk of false positives (a Requirement's claim text can legitimately assert a count or a status word as part of its own normative substance, unlike why/goals/charter's narrower status-narrative role) -- a future requirement MAY extend this discipline there if a design consult finds the same two predicates stay low-noise against that register.",
	Owner:          "framework-author",
	Status:         "DRAFT",
	Why:            "Task #333 (R4F-prose-lint), fourth external review §4.1 synthesis: the \"live numbers baked into durable authored prose\" smell task #331 found and fixed for Process.Why/Step.Why (prat/gpsm-sm's Process.Why literally read \"27 из 32 ФТ... ТЕКУЩЕЕ ПОЛОЖЕНИЕ на 2026-07-21\" while the graph had since moved to 32/32) is not unique to that one field -- it is a CLASS affecting any authored text field. Confirmed live in the same sibling domain: gpsm-sm's manifest.json `goals` field, before task #329's rewording, baked in an identical \"32/32 SIGNED\"-shaped snapshot. This requirement generalizes #331's engine-portion fix. `internal/invariants/authored_prose_snapshot.go`'s `checkAuthoredProseSnapshot` (renamed from `process_why_snapshot.go`'s `checkProcessWhySnapshotProse`, exported as `AuthoredProseSnapshotWarnings`, replacing `ProcessWhySnapshotWarnings` -- wired into `cmd/hotam`'s non-blocking ADVISORY section exactly as before, `all_violations.go:printAdvisorySection`, never registered in the `All` registry) now ALSO scans manifest.json's `goals` (each list entry) and `charter` (a single string), resolved via `loader.ResolveDomainPresentation` -- the identical loader already used by the DOMAIN-MAP/PROJECT-ESSENCE renderers -- with the EXACT SAME two predicates #331 established, no broadening of the pattern set. Verified against both real sibling-repo consumer manifests (read-only inspection, PRAT-hotam is never edited by this engine-side task): `domains/gpsm-sm/manifest.json`'s CURRENT (post-#329) goals/charter text produces zero violations (the rewording that removed the hardcoded tally is exactly the fix this check exists to push toward), and a reconstructed pre-#329-shaped goals sentence (a marker phrase + ISO date, mirroring the real historical smell) DOES fire, proving the check has real teeth. `domains/prat/manifest.json`'s goals/charter also produce zero violations. A scan of `hotam-spec-self`'s own 297-requirement graph found zero real fires of the two precise predicates against `Requirement.Claim`/`Conflict.Context` text (so extending there would currently be a safe no-op), but also found roughly a dozen claims pairing a bare digit with a status word in ordinary normative prose (e.g. a requirement legitimately describing a command's behavior using a count) -- evidence that the CLAIM/CONTEXT register is noisier than why/goals/charter's narrower \"narrate current standing\" role, so this requirement's claim text explicitly declines to extend there for now, leaving the door open to a future design consult.",
	Assumptions:    nil,
	Relations:      []ontology.Relation{{Kind: "refines", Target: "R-domain-overview-projection"}},
	Enforcement:    "PROSE",
	EnforcedBy:     []string{"check_authored_prose_snapshot"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-07-23",
	SettledAt:      "",
	SourceRefs:     []string{"internal/invariants/authored_prose_snapshot.go", "internal/loader/loader.go", "cmd/hotam/all_violations.go"},
	DeclOrder:      0,
	ImplementedBy:  []string{"internal/invariants/authored_prose_snapshot.go:checkAuthoredProseSnapshot"},
	VerifiedBy:     []string{"internal/invariants/authored_prose_snapshot_test.go:TestCheckAuthoredProseSnapshot_FiresOnManifestGoalsPreTask329Shape", "internal/invariants/authored_prose_snapshot_test.go:TestCheckAuthoredProseSnapshot_TrueNegativeOnRealPostTask329GpsmSmGoals"},
})

var _ = Requirements.MustRegister("R-authored-spec-layer-progression", ontology.Requirement{
	ID:             "R-authored-spec-layer-progression",
	Claim:          "Authored spec/ coverage of a domain SHALL proceed in layer order, general before specific, the same skeleton-first discipline R-domain-founded-in-wave-order already applies to graph founding: (1) MODELS -- first author the full skeleton of the domain's object model, every aggregate/entity/value-object that exists, before any one of them is fleshed out; (2) FIELDS -- then author each model's fields/attributes; (3) METHODS -- then author operations/methods, ALL the interactions between models (behavior, invariants, error paths), not just one model's; (4) TESTS -- then author the executable tests that prove requirements against that code. An agent building authored spec/ shall NOT take one requirement all the way from model to test before starting the next; it shall complete each layer across the WHOLE domain before advancing to the next layer.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "PLAN-authored-spec-discipline.md §5 (\"Гейт готовности\", resolver decision 2026-07-16) states the layer order explicitly: \"Сначала полная картина моделей, потом деталь -- не 'одно требование целиком до конца, потом следующее'\", and names the four layers (models -> fields -> methods -> tests) as the coverage progression a coverage-audit tool tracks (\"Coverage-дисциплина отслеживает, на каком слое домен сейчас\"). This is the code-authoring analogue of R-domain-founded-in-wave-order (#203), which already establishes the identical general-before-specific principle for GRAPH founding (skeleton -> artifacts -> rules -> tensions -> data) -- this requirement is the sibling discipline for CODE authoring inside a founded domain's spec/ tree, explicitly refining it rather than duplicating it: R-domain-founded-in-wave-order governs the order in which graph.json nodes (manifest, Process, EntityType, Requirement, Assumption/Conflict, EntityInstance) are landed; this requirement governs the order in which authored Go code (spec/model, spec/model fields, spec/application+policy methods, spec/tests) is written once a domain's requirements already exist. Both are honest roadmap-debt PROSE claims today: no coverage-audit tool yet exists that mechanically detects an agent skipping ahead (e.g. writing one requirement's test before another requirement's model exists) -- PLAN §5's promised \"Coverage-дисциплина\" and PLAN §7's COVERAGE.md generated projection are the not-yet-built enforcers (tracked by PLAN §11 task #225), so this requirement is honest operator discipline today, exactly the same shape as R-domain-founded-in-wave-order's own honest-PROSE status.",
	Assumptions:    nil,
	Relations:      []ontology.Relation{{Kind: "refines", Target: "R-domain-founded-in-wave-order"}},
	Enforcement:    "PROSE",
	EnforcedBy:     nil,
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-07-16",
	SettledAt:      "2026-07-16",
	SourceRefs:     []string{"PLAN-authored-spec-discipline.md"},
	DeclOrder:      0,
})

var _ = Requirements.MustRegister("R-authored-spec-links-mechanically-checked", ontology.Requirement{
	ID:             "R-authored-spec-links-mechanically-checked",
	Claim:          "Every requirement's implemented_by/verified_by entries (path-qualified file:symbol / file:test references into a domain's authored spec/ tree) shall be mechanically checked: the named symbol/test shall exist; a verified_by test shall be non-vacuous (a real assertion or exercising branch, not t.Log-only or empty) and free of an unconditional top-level t.Skip; the same verified_by entry shall not be formally cited by two or more requirements that are not all mutually related via Relations; and a resolvable, non-vacuous, non-skipped verified_by test shall actually PASS when compiled and executed via `go test`, not merely be shaped like a proof.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "PLAN-authored-spec-discipline.md §6 (the mechanical-checks catalog) requires a STRUCTURAL floor under the authored-spec era's implemented_by/verified_by fields (added additively in a prior session, internal/ontology/requirement.go): a stale, vacuous, skipped, promiscuously-reused, or NEVER-ACTUALLY-RUN reference would let ENFORCED mean nothing for a domain's own authored code+tests, exactly the failure PLAN §1 documents from the old generator era (\"t.Log('no structural atom') in 10 of 22 requirements\"). Seven atomic check_* invariants implement this (internal/invariants/authored_links.go): check_implemented_by_symbol_resolvable (the symbol -- function, method, or type -- really exists), check_verified_by_test_resolvable (the test really exists and is Test*-shaped with the real go-test signature), check_verified_by_test_has_teeth (a resolvable verified_by test whose body is empty or t.Log-only fires), check_verified_by_test_no_skip (an unconditional top-level t.Skip/t.Skipf fires), check_verified_by_no_unrelated_reuse (the same verified_by entry formally cited by requirements that do not all collapse into one connected component under the Relations adjacency is a red flag), and check_verified_by_test_passes (@fh finding F1, Probe C, added this session: every check before it is AST-only -- it inspects the TEST's source text but never actually COMPILES or RUNS it, so a requirement could stay ENFORCED with a verified_by test that fails or does not even compile as long as the test's SHAPE looked right; Probe C demonstrated this concretely by gutting an implementation, e.g. a validation method rewritten to unconditionally return nil, which turned `go test` red for that package while every AST-only check stayed green. check_verified_by_test_passes closes that gap: for every verified_by entry that already resolved, has teeth, and is not skipped, it actually invokes `go test -run` via internal/gate.RunVerifiedByTest against the owning Go module -- the domain's own spec/ module for an ordinary domain, or the engine's own module for a self-hosting domain, resolved by gate.ModuleRoot walking up to the nearest go.mod -- and requires PASS; a non-zero exit, a FAIL in the output, or a compile failure fires a violation naming the test and a bounded tail of the actual go-test output. PERFORMANCE (design decision A): results are memoized in a process-lifetime cache (gate.RunVerifiedByTest) keyed by (package directory, test name) with content-hash invalidation over go.mod/go.sum plus every *.go file in the test's own package directory (gate.hashPackageInputs) -- not just the two named files, since `go test` compiles the WHOLE package and Probe C's mutation shape is exactly an impl-file edit in a file the test does not itself name -- so an unchanged spec is not re-run on every all-violations call, while any relevant edit forces a real re-run. RECURSION: a self-hosting domain's own graph names its own engine test files as verified_by targets, and several of the engine's own package test suites (internal/invariants, internal/generator, cmd/hotam) themselves call AllViolations against that same real graph -- gate.RunVerifiedByTest carries a recursion guard (HOTAM_VERIFIED_BY_EXEC_GUARD env var set on every spawned `go test` child) so a nested invocation reports Skipped (no violation either way) instead of spawning an unbounded further generation; the outer, non-nested invocation is the one that actually proves it. CONCURRENCY: checkVerifiedByTestPasses fans independent RunVerifiedByTest calls out across a small bounded worker pool (4 workers) rather than running them sequentially, since each is I/O-bound subprocess work, not CPU-bound.) HONESTY BOUNDARY (§6): these checks hold the structural floor only -- symbol/test exists, runs, is not hollow, is not skipped, is not promiscuously reused, and (as of check_verified_by_test_passes) actually PASSES -- they do NOT and cannot verify that a test SEMANTICALLY proves the requirement's claim; that remains a mirror audit performed by a human or an LLM reading the pair (requirement text, authored code+test), never encoded as a lexical/semantic heuristic in the graph invariant layer. All seven checks are structurally NO-OP for any requirement with empty implemented_by/verified_by (both fields remain optional); mutation-proof coverage lives in internal/gate/spec_resolver_test.go, internal/gate/test_exec_test.go, and internal/invariants/authored_links_test.go (each check has a break-then-fix round-trip test proving it fires on a real mutated fixture and clears once fixed; check_verified_by_test_passes additionally has TestRunVerifiedByTest_MUTATION_CacheInvalidatesOnImplChange, an impl-only mutation round-trip proving the cache is invalidated by a sibling file edit, never just a test-file edit).",
	Assumptions:    nil,
	Relations:      []ontology.Relation{{Kind: "refines", Target: "R-enforced-by-resolvable"}},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"check_implemented_by_symbol_resolvable", "check_verified_by_test_resolvable", "check_verified_by_test_has_teeth", "check_verified_by_test_no_skip", "check_verified_by_no_unrelated_reuse", "check_verified_by_test_passes"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-07-16",
	SettledAt:      "2026-07-16",
	SourceRefs:     []string{"internal/invariants/authored_links.go", "internal/invariants/authored_links_test.go", "internal/gate/test_exec.go", "internal/gate/test_exec_test.go"},
	DeclOrder:      0,
	ImplementedBy:  []string{"internal/invariants/authored_links.go:checkImplementedBySymbolResolvable"},
	VerifiedBy:     []string{"internal/invariants/authored_links_test.go:TestCheckImplementedBySymbolResolvable_MUTATION_StalenessRoundTrip"},
})

var _ = Requirements.MustRegister("R-authored-spec-projections-are-derived", ontology.Requirement{
	ID:             "R-authored-spec-projections-are-derived",
	Claim:          "Every generated document that describes a domain's authored spec/ tree -- TRACEABILITY.md (requirement -> implemented_by symbol -> verified_by test), MODELS.md (an inventory of authored model structs/fields/methods/invariants extracted from spec/model via go/ast), COVERAGE.md (which SETTLED+ENFORCEABLE requirements have real implemented_by/verified_by carriers versus roadmap debt, and which layer per R-authored-spec-layer-progression the domain currently sits at), and UNENFORCED.md's authored-era burn-down -- shall be a GENERATED projection assembled by `hotam gen-spec` from the graph plus the spec/ resolver (internal/gate/spec_resolver.go), and shall NEVER be hand-written or hand-edited. spec/ itself (the domain's authored model/application/policy/tests code) is the one artifact in this pipeline authored by hand and NEVER regenerated or overwritten by the engine; docs/gen/ is the generated side and is ALWAYS safe to regenerate and overwrite.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "PLAN-authored-spec-discipline.md §3 draws the authored/generated line at the directory level (\"spec/ -- AUTHORED код-спека -- пишется РУКАМИ, движок НЕ перезаписывает\" versus \"docs/gen/ -- ГЕНЕРИРУЕМЫЕ проекции -- движок перезаписывает\"), and §7 (\"Генерируемые проекции (вместо кода)\") names the specific four documents this requirement covers: TRACEABILITY.md, MODELS.md, COVERAGE.md, UNENFORCED.md. This is the natural-language DEFINITION half of the authored/generated split; it is distinct from R-domain-overview-projection (#201/PIPELINE.md), which governs a DIFFERENT generated document (the Process/EntityType-driven whole-domain overview, unrelated to spec/ code) and from R-requirement-freshness-fields (#the history mechanism), which governs a DIFFERENT derived artifact (per-node History, not a whole document). Naming this requirement closes the same gap R-domain-overview-projection closes for PIPELINE.md, but for the NEW authored-spec-era documents PLAN §7 introduces -- without this node, an agent reading the self-domain graph would find no anchor stating that TRACEABILITY/MODELS/COVERAGE/UNENFORCED are derived, not authored, and might be tempted to hand-edit them the way spec/ itself is meant to be hand-edited, exactly inverting PLAN §3's authored/generated boundary. Honestly PROSE/feature-blocked today (R-speculative-aspects-frozen's pattern): none of these four generators exist yet in internal/generator (task #225, PLAN §11, not yet executed at authorship time) -- this requirement fixes the CONTRACT the future generator must honor (never hand-write these four documents) before the generator itself is built, the same order R-domain-overview-projection followed for PIPELINE.md.",
	Assumptions:    nil,
	Relations:      []ontology.Relation{{Kind: "refines", Target: "R-domain-overview-projection"}, {Kind: "refines", Target: "R-authored-spec-layer-progression"}},
	Enforcement:    "ENFORCED",
	EnforcedBy:     nil,
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-07-16",
	SettledAt:      "2026-07-16",
	SourceRefs:     []string{"internal/generator/traceability.go", "internal/generator/models.go", "internal/generator/coverage.go", "internal/generator/constitution_entities_framework_repomap_test.go"},
	DeclOrder:      0,
	ImplementedBy:  []string{"internal/generator/traceability.go:BuildTraceability", "internal/generator/models.go:BuildModels", "internal/generator/coverage.go:BuildCoverage"},
	VerifiedBy:     []string{"internal/generator/constitution_entities_framework_repomap_test.go:TestBuildTraceability_ByteIdenticalToFixture", "internal/generator/constitution_entities_framework_repomap_test.go:TestBuildModels_ByteIdenticalToFixture", "internal/generator/constitution_entities_framework_repomap_test.go:TestBuildCoverage_ByteIdenticalToFixture"},
})

var _ = Requirements.MustRegister("R-generations-inherit-doc-test-code", ontology.Requirement{
	ID:             "R-generations-inherit-doc-test-code",
	Claim:          "Every artifact the methodology generates MUST recursively inherit the doc-test-code form: EVERY EntityType MUST yield a Go struct, its lifecycle methods, and transition tests; EVERY SETTLED requirement MUST yield a named Go test case (a real assertion when formalizable, an honest skip carrying the rule text otherwise).",
	Owner:          "framework-author",
	Status:         "REJECTED",
	Why:            "REJECTED -- REPLACES by R-requirement-generation-mechanized-by-registry + R-entity-type-realized-by-go-symbol-never-generated per atomicity discipline (R-requirement-claim-is-atomic): the original claim mixed a Requirement-generation concern (already independently ENFORCED via the self-hosting registry, see R-requirement-generation-mechanized-by-registry) with an EntityType-generation concern that pointed in the WRONG direction relative to this framework's own \"Go code is the source of truth\" law (docs/AUTHORED-SPEC-CONTRACT.md §9 already rejected gen-code; generating Go structs/lifecycle-methods/transition-tests FROM an EntityType is backwards, see R-entity-type-realized-by-go-symbol-never-generated's reversed claim).",
	Assumptions:    nil,
	Relations:      []ontology.Relation{},
	Enforcement:    "PROSE",
	EnforcedBy:     []string{},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-07-15",
	SettledAt:      "",
	SourceRefs:     []string{"PLAN-gen-code.md"},
	DeclOrder:      0,
})

var _ = Requirements.MustRegister("R-requirement-generation-mechanized-by-registry", ontology.Requirement{
	ID:             "R-requirement-generation-mechanized-by-registry",
	Claim:          "Every SETTLED Requirement in a self-hosting domain shall be authored as a named Go declaration in internal/selfspec (not merely a JSON graph node), mechanically verified byte-identical to the projected graph via `hotam sync-self`.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "The surviving, already-true half of R-generations-inherit-doc-test-code's original bundled claim, split out atomically (R-requirement-claim-is-atomic) rather than left bundled with the EntityType-generation debt half the parent requirement also carried. Task #345 (RAC-A) introduced internal/selfspec.Requirements, a Go registry of ontology.Requirement values; task #349 (RAC-B2) added `hotam sync-self`, which projects that registry onto domains/hotam-spec-self/graph.json; task #351 (RAC-B4) promoted check_self_requirements_match_registry from a shadow-only advisory to a real All-registered gate, so a hand-edit or registry/graph disagreement is mechanically detectable inside `hotam all-violations` itself, not merely a test-only guard. Together these mean EVERY SETTLED requirement on this domain now DOES yield a named Go declaration, not merely a JSON node -- the requirement-generation half of the original bundled claim, now standing on its own as a fully mechanized, ENFORCED anchor rather than sharing a Claim with an unrelated, still-debt-carrying EntityType concern.",
	Assumptions:    nil,
	Relations:      []ontology.Relation{{Kind: "replaces", Target: "R-generations-inherit-doc-test-code"}},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"check_self_requirements_match_registry", "TestMergeIntoGraph_ByteIdenticalRoundTrip", "TestMergeIntoGraph_AllRequirementsRegistered"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-07-30",
	SettledAt:      "2026-07-30",
	SourceRefs:     []string{"internal/selfspec/selfspec.go", "internal/selfspec/merge.go", "cmd/hotam/sync_self.go", "internal/invariants/selfspec_shadow.go"},
	DeclOrder:      0,
})

var _ = Requirements.MustRegister("R-entity-type-realized-by-go-symbol-never-generated", ontology.Requirement{
	ID:             "R-entity-type-realized-by-go-symbol-never-generated",
	Claim:          "An EntityType MAY declare model_symbol naming the Go type in the domain's authored spec/model/ that realizes it; the Go type is the PRIMARY source, EntityType is a graph-level reference/projection of it. The methodology shall NEVER generate a Go struct, lifecycle methods, or transition tests FROM an EntityType -- the direction is Go-code-to-graph, never graph-to-Go-code (docs/AUTHORED-SPEC-CONTRACT.md §9).",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "The reversed-direction successor to R-generations-inherit-doc-test-code's EntityType-half, which pointed the wrong way relative to this framework's own \"Go code is the source of truth\" law: docs/AUTHORED-SPEC-CONTRACT.md §9 already rejected gen-code (generating Go FROM spec), so a requirement demanding an EntityType-to-Go generator was asking for exactly the direction the framework had already rejected elsewhere. Task #395 (W1.3) resolves the underlying honest debt not by building the rejected generator, but by adding the missing LINK in the correct direction: EntityType.ModelSymbol (internal/ontology/entity.go), an optional \"file:Symbol\" reference naming the Go type that already realizes this EntityType, checked by check_entity_type_model_symbol_resolves (internal/invariants/entity_checks.go) -- the same gate.ParseFileColonSymbol/SpecRootForGraph/ResolveSpecSymbol machinery check_implemented_by_symbol_resolvable already uses for Requirement.ImplementedBy. This mechanically closes the CHECKABLE half of this claim (a declared model_symbol really resolves to a real Go declaration). The \"shall NEVER generate FROM EntityType\" half is a negative/prohibition claim with no natural mechanical enforcer of its own -- the same honesty-boundary shape R-authored-spec-projections-are-derived's \"shall NEVER be hand-written\" prohibition and R-structural-floor-vs-mirror-audit's \"shall NEVER be blurred\" prohibition already carry: both are Enforcement=ENFORCED via a real carrier for their checkable half (implemented_by+verified_by pointing at the generator/boundary-proof code) with no enforcer directly proving the negative itself, because a negative existence claim (\"no such generator will ever be written\") is not something a check_* can affirmatively prove -- it can only fail to find evidence the prohibition was violated, which check_entity_type_model_symbol_resolves does not even attempt (it verifies a REFERENCE resolves, not that no generator exists). Following that precedent, this requirement sets Enforcement=ENFORCED on the strength of the checkable reference-resolution half, with EnforcedBy naming the one real gate that closes it.",
	Assumptions:    nil,
	Relations:      []ontology.Relation{{Kind: "replaces", Target: "R-generations-inherit-doc-test-code"}},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"check_entity_type_model_symbol_resolves"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-07-30",
	SettledAt:      "2026-07-30",
	SourceRefs:     []string{"docs/PLAN-code-authority-completion.md", "docs/AUTHORED-SPEC-CONTRACT.md"},
	DeclOrder:      0,
})

var _ = Requirements.MustRegister("R-scenario-spec-obligations-mechanically-enforced", ontology.Requirement{
	ID:             "R-scenario-spec-obligations-mechanically-enforced",
	Claim:          "PLAN-scenario-generated-spec.md §3 W2 (the obligatoriness wave) makes the scenario-generated-spec layer's obligations mechanically real rather than aspirational, and each of its four gates shall be anchored here as the claim it enforces: check_settled_requires_scenario (in a domain whose manifest declares discipline:\"full\", every SETTLED requirement carries a real carrier -- enforced_by OR implemented_by+verified_by+at-least-one-scenario-narrated verified_by test; an honest no-op for every domain that has not opted in); check_scenario_executes_impl (for every authored-path requirement with implemented_by AND verified_by both non-empty, regardless of discipline:full, every implemented_by symbol is actually executed by at least one verified_by test under real `go test -coverprofile` instrumentation); check_spec_md_current (a committed docs/gen/SPEC.md, when present, is byte-identical to a fresh `hotam gen-spec --spec` run; an honest no-op for a domain with no SPEC.md yet); and check_model_complete (in a discipline:\"full\" domain, every authored model object with at least one exported method cited as implemented_by is COMPLETE, each cited method backed by a scenario-narrated verified_by test). Each gate is an honest no-op before its own opt-in trigger fires (no discipline:full, no SPEC.md, no authored-path pair), so the migration is per-domain and carries no long-lived opt-out flag. Task #369 (RAC3-A) added a fifth gate to this same family: check_claim_matches_scenario (in a discipline:\"full\" domain, every Requirement in Claim-derivation scope -- not INHERENTLY_PROSE, carries verified_by entries -- has a Claim matching the concatenation of its verified_by test(s)' currently-recorded hotamspec scenario description(s); an honest no-op for every domain that has not opted in).",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "PLAN-scenario-generated-spec.md §0/§2 D4-D5/§3 W2: the authored-spec discipline MUST be mechanically obligatory once a domain opts in, not held together by text. Before W2, the engine's authored-spec layer was a NO-OP contract (authored_links.go:33-36) -- a consumer domain with zero authored models passed every check cleanly, so the methodology connected into sub-projects as INSTRUCTION only, never as a binding obligation. W2's four gates close that: each turns one facet of the scenario-generated-spec layer (per-requirement carrier existence, coverage-proof of the carrier, generated SPEC.md currency, model-level completeness) into a mechanical gate with an honest opt-in trigger, so obligation is per-domain and one-way (the discipline:\"full\" flip lands in the same commit that completes a domain's migration, per §2 D4). These four check_* invariants are the engine mechanism that makes this requirement ENFORCED; the gates are registered in internal/invariants/ (scenario_discipline.go, scenario_coverage.go, spec_md_current.go, model_complete.go) and each has its own mutation-round-trip test proving it fires on a real mutated fixture and clears once fixed. This requirement is the self-hosting anchor (W3.2 spirit) for the four orphan-enforcer gates check_bijection_r_to_enforcer flagged on hotam-spec-self: the engine holds itself to the same obligation it imposes on consumer domains. Task #369 (RAC3-A) folded a fifth gate into this SAME family (rather than minting a new anchor requirement) for the identical reason check_discipline_ratchet was folded in before it: check_claim_matches_scenario is one more discipline:\"full\"-gated, honest-no-op-when-absent obligation belonging to the scenario-generated-spec layer's own mechanical-obligatoriness contract (drift detection for Claim, the layer's textual output, mirroring check_spec_md_current's drift detection for SPEC.md, the layer's document output) -- registered in internal/invariants/claim_scenario_current.go, with its own mutation-round-trip test (internal/invariants/claim_scenario_current_test.go) proving it fires on a real mutated fixture (a verified_by test's scenario title edited without re-deriving Claim) and clears once re-derived.",
	Assumptions:    nil,
	Relations:      []ontology.Relation{{Kind: "refines", Target: "R-authored-spec-projections-are-derived"}},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"check_settled_requires_scenario", "check_scenario_executes_impl", "check_spec_md_current", "check_model_complete", "check_discipline_ratchet", "check_claim_matches_scenario"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-07-19",
	SettledAt:      "2026-07-19",
	SourceRefs:     []string{"PLAN-scenario-generated-spec.md", "internal/invariants/scenario_discipline.go", "internal/invariants/scenario_coverage.go", "internal/invariants/spec_md_current.go", "internal/invariants/model_complete.go"},
	DeclOrder:      0,
})

var _ = Requirements.MustRegister("R-shared-projections-mode-independent", ontology.Requirement{
	ID:             "R-shared-projections-mode-independent",
	Claim:          "Every docs/gen/ projection generated by plain `hotam gen-spec` (implemented_by TRACEABILITY.md/COVERAGE.md/REPO-MAP.md's own Build* functions) MUST render byte-identically regardless of whether the SAME `gen-spec` invocation also passed `--spec`, EXCEPT SPEC.md itself, which ALWAYS remains the sole `--spec`-shaped artifact whose staleness is separately enforced by check_spec_md_current.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "task #334 (R4F-bind-test, fourth external review §4.3): the requirement landed SETTLED/PROSE with empty implemented_by/verified_by despite a real regression test for exactly this property already existing and being named in the requirement's own claim evidence — TestGenSpec_SharedProjectionsModeIndependent (cmd/hotam/gen_spec_test.go). This claim is about GENERATOR/engine behavior (a property of cmd/hotam/gen_spec.go and internal/generator/traceability.go+coverage.go), the same shape as the neighboring R-empty-content-gen-notice, which binds via enforced_by to a bare Test* name rather than the authored implemented_by+verified_by path (that path is reserved for path-qualified references into a domain's own authored spec/ tree, per internal/invariants/authored_links.go and PLAN-authored-spec-discipline.md §5/§12's disjunctive gate — an engine-self-hosting requirement is not forced to fabricate one). Binding enforced_by alone satisfies check_enforced_requires_enforcer_or_authored_link's disjunction and check_enforced_by_resolvable resolves TestGenSpec_SharedProjectionsModeIndependent via the repo-wide cmd/**/*_test.go scan. Mechanical traceability-completion fix, not a new judgment call — decision-ref: task #334, review-sourced finding, linking an existing test to an existing requirement.",
	Assumptions:    nil,
	Relations:      []ontology.Relation{{Kind: "refines", Target: "R-authored-spec-projections-are-derived"}, {Kind: "depends_on", Target: "R-drift-structurally-impossible"}},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"TestGenSpec_SharedProjectionsModeIndependent"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-07-23",
	SettledAt:      "2026-07-23",
	SourceRefs:     []string{"cmd/hotam/gen_spec.go", "internal/generator/traceability.go", "internal/generator/coverage.go", "cmd/hotam/gen_spec_test.go"},
	DeclOrder:      0,
})

var _ = Requirements.MustRegister("R-shared-tools-in-spec-tools", ontology.Requirement{
	ID:             "R-shared-tools-in-spec-tools",
	Claim:          "Tools available to all operators shall be the single shared hotam CLI toolset -- Go subcommands wired in cmd/hotam/main.go and declared once in the methodology.Tools registry -- with no per-agent private tool namespace.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Scoping rule, structurally enforced by code layout. There is no per-agent tools/ directory; the shared toolset is the set of `hotam <command>` subcommands dispatched in cmd/hotam/main.go, each declared exactly once as a methodology.Tool entry in internal/methodology/tools_data.go (Command/Canon/Purpose/Status, Status=Implemented for wired subcommands, Planned for not-yet-implemented surface). (Historical note: the original rule located shared tools in spec/tools/; there is no spec/ tree in this codebase.) Because there is exactly one operator (OP-director) and zero active sub-agents, every tool is by construction available to all operators -- there is no private-tool namespace to leak. When a real sub-agent is spawned (R-sub-agent-crystal-triad), the same single registry remains the shared floor; per-agent tool customization is deferred until that spawn materializes. SETTLED -- already true today. ENFORCED 2026-07-13: TestSharedTools_InSpecTools in internal/selfcheck/imports_test.go mechanically verifies this claim by static source scan: every Status=Implemented entry in methodology.Tools is wired as a dispatch case in cmd/hotam/main.go, and the registry is the single shared tool namespace (no per-agent tool package).",
	Assumptions:    []string{"A-python-stack"},
	Relations:      []ontology.Relation{},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"TestSharedTools_InSpecTools"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-07-12",
	SourceRefs:     []string{"cmd/hotam/main.go", "internal/methodology/tools_data.go", "internal/methodology/tool.go"},
	DeclOrder:      76,
})

var _ = Requirements.MustRegister("R-spec-link-embodied-vs-proven", ontology.Requirement{
	ID:             "R-spec-link-embodied-vs-proven",
	Claim:          "An authored-spec requirement's link to code shall carry two ORTHOGONAL fields, never collapsed into one: implemented_by names WHERE the requirement is EMBODIED (a path-qualified file:symbol reference into the domain's authored spec/ tree, the model/method that realizes the claim), and verified_by names WHERE the requirement is PROVEN (a path-qualified file:test reference, the executable test that demonstrates the claim holds). A symbol that embodies a requirement without a test that proves it, or a test cited without the symbol it exercises, is an incomplete SpecLink -- ENFORCED status requires both halves together (see R-enforced-requires-enforcer-or-authored-link), but the two fields answer two DIFFERENT questions and shall never be merged into a single field or treated as aliases of one another.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "PLAN-authored-spec-discipline.md §4 (\"Схема связи: requirement -> code -> test\") and §12 (resolver decision 2026-07-16) establish implemented_by/verified_by as two separate fields on Requirement (internal/ontology/requirement.go), landed additively in task #223 and already carrying inline doc comments naming the same embodied/proven distinction (requirement.go:80-96: \"ImplementedBy names WHERE this requirement is embodied\", \"VerifiedBy names WHERE this requirement is PROVEN\"). R-authored-spec-links-mechanically-checked (#223) and R-enforced-requires-enforcer-or-authored-link (#223) already model the MECHANICAL checking of these fields (symbol/test resolvability, non-vacuousness, no-skip, no-reuse) and the DISJUNCTIVE ENFORCED gate that accepts either enforced_by or implemented_by+verified_by together -- but neither requirement states the CONCEPTUAL distinction itself: why two fields exist, what each one MEANS, and why they are not interchangeable. Without this requirement as a first-class node, the SpecLink concept (PLAN §4's requirement->code->test schema) exists only in code comments and PLAN prose, not as a graph anchor a future agent can cite when modeling a business domain's own spec/ tree (task #224 pilot, task #236 recursion into hotam-spec-self's own engine code). This requirement is the missing OBJECT-level node: it names the SpecLink concept and its two fields' distinct semantics, one layer above the two already-landed mechanical-check requirements which govern HOW the fields are validated, not WHAT they mean. F5 remediation (2026-07-17, @fh adversarial review): the previous carrier (implemented_by internal/gate/spec_resolver.go:ResolveSpecSymbol, verified_by a symbol-resolution staleness mutation test) proved a SINGLE field resolves correctly, not that the two fields are ORTHOGONAL -- the claim's own load-bearing word. The new carrier is internal/proposal/mutate.go's resolveImplementedBy AND resolveVerifiedBy together -- two structurally near-identical wrapper functions (both delegate to coalesceSlice with the same clear-sentinel handling) that are consequently easy to cross-wire by accident, proven distinct and independently-addressable by TestApply_Requirement_ImplementedByAndVerifiedByAreOrthogonal (internal/proposal/proposal_test.go): an implemented_by-only UPDATE leaves verified_by byte-identical, a verified_by-only UPDATE leaves implemented_by byte-identical, and each field's own clear-sentinel clears only itself. This is a genuine ORTHOGONALITY proof (mutation-verified: swapping the two resolve calls in mutate.go's apply path makes the test fail), not merely a staleness/resolvability check on one field in isolation.",
	Assumptions:    nil,
	Relations:      []ontology.Relation{{Kind: "refines", Target: "R-authored-spec-links-mechanically-checked"}, {Kind: "refines", Target: "R-enforced-requires-enforcer-or-authored-link"}},
	Enforcement:    "ENFORCED",
	EnforcedBy:     nil,
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-07-16",
	SettledAt:      "2026-07-16",
	SourceRefs:     []string{"internal/proposal/mutate.go", "internal/proposal/proposal_test.go"},
	DeclOrder:      0,
	ImplementedBy:  []string{"internal/proposal/mutate.go:resolveImplementedBy", "internal/proposal/mutate.go:resolveVerifiedBy"},
	VerifiedBy:     []string{"internal/proposal/proposal_test.go:TestApply_Requirement_ImplementedByAndVerifiedByAreOrthogonal"},
})

var _ = Requirements.MustRegister("R-structural-floor-vs-mirror-audit", ontology.Requirement{
	ID:             "R-structural-floor-vs-mirror-audit",
	Claim:          "Two DIFFERENT parties hold two DIFFERENT guarantees over an authored SpecLink, and the boundary between them shall NEVER be blurred: the ENGINE holds the STRUCTURAL floor -- a cited symbol or test really exists, resolves by name against the domain's own authored spec/ tree, is not t.Log-only or otherwise empty (has teeth), is not an unconditional t.Skip, is not formally reused across unrelated requirements, and is not orphaned by a later code change -- while a MIRROR AUDIT, performed by a human or an LLM reading the pair (requirement claim text, authored code+test) without domain-specific heuristics baked into the engine, certifies that the cited test SEMANTICALLY proves the requirement's claim. The engine's structural checks shall NEVER be represented, documented, or relied upon as a substitute for the mirror audit's semantic certification, and the mirror audit's semantic judgment shall NEVER be encoded as a lexical or keyword heuristic inside the graph invariant layer.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "PLAN-authored-spec-discipline.md §6 (\"Каталог механических проверок\") states this boundary as its closing paragraph, calling it out explicitly as an \"honesty boundary\": \"Граница честности: движок держит СТРУКТУРНЫЙ пол. Он не может механически доказать, что тест семантически доказывает требование -- это остаётся зеркальным аудитом.\" R-authored-spec-links-mechanically-checked (#223) already implements and names the six structural checks (symbol/test resolvable, has-teeth, no-skip, no-unrelated-reuse) and its own WHY paragraph already states the boundary in passing (\"HONESTY BOUNDARY (§6): these checks hold the structural floor only... they do NOT and cannot verify that a test SEMANTICALLY proves the requirement's claim; that remains a mirror audit\"). This requirement promotes that boundary from a parenthetical inside #223's WHY text to its OWN first-class graph node, because the boundary is a distinct discipline concept with its own failure mode worth naming and citing independently: the session's own history shows repeated near-misses where lexical/keyword heuristics were proposed as a shortcut for semantic judgment (e.g. the CONFRONT opposite-marker gate's own false-positive collisions, R-authored-spec-links-mechanically-checked's own history entry documents one on 2026-07-16) -- the temptation to fold semantic certification into the engine as \"just one more check_*\" is the exact failure this requirement stands against. PLAN §1 documents the concrete cost of skipping this boundary in the old generator era (\"t.Log('no structural atom') in 10 of 22 requirements... a always-green test is not coverage; it creates the appearance of an executable requirement\") -- the structural floor prevents THAT specific failure (a hollow always-green test), but does not and cannot prevent a technically-real, technically-passing test that simply tests the wrong thing; only a mirror audit catches that. Naming both halves as one requirement (not two) reflects that the discipline IS the boundary between them, not either half alone. F5 remediation (2026-07-17, @fh adversarial review): the previous verified_by carrier (TestCheckVerifiedByTestHasTeeth_MUTATION_VacuousRoundTrip) proved only ONE structural check's own break->fix round trip (vacuous-body detection) -- one brick, not the wall this claim is actually about (the STRUCTURAL-vs-MIRROR boundary itself). The new verified_by carrier, TestStructuralFloorDoesNotCatchSemanticMismatch (internal/invariants/authored_links_test.go), proves the boundary operationally: a requirement claiming Risk-ownership validation is wired to a verified_by test that is completely unrelated (a bare arithmetic assertion) yet passes every structural check the engine has and every enforced_by/authored gate -- the FULL AllViolations sweep reports ZERO violations for a pairing no mirror audit would ever accept. That gap IS the claim: the engine cannot and does not catch this, which is exactly what 'shall never be relied upon as a substitute for the mirror audit' asserts. implemented_by keeps checkVerifiedByTestHasTeeth (internal/invariants/authored_links.go) as the STRUCTURAL-floor half's own embodiment (one of the six mechanical checks the ENGINE side of the boundary actually performs), now paired with a verified_by that demonstrates the boundary rather than one check's internal correctness.",
	Assumptions:    nil,
	Relations:      []ontology.Relation{{Kind: "refines", Target: "R-authored-spec-links-mechanically-checked"}},
	Enforcement:    "ENFORCED",
	EnforcedBy:     nil,
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-07-16",
	SettledAt:      "2026-07-16",
	SourceRefs:     []string{"internal/invariants/authored_links.go", "internal/invariants/authored_links_test.go"},
	DeclOrder:      0,
	ImplementedBy:  []string{"internal/invariants/authored_links.go:checkVerifiedByTestHasTeeth"},
	VerifiedBy:     []string{"internal/invariants/authored_links_test.go:TestStructuralFloorDoesNotCatchSemanticMismatch"},
})

var _ = Requirements.MustRegister("R-vendored-recorder-matches-engine-canon", ontology.Requirement{
	ID:             "R-vendored-recorder-matches-engine-canon",
	Claim:          "A domain's vendored scenario-recorder, when present at <domainDir>/spec/hotamspec/hotamspec.go, MUST be byte-identical (post-banner) to the engine's own canonical recorder source (internal/recorder/canon), so that every domain running the scenario API runs the SAME contract the engine itself defines and generates -- never a stale, locally-patched, or divergent copy. check_recorder_current (internal/invariants/recorder_check.go) mechanically enforces this via a sha256 comparison between the vendored file and the engine canon, and is an honest no-op for a domain that has not yet vendored a recorder (no file at that path).",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "PLAN-scenario-generated-spec.md §2 D1: the scenario-recorder (the hotamspec Scenario/Given/When/Then API) is VENDORED into a consumer domain's own spec/ module as a generated single-package file -- the same crystal-style copy pattern, NOT a cross-module `replace` (which would reopen the NEW-2-bis dependency debt). Vendoring means the domain compiles and runs its OWN copy; without an integrity check that copy could silently drift from the engine canon (a partial update, a local patch, a stale vendoring), so a domain's scenario artifacts would be produced by a DIFFERENT contract than the engine documents and generates SPEC.md from -- defeating the byte-identical-across-domains guarantee the recorder's deterministic renderer exists to provide. check_recorder_current closes that the same filesystem-aware, honest-no-op-when-absent shape check_graph_lock_pins_graph_json already established for graph.json+graph.lock integrity (R-no-hand-edit-graph): a vendored recorder that diverges from the canon is the recorder-side analog of a hand-edited graph, and is detected the same way (sha256, content-addressed). This requirement is the self-hosting anchor (W3.2 spirit) for the orphan-enforcer gate check_bijection_r_to_enforcer flagged on hotam-spec-self: the engine holds its own vendored-recorder integrity obligation, symmetric to the one it imposes on consumer domains.",
	Assumptions:    nil,
	Relations:      []ontology.Relation{{Kind: "refines", Target: "R-authored-spec-projections-are-derived"}},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"check_recorder_current"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-07-19",
	SettledAt:      "2026-07-19",
	SourceRefs:     []string{"PLAN-scenario-generated-spec.md", "internal/invariants/recorder_check.go"},
	DeclOrder:      0,
})

var _ = Requirements.MustRegister("R-vendored-ontology-matches-engine-canon", ontology.Requirement{
	ID:             "R-vendored-ontology-matches-engine-canon",
	Claim:          "A domain's vendored minimal ontology mirror, when present at <domainDir>/spec/hotamontology/requirement.go and/or <domainDir>/spec/hotamontology/registry.go, shall be byte-identical (post-banner) to the engine's own canonical internal/ontology/canon package, so that every domain authoring Requirement identity in Go code relies on the identical structural shape the engine itself defines and generates, rather than a stale, locally-patched, or otherwise diverging copy. check_ontology_vendor_current (internal/invariants/ontology_vendor_check.go) mechanically enforces this via a sha256 comparison between each vendored file and the engine's canon (checked independently per file), and stays a quiet no-op for a domain that has not yet vendored the mirror (no file at either path).",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Task #365 (RAC2 Phase A, \"Go-code-only authority\" for consumer-domain requirements): the goal is for a consumer domain's structural Requirement identity (id/claim/owner/status/relations) to be authored in Go code rather than hand-edited JSON, the same shape hotam-spec-self's own self-hosting already uses (internal/selfspec/requirements_*.go + `hotam sync-self`). Since a domain's spec/ tree is a SEPARATE Go module from the engine (per NEW-2-bis, no cross-module `replace` directive), the minimal Requirement type + generic Registry[T] a domain needs to declare its own requirement literals is VENDORED -- copied byte-for-byte into <domainDir>/spec/hotamontology/, banner-stamped, mirroring the existing scenario-recorder vendoring precedent (internal/recorder/canon + `hotam vendor-recorder`) 1-in-1: same canon/vendor package split, same banner convention, same sha256 post-banner comparison shape. Without an integrity check, a vendored copy could silently drift from the engine canon (a partial update, a local hand-edit, a stale vendoring after an engine upgrade changed the mirror's fields or JSON tags) -- corrupting the round-trip the moment that domain's registry is later projected onto its own graph.json (a later task, #366/#367, not this one). check_ontology_vendor_current closes that gap the same filesystem-aware, honest-no-op-when-absent shape check_recorder_current already established (itself modeled on check_graph_lock_pins_graph_json for graph.json+graph.lock integrity, R-no-hand-edit-graph): a vendored ontology mirror that diverges from the canon is the ontology-side analog of a hand-edited graph, detected the same way (sha256, content-addressed), just checked independently for each of the two vendored files (requirement.go, registry.go) so a partial drift is reported precisely. This requirement is the self-hosting anchor for the orphan-enforcer gate check_bijection_r_to_enforcer, symmetric to R-vendored-recorder-matches-engine-canon's identical role for check_recorder_current: the engine holds its own vendored-ontology-mirror integrity obligation, the same one it imposes on consumer domains that adopt this path. Task #365 is infrastructure ONLY -- it does not implement `hotam sync-domain` or touch internal/proposal/apply.go's self-hosting lock (later tasks #366/#367).",
	Assumptions:    nil,
	Relations:      []ontology.Relation{{Kind: "refines", Target: "R-vendored-recorder-matches-engine-canon"}},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"check_ontology_vendor_current"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-07-26",
	SettledAt:      "2026-07-26",
	SourceRefs:     []string{"internal/ontology/canon", "internal/invariants/ontology_vendor_check.go", "cmd/hotam/vendor_ontology.go"},
	DeclOrder:      0,
})

var _ = Requirements.MustRegister("R-opt-in-trigger-owns-its-own-obligations", ontology.Requirement{
	ID:             "R-opt-in-trigger-owns-its-own-obligations",
	Claim:          "An already-spent opt-in trigger (a manifest.json flag whose flip was accepted by a domain to activate a SPECIFIC, named set of obligations at the time the domain flipped it) is CLOSED to new mechanical obligations: a later check that imposes a NEW class of duty MUST NOT activate merely because that same already-spent trigger is set, and MUST instead require its OWN, separately-declared opt-in trigger -- a new manifest.json flag (or an equally explicit signal) that the domain affirmatively sets to consent to the new obligation. A domain's consent, once given to a NAMED set of obligations, is never silently reinterpreted to cover obligations invented after that consent was given.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Task #388 (W0.1), a live regression against R-scenario-spec-obligations-mechanically-enforced's own law: that requirement's Why text already states the rule this requirement now anchors as its own first-class node -- \"Each gate is an honest no-op before its own opt-in trigger fires... the discipline:\\\"full\\\" flip lands in the same commit that completes a domain's migration.\" Task #369 (RAC3-A, check_claim_matches_scenario) violated exactly that law: it activated on discipline:\"full\" ALONE, an opt-in trigger PRAT-hotam's `prat` and `gpsm-sm` domains had already spent (flipped) long before check_claim_matches_scenario existed, consenting only to the four checks live at that time (check_settled_requires_scenario, check_scenario_executes_impl, check_spec_md_current, check_model_complete). The result was a LIVE regression: `all-violations --domain domains/prat` produced 19 check_claim_matches_scenario violations and `--domain domains/gpsm-sm` produced 22, against two domains that had done nothing wrong -- their claims simply predated a check that retroactively redefined what discipline:\"full\" meant. Task #388 fixes this by giving check_claim_matches_scenario its OWN opt-in trigger, claim_authority:\"scenario\" (loader.ClaimAuthorityScenario, internal/loader/loader.go), required IN ADDITION TO discipline:\"full\" -- neither condition alone activates the check (see claim_scenario_current.go's own doc comment). check_claim_authority_ratchet (internal/invariants/claim_authority_ratchet.go, symmetric with check_discipline_ratchet's F2 ratchet for discipline:\"full\") makes that new trigger's OWN one-way-door promise mechanical: once a domain has explicitly opted into claim_authority:\"scenario\", it cannot silently un-opt. Together, the two checks are the mechanical embodiment of this requirement's claim: a new obligation gets a new, named, separately-ratcheted trigger -- it does not silently ride in on an old one.",
	Assumptions:    nil,
	Relations:      []ontology.Relation{{Kind: "refines", Target: "R-scenario-spec-obligations-mechanically-enforced"}},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"check_claim_authority_ratchet"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-07-30",
	SettledAt:      "2026-07-30",
	SourceRefs:     []string{"internal/loader/loader.go", "internal/invariants/claim_scenario_current.go", "internal/invariants/claim_authority_ratchet.go", "internal/loader/lock.go"},
	DeclOrder:      0,
})

var _ = Requirements.MustRegister("R-public-surface-authority-owns-its-own-obligations", ontology.Requirement{
	ID:             "R-public-surface-authority-owns-its-own-obligations",
	Claim:          "check_public_surface_linked_or_marked's obligation (every EXPORTED authored symbol -- receiver method, interface method, or top-level function/constructor -- is EITHER cited by a SETTLED requirement's implemented_by AND scenario-complete, OR its doc comment carries an explicit INFRASTRUCTURE:/IGNORED: marker with a stated reason) is gated behind its own opt-in trigger, public_surface_authority:\"linked\" (loader.PublicSurfaceAuthorityLinked), entirely INDEPENDENT of discipline:\"full\" -- it does NOT activate merely because a domain has already flipped discipline:\"full\" for the four pre-existing scenario-generated-spec obligations, and it does NOT require discipline:\"full\" as a co-requirement either.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Task #396 (W1.4): check_model_complete only asks 'for every method ALREADY cited as implemented_by, is it scenario-complete?' -- a public method/interface-method/constructor no requirement has ever cited is invisible to that check, so a domain's model can silently accumulate uncovered public surface with no gate noticing. check_public_surface_linked_or_marked (internal/invariants/model_complete_symmetric.go) closes that gap with the SYMMETRIC inverse obligation. This is a BRAND NEW class of duty, and R-opt-in-trigger-owns-its-own-obligations already states the general law it must obey: 'an already-spent opt-in trigger is closed to new mechanical obligations... a new duty requires its own, separately-declared opt-in trigger.' check_model_complete and its three siblings (check_settled_requires_scenario, check_scenario_executes_impl, check_spec_md_current) plus check_discipline_ratchet are ALL already bundled under discipline:\"full\", and TWO REAL CONSUMER DOMAINS (PRAT-hotam/domains/prat, domains/gpsm-sm) had ALREADY flipped that flag long before this check existed, consenting only to the obligation set live at that time -- never to this one. Tacking check_public_surface_linked_or_marked onto discipline:\"full\" would have reproduced EXACTLY the live regression task #369 caused and task #388 fixed: both domains would jump from 0 to many violations overnight, since neither has ever cited an interface method or constructor (those categories did not exist in gate.ScanAuthoredModels before task #393) nor added any infrastructure/ignored marker anywhere. This requirement is the concrete INSTANCE of R-opt-in-trigger-owns-its-own-obligations' general law for this specific new check -- mirroring the identical relationship R-scenario-spec-obligations-mechanically-enforced's own four gates have to their shared anchor -- not a restatement of the general law itself. The mechanical embodiment: public_surface_authority:\"linked\" (internal/loader/loader.go's PublicSurfaceAuthorityLinked, manifest.json's \"public_surface_authority\" field) is a wholly new, independently-resolved DomainManifest field, and check_public_surface_authority_ratchet (internal/invariants/public_surface_authority_ratchet.go, symmetric with check_claim_authority_ratchet) makes that trigger's own one-way-door promise mechanical: once a domain has explicitly opted in (pinned in graph.lock's PublicSurfaceAuthorityLinkedObserved), it cannot silently un-opt. This wave deliberately opts NO real domain into public_surface_authority:\"linked\" -- domains/hotam-spec-self, domains/hotam-dev, and everything under PRAT-hotam stay honest no-ops for this check.",
	Assumptions:    nil,
	Relations:      []ontology.Relation{{Kind: "refines", Target: "R-opt-in-trigger-owns-its-own-obligations"}},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"check_public_surface_linked_or_marked", "check_public_surface_authority_ratchet"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-07-30",
	SettledAt:      "2026-07-30",
	SourceRefs:     []string{"internal/loader/loader.go", "internal/invariants/model_complete_symmetric.go", "internal/invariants/public_surface_authority_ratchet.go", "internal/loader/lock.go"},
	DeclOrder:      0,
})

var _ = Requirements.MustRegister("R-scenario-authority-owns-its-own-obligations", ontology.Requirement{
	ID:             "R-scenario-authority-owns-its-own-obligations",
	Claim:          "check_scenario_quality's obligation (for a SETTLED requirement carrying a scenario, at least one verified_by entry's pass-verdict recorded artifact must have a non-empty title, an exact match between its own req_id and the citing requirement's ID, at least one Then step, and -- for a behavioral scenario carrying a When step -- a strict Given-before-When-before-Then order) is gated behind its own opt-in trigger, scenario_authority:\"quality\" (loader.ScenarioAuthorityQuality), entirely INDEPENDENT of discipline:\"full\"/claim_authority:\"scenario\"/public_surface_authority:\"linked\" -- it does NOT activate merely because a domain has already flipped ANY of those three pre-existing triggers, and it does NOT require any of them as a co-requirement either.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Task #397 (W1.5): check_settled_requires_scenario/check_model_complete's 'has a scenario' bar is purely AST-based (does the test body call hotamspec.NewScenario anywhere, gate.ResolveSpecTest's HasScenario) -- a test that does `s := hotamspec.NewScenario(t, \"R-x\", \"\"); s.Then(\"\", true)` formally satisfies that bar with an empty title, an empty Then description, and (if it also has a Given/When) no guarantee they are recorded in a sensible order, directly undermining the methodology's core claim that 'a claim cannot exist without a GREEN and MEANINGFUL proof beside it' -- not merely without a scenario-constructor call. check_scenario_quality (internal/invariants/scenario_quality.go) closes that gap by inspecting the REAL recorded Artifact (via gate.RunVerifiedByTestRecording, the same call shape check_claim_matches_scenario/DeriveClaimsFromScenarios already use) against four quality rules. This is a BRAND NEW class of duty, and R-opt-in-trigger-owns-its-own-obligations already states the general law it must obey: 'an already-spent opt-in trigger is closed to new mechanical obligations... a new duty requires its own, separately-declared opt-in trigger.' check_settled_requires_scenario/check_model_complete (bundled under discipline:\"full\") and check_claim_matches_scenario/check_public_surface_linked_or_marked (their own separate triggers, claim_authority:\"scenario\" and public_surface_authority:\"linked\" respectively) ALL already have real consumer-domain or historical obligation sets tied to their CURRENT definitions -- tightening any of THEIR existing 'has a scenario' bar to demand quality, instead of giving this new demand its own trigger, would silently break those domains overnight, structurally the same harm task #369 caused and task #388 fixed, regardless of whether the change is framed as 'a new duty' or 'a tightened old one': the practical harm (a domain that opted in under one implicit contract wakes up to new failures with zero action on their part) is identical either way. This requirement is the concrete INSTANCE of R-opt-in-trigger-owns-its-own-obligations' general law for this specific new check -- mirroring the identical relationship R-public-surface-authority-owns-its-own-obligations has to the same shared anchor -- not a restatement of the general law itself. The mechanical embodiment: scenario_authority:\"quality\" (internal/loader/loader.go's ScenarioAuthorityQuality, manifest.json's \"scenario_authority\" field) is a wholly new, independently-resolved DomainManifest field, and check_scenario_authority_ratchet (internal/invariants/scenario_authority_ratchet.go, symmetric with check_public_surface_authority_ratchet) makes that trigger's own one-way-door promise mechanical: once a domain has explicitly opted in (pinned in graph.lock's ScenarioAuthorityQualityObserved), it cannot silently un-opt. This wave deliberately opts NO real domain into scenario_authority:\"quality\" -- domains/hotam-spec-self, domains/hotam-dev, and everything under PRAT-hotam stay honest no-ops for this check.",
	Assumptions:    nil,
	Relations:      []ontology.Relation{{Kind: "refines", Target: "R-opt-in-trigger-owns-its-own-obligations"}},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"check_scenario_quality", "check_scenario_authority_ratchet"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-07-30",
	SettledAt:      "2026-07-30",
	SourceRefs:     []string{"internal/loader/loader.go", "internal/invariants/scenario_quality.go", "internal/invariants/scenario_authority_ratchet.go", "internal/loader/lock.go"},
	DeclOrder:      0,
})
