// Code generated by .scratch/selfspec-codegen (task #345, RAC-A). DO NOT EDIT BY HAND.
// Regenerate by re-running the throwaway codegen program against the current
// domains/hotam-spec-self/graph.json if this topic's requirement set ever needs
// to change.
//
// Topic: Attention (agent-agnostic signal registry).
//
// STRUCTURAL fields only: Claim, Why, Owner, Status, Relations, Assumptions,
// Enforcement, EnforcedBy, Enforceability, MTag, Summary, CreatedAt, SettledAt,
// BlockedOn, ImplementedBy, VerifiedBy, SourceRefs, DeclOrder. EVENT fields
// (History, GateSignoffs, LastReviewedAt, ReviewAfter, Evidence) are
// deliberately absent — MergeIntoGraph passes them through from the graph's
// existing node untouched.
package selfspec

import "github.com/PHPCraftdream/HotamSpec/internal/ontology"

var _ = Requirements.MustRegister("R-attention-agent-agnostic-core", ontology.Requirement{
	ID:             "R-attention-agent-agnostic-core",
	Claim:          "The attention core shall name no agent-platform token (Claude/Anthropic/hook/model name) so a platform adapter is one consumer, never the owner.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Resolver verdict (2026-07-03): 'make the solution universal for any agent, and at the seam make an API for Claude'. The core must therefore know nothing of any one agent platform -- the platform adapter is a thin wrapper, not part of the core. This is the same backend-neutrality stance as R-core-imports-stdlib-or-hotam-spec-only, extended with a claim-specific platform-token scan. Not yet implemented: the attention layer is Planned (previously the core lived in src/hotam_spec/attention.py, the adapter in tools/attention_hook.py, guarded by tests/test_attention_core.py::test_core_names_no_platform_token). settled_at RESTORED 2026-07-13 from git HEAD 9af0176 (pre-corruption value) after a mutate.go bug this session silently reset it on content-only updates; see task #84.",
	Assumptions:    []string{"A-text-grounded-in-models"},
	Relations:      []ontology.Relation{{Kind: "refines", Target: "R-backend-scope"}},
	Enforcement:    "PROSE",
	EnforcedBy:     []string{},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-07-04",
	SettledAt:      "2026-07-12",
	SourceRefs:     []string{},
	DeclOrder:      252,
	BlockedOn:      "blocked on the internal/attention package (absent on disk)",
})

var _ = Requirements.MustRegister("R-attention-claude-adapter", ontology.Requirement{
	ID:             "R-attention-claude-adapter",
	Claim:          "The committed sensorium generator shall wire the Claude attention adapter onto UserPromptSubmit, and that adapter shall delegate to the attention core rather than re-implement sensing.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Resolver verdict (2026-07-03): 'at the seam make an API for Claude'. The universal core needs a Claude-specific seam that injects the attention list into the agent's context each turn: a thin UserPromptSubmit hook that calls the attention core's collect() and prints the rendered list to stdout (which the host injects into context). The committed, portable sensorium generator wires it so a fresh clone gets the pulse with zero edits (R-sensorium-committed). Not yet implemented: setup-hooks and the attention adapter are Planned (previously implemented as tools/setup_hooks.py wiring tools/attention_hook.py, guarded by tests/test_attention_claude_adapter.py). settled_at RESTORED 2026-07-13 from git HEAD 9af0176 (pre-corruption value) after a mutate.go bug this session silently reset it on content-only updates; see task #84.",
	Assumptions:    []string{"A-text-grounded-in-models"},
	Relations:      []ontology.Relation{{Kind: "refines", Target: "R-sensorium-committed"}},
	Enforcement:    "PROSE",
	EnforcedBy:     []string{},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-07-04",
	SettledAt:      "2026-07-12",
	SourceRefs:     []string{},
	DeclOrder:      254,
	BlockedOn:      "blocked on the attention_hook tool + setup_hooks tool (Planned) + the internal/attention package (absent)",
})

var _ = Requirements.MustRegister("R-attention-registry", ontology.Requirement{
	ID:             "R-attention-registry",
	Claim:          "An agent-agnostic attention-source registry shall exist whose collect() runs every registered source and returns typed AttentionSignal records, with the graph-source diagnosis deterministic across runs.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Resolver verdict (2026-07-03): the 'pay attention here' signals were scattered -- half in the what-now diagnosis, half as CLI-only bands -- with no single, agent-agnostic, importable-as-a-library place an arbitrary agent could call to learn what needs attention. This lifts them into ONE core with an explicit registry of named sources, each producing typed AttentionSignal records the substrate and any agent share; the graph-source diagnosis is deterministic (byte-identical across runs) so it can feed the byte-stable substrate. Not yet implemented: the attention registry is Planned (previously implemented as src/hotam_spec/attention.py (ATTENTION_SOURCES), guarded by tests/test_attention_core.py). settled_at RESTORED 2026-07-13 from git HEAD 9af0176 (pre-corruption value) after a mutate.go bug this session silently reset it on content-only updates; see task #84.",
	Assumptions:    []string{"A-text-grounded-in-models"},
	Relations:      []ontology.Relation{},
	Enforcement:    "PROSE",
	EnforcedBy:     []string{},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-07-04",
	SettledAt:      "2026-07-12",
	SourceRefs:     []string{},
	DeclOrder:      251,
	BlockedOn:      "blocked on the internal/attention package (absent) + the attention tool (Planned in internal/methodology/tools_data.go)",
})

var _ = Requirements.MustRegister("R-attention-superset-of-diagnose", ontology.Requirement{
	ID:             "R-attention-superset-of-diagnose",
	Claim:          "The live attention list collect(g) shall be a superset of the deterministic graph subset diagnose(g), equal to it exactly when no runtime-fs sources are injected.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "The honest split at the centre of the attention design: the SUBSTRATE (gen-spec / LIVE-STATE) must stay byte-stable (R-deterministic-generation), so it consumes ONLY the deterministic graph diagnosis; the LIVE AGENT wants more -- pending proposals, open tickets, stale audit, unread revisit markers -- which read the filesystem and are non-deterministic. Rather than couple those into the graph diagnosis (breaking determinism and polluting graph tests), the filesystem sources are INJECTED by the live consumer via collect(runtime_sources=...): the registry holds graph-only sources, the live consumer supplies the fs half, so collect(agent) is a superset of diagnose(substrate). Not yet implemented: the attention layer is Planned (the deterministic graph diagnosis it builds on does live in internal/diagnose, Implemented); previously implemented in src/hotam_spec/attention.py with what_now.runtime_fs_sources(), guarded by tests/test_attention_core.py. settled_at RESTORED 2026-07-13 from git HEAD 9af0176 (pre-corruption value) after a mutate.go bug this session silently reset it on content-only updates; see task #84.",
	Assumptions:    []string{"A-text-grounded-in-models"},
	Relations:      []ontology.Relation{{Kind: "refines", Target: "R-attention-registry"}},
	Enforcement:    "PROSE",
	EnforcedBy:     []string{},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-07-04",
	SettledAt:      "2026-07-12",
	SourceRefs:     []string{},
	DeclOrder:      253,
	BlockedOn:      "blocked on the internal/attention package (absent) — the superset relationship is only testable once both sides exist",
})
