// Code generated by .scratch/selfspec-codegen (task #345, RAC-A). DO NOT EDIT BY HAND.
// Regenerate by re-running the throwaway codegen program against the current
// domains/hotam-spec-self/graph.json if this topic's requirement set ever needs
// to change.
//
// Topic: Critical Core (minimal enforced kernel).
//
// STRUCTURAL fields only: Claim, Why, Owner, Status, Relations, Assumptions,
// Enforcement, EnforcedBy, Enforceability, MTag, Summary, CreatedAt, SettledAt,
// BlockedOn, ImplementedBy, VerifiedBy, SourceRefs, DeclOrder. EVENT fields
// (History, GateSignoffs, LastReviewedAt, ReviewAfter, Evidence) are
// deliberately absent — MergeIntoGraph passes them through from the graph's
// existing node untouched.
package selfspec

import "github.com/PHPCraftdream/HotamSpec/internal/ontology"

var _ = Requirements.MustRegister("R-critical-core-methodology", ontology.Requirement{
	ID:             "R-critical-core-methodology",
	Claim:          "The methodology's own critical core shall be the six invariants named in criticalCoreNames (internal/generator/constitution.go), guarding every path by which a contradiction could be introduced without being seen.",
	Owner:          "domain-user",
	Status:         "SETTLED",
	Why:            "Atom of R-critical-core-scope (methodology scope). M7 resolved: these six guard every path by which a contradiction could be introduced without being seen. The six are named in internal/generator/constitution.go (criticalCoreNames: check_resolver_not_a_member_owner, check_operator_resolver_not_self, check_decided_has_decided_by, check_typed_anchors, check_no_dangling_ids, check_open_has_question) and rendered into docs/gen/CONSTITUTION.md by the generator. settled_at RESTORED 2026-07-13 from git HEAD 9af0176 (pre-corruption value) after a mutate.go bug this session silently reset it on content-only updates; see task #84.",
	Assumptions:    []string{"A-text-grounded-in-models"},
	Relations:      []ontology.Relation{{Kind: "replaces", Target: "R-critical-core-scope"}},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"check_no_dangling_assumption_owner", "check_no_dangling_requirement_owner", "check_no_dangling_requirement_assumptions", "check_no_dangling_requirement_relations", "check_no_dangling_conflict_refs"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-07-12",
	SourceRefs:     []string{"internal/generator/constitution.go"},
	DeclOrder:      146,
})

var _ = Requirements.MustRegister("R-critical-core-per-domain", ontology.Requirement{
	ID:             "R-critical-core-per-domain",
	Claim:          "Business-domain critical core (money, access, SLA) shall be a separate per-domain calibration, not framework-imposed.",
	Owner:          "domain-user",
	Status:         "SETTLED",
	Why:            "Atom of R-critical-core-scope (per-domain scope). Each domain has its own cost-of-unnoticed-conflict profile; the framework must not impose the methodology's own critical core onto business domains.",
	Assumptions:    []string{"A-text-grounded-in-models"},
	Relations:      []ontology.Relation{{Kind: "replaces", Target: "R-critical-core-scope"}},
	Enforcement:    "PROSE",
	EnforcedBy:     []string{},
	MTag:           "",
	Enforceability: "INHERENTLY_PROSE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-06-30",
	SourceRefs:     []string{},
	DeclOrder:      147,
})

var _ = Requirements.MustRegister("R-critical-core-scope", ontology.Requirement{
	ID:             "R-critical-core-scope",
	Claim:          "The set of requirement domains warranting the deferred formal layers (Z3 conflict-detector, Quint temporal, mutation testing) shall be declared.",
	Owner:          "domain-user",
	Status:         "REJECTED",
	Why:            "REJECTED — REPLACES split into R-critical-core-methodology + R-critical-core-per-domain (wave 2, decided by framework-author 2026-06-30) — (was: REJECTED — REPLACES split into R-critical-core-methodology + R-critical-core-per-domain (wave 2, decided by framework-author 2026-06-30) — (was: M7 resolved (P6 — §Conscience): the critical core for the methodology's OWN domain is the six invariants in CRITICAL_CORE_INVARIANTS — check_resolver_not_a_member_owner, check_operator_resolver_not_self, check_decided_has_decided_by, check_typed_anchors, check_no_dangling_ids, check_open_has_question. These six guard every path by which a contradiction could be introduced without being seen. Business-domain 'critical core' (money / access / SLA) is a separate per-domain calibration; the framework's own methodology critical core is now declared and property-tested via test_conscience.py.))",
	Assumptions:    []string{"A-text-grounded-in-models"},
	Relations:      []ontology.Relation{},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"test_conscience.py"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "",
	SourceRefs:     []string{},
	DeclOrder:      15,
})
