// Code generated by .scratch/selfspec-codegen (task #345, RAC-A). DO NOT EDIT BY HAND.
// Regenerate by re-running the throwaway codegen program against the current
// domains/hotam-spec-self/graph.json if this topic's requirement set ever needs
// to change.
//
// Topic: Reflection and Self-Diagnosis.
//
// STRUCTURAL fields only: Claim, Why, Owner, Status, Relations, Assumptions,
// Enforcement, EnforcedBy, Enforceability, MTag, Summary, CreatedAt, SettledAt,
// BlockedOn, ImplementedBy, VerifiedBy, SourceRefs, DeclOrder. EVENT fields
// (History, GateSignoffs, LastReviewedAt, ReviewAfter, Evidence) are
// deliberately absent — MergeIntoGraph passes them through from the graph's
// existing node untouched.
package selfspec

import "github.com/PHPCraftdream/HotamSpec/internal/ontology"

var _ = Requirements.MustRegister("R-confront-includes-aspirations", ontology.Requirement{
	ID:             "R-confront-includes-aspirations",
	Claim:          "At the CONFRONT step the operator shall check every change not only against SETTLED rules but also against the graph's goals, IMPLEMENTS aspirations and values, surfacing any contradiction before writing.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Resolver verdict 2026-07-05, verbatim: 'кажется, не получится [таймер-будильник для IMPLEMENTS]. Это просто нужно модели помнить при внесении изменений - нет ли противоречий нашим целям, правилам, ценностям'. Context: the six-lens review flagged IMPLEMENTS aspirations as a silent corner (no aging, no fallout, no progress measure) and proposed a decay timer; the resolver rejected the timer as unworkable -- aliveness of an aspiration is not measured by a calendar but verified at the moment of every change, by the operator's own conscience. So the duty lands on the CONFRONT step of the mediation loop: the confrontation scope explicitly includes goals, aspirations and values, not just SETTLED claims. INHERENTLY_PROSE: this is an operator-conscience discipline; the lexical confront tool cannot see semantic contradiction with values (its honesty boundary is already documented).",
	Assumptions:    []string{},
	Relations:      []ontology.Relation{},
	Enforcement:    "PROSE",
	EnforcedBy:     []string{},
	MTag:           "",
	Enforceability: "INHERENTLY_PROSE",
	Summary:        "",
	CreatedAt:      "2026-07-05",
	SettledAt:      "2026-07-05",
	SourceRefs:     []string{},
	DeclOrder:      265,
})

var _ = Requirements.MustRegister("R-reflection-predicates-first-class", ontology.Requirement{
	ID:             "R-reflection-predicates-first-class",
	Claim:          "The operator's self-diagnosis conditions shall be named, pure, graph-only predicate functions in internal/diagnose/finding.go composed by AllFindings in a fixed registry order, and consumed by the what-now harness via internal/diagnose/signal.go -- never inlined in tool code.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Concept-Map gap closed: §Reflection is the home in internal/ for the P0 self-diagnosis conditions. These live as eight named predicates in internal/diagnose/finding.go -- ReflectDraftOverhang, ReflectUnenforcedSettled, ReflectOverBudgetOperators, ReflectDeadAssumptionOnEnforcer, ReflectDerivedButUnbuilt, ReflectImplementsDecay, ReflectReplacesEdgeMigration, ReflectAllMembersRejected -- each returning []Finding (Condition/Target/Imperative records). The registry order is fixed by AllFindings(g), which appends each predicate's findings in that exact sequence (no per-call reordering); the what-now harness consumes them through internal/diagnose/signal.go (collectAttentionSignals ranges over AllFindings(g)) and renders, exactly as it composes invariants.AllViolations -- the substrate owns the diagnosis vocabulary, the tool only renders. This is the same extraction pattern as the §Invariants layer: reflect_* predicates return Finding records and the harness composes AllFindings() the way it composes AllViolations(). TestAllFindings_OrderFollowsRegistry (internal/diagnose/finding_test.go) pins the registry order. settled_at RESTORED 2026-07-13 from git HEAD 9af0176 (pre-corruption value) after a mutate.go bug this session silently reset it on content-only updates; see task #84.",
	Assumptions:    []string{},
	Relations:      []ontology.Relation{{Kind: "refines", Target: "R-agent-never-lost"}},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"TestAllFindings_OrderFollowsRegistry"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-07-02",
	SettledAt:      "2026-07-12",
	SourceRefs:     []string{"internal/diagnose/finding.go", "internal/diagnose/signal.go", "internal/diagnose/finding_test.go"},
	DeclOrder:      201,
})

var _ = Requirements.MustRegister("R-tree-of-crystals-cognitive-trigger", ontology.Requirement{
	ID:             "R-tree-of-crystals-cognitive-trigger",
	Claim:          "Tree-of-crystals delegation shall fire when a sub-domain's detail granularity exceeds the director's altitude, independently of the φ-cap size trigger.",
	Owner:          "framework-author",
	Status:         "REJECTED",
	Why:            "REJECTED — REPLACES R-claude-md-tree-of-crystals: the cognitive-trigger framing rested on the already-REJECTED φ-cap notion; the only real delegated trigger that survives is the CRYSTAL_CHARS warn threshold on the resident crystal (contextbudget), which is already first-class. No separate cognitive-trigger node is needed. — (was: Second trigger besides R-claude-md-budget-phi-cap: cognitive load, not token load. BUILD-TRIGGER: a heuristic detector exists (planned: count of distinct concerns per sub-domain crossing a threshold).)",
	Assumptions:    []string{"A-finite-context-operators"},
	Relations:      []ontology.Relation{},
	Enforcement:    "PROSE",
	EnforcedBy:     []string{},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "",
	SourceRefs:     []string{},
	DeclOrder:      96,
})
