// Code generated by .scratch/selfspec-codegen (task #345, RAC-A). DO NOT EDIT BY HAND.
// Regenerate by re-running the throwaway codegen program against the current
// domains/hotam-spec-self/graph.json if this topic's requirement set ever needs
// to change.
//
// Topic: Entity (EntityType/EntityField/EntityInstance).
//
// STRUCTURAL fields only: Claim, Why, Owner, Status, Relations, Assumptions,
// Enforcement, EnforcedBy, Enforceability, MTag, Summary, CreatedAt, SettledAt,
// BlockedOn, ImplementedBy, VerifiedBy, SourceRefs, DeclOrder. EVENT fields
// (History, GateSignoffs, LastReviewedAt, ReviewAfter, Evidence) are
// deliberately absent — MergeIntoGraph passes them through from the graph's
// existing node untouched.
package selfspec

import "github.com/PHPCraftdream/HotamSpec/internal/ontology"

var _ = Requirements.MustRegister("R-entity-checks-by-iteration", ontology.Requirement{
	ID:             "R-entity-checks-by-iteration",
	Claim:          "The check_entity_* invariant family shall cover every declared EntityType by iterating g.EntityTypes, requiring no new check_* code per additional type.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Parametric iteration is what makes the entity aspect scale: one invariant covers all types today and tomorrow. Per-type invariants would grow the check surface linearly and force framework edits on every domain addition -- the inverse of the content-free design. checkEntityTypeLifecycleWellformed (internal/invariants/entity_checks.go) iterates g.EntityTypes directly, calling the shared lifecycleWellformedIssues function on each EntityType.Lifecycle; the same parametric-iteration pattern is used by every check_entity_* invariant (check_entity_instance_state_in_lifecycle, check_entity_instance_required_fields, etc.). Adding an EntityType to the graph requires zero new check_* code. Wave 1 mechanical-honesty pass (2026-07-02) promoted this from STRUCTURAL to ENFORCED once a demo fixture proved the iteration claim end-to-end; the iteration is directly visible in the check source and exercised by the entity_checks_test.go fixtures. settled_at RESTORED 2026-07-13 from git HEAD 9af0176 (pre-corruption value) after a mutate.go bug this session silently reset it on content-only updates; see task #84.",
	Assumptions:    []string{"A-python-stack"},
	Relations:      []ontology.Relation{},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"check_entity_type_lifecycle_wellformed"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-07-12",
	SourceRefs:     []string{"internal/invariants/entity_checks.go"},
	DeclOrder:      178,
})

var _ = Requirements.MustRegister("R-entity-derived-requirement", ontology.Requirement{
	ID:             "R-entity-derived-requirement",
	Claim:          "Each EntityType in the domain's graph shall be projected as R-entity-<slug> in the domain's FRAMEWORK-INVARIANTS.md, with enforced_by listing the check_entity_* family covering it.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Mirrors R-tool-is-its-own-requirement at the entity layer: an EntityType IS its own requirement; deleting it removes the R; changing its description changes the claim. Eliminates the prose gap between 'R about entity behavior' and 'EntityType implementing it'. renderEntityDerivedConstitutionSection (internal/generator/entities.go) projects each EntityType as a '- **R-entity-<slug>**' line into FRAMEWORK-INVARIANTS.md via BuildFrameworkInvariants (internal/generator/frameworkinvariants.go), listing the entityCoveringChecks family as enforced_by. The invariant check_entity_type_constitution_projection is registered but is a NO-OP (filesystem-coherence check that does not fit the pure-graph Check signature; the guarantee is carried by the byte-identity test layer instead). Dormant-but-real: 0 entity_types in the active domain today makes the projection section empty (rendered only when len(g.EntityTypes) > 0), not falsely enforced -- the guard is live and will project the moment a domain declares an EntityType. Wording precision (Wave 7 move 3a): entity-derived requirements are framework-plumbing, relocated out of CONSTITUTION.md into FRAMEWORK-INVARIANTS.md; the projection target is FRAMEWORK-INVARIANTS.md. settled_at RESTORED 2026-07-13 from git HEAD 9af0176 (pre-corruption value) after a mutate.go bug this session silently reset it on content-only updates; see task #84.",
	Assumptions:    []string{"A-python-stack"},
	Relations:      []ontology.Relation{},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"check_entity_type_constitution_projection"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-07-12",
	SourceRefs:     []string{"internal/generator/entities.go", "internal/generator/frameworkinvariants.go"},
	DeclOrder:      175,
})

var _ = Requirements.MustRegister("R-entity-field-kind-known", ontology.Requirement{
	ID:             "R-entity-field-kind-known",
	Claim:          "Every EntityField.kind shall be in ENTITY_FIELD_KINDS (string | number | enum | reference | state).",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Atom of §Entity aspect (field-kind concern). An unknown kind breaks the discriminant for kind-specific invariants and future machine-checkable field validation.",
	Assumptions:    []string{"A-text-grounded-in-models", "A-bootstrap-self-applies"},
	Relations:      []ontology.Relation{},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"check_entity_field_kind_known"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-06-30",
	SourceRefs:     []string{},
	DeclOrder:      134,
})

var _ = Requirements.MustRegister("R-entity-instance-id-prefix", ontology.Requirement{
	ID:             "R-entity-instance-id-prefix",
	Claim:          "Every EntityInstance.id shall start with 'ENT-<entity_type>-' (typed-anchor discipline).",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Atom of §Entity aspect (typed-anchor concern). Encodes both type and entity kind in the id, enabling unambiguous cross-reference (R-anchor-everything).",
	Assumptions:    []string{"A-text-grounded-in-models", "A-bootstrap-self-applies"},
	Relations:      []ontology.Relation{},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"check_entity_instance_id_prefix", "check_typed_anchors_entity"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-06-30",
	SourceRefs:     []string{},
	DeclOrder:      132,
})

var _ = Requirements.MustRegister("R-entity-instance-refs-resolve", ontology.Requirement{
	ID:             "R-entity-instance-refs-resolve",
	Claim:          "Every EntityInstance reference field shall resolve in the graph according to its ref_target.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Atom of §Entity aspect (referential integrity concern). A dangling reference field is the entity-level equivalent of a dangling Conflict member.",
	Assumptions:    []string{"A-text-grounded-in-models", "A-bootstrap-self-applies"},
	Relations:      []ontology.Relation{},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"check_entity_instance_refs_resolve"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-06-30",
	SourceRefs:     []string{},
	DeclOrder:      133,
})

var _ = Requirements.MustRegister("R-entity-instance-required-fields", ontology.Requirement{
	ID:             "R-entity-instance-required-fields",
	Claim:          "Every EntityInstance shall provide values for all EntityFields with required=True.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Atom of §Entity aspect (required-fields concern). A missing required field violates the declared EntityType schema and makes downstream traversal unreliable.",
	Assumptions:    []string{"A-text-grounded-in-models", "A-bootstrap-self-applies"},
	Relations:      []ontology.Relation{},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"check_entity_instance_required_fields"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-06-30",
	SourceRefs:     []string{},
	DeclOrder:      131,
})

var _ = Requirements.MustRegister("R-entity-instance-state-in-lifecycle", ontology.Requirement{
	ID:             "R-entity-instance-state-in-lifecycle",
	Claim:          "Every EntityInstance.state shall be a valid state in the corresponding EntityType.lifecycle.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Atom of §Entity aspect (state validity concern). An instance with an unknown state is structurally invalid — mirrors check_requirement_status_in_lifecycle for requirements.",
	Assumptions:    []string{"A-text-grounded-in-models", "A-bootstrap-self-applies"},
	Relations:      []ontology.Relation{},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"check_entity_instance_state_in_lifecycle"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-06-30",
	SourceRefs:     []string{},
	DeclOrder:      130,
})

var _ = Requirements.MustRegister("R-entity-is-declarative", ontology.Requirement{
	ID:             "R-entity-is-declarative",
	Claim:          "The framework shall supply no built-in EntityType values â€” all entity types are declared by domains in build_graph().",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "The content-free contract (R-content-free-no-business-data) extends to the entity layer: entity types are domain knowledge, not framework knowledge. Supplying built-in types would violate the blank-kit invariant and couple the framework to a particular domain model. ENFORCED 2026-07-13: TestEntityTypesAreDeclarative in internal/ontology/entity_declarative_test.go mechanically verifies this claim: a zero-value Graph has an empty EntityTypes slice, and a static source scan of internal/ and cmd/hotam/ finds no package-level var binding an EntityType value (entity types are domain-only declarations).",
	Assumptions:    []string{"A-python-stack"},
	Relations:      []ontology.Relation{},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"TestEntityTypesAreDeclarative"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-07-12",
	SourceRefs:     []string{},
	DeclOrder:      176,
})

var _ = Requirements.MustRegister("R-entity-reuses-lifecycle", ontology.Requirement{
	ID:             "R-entity-reuses-lifecycle",
	Claim:          "Each EntityType.Lifecycle shall be a Lifecycle value (the §Lifecycle keystone) with no parallel state machinery introduced.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "The §Lifecycle keystone was introduced precisely so that every stateful aspect (Process, Entity, Goal, Operator) reuses one mechanism. Parallel state machinery would fracture the invariant surface and double the maintenance burden for each new aspect. The Lifecycle type is defined once in internal/ontology/lifecycle.go (State, Transition, Lifecycle structs); EntityType.Lifecycle embeds it directly (ontology.EntityType.Lifecycle is of type ontology.Lifecycle). The check check_entity_type_lifecycle_wellformed (internal/invariants/entity_checks.go) validates every EntityType.Lifecycle through the exact same lifecycleWellformedIssues BFS machinery that validates Process and Goal lifecycles -- no parallel state machinery. Wave 1 mechanical-honesty pass (2026-07-02) promoted this from STRUCTURAL to ENFORCED; the shared-keystone reuse is directly visible in the check source. settled_at RESTORED 2026-07-13 from git HEAD 9af0176 (pre-corruption value) after a mutate.go bug this session silently reset it on content-only updates; see task #84.",
	Assumptions:    []string{"A-python-stack"},
	Relations:      []ontology.Relation{},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"check_entity_type_lifecycle_wellformed"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-07-12",
	SourceRefs:     []string{"internal/invariants/entity_checks.go", "internal/ontology/lifecycle.go"},
	DeclOrder:      177,
})

var _ = Requirements.MustRegister("R-entity-state-conflict-surfaced", ontology.Requirement{
	ID:             "R-entity-state-conflict-surfaced",
	Claim:          "Two processes driving one EntityType to disjoint terminal or quiescent states shall surface as a P5 LATENT_CONNECTOR action via entity_state_conflict_suspects().",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Process-induced state conflicts on a shared entity are a category of hidden dependency (the third invisibility the methodology surfaces). Routing them to P5 keeps them visible without premature closure — the detector returns suspects, never decisions.",
	Assumptions:    []string{"A-python-stack"},
	Relations:      []ontology.Relation{},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"TestEntityStateConflictSuspects"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-07-12",
	SourceRefs:     []string{},
	DeclOrder:      179,
})

var _ = Requirements.MustRegister("R-entity-type-lifecycle-wellformed", ontology.Requirement{
	ID:             "R-entity-type-lifecycle-wellformed",
	Claim:          "Every EntityType.lifecycle shall be a well-formed Lifecycle validated by check_entity_type_lifecycle_wellformed.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Atom of §Entity aspect (lifecycle wellformedness concern). An EntityType with an invalid lifecycle is structurally broken — check_entity_type_lifecycle_wellformed reuses check_lifecycle_wellformed (the §Lifecycle keystone) for zero-parallel machinery (M12).",
	Assumptions:    []string{"A-text-grounded-in-models", "A-bootstrap-self-applies"},
	Relations:      []ontology.Relation{},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"check_entity_type_lifecycle_wellformed"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-06-30",
	SourceRefs:     []string{},
	DeclOrder:      129,
})

var _ = Requirements.MustRegister("R-entity-typed-anchors", ontology.Requirement{
	ID:             "R-entity-typed-anchors",
	Claim:          "check_typed_anchors shall validate the ENT- prefix for EntityInstance nodes.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Atom of §Entity aspect (typed-anchors concern). Without prefix validation, EntityInstance nodes escape the anchoring discipline (R-anchor-everything).",
	Assumptions:    []string{"A-text-grounded-in-models", "A-bootstrap-self-applies"},
	Relations:      []ontology.Relation{},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"check_typed_anchors_entity"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-06-30",
	SourceRefs:     []string{},
	DeclOrder:      135,
})
