// Code generated by .scratch/selfspec-codegen (task #345, RAC-A). DO NOT EDIT BY HAND.
// Regenerate by re-running the throwaway codegen program against the current
// domains/hotam-spec-self/graph.json if this topic's requirement set ever needs
// to change.
//
// Topic: Context Budget and Measurement.
//
// STRUCTURAL fields only: Claim, Why, Owner, Status, Relations, Assumptions,
// Enforcement, EnforcedBy, Enforceability, MTag, Summary, CreatedAt, SettledAt,
// BlockedOn, ImplementedBy, VerifiedBy, SourceRefs, DeclOrder. EVENT fields
// (History, GateSignoffs, LastReviewedAt, ReviewAfter, Evidence) are
// deliberately absent — MergeIntoGraph passes them through from the graph's
// existing node untouched.
package selfspec

import "github.com/PHPCraftdream/HotamSpec/internal/ontology"

var _ = Requirements.MustRegister("R-budget-measure", ontology.Requirement{
	ID:             "R-budget-measure",
	Claim:          "An operator's context budget shall measure the SIZE of its resident business content in bytes/chars (tokens when the host exposes them), not node counts.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "M17. Resolver verdict 2026-07-02 (verbatim): «наверное, это размер бизнес-требований. Лучше в байтах или в токенах» (English: 'probably it's the size of the business requirements. Better in bytes or in tokens'). Landed reality already matches: BudgetMeasureCRYSTAL_CHARS ('measure = len(root CLAUDE.md) in characters') in internal/ontology/operator.go is the current byte-approximation of resident business content, wired into check_operator_within_budget (internal/invariants/lifecycle_checks.go) and used by the live meta-domain operator. BudgetMeasureTOKEN_ESTIMATE is declared in the BudgetMeasures map (internal/ontology/operator.go) as the token-exact seam the resolver names ('в токенах') for when the host exposes token counts, but is deferred (not measured yet) since no host API is wired. BudgetMeasureNODE_COUNT (the original M17 default, size = len(requirements)+len(conflicts)+len(assumptions)) is DEMOTED to a legacy measure: it counts the crystallized SUBSTRATE, which R-working-vs-substrate-budget declares free, so it over-penalizes crystallizing; it remains selectable only for operators/tests that opted into it before CRYSTAL_CHARS existed.",
	Assumptions:    []string{"A-finite-context-operators"},
	Relations:      []ontology.Relation{{Kind: "replaces", Target: "R-claude-md-budget-phi-cap"}},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"check_operator_within_budget"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-07-12",
	SourceRefs:     []string{"internal/ontology/operator.go", "internal/invariants/lifecycle_checks.go"},
	DeclOrder:      59,
})

var _ = Requirements.MustRegister("R-context-budget-rule", ontology.Requirement{
	ID:             "R-context-budget-rule",
	Claim:          "An operator's RESIDENT working set shall not exceed its context budget (measured by budget.measure — for CRYSTAL_CHARS the char-length of root CLAUDE.md vs the host cap), with any excess flagged as a structural OVERLOADED contradiction by the harness.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Built (P2): check_operator_within_budget fires when the operator's budget.measure exceeds limit. History: NODE_COUNT originally measured the crystallized SUBSTRATE (requirements+conflicts+assumptions), which R-working-vs-substrate-budget declares free — this falsely flagged operators as near-OVERLOADED for the very act of crystallizing or keeping REJECTED history. OP-director moved to CRYSTAL_CHARS (limit=150000, the observed host char cap) — the RESIDENT crystal (root CLAUDE.md) is now the thing actually metered, per R-working-vs-substrate-budget. DomainScope narrowing deferred to P5+. UPDATED 2026-07-13 (task #102): the CRYSTAL_CHARS value embedded in the LIVE-STATE \"resident crystal N chars\" line is now a fixpoint computed at generation time (generator.ComputeCrystalCharCountFixpoint: render → rune-count via utf8.RuneCountInString → re-render until the embedded number stops changing), not a read of a stale pre-existing CLAUDE.md from the previous run. Because the crystal embeds its own size, a non-fixpoint measurement never converged — two consecutive gen-spec passes produced different output — and the docs/gen/AGENT-CONTEXT.md LIVE-STATE was stuck at \"0 chars\" whenever gen-spec ran without --claude-md. The fixpoint is computed once per pass and feeds every LIVE-STATE carrier (root crystal + AGENT-CONTEXT.md + live-state.md) so they agree; the --claude-md flag now gates only whether the root crystal is written to disk. See TestComputeCrystalCharCountFixpoint_RealDomainGraph, TestGenSpec_CrystalFixpointConvergesAcrossRuns.",
	Assumptions:    []string{"A-finite-context-operators"},
	Relations:      []ontology.Relation{},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"check_operator_within_budget"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-07-12",
	SourceRefs:     []string{},
	DeclOrder:      34,
})

var _ = Requirements.MustRegister("R-context-hook-piggybacks-cah-stamp", ontology.Requirement{
	ID:             "R-context-hook-piggybacks-cah-stamp",
	Claim:          "The project-local hook (context_producer.py, wired via PostToolUse + Stop in .claude/settings.local.json) shall read a context-cache.json written by the global statusline script and write spec/.runtime/context.json.",
	Owner:          "framework-author",
	Status:         "REJECTED",
	Why:            "REJECTED — REPLACES by R-work-within-launch-dir + the local-only context bridge. The claim required the project-local hook to READ a context-cache.json written by the global statusline script — i.e. it depended on patching/reading the sovereign host (~/.claude/cah-bin). Resolver verdict 2026-07-05 (verbatim): 'cah вообще нельзя трогать - он ведь обновится всё сотрет. И он в праве быть собой, без наших вмешательств'. The --patch-global mechanism and the global-cache read were removed from setup_context_hook.py / context_producer.py; the honest local design is: context_producer reads ctx_pct ONLY from the local stdin payload, writing nothing when absent. This claim is now structurally impossible under R-work-within-launch-dir and is preserved for history. — (was: Design refined by the 2026-07-02 --patch-global investigation: the global cah-stamp/cah-status pipeline had NO existing on-disk cache for ctx_pct (rate-limits.json holds only 5h/weekly/effort, never context %) -- so this cannot honestly 'read the global cah-stamp cache' as originally worded. Instead spec/tools/setup_context_hook.py --patch-global (a separate, user-run, opt-in tool -- never applied automatically) surgically patches the global cah-status.js to ALSO write a sibling ~/.claude/cah-bin/cache/context-cache.json = {ctx_pct, model, stamp}; context_producer.py now reads that path (CAH_CONTEXT_CACHE override) as a fallback when its stdin payload lacks ctx_pct. Stays DRAFT: the patch exists and is tested hermetically, but no user has yet run --patch-global --apply against the real global script, so the end-to-end chain is not yet proven live. BUILD-TRIGGER unchanged: R-setup-claude-generates-settings has landed.)",
	Assumptions:    []string{"A-finite-context-operators"},
	Relations:      []ontology.Relation{},
	Enforcement:    "PROSE",
	EnforcedBy:     []string{},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "",
	SourceRefs:     []string{},
	DeclOrder:      100,
})

var _ = Requirements.MustRegister("R-measure-context-size", ontology.Requirement{
	ID:             "R-measure-context-size",
	Claim:          "The operator's working-context fullness shall be MEASURED from a runtime stamp, not estimated, so the three-cipher pulse cites a real number.",
	Owner:          "ai-agent",
	Status:         "REJECTED",
	Why:            "REJECTED — premise requires installing/wiring a hook in the user's global ~/.claude configuration to emit context %, which R-work-within-launch-dir (SETTLED/ENFORCED) explicitly forbids (\"never modifying anything outside it — including ... the global ~/.claude configuration\"). This is the same resolver-cited reason (2026-07-05: \"cah вообще нельзя трогать — он ведь обновится всё сотрет\") that already REJECTED the sibling R-context-hook-piggybacks-cah-stamp. An honest successor already exists and is SETTLED/ENFORCED: R-unmeasured-cipher-names-host-boundary, which measures context only when the local stdin payload honestly carries ctx_pct and otherwise reports UNMEASURED — exactly the scope this DRAFT wanted, without crossing the host boundary. Resolver decision 2026-07-12, independently confirmed by two agents (crush and fm) reading the same graph evidence. — (was: tools/context.py reads spec/.runtime/context.json; the producing hook lives in the user's global ~/.claude settings (cah-stamp emits context %) — installing it is a RESOLVER decision outside the framework body, so this stays DRAFT until the hook is approved and wired.)",
	Assumptions:    []string{"A-finite-context-operators"},
	Relations:      []ontology.Relation{},
	Enforcement:    "PROSE",
	EnforcedBy:     []string{"tools/context.py"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "",
	SourceRefs:     []string{},
	DeclOrder:      69,
})

var _ = Requirements.MustRegister("R-three-cipher-pulse-structurally-injected", ontology.Requirement{
	ID:             "R-three-cipher-pulse-structurally-injected",
	Claim:          "The three-cipher pulse (top action / debt / context) shall be structurally present in the LIVE-STATE block of the root CLAUDE.md, regenerated on every gen-spec / land, so the operator's per-turn ORIENT step reads it by reference rather than re-deriving it.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Closes the per-turn edge of the inversion. The three-cipher pulse (top action / debt / context) is required by the boot ritual to be cited in the first sentence of every substantive reply (R-boot-cite-in-first-sentence). The pulse IS structurally generated: BuildLiveState (internal/generator/livestate.go) reads diagnose.DiagnoseSignals for the top-action line, computes the SETTLED/DRAFT/OPEN/closeable-debt counts for the debt line, and emits the context line (ctxLineStatic — the honest UNMEASURED explanation) verbatim; this runs on every `hotam gen-spec` and every `hotam land` (cmd/hotam/land.go step b → genSpec → BuildLiveState). The Mediation loop step 1 (ORIENT, embedded in CLAUDE.md) instructs the operator to reload this pulse by reference. NOT YET IMPLEMENTED is the automatic per-turn HOOK INJECTION: emit-cipher is Planned (not Implemented) in methodology.Tools, so the pulse is present in LIVE-STATE but the operator reads it manually per the ORIENT step, not via an auto-injected hook. (Historical note: the original emit_cipher.py was a UserPromptSubmit hook in .claude/settings.local.json that read the LIVE-STATE sentinels and emitted a JSON hookSpecificOutput consumed by the host harness, structurally forcing the pulse into every user turn; proven by test_user_prompt_submit_hook_emits_cipher.) The original WHY stands: structural presence of the pulse prevents the operator from forgetting to orient. PROSE (not ENFORCED): no enforcer test exists. ENFORCED 2026-07-13: TestBuildLiveState_ThreeCipherPulsePresent in internal/generator/atoms_livestate_test.go mechanically verifies this claim against the generated crystal on the fixture graph.",
	Assumptions:    []string{"A-python-stack"},
	Relations:      []ontology.Relation{},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"TestBuildLiveState_ThreeCipherPulsePresent"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-07-12",
	SourceRefs:     []string{"internal/generator/livestate.go", "internal/generator/claudemd.go", "cmd/hotam/land.go"},
	DeclOrder:      183,
})

var _ = Requirements.MustRegister("R-unmeasured-cipher-names-host-boundary", ontology.Requirement{
	ID:             "R-unmeasured-cipher-names-host-boundary",
	Claim:          "While the context cipher is UNMEASURED, the generated LIVE-STATE shall honestly explain that measuring working-context requires host cooperation the framework will not touch, naming no command-to-call.",
	Owner:          "ai-agent",
	Status:         "SETTLED",
	Why:            "REPLACES R-unmeasured-cipher-names-user-action (resolver verdict 2026-07-05). Measuring working-context would require the sovereign host's statusline / global configuration to deliver ctx_pct — cooperation the framework will not reach for (R-work-within-launch-dir). The prior atom demanded the UNMEASURED line name the exact command to run; the only such command (setup_context_hook.py --patch-global --apply) patched the host and is now removed. Naming a nonexistent in-bounds command would be dishonest, so the cipher instead states the host boundary plainly. This is realized by the static constant ctxLineStatic (internal/generator/livestate.go:25): the exact string 'context: UNMEASURED — measuring working-context requires host cooperation the framework will not touch (R-work-within-launch-dir); it measures only if the local stdin payload honestly carries ctx_pct — R-unmeasured-cipher-names-host-boundary' is emitted verbatim as the last line of every LIVE-STATE block by BuildLiveState (internal/generator/livestate.go), which runs on every `hotam gen-spec` and `hotam land`. The fixture at internal/generator/testdata/fixture/live-state.md asserts this line is rendered exactly. The cipher measures only if the local stdin payload honestly carries ctx_pct. STRUCTURAL (not ENFORCED): the static-line presence is upheld by the generator's own rendering (the line is a hardcoded constant, not computed), not by a dedicated enforcer test. ENFORCED 2026-07-13: TestBuildLiveState_ContextLineNamesHostBoundaryNoCommand in internal/generator/atoms_livestate_test.go mechanically verifies this claim against the generated crystal on the fixture graph.",
	Assumptions:    []string{"A-finite-context-operators"},
	Relations:      []ontology.Relation{{Kind: "replaces", Target: "R-unmeasured-cipher-names-user-action"}, {Kind: "replaces", Target: "R-measure-context-size"}},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"TestBuildLiveState_ContextLineNamesHostBoundaryNoCommand"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-07-05",
	SettledAt:      "2026-07-12",
	SourceRefs:     []string{"internal/generator/livestate.go", "internal/generator/testdata/fixture/live-state.md"},
	DeclOrder:      258,
})

var _ = Requirements.MustRegister("R-unmeasured-cipher-names-user-action", ontology.Requirement{
	ID:             "R-unmeasured-cipher-names-user-action",
	Claim:          "While the context cipher is UNMEASURED, the generated LIVE-STATE shall name the exact user-run command that activates measurement.",
	Owner:          "ai-agent",
	Status:         "REJECTED",
	Why:            "REJECTED — REPLACES by R-unmeasured-cipher-names-host-boundary. The claim required the UNMEASURED cipher to name the EXACT user-run command that activates measurement — but the only such command was setup_context_hook.py --patch-global --apply, which patched the sovereign host and is now forbidden (R-work-within-launch-dir, resolver verdict 2026-07-05). There is no in-bounds command that activates measurement, so naming one would be dishonest. The replacement claims the honest form: while UNMEASURED, the cipher explains WHY there is no number (host cooperation the framework will not touch), naming no command-to-call. — (was: R-ai-presents-not-decides means the operator cannot self-install a hook that touches the user's GLOBAL ~/.claude config -- that is a resolver decision (spec/tools/setup_context_hook.py --patch-global --apply). Leaving the UNMEASURED cipher as a bare status word made the gap invisible: the operator knew context was unmeasured but never told the user what to run to fix it, so the gap persisted turn after turn with no forcing function. tools/context.py's render_line() now embeds the exact command in the UNMEASURED line itself, and gen_spec's LIVE-STATE + emit_cipher's pulse both surface it verbatim (R-boot-cite-in-first-sentence then forces the operator to cite it every turn until the user runs the command and the cipher measures for real).)",
	Assumptions:    []string{"A-finite-context-operators"},
	Relations:      []ontology.Relation{},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"test_tool_context.py::test_absent_stamp_reads_unmeasured", "test_tool_context.py::test_stamp_without_pct_renders_unmeasured_line"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-07-02",
	SettledAt:      "",
	SourceRefs:     []string{},
	DeclOrder:      214,
})

var _ = Requirements.MustRegister("R-working-vs-substrate-budget", ontology.Requirement{
	ID:             "R-working-vs-substrate-budget",
	Claim:          "The context budget shall bound only the WORKING store of active uncrystallized knowledge, leaving the crystallized substrate free and unbounded.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "SETTLED (P8): the over-budget REFLECTION predicate (ReflectOverBudgetOperators, internal/diagnose/finding.go) measures only the live graph nodes -- graphSize(g) = len(g.Requirements) + len(g.Conflicts) + len(g.Assumptions) -- never the crystallized substrate. Only un-offloaded working knowledge competes for context, so only it is metered; bounding the substrate would punish the very act -- crystallizing -- that the budget rewards. RECLASSIFIED 2026-07-13 (task #113, decision brief §7): enforceability ENFORCEABLE -> INHERENTLY_PROSE. This is an architectural/design-principle claim ('the budget bounds only the WORKING store, leaving substrate free') where any test would be vacuous or just re-assert the design — the same shape as this session's already-landed R-crystal-is-claude-md / R-crystal-reload-by-reference INHERENTLY_PROSE reclassifications (decision brief §7, matching their proposals in proposals/wave6-enforcement-debt/category-b/). The mechanical teeth this principle motivates already live in its ENFORCED sibling R-context-budget-rule (check_operator_within_budget, CRYSTAL_CHARS measure), whose own why-text explicitly credits this requirement by name as its design rationale ('which R-working-vs-substrate-budget declares free', 'per R-working-vs-substrate-budget') — reclassifying (NOT rejecting) keeps the claim, ID, and that cross-reference valid, so the citation does NOT break; rejecting this source of the explanation would leave a dangling citation (decision brief §7 option (a) over (b)). The REFLECTION-tier Finding (advisory, surfaces via `hotam what-now` / the LIVE-STATE budget line) is composed by AllFindings (internal/diagnose/finding.go) and rendered by BuildLiveState (internal/generator/livestate.go); it does not block a write.",
	Assumptions:    []string{"A-finite-context-operators"},
	Relations:      []ontology.Relation{{Kind: "replaces", Target: "R-claude-md-budget-phi-cap"}},
	Enforcement:    "PROSE",
	EnforcedBy:     []string{},
	MTag:           "",
	Enforceability: "INHERENTLY_PROSE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-07-12",
	SourceRefs:     []string{"internal/diagnose/finding.go", "internal/generator/livestate.go"},
	DeclOrder:      54,
})
