// Code generated by .scratch/selfspec-codegen (task #345, RAC-A). DO NOT EDIT BY HAND.
// Regenerate by re-running the throwaway codegen program against the current
// domains/hotam-spec-self/graph.json if this topic's requirement set ever needs
// to change.
//
// Topic: Lifecycle and State Machine.
//
// STRUCTURAL fields only: Claim, Why, Owner, Status, Relations, Assumptions,
// Enforcement, EnforcedBy, Enforceability, MTag, Summary, CreatedAt, SettledAt,
// BlockedOn, ImplementedBy, VerifiedBy, SourceRefs, DeclOrder. EVENT fields
// (History, GateSignoffs, LastReviewedAt, ReviewAfter, Evidence) are
// deliberately absent — MergeIntoGraph passes them through from the graph's
// existing node untouched.
package selfspec

import "github.com/PHPCraftdream/HotamSpec/internal/ontology"

var _ = Requirements.MustRegister("R-lifecycle-abstraction", ontology.Requirement{
	ID:             "R-lifecycle-abstraction",
	Claim:          "A generic hotam_spec.lifecycle (State / Transition / Lifecycle) shall be introduced; Requirement.status and Conflict.lifecycle shall validate against framework-supplied Lifecycle constants.",
	Owner:          "framework-author",
	Status:         "REJECTED",
	Why:            "REJECTED — REPLACES split into R-lifecycle-type-exists + R-lifecycle-validates-requirement + R-lifecycle-validates-conflict (wave 2, decided by framework-author 2026-06-30) — (was: REJECTED — REPLACES split into R-lifecycle-type-exists + R-lifecycle-validates-requirement + R-lifecycle-validates-conflict (wave 2, decided by framework-author 2026-06-30) — (was: Built: hotam_spec/lifecycle.py ships REQUIREMENT_STATUS_LIFECYCLE and CONFLICT_LIFECYCLE; check_status_in_lifecycle validates stored values against them on every invariant run (P1).))",
	Assumptions:    []string{"A-bootstrap-self-applies"},
	Relations:      []ontology.Relation{},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"check_status_in_lifecycle", "test_lifecycle.py"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "",
	SourceRefs:     []string{},
	DeclOrder:      26,
})

var _ = Requirements.MustRegister("R-lifecycle-type-exists", ontology.Requirement{
	ID:             "R-lifecycle-type-exists",
	Claim:          "A generic lifecycle module shall define State, Transition, and Lifecycle types.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Atom of R-lifecycle-abstraction (type-existence concern). The Lifecycle type is the keystone that Requirement.status and Conflict.lifecycle validate against. State (Name, Kind, Why), Transition (Src, Dst, Event, Guard, GuardAssumption, Why), and Lifecycle (Slug, States, Transitions, Cyclic) are defined as structs in internal/ontology/lifecycle.go. Canonical lifecycles (RequirementLifecycle, ConflictLifecycle, GoalLifecycle, ProcessLifecycle, OperatorLifecycle) are defined in their respective ontology files and validated by TestCanonicalLifecyclesSanity (internal/ontology/graph_smoke_test.go). settled_at RESTORED 2026-07-13 from git HEAD 9af0176 (pre-corruption value) after a mutate.go bug this session silently reset it on content-only updates; see task #84.",
	Assumptions:    []string{"A-bootstrap-self-applies"},
	Relations:      []ontology.Relation{{Kind: "replaces", Target: "R-lifecycle-abstraction"}},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"TestCanonicalLifecyclesSanity"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-07-12",
	SourceRefs:     []string{"internal/ontology/lifecycle.go", "internal/ontology/graph_smoke_test.go"},
	DeclOrder:      118,
	ImplementedBy:  []string{"internal/ontology/lifecycle.go:Lifecycle"},
	VerifiedBy:     []string{"internal/ontology/graph_smoke_test.go:TestCanonicalLifecyclesSanity"},
})

var _ = Requirements.MustRegister("R-lifecycle-validates-conflict", ontology.Requirement{
	ID:             "R-lifecycle-validates-conflict",
	Claim:          "Conflict.lifecycle shall validate against the framework-supplied CONFLICT_LIFECYCLE.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Atom of R-lifecycle-abstraction (conflict validation concern). check_status_in_lifecycle validates Conflict lifecycles on every invariant run.",
	Assumptions:    []string{"A-bootstrap-self-applies"},
	Relations:      []ontology.Relation{{Kind: "replaces", Target: "R-lifecycle-abstraction"}},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"check_conflict_lifecycle_in_lifecycle"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-06-30",
	SourceRefs:     []string{},
	DeclOrder:      120,
})

var _ = Requirements.MustRegister("R-lifecycle-validates-goal", ontology.Requirement{
	ID:             "R-lifecycle-validates-goal",
	Claim:          "Goal.lifecycle shall validate against the framework-supplied GOAL_LIFECYCLE.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Atom of R-lifecycle-abstraction (goal validation concern). check_goal_lifecycle_in_lifecycle validates Goal lifecycles on every invariant run.",
	Assumptions:    []string{"A-bootstrap-self-applies"},
	Relations:      []ontology.Relation{},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"check_goal_lifecycle_in_lifecycle"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-06-30",
	SourceRefs:     []string{},
	DeclOrder:      122,
})

var _ = Requirements.MustRegister("R-lifecycle-validates-operator", ontology.Requirement{
	ID:             "R-lifecycle-validates-operator",
	Claim:          "Operator.lifecycle shall validate against the framework-supplied OPERATOR_LIFECYCLE.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Atom of R-lifecycle-abstraction (operator validation concern). check_operator_lifecycle_in_lifecycle validates Operator lifecycles on every invariant run.",
	Assumptions:    []string{"A-bootstrap-self-applies"},
	Relations:      []ontology.Relation{},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"check_operator_lifecycle_in_lifecycle"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-06-30",
	SourceRefs:     []string{},
	DeclOrder:      121,
})

var _ = Requirements.MustRegister("R-lifecycle-validates-requirement", ontology.Requirement{
	ID:             "R-lifecycle-validates-requirement",
	Claim:          "Requirement.status shall validate against the framework-supplied REQUIREMENT_STATUS_LIFECYCLE.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Atom of R-lifecycle-abstraction (requirement validation concern). check_status_in_lifecycle validates Requirement statuses on every invariant run.",
	Assumptions:    []string{"A-bootstrap-self-applies"},
	Relations:      []ontology.Relation{{Kind: "replaces", Target: "R-lifecycle-abstraction"}},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"check_requirement_status_in_lifecycle"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-06-30",
	SourceRefs:     []string{},
	DeclOrder:      119,
})

var _ = Requirements.MustRegister("R-statemachine-deterministic", ontology.Requirement{
	ID:             "R-statemachine-deterministic",
	Claim:          "A Lifecycle's transitions shall be deterministic — no two transitions with the same (src, event) and overlapping guards.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Atom of R-statemachine-wellformedness (determinism concern). check_lifecycle_wellformed validates determinism.",
	Assumptions:    []string{"A-bootstrap-self-applies"},
	Relations:      []ontology.Relation{{Kind: "replaces", Target: "R-statemachine-wellformedness"}},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"check_canonical_lifecycles_wellformed"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-06-30",
	SourceRefs:     []string{},
	DeclOrder:      46,
})

var _ = Requirements.MustRegister("R-statemachine-guard-on-assumption", ontology.Requirement{
	ID:             "R-statemachine-guard-on-assumption",
	Claim:          "A Transition.guard may name an Assumption it rests on (drift seam) — when that Assumption dies, the guard is surfaced.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Atom of R-statemachine-wellformedness (guard-on-assumption concern). Structural via Transition.guard_assumption field. Wave 1 mechanical-honesty pass (2026-07-02): promoted to ENFORCED by the new check_transition_guard_assumption_resolves invariant, which fires when a non-empty guard_assumption fails to resolve in assumption_ids(g) (dangling-ref family, RULES_AS_DATA_TABLE: TABLE_DRIVEN) -- plus a drift-fallout unit test proving a DEAD assumption referenced only via guard_assumption is still discoverable through graph.dead_assumptions(), never invisibly stale.",
	Assumptions:    []string{"A-bootstrap-self-applies"},
	Relations:      []ontology.Relation{{Kind: "replaces", Target: "R-statemachine-wellformedness"}},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"check_transition_guard_assumption_resolves"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-07-12",
	SourceRefs:     []string{},
	DeclOrder:      48,
})

var _ = Requirements.MustRegister("R-statemachine-reachable", ontology.Requirement{
	ID:             "R-statemachine-reachable",
	Claim:          "Every state in a canonical Lifecycle shall be reachable from the initial state.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Atom of R-statemachine-wellformedness (reachability concern). check_lifecycle_wellformed and check_canonical_lifecycles_wellformed validate reachability for all framework lifecycles.",
	Assumptions:    []string{"A-bootstrap-self-applies"},
	Relations:      []ontology.Relation{{Kind: "replaces", Target: "R-statemachine-wellformedness"}},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"check_canonical_lifecycles_wellformed"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-06-30",
	SourceRefs:     []string{},
	DeclOrder:      45,
})

var _ = Requirements.MustRegister("R-statemachine-terminal-or-cyclic", ontology.Requirement{
	ID:             "R-statemachine-terminal-or-cyclic",
	Claim:          "Every non-cyclic Lifecycle shall reach at least one terminal/quiescent state.",
	Owner:          "framework-author",
	Status:         "SETTLED",
	Why:            "Atom of R-statemachine-wellformedness (termination concern). check_lifecycle_wellformed validates terminal reachability.",
	Assumptions:    []string{"A-bootstrap-self-applies"},
	Relations:      []ontology.Relation{{Kind: "replaces", Target: "R-statemachine-wellformedness"}},
	Enforcement:    "ENFORCED",
	EnforcedBy:     []string{"check_canonical_lifecycles_wellformed"},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "2026-06-30",
	SourceRefs:     []string{},
	DeclOrder:      47,
})

var _ = Requirements.MustRegister("R-statemachine-wellformedness", ontology.Requirement{
	ID:             "R-statemachine-wellformedness",
	Claim:          "Every modeled state machine shall be reachable, deterministic, and terminal (or explicitly cyclic); a transition guard may rest on an Assumption (the behavioral drift seam).",
	Owner:          "framework-author",
	Status:         "REJECTED",
	Why:            "REJECTED — REPLACES by R-statemachine-reachable + R-statemachine-deterministic + R-statemachine-terminal-or-cyclic + R-statemachine-guard-on-assumption per atomicity discipline (R-requirement-claim-is-atomic). The original claim mixed four concerns: reachability, determinism, termination, guard-on-assumption.",
	Assumptions:    []string{"A-bootstrap-self-applies"},
	Relations:      []ontology.Relation{},
	Enforcement:    "PROSE",
	EnforcedBy:     []string{},
	MTag:           "",
	Enforceability: "ENFORCEABLE",
	Summary:        "",
	CreatedAt:      "2026-06-30",
	SettledAt:      "",
	SourceRefs:     []string{},
	DeclOrder:      44,
})
