// spec_build.go holds the data-collection AND rendering machinery behind
// docs/gen/SPEC.md: the generated NORMATIVE TEXT projection
// PLAN-scenario-generated-spec.md §2 D2/§3 W1.3 names — the successor stage
// to the authored-spec discipline's own projections (traceability.go/
// models.go/coverage.go, internal/generator): a requirement's claim (still
// the short AUTHORED intent from graph.json, D2 — never invented here)
// followed by the GENERATED prose narrative of its verified_by scenario(s),
// rendered from the ACTUAL Given/When/Then/Value steps a real, passing
// `go test` run just recorded via internal/recorder/canon's hotamspec API
// (PLAN-scenario-generated-spec.md §1's "text incarnates the actually-run
// test", never a second, independently-writable source of truth).
//
// LAYERING: collection and rendering live here so internal/invariants can
// consume SPEC freshness without importing internal/generator and closing its
// existing diagnose -> invariants dependency cycle. This package remains a
// leaf over loader, ontology, localization, and docbundle; generator and CLI
// entry points share the same rows/renderers through their wrappers.
//
// Unlike traceability.go/models.go/coverage.go, SPEC includes real execution
// evidence. Legacy scenario graphs record each verified_by test through
// RunVerifiedByTestRecording; self-executing atom graphs record each distinct
// source package once through RunAtomPackageRecording, preserving per-test and
// per-subtest verdicts/artifacts in one invocation-local snapshot.
//
// This file is read-only over the graph and re-EXECUTES the domain's own
// authored code via `go test` purely to observe what a real scenario
// narrated; it never mutates the graph, never writes to the domain's spec/
// tree. check_spec_md_current (internal/invariants/spec_md_current.go, W2.3)
// is the mechanical staleness gate that consumes this file's output; this
// file itself only renders what a fresh run reports NOW.
package gate

import (
	"encoding/json"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/PHPCraftdream/HotamSpec/internal/docbundle"
	"github.com/PHPCraftdream/HotamSpec/internal/localization"
	"github.com/PHPCraftdream/HotamSpec/internal/ontology"
)

// specBanner/specEmptyNotice/specCell/specReaderHeaderLine are local,
// SPEC.md-scoped equivalents of internal/generator/common.go's
// Banner/EmptyNotice/Cell/ReaderHeaderLine -- duplicated here (rather than
// imported) because internal/generator is not reachable from internal/gate
// without inverting the dependency this file exists to avoid (see the
// package doc comment's LAYERING section). Kept as the SAME literal text
// generator.Banner/generator.EmptyNotice carry today, and Cell/
// ReaderHeaderLine reimplemented against the identical logic, so
// BuildSpecFromRows's rendered bytes are unchanged from before this move --
// internal/generator/spec_test.go's byte-identical-to-golden test is the
// mechanical proof this duplication stayed faithful.
const specBanner = "<!-- AUTOGENERATED from the domain graph.json — do not edit by hand. Edits: methodology/graph -> hotam gen-spec -->"

// IsGeneratedSpecDocument recognizes existing generated first-line banners.
func IsGeneratedSpecDocument(content string) bool {
	firstLine, _, hasLine := strings.Cut(content, "\n")
	if !hasLine {
		return false
	}
	firstLine = strings.TrimSuffix(firstLine, "\r")
	for _, language := range []string{"en", "ru", "zh"} {
		banner, err := localization.Lookup(language, specBanner)
		if err == nil && firstLine == banner {
			return true
		}
	}
	return false
}

const specEmptyNotice = "_No domain content loaded — no `domains/<name>/graph.json` found. Run `hotam init <dir>` to scaffold a new domain, then `hotam gen-spec --domain <dir>` to populate docs/gen/. The methodology narrative below is the framework itself and is always present._"

const specIntro = "Generated from this domain's `graph.json` claims plus REAL, currently-passing `go test` runs of every `verified_by` entry, recorded via the `hotamspec` scenario API (PLAN-scenario-generated-spec.md §1/§2 D1/D2, task W1.3): the normative body under each requirement is not hand-written prose — it is the Given/When/Then/Value narrative a real test run just produced. `graph.json` remains the bookkeeping layer (id, short authored claim, status); this document is the derived projection, never the other way around. Not an enforcement gate itself — a future `check_spec_md_current` (W2.3) is the mechanical staleness floor; this generator only renders what the CURRENT run reports."

func specText(language, template string, args ...any) (string, error) {
	if language == "" {
		return fmt.Sprintf(template, args...), nil
	}
	localized, err := localization.Lookup(language, template)
	if err != nil {
		return "", err
	}
	return fmt.Sprintf(localized, args...), nil
}

func specLanguage(g *ontology.Graph) string {
	if g.RenderLanguage != "" {
		return g.RenderLanguage
	}
	if g.DefaultLanguage != "" {
		return g.DefaultLanguage
	}
	if len(g.Languages) == 1 {
		return g.Languages[0]
	}
	return ""
}

func specClaim(g *ontology.Graph, r ontology.Requirement, language string) (string, error) {
	if language == "" {
		return r.Claim, nil
	}
	if claim, ok := r.ClaimTexts[language]; ok && strings.TrimSpace(claim) != "" {
		return claim, nil
	}
	if len(g.Languages) > 1 {
		return "", fmt.Errorf("requirement %s has no claim text for language %q", r.ID, language)
	}
	return r.Claim, nil
}

// specReaderHeaderLine mirrors generator.ReaderHeaderLine("SPEC", g) except
// that an unresolved reader yields an empty line: consumer domains have no
// "domain-user" stakeholder, and a "reader: (unresolved-reader)" line carries
// no information. SPEC.md's DocReaderRoles entry is RoleDomainResolver and its
// DomainDocReaders binding is "domain-user" -- both hardcoded here since
// this file only ever renders the one "SPEC" docKind, unlike
// generator.ReaderHeaderLine's general docKind lookup table.
func specReaderHeaderLine(g *ontology.Graph, language string) (string, error) {
	boundID := "domain-user"
	if _, exists := ontology.StakeholderIDs(g)[boundID]; !exists {
		return "", nil
	}
	return specText(language, "reader: %s", boundID)
}

// specCell mirrors generator.Cell exactly: a Markdown-table-safe cell
// renderer (newlines flattened, pipes escaped).
func specCell(text string) string {
	t := strings.ReplaceAll(text, "\n", " ")
	t = strings.ReplaceAll(t, "|", "\\|")
	return t
}

// specArtifact is one parsed hotamspec.Artifact (internal/recorder/canon's
// JSON shape) read back from a RunVerifiedByTestRecording call -- this
// package's own local decode target so this file does not need to import
// internal/recorder/canon (gate already avoids that coupling for the same
// reason, see RecordedArtifact's doc comment: canon is vendored into
// consumer domains, never imported cross-module by the engine).
type specArtifact struct {
	ReqID   string                   `json:"req_id"`
	Test    string                   `json:"test"`
	Title   string                   `json:"title"`
	Steps   []specArtifactStep       `json:"steps"`
	Verdict string                   `json:"verdict"`
	Mode    string                   `json:"mode,omitempty"`
	Case    *ontology.CaseDefinition `json:"-"`
}

type specArtifactStep struct {
	Kind    string           `json:"kind"`
	Desc    string           `json:"desc"`
	Values  []specArtifactKV `json:"values,omitempty"`
	Passed  bool             `json:"passed,omitempty"`
	Subject string           `json:"subject,omitempty"`
	Value   string           `json:"value,omitempty"`
}

type specArtifactKV struct {
	Key   string `json:"k"`
	Value string `json:"v"`
}

// specTestOutcome separates passing, narratable artifacts from failed siblings.
// A package-level failure must not erase an independently passing subtest.
type specTestOutcome struct {
	entry           string
	artifacts       []specArtifact
	failedArtifacts []specArtifact
	problem         string
	passed          bool
}

// SpecRow is one rendered requirement section: its own id/claim (the D2
// short authored intent, taken verbatim from the graph, never invented
// here) plus every verified_by entry's recording outcome.
type SpecRow struct {
	req         ontology.Requirement
	outcomes    []specTestOutcome
	sourceError error
}

// ScenarioVerdict is one requirement's REAL (executed, `--spec`-gated)
// scenario-narrative outcome, derived from the same SpecRow/specTestOutcome
// data BuildSpecFromRows itself renders narratives from (see
// ScenarioVerdictsFromRows).
//
// HISTORICAL NOTE (task #317, superseded by task #370/RAC3-B's audit): this
// type was originally meant to feed an optional "verdict" sub-column on
// internal/generator.BuildTraceability/BuildCoverage (PLAN-scenario-
// generated-spec.md §3 W1.4) -- but task #317 deliberately REMOVED that
// overlay (see internal/generator/scenario_traceability_test.go's
// TestBuildTraceability_ModeIndependent_.../
// TestBuildCoverage_ModeIndependent_...) to keep those two docs pure,
// mode-independent functions of the graph plus a cheap AST scan, so `hotam
// land`'s routine (non---spec) regeneration can never flip their content --
// see cmd/hotam/gen_spec.go's own comment on specRows for the current,
// authoritative wiring (SPEC.md only). Neither BuildTraceability nor
// BuildCoverage has taken a verdicts parameter since; this type and
// ScenarioVerdictsFromRows are kept only because generator.ScenarioVerdict
// re-exports them as part of this package's public surface and a test
// exercises them directly to prove they have zero effect on generator
// output -- task #370's own RequirementState (internal/selfspec/
// requirement_state.go) is the CURRENT, correct home for "is this
// requirement's verified_by evidence real, passing, and fresh" as a
// general-purpose, execution-based predicate; a caller that genuinely needs
// a real per-requirement pass/fail+freshness verdict should use that instead
// of this narrower, SPEC.md-era shape.
type ScenarioVerdict struct {
	// Narrated is true when at least one verified_by entry produced at
	// least one hotamspec.Artifact with verdict "pass" -- the same bar
	// BuildSpecFromRows's own narratedCount uses.
	Narrated bool
	// AllEntriesPass is true when EVERY verified_by entry on the
	// requirement resolved to a currently-passing `go test` run (whether or
	// not it narrated a scenario) -- i.e. specTestOutcome.passed is true for
	// every entry. Deliberately independent of whether an entry narrated: a
	// PLAIN (non-scenario) verified_by test that genuinely passes still
	// counts as "passing" here (see specTestOutcome.passed's own doc
	// comment -- zero-trust finding: conflating "did not narrate" with "did
	// not pass" produced a false failure signal in TRACEABILITY.md's
	// verdict column for a requirement whose second verified_by entry was
	// simply a passing plain test). A requirement can have Narrated==true
	// and AllEntriesPass==false if it carries more than one verified_by
	// entry and one of them GENUINELY fails/errors/is skipped; callers that
	// want a single pass/fail verdict should treat
	// Narrated && AllEntriesPass as the strict "fully proven, fully
	// narrated" state.
	AllEntriesPass bool
}

// AtomExecutionSnapshot owns the package results and source/test maps shared
// by discovery, evidence/conformance, and SPEC projection for one invocation.
type AtomExecutionSnapshot struct {
	PackageFiles map[string]string
	PackageRuns  map[string]RecordingResult
	SourceIndex  *AtomSourceIndex
	TestFiles    map[string]map[string]string
	SourceErr    error
	DiscoveryErr error
}

// CollectAtomExecutionSnapshot records every required package once. Self-
// executing atom domains additionally scan their model test packages to retain
// report-only atoms; rule-case configuration alone never enables that scan.
func CollectAtomExecutionSnapshot(g *ontology.Graph) (*AtomExecutionSnapshot, error) {
	if g == nil {
		return nil, fmt.Errorf("atom execution snapshot graph is nil")
	}
	snapshot := &AtomExecutionSnapshot{
		PackageFiles: make(map[string]string),
		PackageRuns:  make(map[string]RecordingResult),
		TestFiles:    make(map[string]map[string]string),
	}
	for _, requirement := range g.Requirements {
		if requirement.Status == ontology.StatusREJECTED {
			continue
		}
		for _, reference := range requirement.VerifiedBy {
			addSnapshotTestReference(snapshot, reference)
		}
		for _, caseDef := range requirement.Cases {
			addSnapshotTestReference(snapshot, caseDef.Test)
		}
	}
	specRoot := SpecRootForGraph(g)
	if g.SelfExecutingAtoms {
		snapshot.SourceIndex, snapshot.SourceErr = NewAtomSourceIndexForGraph(g)
		if snapshot.SourceErr == nil {
			for _, requirement := range g.Requirements {
				if requirement.Status == ontology.StatusREJECTED ||
					(len(requirement.VerifiedBy) == 0 && len(requirement.Cases) == 0) ||
					len(requirement.ImplementedBy) == 0 {
					continue
				}
				if snapshot.SourceErr = snapshot.SourceIndex.ValidatePhraseLanguages(requirement.ImplementedBy); snapshot.SourceErr != nil {
					break
				}
			}
		}
		snapshot.DiscoveryErr = discoverSnapshotModelTests(specRoot, snapshot)
	}
	if snapshot.SourceErr == nil && snapshot.DiscoveryErr == nil {
		for _, dir := range sortedSnapshotDirs(snapshot.PackageFiles) {
			snapshot.PackageRuns[dir] = RunAtomPackageRecording(specRoot, snapshot.PackageFiles[dir])
		}
	}
	return snapshot, nil
}

// CollectSpecRows preserves the legacy per-verified_by scenario runner for
// ordinary graphs. Atom/case graphs opt into the package snapshot path.
func CollectSpecRows(g *ontology.Graph) map[string]SpecRow {
	if !needsAtomSnapshot(g) {
		return collectLegacySpecRows(g)
	}
	snapshot, err := CollectAtomExecutionSnapshot(g)
	if err != nil {
		panic(err)
	}
	return CollectSpecRowsFromSnapshot(g, snapshot)
}

func needsAtomSnapshot(g *ontology.Graph) bool {
	if g.SelfExecutingAtoms {
		return true
	}
	for _, requirement := range g.Requirements {
		if requirement.AtomKind == "rule" || len(requirement.Cases) != 0 {
			return true
		}
	}
	return false
}

func collectLegacySpecRows(g *ontology.Graph) map[string]SpecRow {
	rows := make(map[string]SpecRow, len(g.Requirements))
	if g.IsEmpty() {
		return rows
	}
	specRoot := SpecRootForGraph(g)
	for _, requirement := range g.Requirements {
		if len(requirement.VerifiedBy) == 0 {
			continue
		}
		coverFile := firstImplementedByFile(requirement)
		row := SpecRow{req: requirement}
		for _, entry := range requirement.VerifiedBy {
			row.outcomes = append(row.outcomes, recordVerifiedByEntry(specRoot, requirement.ID, entry, coverFile))
		}
		rows[requirement.ID] = row
	}
	return rows
}

// CollectSpecRowsFromSnapshot projects SPEC outcomes without executing tests.
func CollectSpecRowsFromSnapshot(g *ontology.Graph, snapshot *AtomExecutionSnapshot) map[string]SpecRow {
	rows := make(map[string]SpecRow, len(g.Requirements))
	if g.IsEmpty() || snapshot == nil {
		return rows
	}
	var snapshotError error
	if g.SelfExecutingAtoms {
		snapshotError = snapshot.SourceErr
		if snapshotError == nil {
			snapshotError = snapshot.DiscoveryErr
		}
	}
	for _, requirement := range g.Requirements {
		if requirement.Status == ontology.StatusREJECTED {
			continue
		}
		references := specTestReferences(requirement)
		if len(references) == 0 {
			continue
		}
		row := SpecRow{req: requirement, sourceError: snapshotError}
		for _, entry := range references {
			file, test, ok := ParseFileColonSymbol(strings.TrimSpace(entry))
			if !ok {
				row.outcomes = append(row.outcomes, specTestOutcome{entry: entry, problem: "malformed test or case reference"})
				continue
			}
			if snapshotError != nil {
				row.outcomes = append(row.outcomes, specTestOutcome{entry: entry, problem: snapshotError.Error()})
				continue
			}
			packageDir := snapshotPackageDir(file)
			result, found := snapshot.PackageRuns[packageDir]
			if !found {
				problem := "verified_by package was not present in the shared execution snapshot"
				row.outcomes = append(row.outcomes, specTestOutcome{entry: entry, problem: problem})
				continue
			}
			if g.SelfExecutingAtoms {
				row.outcomes = append(row.outcomes, atomRecordingOutcome(snapshot.SourceIndex, requirement, entry, test, result))
			} else {
				row.outcomes = append(row.outcomes, scenarioRecordingOutcomeFromPackage(g, requirement, entry, test, result))
			}
		}
		rows[requirement.ID] = row
	}
	return rows
}

func addSnapshotTestReference(snapshot *AtomExecutionSnapshot, reference string) {
	file, test, ok := ParseFileColonSymbol(strings.TrimSpace(reference))
	if !ok {
		return
	}
	file = filepath.ToSlash(filepath.Clean(filepath.FromSlash(file)))
	dir := snapshotPackageDir(file)
	if old, exists := snapshot.PackageFiles[dir]; !exists || file < old {
		snapshot.PackageFiles[dir] = file
	}
	rootTest := strings.SplitN(test, "/", 2)[0]
	if rootTest == "" {
		return
	}
	if snapshot.TestFiles[dir] == nil {
		snapshot.TestFiles[dir] = make(map[string]string)
	}
	if old, exists := snapshot.TestFiles[dir][rootTest]; !exists || file < old {
		snapshot.TestFiles[dir][rootTest] = file
	}
}

func snapshotPackageDir(file string) string {
	return filepath.ToSlash(filepath.Dir(filepath.FromSlash(file)))
}

func sortedSnapshotDirs(files map[string]string) []string {
	dirs := make([]string, 0, len(files))
	for dir := range files {
		dirs = append(dirs, dir)
	}
	sort.Strings(dirs)
	return dirs
}

func discoverSnapshotModelTests(specRoot string, snapshot *AtomExecutionSnapshot) error {
	modelRoot := filepath.Join(specRoot, "spec", "model")
	fileSet := token.NewFileSet()
	hasRuleCaseOption := false
	err := filepath.WalkDir(modelRoot, func(path string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() || !strings.HasSuffix(path, "_test.go") {
			return nil
		}
		relative, err := filepath.Rel(specRoot, path)
		if err != nil {
			return err
		}
		relative = filepath.ToSlash(relative)
		dir := snapshotPackageDir(relative)
		if old, exists := snapshot.PackageFiles[dir]; !exists || relative < old {
			snapshot.PackageFiles[dir] = relative
		}
		file, err := parser.ParseFile(fileSet, path, nil, 0)
		if err != nil {
			return err
		}
		testingAliases := testingPackageAliases(file)
		recorderAliases := make(map[string]bool)
		if snapshot.SourceIndex != nil {
			recorderAliases = recorderPackageAliases(file, snapshot.SourceIndex.RecorderImportPath)
		}
		if snapshot.TestFiles[dir] == nil {
			snapshot.TestFiles[dir] = make(map[string]string)
		}
		for _, declaration := range file.Decls {
			fn, ok := declaration.(*ast.FuncDecl)
			if !ok || !isSnapshotTest(fn, testingAliases) {
				continue
			}
			if previous, exists := snapshot.TestFiles[dir][fn.Name.Name]; exists && previous != relative {
				return fmt.Errorf("duplicate test %s in %s and %s", fn.Name.Name, previous, relative)
			}
			snapshot.TestFiles[dir][fn.Name.Name] = relative
			ast.Inspect(fn.Body, func(node ast.Node) bool {
				call, ok := node.(*ast.CallExpr)
				if !ok {
					return true
				}
				function := call.Fun
				if indexed, ok := function.(*ast.IndexExpr); ok {
					function = indexed.X
				}
				selector, ok := function.(*ast.SelectorExpr)
				if !ok || selector.Sel.Name != "WithCase" {
					return true
				}
				qualifier, ok := selector.X.(*ast.Ident)
				if ok && recorderAliases[qualifier.Name] {
					hasRuleCaseOption = true
				}
				return true
			})
		}
		return nil
	})
	if err != nil {
		return err
	}
	if hasRuleCaseOption && snapshot.SourceIndex != nil && !snapshot.SourceIndex.ruleCases {
		return fmt.Errorf("hotamspec.WithCase requires conformance.rule_cases")
	}
	return nil
}

func recorderPackageAliases(file *ast.File, recorderImportPath string) map[string]bool {
	aliases := make(map[string]bool)
	for _, imported := range file.Imports {
		path, err := strconv.Unquote(imported.Path.Value)
		if err != nil || path != recorderImportPath {
			continue
		}
		name := filepath.Base(path)
		if imported.Name != nil {
			name = imported.Name.Name
		}
		if name != "_" && name != "." {
			aliases[name] = true
		}
	}
	return aliases
}

func testingPackageAliases(file *ast.File) map[string]bool {
	aliases := make(map[string]bool)
	for _, imported := range file.Imports {
		path, err := strconv.Unquote(imported.Path.Value)
		if err != nil || path != "testing" {
			continue
		}
		name := filepath.Base(path)
		if imported.Name != nil {
			name = imported.Name.Name
		}
		if name != "_" && name != "." {
			aliases[name] = true
		}
	}
	return aliases
}

func isSnapshotTest(fn *ast.FuncDecl, testingAliases map[string]bool) bool {
	if fn.Recv != nil || fn.Body == nil || !strings.HasPrefix(fn.Name.Name, "Test") ||
		fn.Type.TypeParams != nil || (fn.Type.Results != nil && len(fn.Type.Results.List) != 0) {
		return false
	}
	suffix := strings.TrimPrefix(fn.Name.Name, "Test")
	firstRune, _ := utf8.DecodeRuneInString(suffix)
	if unicode.IsLower(firstRune) {
		return false
	}
	if fn.Type.Params == nil || len(fn.Type.Params.List) != 1 || len(fn.Type.Params.List[0].Names) > 1 {
		return false
	}
	pointer, ok := fn.Type.Params.List[0].Type.(*ast.StarExpr)
	if !ok {
		return false
	}
	selector, ok := pointer.X.(*ast.SelectorExpr)
	if !ok || selector.Sel.Name != "T" {
		return false
	}
	qualifier, ok := selector.X.(*ast.Ident)
	return ok && testingAliases[qualifier.Name]
}

// ScenarioVerdictsFromRows reduces a CollectSpecRows result to the
// requirement-keyed ScenarioVerdict map internal/generator's
// BuildTraceability/BuildCoverage accept, without touching the disk or
// spawning any further subprocess -- pure post-processing of data already
// collected.
func ScenarioVerdictsFromRows(rows map[string]SpecRow) map[string]ScenarioVerdict {
	verdicts := make(map[string]ScenarioVerdict, len(rows))
	for id, row := range rows {
		narrated := false
		allPass := true
		for _, o := range row.outcomes {
			if len(o.artifacts) > 0 {
				narrated = true
			}
			// AllEntriesPass reflects whether the test GENUINELY passed
			// (o.passed), not whether it narrated (o.problem != "" is also
			// true for a plain, passing, non-scenario test -- see
			// specTestOutcome.passed's doc comment for the zero-trust finding
			// this fixes).
			if !o.passed {
				allPass = false
			}
		}
		verdicts[id] = ScenarioVerdict{Narrated: narrated, AllEntriesPass: allPass}
	}
	return verdicts
}

// BuildSpec renders a single selected view from one fresh CollectSpecRows
// snapshot. Multilingual publication callers use BuildSpecDocumentsFromRows
// with a shared rows map so each language consumes identical evidence.
//
// BuildSpec itself is the convenient execution entry point; callers that also
// need other projections from the same snapshot should collect once and pass
// those rows to each renderer. No renderer persists verdicts or executes
// methods while changing language.
func BuildSpec(g *ontology.Graph) string {
	return BuildSpecFromRows(g, CollectSpecRows(g))
}

// BuildSpecFromRows renders a single language view from an already-collected
// snapshot. Its legacy string signature panics with the original render error
// instead of returning an empty/fallback document; callers needing an error
// value use BuildSpecFromRowsForLanguage or BuildSpecDocumentsFromRows.
func BuildSpecFromRows(g *ontology.Graph, rows map[string]SpecRow) string {
	document, err := BuildSpecFromRowsForLanguage(g, rows, specLanguage(g))
	if err != nil {
		panic(err)
	}
	return document
}

// BuildSpecFromRowsForLanguage strictly renders one explicit language view
// without executing tests or changing shared graph state.
func BuildSpecFromRowsForLanguage(g *ontology.Graph, rows map[string]SpecRow, language string) (string, error) {
	view := *g
	view.RenderLanguage = language
	return renderSpecFromRows(&view, rows, language)
}

func renderSpecFromRows(g *ontology.Graph, rows map[string]SpecRow, language string) (string, error) {
	for _, requirement := range g.Requirements {
		if row, ok := rows[requirement.ID]; ok && row.sourceError != nil {
			return "", row.sourceError
		}
	}
	banner, err := specText(language, specBanner)
	if err != nil {
		return "", err
	}
	reader, err := specReaderHeaderLine(g, language)
	if err != nil {
		return "", err
	}
	title, err := specText(language, "# SPEC.md — generated normative text (Hotam-Spec)")
	if err != nil {
		return "", err
	}
	intro, err := specText(language, specIntro)
	if err != nil {
		return "", err
	}
	lines := []string{banner}
	if reader != "" {
		lines = append(lines, reader)
	}
	lines = append(lines, "", title, "", intro, "")
	if g.IsEmpty() {
		emptyNotice, err := specText(language, specEmptyNotice)
		if err != nil {
			return "", err
		}
		lines = append(lines, emptyNotice, "")
		return strings.TrimRight(strings.Join(lines, "\n"), " \t\r\n") + "\n", nil
	}

	reqs := make([]ontology.Requirement, len(g.Requirements))
	copy(reqs, g.Requirements)
	sort.Slice(reqs, func(i, j int) bool { return reqs[i].ID < reqs[j].ID })
	if g.SelfExecutingAtoms {
		sort.SliceStable(reqs, func(i, j int) bool {
			if reqs[i].DeclOrder != reqs[j].DeclOrder {
				return reqs[i].DeclOrder < reqs[j].DeclOrder
			}
			return reqs[i].ID < reqs[j].ID
		})
	}

	var withScenario, withoutVerifiedBy []ontology.Requirement
	verifiedByCount := 0
	caseOnlyCount := 0
	for _, r := range reqs {
		if r.Status == ontology.StatusREJECTED {
			continue
		}
		if len(specTestReferences(r)) == 0 {
			withoutVerifiedBy = append(withoutVerifiedBy, r)
			continue
		}
		withScenario = append(withScenario, r)
		if len(r.VerifiedBy) == 0 {
			caseOnlyCount++
		} else {
			verifiedByCount++
		}
	}

	narratedCount := 0
	for _, r := range withScenario {
		for _, outcome := range rows[r.ID].outcomes {
			if len(outcome.artifacts) > 0 {
				narratedCount++
				break
			}
		}
	}
	var summary string
	if caseOnlyCount == 0 {
		summary, err = specText(language,
			"**%d requirement(s) carry `verified_by`; %d have at least one recorded scenario narrative; %d carry no `verified_by` yet (no code carrier, honest gap).**",
			verifiedByCount, narratedCount, len(withoutVerifiedBy))
	} else {
		summary, err = specText(language,
			"**%d requirement(s) carry `verified_by`; %d carry declared case tests only; %d have at least one recorded scenario narrative; %d have neither test nor case reference (honest gap).**",
			verifiedByCount, caseOnlyCount, narratedCount, len(withoutVerifiedBy))
	}
	if err != nil {
		return "", err
	}
	lines = append(lines, summary, "", "---", "")
	withHeadingTemplate := "## Requirements with a verified_by scenario"
	if caseOnlyCount > 0 {
		withHeadingTemplate = "## Requirements with a verified_by scenario or declared case test"
	}
	withHeading, err := localization.Lookup(language, withHeadingTemplate)
	if err != nil {
		return "", err
	}
	lines = append(lines, withHeading, "")
	if len(withScenario) == 0 {
		none, err := specText(language, "_None in this domain yet — the scenario-generated-spec layer (PLAN-scenario-generated-spec.md §3 W1.3) has not been started for this domain._")
		if err != nil {
			return "", err
		}
		lines = append(lines, none, "")
	} else {
		for _, r := range withScenario {
			rendered, err := renderSpecRequirement(g, rows[r.ID], language)
			if err != nil {
				return "", err
			}
			lines = append(lines, rendered...)
		}
	}

	withoutHeadingTemplate := "## Without a scenario (no verified_by — honest gap)"
	noCarrierTemplate := "Requirements with no `verified_by` entry at all: SETTLED without a code carrier is honest roadmap debt (mirrors TRACEABILITY.md/COVERAGE.md's own partition), never silently claimed narrated."
	if caseOnlyCount > 0 {
		withoutHeadingTemplate = "## Without a scenario or declared case test (honest gap)"
		noCarrierTemplate = "Requirements with no `verified_by` or declared case test: no code carrier or executed case is available; honest gap."
	}
	withoutHeading, err := localization.Lookup(language, withoutHeadingTemplate)
	if err != nil {
		return "", err
	}
	noCarrier, err := localization.Lookup(language, noCarrierTemplate)
	if err != nil {
		return "", err
	}
	lines = append(lines, withoutHeading, "", noCarrier, "")
	if len(withoutVerifiedBy) == 0 {
		noneTemplate := "_None — every requirement in this domain carries at least one `verified_by` entry._"
		if caseOnlyCount > 0 {
			noneTemplate = "_None — every requirement in this domain carries a `verified_by` entry or declared case test._"
		}
		none, err := localization.Lookup(language, noneTemplate)
		if err != nil {
			return "", err
		}
		lines = append(lines, none, "")
	} else {
		header, err := specText(language, "| id | status | claim |")
		if err != nil {
			return "", err
		}
		lines = append(lines, header, "|---|---|---|")
		for _, r := range withoutVerifiedBy {
			claim, err := specClaim(g, r, language)
			if err != nil {
				return "", err
			}
			lines = append(lines, "| `"+r.ID+"` | "+specCell(r.Status)+" | "+specCell(claim)+" |")
		}
		lines = append(lines, "")
	}
	return strings.TrimRight(strings.Join(lines, "\n"), " \t\r\n") + "\n", nil
}

// firstImplementedByFile returns the file half of r's first implemented_by
// entry (best-effort coverPkgFile input for RunVerifiedByTestRecording —
// implemented_by and verified_by are independent lists, not index-paired,
// per PLAN-authored-spec-discipline.md §4/§12; a requirement with more than
// one implemented_by symbol still only needs ONE file in that symbol's own
// package to point -coverpkg at the right import path). Returns "" when r
// carries no implemented_by at all or the entry does not parse as
// "file:symbol" — RunVerifiedByTestRecording treats an empty coverPkgFile as
// "skip coverage collection", never an error, so a requirement missing
// implemented_by still gets its scenario narrated, just without a coverage
// profile (coverage-proof enforcement is check_scenario_executes_impl's job,
// W2.2, not this file's).
func firstImplementedByFile(r ontology.Requirement) string {
	if len(r.ImplementedBy) == 0 {
		return ""
	}
	file, _, ok := ParseFileColonSymbol(strings.TrimSpace(r.ImplementedBy[0]))
	if !ok {
		return ""
	}
	return file
}

// recordVerifiedByEntry runs ONE verified_by entry via
// RunVerifiedByTestRecording (a single real `go test` invocation) and
// classifies the outcome honestly: a non-empty problem string names EXACTLY
// why no scenario narrative could be rendered for this entry, so
// renderSpecRequirement never has to guess or paper over a gap.
func recordVerifiedByEntry(specRoot, reqID, entry, coverFile string) specTestOutcome {
	out := specTestOutcome{entry: entry}
	file, testName, ok := ParseFileColonSymbol(strings.TrimSpace(entry))
	if !ok {
		out.problem = "malformed verified_by entry (expected file:symbol)"
		return out
	}

	result := RunVerifiedByTestRecording(specRoot, file, testName, coverFile)
	switch {
	case result.Skipped:
		out.problem = "not executed at this nesting level (recursion guard honored) — " + result.InfraWarning
		return out
	case result.Err != nil:
		out.problem = "could not be executed: " + result.Err.Error()
		return out
	case result.CompileFailed:
		out.problem = "package does not compile"
		return out
	case !result.Passed:
		out.problem = "test does not currently pass"
		return out
	}

	// Reached only when result.Passed is true (every earlier branch above
	// returns first) -- this entry's test genuinely passes, whether or not
	// it goes on to narrate a scenario below.
	out.passed = true

	var artifacts []specArtifact
	for _, a := range result.Artifacts {
		var parsed specArtifact
		if err := json.Unmarshal(a.RawJSON, &parsed); err != nil {
			// A malformed artifact from a passing run should be structurally
			// impossible (internal/recorder/canon's writeArtifact only ever
			// emits its own Artifact shape) — treat it as "no narrative"
			// rather than fail the whole document, since the test itself did
			// pass and that verdict must not be hidden by a rendering bug.
			continue
		}
		if parsed.Verdict != "pass" {
			continue
		}
		// F6 (task W7.2, @fx finding F6): cross-check the artifact's req_id
		// against the requirement ID actually being processed. A test cited
		// by R-A's verified_by whose hotamspec.NewScenario(t, "R-B", ...)
		// call names a DIFFERENT requirement would otherwise have its
		// narrative rendered into R-A's SPEC.md section undetected. Filter
		// it out the same way Verdict != "pass" is filtered -- do not render
		// an artifact that belongs to a different requirement.
		if parsed.ReqID != reqID {
			continue
		}
		artifacts = append(artifacts, parsed)
	}
	out.artifacts = artifacts
	if len(artifacts) == 0 {
		out.problem = "test passes but recorded no hotamspec scenario (plain go test, no narrative to render)"
	}
	return out
}

func scenarioRecordingOutcomeFromPackage(g *ontology.Graph, req ontology.Requirement, entry, test string, result RecordingResult) specTestOutcome {
	out := specTestOutcome{entry: entry}
	switch {
	case result.Skipped:
		out.problem = result.InfraWarning
		return out
	case result.Err != nil:
		out.problem = result.Err.Error()
		return out
	case result.CompileFailed:
		out.problem = "package does not compile"
		return out
	}
	executed, allPass := atomTestVerdict(result, test)
	out.passed = executed && allPass
	if !executed {
		if req.AtomKind == "rule" {
			out.problem = "declared rule case test was not executed"
		} else {
			out.problem = "test passes but recorded no hotamspec scenario (plain go test, no narrative to render)"
		}
		return out
	}
	var artifactProblem string
	for _, recorded := range result.Artifacts {
		var art specArtifact
		if json.Unmarshal(recorded.RawJSON, &art) != nil || (art.Test != test && !strings.HasPrefix(art.Test, test+"/")) {
			continue
		}
		if art.Mode == "" {
			if art.ReqID != req.ID {
				continue
			}
		} else {
			atom, err := DecodeAtomArtifact(recorded.RawJSON)
			if err != nil {
				artifactProblem = err.Error()
				continue
			}
			if atom.Mode != "rule" || req.AtomKind != "rule" ||
				g.Conformance == nil || !g.Conformance.RuleCases {
				if art.ReqID == req.ID {
					artifactProblem = fmt.Sprintf("atom %s requires self_executing_atoms and conformance.rule_cases discovery", art.ReqID)
				}
				continue
			}
			caseDef, err := atomCaseDefinition(atom, entry)
			if err != nil {
				artifactProblem = err.Error()
				continue
			}
			if art.ReqID != req.ID && !caseListsAtom(caseDef, req.ID) {
				continue
			}
			if caseDef, err = reconcileRecordedCase(req.Cases, *caseDef); err != nil {
				artifactProblem = err.Error()
				continue
			}
			art.Case = caseDef
		}
		if art.Verdict == "pass" {
			out.artifacts = append(out.artifacts, art)
		} else {
			out.failedArtifacts = append(out.failedArtifacts, art)
		}
	}
	if artifactProblem != "" {
		out.problem = artifactProblem
	}
	if !allPass && len(out.failedArtifacts) == 0 && out.problem == "" {
		out.problem = "test does not currently pass"
	}
	if len(out.artifacts) == 0 && len(out.failedArtifacts) == 0 && out.problem == "" {
		if req.AtomKind == "rule" {
			out.problem = "test passes but recorded no matching rule case evidence"
		} else {
			out.problem = "test passes but recorded no hotamspec scenario (plain go test, no narrative to render)"
		}
	}
	return out
}

func caseListsAtom(caseDef *ontology.CaseDefinition, atomID string) bool {
	for _, id := range caseDef.AtomIDs {
		if id == atomID {
			return true
		}
	}
	return false
}
func specStatusText(language, status string) (string, error) {
	if status == "" {
		return "", nil
	}
	token, detail := status, ""
	if strings.HasPrefix(status, "OPEN(") {
		token, detail = "OPEN", strings.TrimPrefix(status, "OPEN")
	}
	translated, err := localization.Lookup(language, token)
	if err != nil {
		return "", err
	}
	return translated + detail, nil
}

func renderSpecRequirement(g *ontology.Graph, row SpecRow, language string) ([]string, error) {
	claim, err := specClaim(g, row.req, language)
	if err != nil {
		return nil, err
	}
	heading := "## `" + row.req.ID + "`"
	claimLine, err := specText(language, "**Claim:** %s", specCell(claim))
	if err != nil {
		return nil, err
	}
	status, err := specStatusText(language, row.req.Status)
	if err != nil {
		return nil, err
	}
	enforcement, err := specStatusText(language, row.req.Enforcement)
	if err != nil {
		return nil, err
	}
	statusLine, err := specText(language, "**Status:** %s · **Enforcement:** %s", specCell(status), specCell(enforcement))
	if err != nil {
		return nil, err
	}
	lines := []string{heading, "", claimLine, "", statusLine, ""}
	for _, outcome := range row.outcomes {
		lines = append(lines, "### `"+outcome.entry+"`", "")
		if outcome.problem != "" {
			if len(outcome.artifacts)+len(outcome.failedArtifacts) == 0 {
				line, err := specText(language, "_No scenario narrative: %s._", specCell(outcome.problem))
				if err != nil {
					return nil, err
				}
				lines = append(lines, line, "")
				continue
			}
			line, err := specText(language, "_Evidence issue: %s._", specCell(outcome.problem))
			if err != nil {
				return nil, err
			}
			lines = append(lines, line, "")
		}
		for _, failed := range outcome.failedArtifacts {
			rendered, err := renderFailedSpecArtifact(failed, language)
			if err != nil {
				return nil, err
			}
			lines = append(lines, rendered...)
		}
		for _, artifact := range outcome.artifacts {
			rendered, err := renderSpecArtifact(artifact, claim, language)
			if err != nil {
				return nil, err
			}
			lines = append(lines, rendered...)
		}
	}
	return lines, nil
}

func renderSpecArtifact(art specArtifact, claim, language string) ([]string, error) {
	var lines []string
	if art.Mode == "" && strings.TrimSpace(art.Title) != strings.TrimSpace(claim) {
		lines = append(lines, "**"+specCell(art.Title)+"**", "")
	}
	caseLines, err := renderSpecCase(art.Case, language)
	if err != nil {
		return nil, err
	}
	lines = append(lines, caseLines...)
	stepLines, err := renderSpecSteps(art.Steps, language)
	if err != nil {
		return nil, err
	}
	lines = append(lines, stepLines...)
	lines = append(lines, "")
	return lines, nil
}

func renderFailedSpecArtifact(art specArtifact, language string) ([]string, error) {
	id := art.Test
	if art.Case != nil {
		id = art.Case.ID
	}
	template := "**Recorded artifact `%s` did not pass; its claim is not shown as verified.**"
	if art.Case != nil {
		template = "**Case `%s` did not pass; its claim is not shown as verified.**"
	}
	label, err := specText(language, template, specCell(id))
	if err != nil {
		return nil, err
	}
	lines := []string{label, ""}
	caseLines, err := renderSpecCase(art.Case, language)
	if err != nil {
		return nil, err
	}
	lines = append(lines, caseLines...)
	stepLines, err := renderSpecSteps(art.Steps, language)
	if err != nil {
		return nil, err
	}
	lines = append(lines, stepLines...)
	lines = append(lines, "")
	return lines, nil
}

func renderSpecCase(caseDef *ontology.CaseDefinition, language string) ([]string, error) {
	if caseDef == nil {
		return nil, nil
	}
	serialized, err := json.Marshal(caseDef)
	if err != nil {
		return nil, fmt.Errorf("render case %s: %w", caseDef.ID, err)
	}
	label, err := specText(language, "**Case descriptor**")
	if err != nil {
		return nil, err
	}
	return []string{label, "", "```json", string(serialized), "```", ""}, nil
}

func renderSpecSteps(steps []specArtifactStep, language string) ([]string, error) {
	var lines []string
	for _, step := range steps {
		if step.Subject != "" {
			lines = append(lines, "- `"+specCell(step.Subject)+"` — "+specCell(step.Value))
			continue
		}
		var line string
		var err error
		switch step.Kind {
		case "given":
			line, err = specText(language, "- Given %s%s", specCell(step.Desc), renderSpecFacts(step.Values))
		case "when":
			line, err = specText(language, "- When %s", specCell(step.Desc))
		case "then":
			outcome := "held"
			if !step.Passed {
				outcome = "FAILED"
			}
			localizedOutcome, err := localization.Lookup(language, outcome)
			if err != nil {
				return nil, err
			}
			line, err = specText(language, "- Then %s — **%s**", specCell(step.Desc), localizedOutcome)
		case "value":
			line, err = specText(language, "- Value%s", renderSpecFacts(step.Values))
		default:
			line, err = specText(language, "- %s: %s%s", specCell(step.Kind), specCell(step.Desc), renderSpecFacts(step.Values))
		}
		if err != nil {
			return nil, err
		}
		lines = append(lines, line)
	}
	return lines, nil
}

// renderSpecFacts renders a Step's Values as an inline " (k1=v1, k2=v2)"
// suffix, in the exact order the artifact already carries them (call order —
// never re-sorted, see internal/recorder/canon's kv doc comment for why
// Given/Value's facts are an ordered slice, not a map). Returns "" for an
// empty Values (a Given/Value step with no supporting facts), so a bare
// description does not grow a trailing " ()".
func renderSpecFacts(values []specArtifactKV) string {
	if len(values) == 0 {
		return ""
	}
	parts := make([]string, 0, len(values))
	for _, v := range values {
		parts = append(parts, v.Key+"="+v.Value)
	}
	return " (" + specCell(strings.Join(parts, ", ")) + ")"
}

func atomTestVerdict(result RecordingResult, test string) (executed, passed bool) {
	passed = true
	for _, verdict := range result.TestVerdicts {
		if verdict.Test != test && !strings.HasPrefix(verdict.Test, test+"/") {
			continue
		}
		executed = true
		if verdict.Verdict != "pass" {
			passed = false
		}
	}
	return executed, passed
}

func atomRecordingOutcome(sourceIndex *AtomSourceIndex, req ontology.Requirement, entry, test string, result RecordingResult) specTestOutcome {
	out := specTestOutcome{entry: entry}
	switch {
	case result.Skipped:
		out.problem = result.InfraWarning
		return out
	case result.Err != nil:
		out.problem = result.Err.Error()
		return out
	case result.CompileFailed:
		out.problem = "package does not compile"
		return out
	}
	executed, allPass := atomTestVerdict(result, test)
	out.passed = executed && allPass
	if !executed {
		out.problem = "verified_by test was not executed"
		return out
	}
	var artifactProblem string
	for _, recorded := range result.Artifacts {
		var art specArtifact
		if json.Unmarshal(recorded.RawJSON, &art) != nil || (art.Test != test && !strings.HasPrefix(art.Test, test+"/")) {
			continue
		}
		matches := art.ReqID == req.ID
		if !matches && art.Mode != "" && len(art.Steps) > 0 {
			source, err := sourceIndex.Resolve(art.Steps[0].Subject)
			if err == nil {
				matches = len(req.ImplementedBy) > 0 && req.ImplementedBy[0] == source.Link()
			}
		}
		if !matches {
			continue
		}
		var atom AtomArtifact
		if art.Mode != "" {
			var err error
			atom, err = DecodeAtomArtifact(recorded.RawJSON)
			if err != nil {
				artifactProblem = err.Error()
				continue
			}
			if atom.Mode == "rule" && !sourceIndex.ruleCases {
				artifactProblem = fmt.Sprintf("rule atom %s requires conformance.rule_cases", atom.ReqID)
				continue
			}
			if atom.Mode == "rule" {
				caseDef, err := atomCaseDefinition(atom, entry)
				if err != nil {
					artifactProblem = err.Error()
					continue
				}
				if caseDef, err = reconcileRecordedCase(req.Cases, *caseDef); err != nil {
					artifactProblem = err.Error()
					continue
				}
				art.Case = caseDef
			}
		}
		if art.Verdict == "pass" {
			if art.Mode != "" {
				claim, err := sourceIndex.DeriveClaim(atom)
				if err != nil {
					artifactProblem = err.Error()
					continue
				}
				art.Title = claim
			}
			out.artifacts = append(out.artifacts, art)
		} else {
			out.failedArtifacts = append(out.failedArtifacts, art)
		}
	}
	if artifactProblem != "" {
		out.problem = artifactProblem
	}
	if !allPass && len(out.failedArtifacts) == 0 && out.problem == "" {
		out.problem = "verified_by test or a nested subtest failed"
	}
	if len(out.artifacts) == 0 && len(out.failedArtifacts) == 0 && out.problem == "" {
		out.problem = "verified_by test passed but recorded no matching atom evidence"
	}
	return out
}

func atomCaseDefinition(atom AtomArtifact, entry string) (*ontology.CaseDefinition, error) {
	file, _, ok := ParseFileColonSymbol(strings.TrimSpace(entry))
	if !ok {
		return nil, fmt.Errorf("malformed verified_by entry")
	}
	if strings.TrimSpace(atom.Test) == "" {
		return nil, fmt.Errorf("rule atom %s artifact omits executed test identity", atom.ReqID)
	}
	return atom.CaseDefinition(file + ":" + atom.Test)
}

func reconcileRecordedCase(declared []ontology.CaseDefinition, recorded ontology.CaseDefinition) (*ontology.CaseDefinition, error) {
	for _, candidate := range declared {
		if candidate.ID != recorded.ID {
			continue
		}
		merged, err := mergeRecordedCase(candidate, recorded)
		if err != nil {
			return nil, err
		}
		return &merged, nil
	}
	return &recorded, nil
}

func mergeRecordedCase(declared, recorded ontology.CaseDefinition) (ontology.CaseDefinition, error) {
	if declared.ID != recorded.ID {
		return ontology.CaseDefinition{}, fmt.Errorf("case descriptor ID %q conflicts with recorded case %q", declared.ID, recorded.ID)
	}
	out := recorded
	mergeString := func(field string, saved *string, actual string) error {
		if *saved != "" && actual != "" && *saved != actual {
			return fmt.Errorf("case %s recorded %s conflicts with graph descriptor", declared.ID, field)
		}
		return nil
	}
	for _, field := range []struct {
		name  string
		saved *string
		value string
	}{
		{"test", &out.Test, declared.Test},
		{"profile", &out.Profile, declared.Profile},
		{"target", &out.Target, declared.Target},
		{"operation", &out.Operation, declared.Operation},
		{"producer", &out.Producer, declared.Producer},
	} {
		if err := mergeString(field.name, field.saved, field.value); err != nil {
			return ontology.CaseDefinition{}, err
		}
		if *field.saved == "" {
			*field.saved = field.value
		}
	}
	mergeSlice := func(field string, saved, actual any, savedEmpty, actualEmpty bool) error {
		if !savedEmpty && !actualEmpty && !reflect.DeepEqual(saved, actual) {
			return fmt.Errorf("case %s recorded %s conflicts with graph descriptor", declared.ID, field)
		}
		return nil
	}
	if err := mergeSlice("atom_ids", out.AtomIDs, declared.AtomIDs, len(out.AtomIDs) == 0, len(declared.AtomIDs) == 0); err != nil {
		return ontology.CaseDefinition{}, err
	}
	if len(out.AtomIDs) == 0 {
		out.AtomIDs = append([]string(nil), declared.AtomIDs...)
	}
	if err := mergeSlice("fixtures", out.Fixtures, declared.Fixtures, len(out.Fixtures) == 0, len(declared.Fixtures) == 0); err != nil {
		return ontology.CaseDefinition{}, err
	}
	if len(out.Fixtures) == 0 {
		out.Fixtures = append([]ontology.FixtureRef(nil), declared.Fixtures...)
	}
	if err := mergeSlice("conditions", out.Conditions, declared.Conditions, len(out.Conditions) == 0, len(declared.Conditions) == 0); err != nil {
		return ontology.CaseDefinition{}, err
	}
	if len(out.Conditions) == 0 {
		out.Conditions = append([]ontology.ConditionEvidence(nil), declared.Conditions...)
	}
	if err := mergeSlice("sides", out.Sides, declared.Sides, len(out.Sides) == 0, len(declared.Sides) == 0); err != nil {
		return ontology.CaseDefinition{}, err
	}
	if len(out.Sides) == 0 {
		out.Sides = append([]string(nil), declared.Sides...)
	}
	if out.Input != nil && declared.Input != nil && !ontology.EqualObservedValues(out.Input, declared.Input) {
		return ontology.CaseDefinition{}, fmt.Errorf("case %s recorded input conflicts with graph descriptor", declared.ID)
	}
	if out.Input == nil && declared.Input != nil {
		copy := *declared.Input
		out.Input = &copy
	}
	if out.Expected != nil && declared.Expected != nil && !ontology.EqualObservedValues(out.Expected, declared.Expected) {
		return ontology.CaseDefinition{}, fmt.Errorf("case %s recorded expected value conflicts with graph descriptor", declared.ID)
	}
	if out.Expected == nil && declared.Expected != nil {
		copy := *declared.Expected
		out.Expected = &copy
	}
	if out.Selection != nil && declared.Selection != nil && !reflect.DeepEqual(*out.Selection, *declared.Selection) {
		return ontology.CaseDefinition{}, fmt.Errorf("case %s recorded selection conflicts with graph descriptor", declared.ID)
	}
	if out.Selection == nil && declared.Selection != nil {
		copy := *declared.Selection
		out.Selection = &copy
	}
	return out, nil
}

// SpecPackage identifies the source package that owns a requirement.
func SpecPackage(r ontology.Requirement) string {
	file := firstImplementedByFile(r)
	if file == "" && len(r.VerifiedBy) > 0 {
		file, _, _ = ParseFileColonSymbol(r.VerifiedBy[0])
	}
	if file == "" {
		for _, caseDef := range r.Cases {
			if caseFile, _, ok := ParseFileColonSymbol(caseDef.Test); ok {
				file = caseFile
				break
			}
		}
	}
	pkg := strings.TrimPrefix(filepath.ToSlash(filepath.Dir(file)), "./")
	if pkg == "." || pkg == "" {
		return "root"
	}
	return pkg
}

func specTestReferences(requirement ontology.Requirement) []string {
	references := make([]string, 0, len(requirement.VerifiedBy)+len(requirement.Cases))
	seen := make(map[string]bool, len(requirement.VerifiedBy)+len(requirement.Cases))
	add := func(reference string) {
		reference = strings.TrimSpace(reference)
		if reference != "" && !seen[reference] {
			seen[reference] = true
			references = append(references, reference)
		}
	}
	for _, reference := range requirement.VerifiedBy {
		add(reference)
	}
	for _, caseDef := range requirement.Cases {
		if caseDef.Test == "" || caseTestCoveredByVerifiedBy(caseDef.Test, requirement.VerifiedBy) {
			continue
		}
		add(caseDef.Test)
	}
	return references
}

func caseTestCoveredByVerifiedBy(caseTest string, verifiedBy []string) bool {
	caseFile, caseName, caseOK := ParseFileColonSymbol(strings.TrimSpace(caseTest))
	if !caseOK {
		return false
	}
	for _, reference := range verifiedBy {
		file, test, ok := ParseFileColonSymbol(strings.TrimSpace(reference))
		if ok && file == caseFile && (caseName == test || strings.HasPrefix(caseName, test+"/")) {
			return true
		}
	}
	return false
}

// BuildSpecDocumentsFromRows strictly renders a full language bundle from one
// already-collected execution snapshot. No output is returned on any catalog
// or claim translation error.
func BuildSpecDocumentsFromRows(g *ontology.Graph, rows map[string]SpecRow) (map[string]string, error) {
	layout, err := docbundle.NewLayout(g.Languages, g.DefaultLanguage)
	if err != nil {
		return nil, err
	}
	hasAtoms := g.SelfExecutingAtoms
	includePackages := hasAtoms || layout.Multilingual()
	groups := make(map[string][]ontology.Requirement)
	if includePackages {
		for _, req := range g.Requirements {
			if req.Status != ontology.StatusREJECTED {
				groups[SpecPackage(req)] = append(groups[SpecPackage(req)], req)
			}
		}
	}
	packages := make([]string, 0, len(groups))
	for pkg := range groups {
		packages = append(packages, pkg)
	}
	sort.Strings(packages)
	packagePaths := make([]string, 0, len(packages))
	for _, pkg := range packages {
		packagePaths = append(packagePaths, pkg+".md")
	}
	if _, err := docbundle.SpecShardNames(packagePaths); err != nil {
		return nil, err
	}
	languages := layout.LanguagesForViews()
	docs := make(map[string]string, len(packages)*len(languages)+len(languages))
	for _, language := range languages {
		indexPath, err := layout.SpecIndexPath(language)
		if err != nil {
			return nil, err
		}
		indexKey, err := specDocGenKey(indexPath)
		if err != nil {
			return nil, err
		}
		view := *g
		view.RenderLanguage = language
		if !includePackages {
			document, err := BuildSpecFromRowsForLanguage(&view, rows, language)
			if err != nil {
				return nil, err
			}
			docs[indexKey] = document
			continue
		}
		shardPaths := make(map[string]string, len(packages))
		for _, pkg := range packages {
			shardPath, err := layout.SpecShardPath(language, pkg+".md")
			if err != nil {
				return nil, err
			}
			shardPaths[pkg] = shardPath
			shardKey, err := specDocGenKey(shardPath)
			if err != nil {
				return nil, err
			}
			shard := view
			shard.Requirements = groups[pkg]
			document, err := BuildSpecFromRowsForLanguage(&shard, rows, language)
			if err != nil {
				return nil, err
			}
			docs[shardKey] = document
		}
		index, err := buildSpecPackageIndex(&view, language, indexPath, packages, shardPaths, groups)
		if err != nil {
			return nil, err
		}
		docs[indexKey] = index
	}
	return docs, nil
}

func specDocGenKey(domainPath string) (string, error) {
	normalized := filepath.ToSlash(filepath.Clean(filepath.FromSlash(domainPath)))
	const prefix = "docs/gen/"
	if !strings.HasPrefix(normalized, prefix) {
		return "", fmt.Errorf("SPEC bundle path %q is outside docs/gen", domainPath)
	}
	return strings.TrimPrefix(normalized, prefix), nil
}

func buildSpecPackageIndex(g *ontology.Graph, language, indexPath string, packages []string, shardPaths map[string]string, groups map[string][]ontology.Requirement) (string, error) {
	banner, err := specText(language, specBanner)
	if err != nil {
		return "", err
	}
	reader, err := specReaderHeaderLine(g, language)
	if err != nil {
		return "", err
	}
	title, err := specText(language, "# SPEC.md — package index")
	if err != nil {
		return "", err
	}
	header, err := specText(language, "| Package | Requirements |")
	if err != nil {
		return "", err
	}
	lines := []string{banner}
	if reader != "" {
		lines = append(lines, reader)
	}
	lines = append(lines, "", title, "", header, "|---|---:|")
	for _, pkg := range packages {
		link, err := filepath.Rel(filepath.Dir(filepath.FromSlash(indexPath)), filepath.FromSlash(shardPaths[pkg]))
		if err != nil {
			return "", err
		}
		row, err := specText(language, "| [%s](%s) | %d |", specCell(pkg), filepath.ToSlash(link), len(groups[pkg]))
		if err != nil {
			return "", err
		}
		lines = append(lines, row)
	}
	return strings.Join(lines, "\n") + "\n", nil
}
