// spec_build.go holds the data-collection AND rendering machinery behind
// docs/gen/SPEC.md: the generated NORMATIVE TEXT projection
// PLAN-scenario-generated-spec.md §2 D2/§3 W1.3 names — the successor stage
// to the authored-spec discipline's own projections (traceability.go/
// models.go/coverage.go, internal/generator): a requirement's claim (still
// the short AUTHORED intent from graph.json, D2 — never invented here)
// followed by the GENERATED prose narrative of its verified_by scenario(s),
// rendered from the ACTUAL Given/When/Then/Value steps a real, passing
// `go test` run just recorded via internal/recorder/canon's hotamspec API
// (PLAN-scenario-generated-spec.md §1's "text incarnates the actually-run
// test", never a second, independently-writable source of truth).
//
// LAYERING: collection and rendering live here so internal/invariants can
// consume SPEC freshness without importing internal/generator and closing its
// existing diagnose -> invariants dependency cycle. This package remains a
// leaf over loader, ontology, localization, and docbundle; generator and CLI
// entry points share the same rows/renderers through their wrappers.
//
// Unlike traceability.go/models.go/coverage.go, SPEC includes real execution
// evidence. Legacy scenario graphs record each verified_by test through
// RunVerifiedByTestRecording; self-executing atom graphs record each distinct
// source package once through RunAtomPackageRecording, preserving per-test and
// per-subtest verdicts/artifacts in one invocation-local snapshot.
//
// This file is read-only over the graph and re-EXECUTES the domain's own
// authored code via `go test` purely to observe what a real scenario
// narrated; it never mutates the graph, never writes to the domain's spec/
// tree. check_spec_md_current (internal/invariants/spec_md_current.go, W2.3)
// is the mechanical staleness gate that consumes this file's output; this
// file itself only renders what a fresh run reports NOW.
package gate

import (
	"encoding/json"
	"fmt"
	"github.com/PHPCraftdream/HotamSpec/internal/localization"
	"github.com/PHPCraftdream/HotamSpec/internal/ontology"
	"sort"
	"strings"
)

// spec_render.go renders the SPEC.md narrative: localized section text assembled from collected rows.

// specBanner/specEmptyNotice/specCell/specReaderHeaderLine are local,
// SPEC.md-scoped equivalents of internal/generator/common.go's
// Banner/EmptyNotice/Cell/ReaderHeaderLine -- duplicated here (rather than
// imported) because internal/generator is not reachable from internal/gate
// without inverting the dependency this file exists to avoid (see the
// package doc comment's LAYERING section). Kept as the SAME literal text
// generator.Banner/generator.EmptyNotice carry today, and Cell/
// ReaderHeaderLine reimplemented against the identical logic, so
// BuildSpecFromRows's rendered bytes are unchanged from before this move --
// internal/generator/spec_test.go's byte-identical-to-golden test is the
// mechanical proof this duplication stayed faithful.
const specBanner = "<!-- AUTOGENERATED from the domain graph.json — do not edit by hand. Edits: methodology/graph -> hotam gen-spec -->"

// IsGeneratedSpecDocument recognizes existing generated first-line banners.
func IsGeneratedSpecDocument(content string) bool {
	firstLine, _, hasLine := strings.Cut(content, "\n")
	if !hasLine {
		return false
	}
	firstLine = strings.TrimSuffix(firstLine, "\r")
	for _, language := range []string{"en", "ru", "zh"} {
		banner, err := localization.Lookup(language, specBanner)
		if err == nil && firstLine == banner {
			return true
		}
	}
	return false
}

const specEmptyNotice = "_No domain content loaded — no `domains/<name>/graph.json` found. Run `hotam init <dir>` to scaffold a new domain, then `hotam gen-spec --domain <dir>` to populate docs/gen/. The methodology narrative below is the framework itself and is always present._"

const specIntro = "Generated from this domain's `graph.json` claims plus REAL, currently-passing `go test` runs of every `verified_by` entry, recorded via the `hotamspec` scenario API (PLAN-scenario-generated-spec.md §1/§2 D1/D2, task W1.3): the normative body under each requirement is not hand-written prose — it is the Given/When/Then/Value narrative a real test run just produced. `graph.json` remains the bookkeeping layer (id, short authored claim, status); this document is the derived projection, never the other way around. Not an enforcement gate itself — `check_spec_md_current` (W2.3) is the mechanical staleness floor; this generator only renders what the CURRENT run reports."

func specText(language, template string, args ...any) (string, error) {
	if language == "" {
		return fmt.Sprintf(template, args...), nil
	}
	localized, err := localization.Lookup(language, template)
	if err != nil {
		return "", err
	}
	return fmt.Sprintf(localized, args...), nil
}

func specLanguage(g *ontology.Graph) string {
	if g.RenderLanguage != "" {
		return g.RenderLanguage
	}
	if g.DefaultLanguage != "" {
		return g.DefaultLanguage
	}
	if len(g.Languages) == 1 {
		return g.Languages[0]
	}
	return ""
}

func specClaim(g *ontology.Graph, r ontology.Requirement, language string) (string, error) {
	if language == "" {
		return r.Claim, nil
	}
	if claim, ok := r.ClaimTexts[language]; ok && strings.TrimSpace(claim) != "" {
		return claim, nil
	}
	if len(g.Languages) > 1 {
		return "", fmt.Errorf("requirement %s has no claim text for language %q", r.ID, language)
	}
	return r.Claim, nil
}

// specReaderHeaderLine mirrors generator.ReaderHeaderLine("SPEC", g) except
// that an unresolved reader yields an empty line: consumer domains have no
// "domain-user" stakeholder, and a "reader: (unresolved-reader)" line carries
// no information. SPEC.md's DocReaderRoles entry is RoleDomainResolver and its
// DomainDocReaders binding is "domain-user" -- both hardcoded here since
// this file only ever renders the one "SPEC" docKind, unlike
// generator.ReaderHeaderLine's general docKind lookup table.
func specReaderHeaderLine(g *ontology.Graph, language string) (string, error) {
	boundID := "domain-user"
	if _, exists := ontology.StakeholderIDs(g)[boundID]; !exists {
		return "", nil
	}
	return specText(language, "reader: %s", boundID)
}

// specCell mirrors generator.Cell exactly: a Markdown-table-safe cell
// renderer (newlines flattened, pipes escaped).
func specCell(text string) string {
	t := strings.ReplaceAll(text, "\n", " ")
	t = strings.ReplaceAll(t, "|", "\\|")
	return t
}

// BuildSpec renders a single selected view from one fresh CollectSpecRows
// snapshot. Multilingual publication callers use BuildSpecDocumentsFromRows
// with a shared rows map so each language consumes identical evidence.
//
// BuildSpec itself is the convenient execution entry point; callers that also
// need other projections from the same snapshot should collect once and pass
// those rows to each renderer. No renderer persists verdicts or executes
// methods while changing language.
func BuildSpec(g *ontology.Graph) string {
	return BuildSpecFromRows(g, CollectSpecRows(g))
}

// BuildSpecFromRows renders a single language view from an already-collected
// snapshot. Its legacy string signature panics with the original render error
// instead of returning an empty/fallback document; callers needing an error
// value use BuildSpecFromRowsForLanguage or BuildSpecDocumentsFromRows.
func BuildSpecFromRows(g *ontology.Graph, rows map[string]SpecRow) string {
	document, err := BuildSpecFromRowsForLanguage(g, rows, specLanguage(g))
	if err != nil {
		panic(err)
	}
	return document
}

// BuildSpecFromRowsForLanguage strictly renders one explicit language view
// without executing tests or changing shared graph state.
func BuildSpecFromRowsForLanguage(g *ontology.Graph, rows map[string]SpecRow, language string) (string, error) {
	view := *g
	view.RenderLanguage = language
	return renderSpecFromRows(&view, rows, language)
}

func renderSpecFromRows(g *ontology.Graph, rows map[string]SpecRow, language string) (string, error) {
	for _, requirement := range g.Requirements {
		if row, ok := rows[requirement.ID]; ok && row.sourceError != nil {
			return "", row.sourceError
		}
	}
	banner, err := specText(language, specBanner)
	if err != nil {
		return "", err
	}
	reader, err := specReaderHeaderLine(g, language)
	if err != nil {
		return "", err
	}
	title, err := specText(language, "# SPEC.md — generated normative text (Hotam-Spec)")
	if err != nil {
		return "", err
	}
	intro, err := specText(language, specIntro)
	if err != nil {
		return "", err
	}
	lines := []string{banner}
	if reader != "" {
		lines = append(lines, reader)
	}
	lines = append(lines, "", title, "", intro, "")
	if g.IsEmpty() {
		emptyNotice, err := specText(language, specEmptyNotice)
		if err != nil {
			return "", err
		}
		lines = append(lines, emptyNotice, "")
		return strings.TrimRight(strings.Join(lines, "\n"), " \t\r\n") + "\n", nil
	}

	reqs := make([]ontology.Requirement, len(g.Requirements))
	copy(reqs, g.Requirements)
	sort.Slice(reqs, func(i, j int) bool { return reqs[i].ID < reqs[j].ID })
	if g.SelfExecutingAtoms {
		sort.SliceStable(reqs, func(i, j int) bool {
			if reqs[i].DeclOrder != reqs[j].DeclOrder {
				return reqs[i].DeclOrder < reqs[j].DeclOrder
			}
			return reqs[i].ID < reqs[j].ID
		})
	}

	var withScenario, withoutVerifiedBy []ontology.Requirement
	verifiedByCount := 0
	caseOnlyCount := 0
	for _, r := range reqs {
		if r.Status == ontology.StatusREJECTED {
			continue
		}
		if len(specTestReferences(r)) == 0 {
			withoutVerifiedBy = append(withoutVerifiedBy, r)
			continue
		}
		withScenario = append(withScenario, r)
		if len(r.VerifiedBy) == 0 {
			caseOnlyCount++
		} else {
			verifiedByCount++
		}
	}

	narratedCount := 0
	for _, r := range withScenario {
		for _, outcome := range rows[r.ID].outcomes {
			if len(outcome.artifacts) > 0 {
				narratedCount++
				break
			}
		}
	}
	var summary string
	if caseOnlyCount == 0 {
		summary, err = specText(language,
			"**%d requirement(s) carry `verified_by`; %d have at least one recorded scenario narrative; %d carry no `verified_by` yet (no code carrier, honest gap).**",
			verifiedByCount, narratedCount, len(withoutVerifiedBy))
	} else {
		summary, err = specText(language,
			"**%d requirement(s) carry `verified_by`; %d carry declared case tests only; %d have at least one recorded scenario narrative; %d have neither test nor case reference (honest gap).**",
			verifiedByCount, caseOnlyCount, narratedCount, len(withoutVerifiedBy))
	}
	if err != nil {
		return "", err
	}
	lines = append(lines, summary, "", "---", "")
	withHeadingTemplate := "## Requirements with a verified_by scenario"
	if caseOnlyCount > 0 {
		withHeadingTemplate = "## Requirements with a verified_by scenario or declared case test"
	}
	withHeading, err := localization.Lookup(language, withHeadingTemplate)
	if err != nil {
		return "", err
	}
	lines = append(lines, withHeading, "")
	if len(withScenario) == 0 {
		none, err := specText(language, "_None in this domain yet — the scenario-generated-spec layer (PLAN-scenario-generated-spec.md §3 W1.3) has not been started for this domain._")
		if err != nil {
			return "", err
		}
		lines = append(lines, none, "")
	} else {
		for _, r := range withScenario {
			rendered, err := renderSpecRequirement(g, rows[r.ID], language)
			if err != nil {
				return "", err
			}
			lines = append(lines, rendered...)
		}
	}

	withoutHeadingTemplate := "## Without a scenario (no verified_by — honest gap)"
	noCarrierTemplate := "Requirements with no `verified_by` entry at all: SETTLED without a code carrier is honest roadmap debt (mirrors TRACEABILITY.md/COVERAGE.md's own partition), never silently claimed narrated."
	if caseOnlyCount > 0 {
		withoutHeadingTemplate = "## Without a scenario or declared case test (honest gap)"
		noCarrierTemplate = "Requirements with no `verified_by` or declared case test: no code carrier or executed case is available; honest gap."
	}
	withoutHeading, err := localization.Lookup(language, withoutHeadingTemplate)
	if err != nil {
		return "", err
	}
	noCarrier, err := localization.Lookup(language, noCarrierTemplate)
	if err != nil {
		return "", err
	}
	lines = append(lines, withoutHeading, "", noCarrier, "")
	if len(withoutVerifiedBy) == 0 {
		noneTemplate := "_None — every requirement in this domain carries at least one `verified_by` entry._"
		if caseOnlyCount > 0 {
			noneTemplate = "_None — every requirement in this domain carries a `verified_by` entry or declared case test._"
		}
		none, err := localization.Lookup(language, noneTemplate)
		if err != nil {
			return "", err
		}
		lines = append(lines, none, "")
	} else {
		header, err := specText(language, "| id | status | claim |")
		if err != nil {
			return "", err
		}
		lines = append(lines, header, "|---|---|---|")
		for _, r := range withoutVerifiedBy {
			claim, err := specClaim(g, r, language)
			if err != nil {
				return "", err
			}
			lines = append(lines, "| `"+r.ID+"` | "+specCell(r.Status)+" | "+specCell(claim)+" |")
		}
		lines = append(lines, "")
	}
	return strings.TrimRight(strings.Join(lines, "\n"), " \t\r\n") + "\n", nil
}

// firstImplementedByFile returns the file half of r's first implemented_by
// entry (best-effort coverPkgFile input for RunVerifiedByTestRecording —
// implemented_by and verified_by are independent lists, not index-paired,
// per PLAN-authored-spec-discipline.md §4/§12; a requirement with more than
// one implemented_by symbol still only needs ONE file in that symbol's own
// package to point -coverpkg at the right import path). Returns "" when r
// carries no implemented_by at all or the entry does not parse as
// "file:symbol" — RunVerifiedByTestRecording treats an empty coverPkgFile as
// "skip coverage collection", never an error, so a requirement missing
// implemented_by still gets its scenario narrated, just without a coverage
// profile (coverage-proof enforcement is check_scenario_executes_impl's job,
// W2.2, not this file's).

func specStatusText(language, status string) (string, error) {
	if status == "" {
		return "", nil
	}
	token, detail := status, ""
	if strings.HasPrefix(status, "OPEN(") {
		token, detail = "OPEN", strings.TrimPrefix(status, "OPEN")
	}
	translated, err := localization.Lookup(language, token)
	if err != nil {
		return "", err
	}
	return translated + detail, nil
}

func renderSpecRequirement(g *ontology.Graph, row SpecRow, language string) ([]string, error) {
	if row.sourceError != nil {
		return nil, row.sourceError
	}
	claim, err := specClaim(g, row.req, language)
	if err != nil {
		return nil, err
	}
	heading := "## `" + row.req.ID + "`"
	claimLine, err := specText(language, "**Claim:** %s", specCell(claim))
	if err != nil {
		return nil, err
	}
	status, err := specStatusText(language, row.req.Status)
	if err != nil {
		return nil, err
	}
	enforcement, err := specStatusText(language, row.req.Enforcement)
	if err != nil {
		return nil, err
	}
	statusLine, err := specText(language, "**Status:** %s · **Enforcement:** %s", specCell(status), specCell(enforcement))
	if err != nil {
		return nil, err
	}
	lines := []string{heading, "", claimLine, "", statusLine, ""}
	for _, outcome := range row.outcomes {
		lines = append(lines, "### `"+outcome.entry+"`", "")
		if outcome.problem != "" {
			if len(outcome.artifacts)+len(outcome.failedArtifacts) == 0 {
				line, err := specText(language, "_No scenario narrative: %s._", specCell(outcome.problem))
				if err != nil {
					return nil, err
				}
				lines = append(lines, line, "")
				continue
			}
			line, err := specText(language, "_Evidence issue: %s._", specCell(outcome.problem))
			if err != nil {
				return nil, err
			}
			lines = append(lines, line, "")
		}
		for _, failed := range outcome.failedArtifacts {
			rendered, err := renderFailedSpecArtifact(failed, language)
			if err != nil {
				return nil, err
			}
			lines = append(lines, rendered...)
		}
		for _, artifact := range outcome.artifacts {
			rendered, err := renderSpecArtifact(artifact, claim, language)
			if err != nil {
				return nil, err
			}
			lines = append(lines, rendered...)
		}
	}
	return lines, nil
}

func renderSpecArtifact(art specArtifact, claim, language string) ([]string, error) {
	var lines []string
	if art.Mode == "" && strings.TrimSpace(art.Title) != strings.TrimSpace(claim) {
		lines = append(lines, "**"+specCell(art.Title)+"**", "")
	}
	caseLines, err := renderSpecCase(art.Case, language)
	if err != nil {
		return nil, err
	}
	lines = append(lines, caseLines...)
	stepLines, err := renderSpecSteps(art.Steps, language)
	if err != nil {
		return nil, err
	}
	lines = append(lines, stepLines...)
	lines = append(lines, "")
	return lines, nil
}

func renderFailedSpecArtifact(art specArtifact, language string) ([]string, error) {
	id := art.Test
	if art.Case != nil {
		id = art.Case.ID
	}
	template := "**Recorded artifact `%s` did not pass; its claim is not shown as verified.**"
	if art.Case != nil {
		template = "**Case `%s` did not pass; its claim is not shown as verified.**"
	}
	label, err := specText(language, template, specCell(id))
	if err != nil {
		return nil, err
	}
	lines := []string{label, ""}
	caseLines, err := renderSpecCase(art.Case, language)
	if err != nil {
		return nil, err
	}
	lines = append(lines, caseLines...)
	stepLines, err := renderSpecSteps(art.Steps, language)
	if err != nil {
		return nil, err
	}
	lines = append(lines, stepLines...)
	lines = append(lines, "")
	return lines, nil
}

func renderSpecCase(caseDef *ontology.CaseDefinition, language string) ([]string, error) {
	if caseDef == nil {
		return nil, nil
	}
	serialized, err := json.Marshal(caseDef)
	if err != nil {
		return nil, fmt.Errorf("render case %s: %w", caseDef.ID, err)
	}
	label, err := specText(language, "**Case descriptor**")
	if err != nil {
		return nil, err
	}
	return []string{label, "", "```json", string(serialized), "```", ""}, nil
}

func renderSpecSteps(steps []specArtifactStep, language string) ([]string, error) {
	var lines []string
	for _, step := range steps {
		var line string
		var err error
		if step.Subject != "" {
			if claim, ok := step.Texts[language]; ok && strings.TrimSpace(claim) != "" {
				line, err = specText(language, "- Given %s%s", specCell(claim), "")
			} else if language == "" && strings.TrimSpace(step.Desc) != "" {
				line, err = specText(language, "- Given %s%s", specCell(step.Desc), "")
			} else if len(step.Texts) > 0 {
				return nil, fmt.Errorf("atom evidence has no text for language %q", language)
			} else {
				lines = append(lines, "- `"+specCell(step.Subject)+"` — "+specCell(step.Value))
				continue
			}
		} else {
			switch step.Kind {
			case "given":
				line, err = specText(language, "- Given %s%s", specCell(step.Desc), renderSpecFacts(step.Values))
			case "when":
				line, err = specText(language, "- When %s", specCell(step.Desc))
			case "then":
				if language == "" {
					if strings.TrimSpace(step.Desc) == "" {
						return nil, fmt.Errorf("atom claim has no primary text")
					}
				} else if localized, ok := step.Texts[language]; ok && strings.TrimSpace(localized) != "" {
					step.Desc = localized
				} else if len(step.Texts) > 0 {
					return nil, fmt.Errorf("atom claim has no text for language %q", language)
				}
				outcome := "held"
				if !step.Passed {
					outcome = "FAILED"
				}
				localizedOutcome, err := localization.Lookup(language, outcome)
				if err != nil {
					return nil, err
				}
				line, err = specText(language, "- Then %s — **%s**", specCell(step.Desc), localizedOutcome)
			case "value":
				line, err = specText(language, "- Value%s", renderSpecFacts(step.Values))
			default:
				line, err = specText(language, "- %s: %s%s", specCell(step.Kind), specCell(step.Desc), renderSpecFacts(step.Values))
			}
		}
		if err != nil {
			return nil, err
		}
		lines = append(lines, line)
	}
	return lines, nil
}

// renderSpecFacts renders a Step's Values as an inline " (k1=v1, k2=v2)"
// suffix, in the exact order the artifact already carries them (call order —
// never re-sorted, see internal/recorder/canon's kv doc comment for why
// Given/Value's facts are an ordered slice, not a map). Returns "" for an
// empty Values (a Given/Value step with no supporting facts), so a bare
// description does not grow a trailing " ()".
func renderSpecFacts(values []specArtifactKV) string {
	if len(values) == 0 {
		return ""
	}
	parts := make([]string, 0, len(values))
	for _, v := range values {
		parts = append(parts, v.Key+"="+v.Value)
	}
	return " (" + specCell(strings.Join(parts, ", ")) + ")"
}
