package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"unicode/utf8"

	"github.com/PHPCraftdream/HotamSpecGo/internal/diagnose"
	"github.com/PHPCraftdream/HotamSpecGo/internal/loader"
	"github.com/PHPCraftdream/HotamSpecGo/internal/methodology"
	"github.com/PHPCraftdream/HotamSpecGo/internal/ontology"
)

// Canon: §Graph — root CLAUDE.md generation (R-claude-md-template-driven).
//
// Ported from spec/tools/gen_spec.py's render_claude_md_from_template /
// render_mind_content / render_business_content (Python reference,
// backup/python-legacy-2026-07-12). The root CLAUDE.md.template.txt is a
// fixed header plus exactly two placeholder lines, "<!-- mind -->" and
// "<!-- business -->", substituted with the MIND bucket (domain-agnostic
// "how to think" layer: OPERATOR-ROLE, MEDIATION-LOOP, EMBEDDED-THINKING,
// EMBEDDED-TOOLS, OPERATOR-RECURSION) and the BUSINESS bucket
// (domain-specific "what this claims" layer: LIVE-STATE, DOMAIN-MAP,
// CONSTITUTION, AGENT-MAP, CONCEPT-MAP, RECENTLY-REJECTED) respectively.
// Every individual block still carries its own BEGIN/END sentinel-comment
// pair (WrapBlock); MIND/BUSINESS are concatenations of those blocks.

const mindPlaceholder = "<!-- mind -->"
const businessPlaceholder = "<!-- business -->"

// claudeMDTemplate is embedded verbatim from CLAUDE.md.template.txt (Python
// reference: hotam_spec/_templates/claude_md.template.txt, read via
// importlib.resources with an optional consumer override at
// project_root()/CLAUDE.md.template.txt). Embedding it here — rather than
// reading an external file — keeps root CLAUDE.md generation self-contained
// within this package and avoids a second file-ownership surface at repo
// root while still producing byte-identical output.
const claudeMDTemplate = "# CLAUDE.md — Hotam-Spec framework\n" +
	"\n" +
	"**Hotam-Spec** — executable memory and discipline for a human + LLM-agent fleet: understand, evolve, protect, and support a shared model over time. Contradictory requirements are one of its properties — held open as tension-graph nodes, never silently discarded. License: MIT OR Apache-2.0.\n" +
	"\n" +
	"Boot: Role + Mediation-loop blocks below = operating seed. Deep-dives: `spec/docs/thinking/`.\n" +
	"\n" +
	mindPlaceholder + "\n" +
	"\n" +
	businessPlaceholder + "\n" +
	"\n" +
	"<!-- Anything you write below this line survives every regeneration verbatim. Use this space for durable notes, reminders, or context that the generator should never touch. -->\n"

const generatedHeaderComment = "<!-- (generated by `go run ./cmd/hotam gen-spec` — do not hand-edit) -->"

// RenderOperatorRoleBlock renders the OPERATOR-ROLE block content (without
// sentinels): the resident seed's identity, parametrized by the active
// domain's name and its SETTLED requirement count.
func RenderOperatorRoleBlock(g *ontology.Graph, scopeLabel string) string {
	if scopeLabel == "" {
		scopeLabel = "(no domain yet)"
	}
	atomCount := 0
	for _, r := range g.Requirements {
		if r.Status == ontology.StatusSETTLED {
			atomCount++
		}
	}
	lines := []string{
		generatedHeaderComment,
		"",
		"### Role (the resident seed)",
		"",
		fmt.Sprintf(
			"Operator of `%s` (%d SETTLED). Guardian: **spec** (`domains/%s/graph.json`) ↔ **tests** (`check_*`/`Test_*`) ↔ **business** (steward decisions). Drift between layers = top signal.",
			scopeLabel, atomCount, scopeLabel,
		),
		"",
		"Confront every input against graph reality BEFORE writing. Cite anchors (`R-…`/`C-…`/`A-…`/`OP-…`), never vibes (R-speak-by-reference). Present, never decide — steward decides; never close a Conflict silently (R-ai-presents-not-decides, R-decided-needs-human-signoff).",
		"",
		"**Generative law:** important-yet-invisible → typed anchored node under a named steward; tension held open as a Conflict node, never quietly extinguished (R-anchor-everything · R-conflict-is-connector-node · R-steward-distinct-from-owners). Every RULE below is a projection of this law.",
	}
	return strings.TrimRight(strings.Join(lines, "\n"), " \t\r\n")
}

// RenderMediationLoopBlock renders the MEDIATION-LOOP block content (without
// sentinels): a static six-step input-processing loop, no graph/filesystem
// dependency.
func RenderMediationLoopBlock() string {
	return mediationLoopText
}

// RenderEmbeddedThinkingBlock renders the EMBEDDED-THINKING block content
// (without sentinels): a compact index of the framework's thinking-topics,
// one linkable line per §-section, derived from methodology.Sections
// (internal/methodology/sections_data.go). The full RULE/Canon/Narrative/Why
// text lives in spec/docs/thinking/<slug>.md (generated by BuildThinkingDocs),
// so duplicating it inline here was pure context-debt — the resident seed only
// needs the index to know a topic exists and where to read it.
//
// This used to be the hand-baked embeddedThinkingText constant in
// claudemd_static.go; that constant had drifted to 23 alphabetical entries
// while the registry grew to 29 (§Loop/§Ticket/§Tick/§Constitution/§Context/
// §Atoms had silently dropped out). Deriving from the registry fixes that drift
// the same way RenderEmbeddedToolsBlock does for tools.
func RenderEmbeddedThinkingBlock() string {
	sections := methodology.Sections.All()
	names := make([]string, len(sections))
	for i, s := range sections {
		names[i] = s.Slug
	}
	lines := []string{
		generatedHeaderComment,
		"",
		"### Methodology — how to think",
		"",
		"One RULE per §-section; full Canon/Narrative/Why at `spec/docs/thinking/<slug>.md` (slug = lowercased §-name): " + strings.Join(names, " · ") + ".",
	}
	return strings.Join(lines, "\n")
}

// RenderEmbeddedToolsBlock renders the EMBEDDED-TOOLS block content
// (without sentinels). Unlike RenderEmbeddedThinkingBlock, this is NOT
// static text: it is a projection of methodology.Tools (internal/methodology/
// tools_data.go), sorted by Command. Ported tools get one full line each
// (name + Purpose + Ported marker) — those are the commands an operator
// actually runs day-to-day. Declared (not-yet-ported) tools are collapsed
// into a single summary line pointing at docs/gen/tools/ and the registry:
// their per-tool Purpose is historical prose with no runnable command behind
// it, so listing all of them inline was pure context-debt (P1-1/Wave 4 cut
// the block from ~6.7KB to ~2.5KB this way).
//
// It used to be the hand-maintained embeddedToolsText constant in
// claudemd_static.go; that constant silently drifted out of sync every time a
// Python-era tool got ported to a real Go command (P1-6 / TaskList #19 found
// it still calling `req`/`due`/`inspect`/`land` "not yet ported" after all four
// had working cmd/hotam commands). Deriving the block from the registry
// instead makes that class of drift structurally impossible, the same way
// gen-spec's whole existence does for docs/gen/*.md (R-... generative law: an
// important-yet-invisible fact goes into a typed node, not prose someone
// forgets to update).
func RenderEmbeddedToolsBlock() string {
	tools := methodology.Tools.All()
	sorted := make([]methodology.Tool, len(tools))
	copy(sorted, tools)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Command < sorted[j].Command })

	lines := []string{
		generatedHeaderComment,
		"",
		"### Tool reference (Go CLI: `hotam <command>` / `go run ./cmd/hotam <command>`)",
		"",
	}
	declaredCount := 0
	for _, t := range sorted {
		displayName := strings.ReplaceAll(t.Command, "_", "-")
		if t.Status == methodology.Ported {
			lines = append(lines, "- **"+displayName+"** — "+t.Purpose+" Ported (`hotam "+displayName+"`).")
			continue
		}
		declaredCount++
	}
	if declaredCount > 0 {
		lines = append(lines, fmt.Sprintf(
			"- %d additional tools declared in the methodology registry but not yet ported to Go — full list + per-tool purpose: `docs/gen/tools/` (one .md per tool) or `internal/methodology/tools_data.go`.",
			declaredCount,
		))
	}
	return strings.Join(lines, "\n")
}

// RenderOperatorRecursionBlock renders the OPERATOR-RECURSION block content
// (without sentinels): sub-operator spawning as a capability, parametrized
// by the active domain name (used in the spawn-path example command).
func RenderOperatorRecursionBlock(domainName string) string {
	if domainName == "" {
		domainName = "hotam-spec-self"
	}
	return strings.Replace(operatorRecursionTemplate, "domains/hotam-spec-self/agents", "domains/"+domainName+"/agents", 1)
}

// RenderMindContent renders the MIND bucket: the domain-agnostic "how to
// think" layer. Order: OPERATOR-ROLE, MEDIATION-LOOP, EMBEDDED-THINKING,
// EMBEDDED-TOOLS, OPERATOR-RECURSION.
func RenderMindContent(g *ontology.Graph, domainName string) string {
	parts := []string{
		WrapBlock("OPERATOR-ROLE", RenderOperatorRoleBlock(g, domainName)),
		WrapBlock("MEDIATION-LOOP", RenderMediationLoopBlock()),
		WrapBlock("EMBEDDED-THINKING", RenderEmbeddedThinkingBlock()),
		WrapBlock("EMBEDDED-TOOLS", RenderEmbeddedToolsBlock()),
		WrapBlock("OPERATOR-RECURSION", RenderOperatorRecursionBlock(domainName)),
	}
	return strings.Join(parts, "\n")
}

// domainManifest carries the DOMAIN-MAP presentation fields sourced from a
// domain's manifest.py (Python reference). The Go port's manifest.json
// schema (internal/loader) carries only self_hosting; the ID/DESCRIPTION/
// GOALS/DIRECTOR fields are not yet represented on disk for any domain, so
// they are looked up here by domain directory name. Domains absent from
// this table (a new domain scaffolded without CLAUDE.md-generator
// awareness) fall back to em-dash placeholders, matching the Python
// behavior for a manifest.py with no matching attributes.
type domainManifest struct {
	ID          string
	Description string
	Goals       []string
	Director    string
}

var knownDomainManifests = map[string]domainManifest{
	"hotam-spec-self": {
		ID:          "hotam-spec-self",
		Description: "The methodology modeling itself — Hotam-Spec about itself as a tension graph.",
		Goals: []string{
			"burn down SETTLED-unenforced to zero",
			"atomize all compound check_*",
			"every CLAUDE.md section auto-generated from substrate",
		},
		Director: "director",
	},
	"hotam-dev": {
		ID:          "hotam-dev",
		Description: "модель разработки самого репозитория Hotam-Spec: волны, коммиты, спавны, верификационные ворота",
		Goals: []string{
			"волны садятся атомарно с зелёным T2 на границе",
			"каждый спавн и каждое применение оставляют трассу в .runtime-логах",
			"пуш только по явному слову стьюарда",
		},
		Director: "director",
	},
}

// runeTruncate truncates s to at most n runes (never mid-rune), appending
// "..." when truncation occurred. Mirrors the Python reference's
// imperative[:137] + "..." for len(imperative) > 140 (Python len() counts
// codepoints, so this must be rune-based, not byte-based — the graph
// carries Cyrillic text).
func runeTruncate(s string, keep int) string {
	if utf8.RuneCountInString(s) <= keep+3 {
		return s
	}
	r := []rune(s)
	if len(r) <= keep {
		return s
	}
	return string(r[:keep]) + "..."
}

// domainPulse mirrors _domain_pulse: a domain's open-action count plus a
// one-line rendering of its top-priority action, via the same
// DiagnoseSignals used for the root LIVE-STATE cipher. Returns (0, "") on a
// clean graph.
func domainPulse(dg *ontology.Graph) (int, string) {
	signals := diagnose.DiagnoseSignals(dg)
	if len(signals) == 0 {
		return 0, ""
	}
	top := signals[0]
	imperative := strings.Join(strings.Fields(top.Message), " ")
	if utf8.RuneCountInString(imperative) > 140 {
		imperative = runeTruncate(imperative, 137)
	}
	return len(signals), fmt.Sprintf("[P%d] %s: %s", top.Priority, top.Target, imperative)
}

// RenderDomainMapBlock renders the DOMAIN-MAP block content (without
// sentinels): every domains/<name>/ directory (sorted, excluding those
// starting with "_"), its manifest presentation fields, SETTLED atom count,
// and open-action pulse (R-domain-map-shows-pulse).
//
// repoRoot is the repository root (the parent of domains/); domainGraphs
// optionally pre-supplies already-loaded graphs keyed by domain directory
// name (dedup with the caller's own load), falling back to loading
// domains/<name>/graph.json from disk when absent.
func RenderDomainMapBlock(repoRoot string, domainGraphs map[string]*ontology.Graph) string {
	lines := []string{
		generatedHeaderComment,
		"",
		"### Domain Map",
		"",
	}

	domainsRoot := filepath.Join(repoRoot, "domains")
	entries, err := os.ReadDir(domainsRoot)
	if err != nil {
		lines = append(lines, "_(no domains yet — domains/ directory absent)_")
		return strings.TrimRight(strings.Join(lines, "\n"), " \t\r\n")
	}

	var domainDirs []string
	for _, e := range entries {
		if !e.IsDir() || strings.HasPrefix(e.Name(), "_") {
			continue
		}
		domainDirs = append(domainDirs, e.Name())
	}
	sort.Strings(domainDirs)

	if len(domainDirs) == 0 {
		lines = append(lines, "_(no domains yet)_")
		return strings.TrimRight(strings.Join(lines, "\n"), " \t\r\n")
	}

	for _, name := range domainDirs {
		m, known := knownDomainManifests[name]
		domainID := name
		description := ""
		goalsText := ""
		director := ""
		if known {
			domainID = m.ID
			description = m.Description
			if len(m.Goals) > 0 {
				goalsText = strings.Join(m.Goals, ", ")
			}
			director = m.Director
		}
		if description == "" {
			description = "—"
		}
		if goalsText == "" {
			goalsText = "—"
		}
		if director == "" {
			director = "—"
		}

		atomsCount := 0
		openActions := 0
		topActionLine := ""

		dg := domainGraphs[name]
		if dg == nil {
			gp := filepath.Join(domainsRoot, name, "graph.json")
			if loaded, err := loader.LoadGraph(gp); err == nil {
				dg = loaded
			}
		}
		if dg != nil {
			for _, r := range dg.Requirements {
				if r.Status == ontology.StatusSETTLED {
					atomsCount++
				}
			}
			openActions, topActionLine = domainPulse(dg)
		}

		lines = append(lines, "### "+domainID)
		lines = append(lines, "- **purpose** — "+description)
		lines = append(lines, "- **goals** — "+goalsText)
		lines = append(lines, "- **director** — "+director)
		lines = append(lines, "- **path** — `domains/"+name+"/`")
		lines = append(lines, fmt.Sprintf("- **atoms-count** — %d SETTLED", atomsCount))
		if openActions > 0 {
			lines = append(lines, fmt.Sprintf("- **open actions** — %d (top: %s)", openActions, topActionLine))
		} else {
			lines = append(lines, "- **open actions** — 0 (graph clean)")
		}
		lines = append(lines, "")
	}

	return strings.TrimRight(strings.Join(lines, "\n"), " \t\r\n")
}

// RenderAgentMapBlock renders the AGENT-MAP block content (without
// sentinels). Static: no spec/agents/<name>/ directories exist in this
// port (R-claude-md-consolidates-when-single-agent — sub-agent crystals
// materialize only at real spawn time), so the placeholder is the only
// reachable output; baked in claudemd_static.go alongside the other
// no-filesystem-equivalent blocks.
func RenderAgentMapBlock() string {
	return agentMapText
}

// RenderConceptMapBlock renders the CONCEPT-MAP block content (without
// sentinels). Static: derived from AST-scanning spec/src/hotam_spec/*.py
// and spec/tests/*.py against glossary §-section terms, none of which
// exist in this Go port (see claudemd_static.go doc comment); the function
// carries no graph dependency in the Python reference either
// (_scan_concept_map takes no g argument).
func RenderConceptMapBlock() string {
	return conceptMapText
}

// recentlyRejectedCap caps the CLAUDE.md RECENTLY-REJECTED block at a small
// taste of the anti-relitigation list (P2-1 compaction — the full list with
// full summaries lives in docs/gen/HISTORY.md, not duplicated into every
// regeneration of the root crystal).
const recentlyRejectedCap = 3

// rejectedReplacesRE matches the "REJECTED <dash> REPLACES" marker across
// em-dash, en-dash, double-dash, and single-hyphen variants — ported
// verbatim from _REJECTED_REPLACES_RE.
var rejectedReplacesRE = regexp.MustCompile(`REJECTED\s*(?:—|–|--|-)\s*REPLACES`)

func hasRejectedReplacesMarker(why string) bool {
	return rejectedReplacesRE.MatchString(why)
}

// replacesMap mirrors graph.replaces_map: REJECTED-id -> ordered tuple of
// successor (carrier) ids, built from every Requirement's "replaces"
// relations, in graph declaration order (NOT raw JSON array order — the
// Python reference iterates g.requirements in the source file's textual
// declaration order, which the Go loader preserves only via DeclOrder;
// see NarrativeOrder, the same pattern every other order-sensitive
// builder in this package uses).
func replacesMap(g *ontology.Graph) map[string][]string {
	out := make(map[string][]string)
	for _, r := range NarrativeOrder(g.Requirements, func(r ontology.Requirement) int { return r.DeclOrder }) {
		for _, rel := range r.Relations {
			if rel.Kind == "replaces" {
				out[rel.Target] = append(out[rel.Target], r.ID)
			}
		}
	}
	return out
}

// RenderRecentlyRejectedBlock renders the RECENTLY-REJECTED block content
// (without sentinels): REJECTED requirements with a known replacement
// (structural `replaces` edge OR legacy prose "REJECTED — REPLACES"
// marker), capped at recentlyRejectedCap entries (a small taste, P2-1
// compaction) in alphabetical-by-id order, with a pointer to the full
// history (docs/gen/HISTORY.md) beyond the cap.
func RenderRecentlyRejectedBlock(g *ontology.Graph) string {
	lines := []string{
		generatedHeaderComment,
		"",
		"### Recently rejected (anti-relitigation — summary)",
		"",
		"Before proposing an architectural change, check this isn't already REJECTED with a REPLACES successor — cite the replacement instead of re-deriving. Full list: `docs/gen/HISTORY.md`.",
		"",
	}

	rmap := replacesMap(g)

	var rejected []ontology.Requirement
	for _, r := range g.Requirements {
		if r.Status != ontology.StatusREJECTED {
			continue
		}
		_, hasEdge := rmap[r.ID]
		if hasEdge || hasRejectedReplacesMarker(r.Why) {
			rejected = append(rejected, r)
		}
	}
	sort.Slice(rejected, func(i, j int) bool { return rejected[i].ID < rejected[j].ID })

	if len(rejected) == 0 {
		lines = append(lines, "_(no anti-relitigation entries — nothing recently rejected.)_")
		return strings.TrimRight(strings.Join(lines, "\n"), " \t\r\n")
	}

	total := len(rejected)
	shown := rejected
	if len(shown) > recentlyRejectedCap {
		shown = shown[:recentlyRejectedCap]
	}

	// P2-1 compaction: id-only (no WHY-derived summary text — that detail
	// lives in docs/gen/HISTORY.md, `hotam req show <id>`, and
	// AGENT-CONTEXT.md's pointer to it) to keep this root-crystal block
	// small regardless of how verbose an individual rejection's WHY prose
	// is.
	ids := make([]string, len(shown))
	for i, r := range shown {
		ids[i] = r.ID
	}
	lines = append(lines, fmt.Sprintf("**REJECTED (REPLACES known)** (%d) — %s", total, strings.Join(ids, " · ")))

	if total > recentlyRejectedCap {
		lines = append(lines, "")
		lines = append(lines, fmt.Sprintf(
			"_(showing %d of %d, alphabetical by id — full history + WHY: docs/gen/HISTORY.md, `hotam req show <id>`)_",
			len(shown), total,
		))
	}

	return strings.TrimRight(strings.Join(lines, "\n"), " \t\r\n")
}

// runeTruncateEllipsis truncates s to keep runes and appends the single
// Unicode ellipsis character "…" (mirrors Python's s[:_TRUNC].rstrip() + "…").
func runeTruncateEllipsis(s string, keep int) string {
	r := []rune(s)
	if len(r) <= keep {
		return s
	}
	return strings.TrimRight(string(r[:keep]), " \t\r\n") + "…"
}

// RenderBusinessContent renders the BUSINESS bucket: the domain-specific
// "what this claims" layer. Order: LIVE-STATE, DOMAIN-MAP, CONSTITUTION,
// AGENT-MAP, CONCEPT-MAP, RECENTLY-REJECTED.
func RenderBusinessContent(g *ontology.Graph, domainName, repoRoot string, claudeMDCharCount int, domainGraphs map[string]*ontology.Graph) string {
	parts := []string{
		WrapBlock("LIVE-STATE", BuildLiveState(g, claudeMDCharCount)),
		WrapBlock("DOMAIN-MAP", RenderDomainMapBlock(repoRoot, domainGraphs)),
		WrapBlock("CONSTITUTION", BuildConstitutionBlock(g, domainName)),
		WrapBlock("AGENT-MAP", RenderAgentMapBlock()),
		WrapBlock("CONCEPT-MAP", RenderConceptMapBlock()),
		WrapBlock("RECENTLY-REJECTED", RenderRecentlyRejectedBlock(g)),
	}
	return strings.Join(parts, "\n")
}

// RenderClaudeMDFromTemplate renders root CLAUDE.md by substituting the two
// template placeholder lines ("<!-- mind -->" / "<!-- business -->") in
// claudeMDTemplate with the rendered MIND and BUSINESS content
// respectively. Every other line of the template — including the trailing
// human-notes marker comment — is preserved byte-for-byte.
//
// claudeMDCharCount feeds the LIVE-STATE CRYSTAL_CHARS budget line (the
// resident crystal's own character count — supplied by the caller to avoid
// the fixpoint hazard of CLAUDE.md measuring its own about-to-be-written
// size; see BuildLiveState / livestate.go).
func RenderClaudeMDFromTemplate(g *ontology.Graph, domainName, repoRoot string, claudeMDCharCount int, domainGraphs map[string]*ontology.Graph) string {
	mind := RenderMindContent(g, domainName)
	business := RenderBusinessContent(g, domainName, repoRoot, claudeMDCharCount, domainGraphs)

	srcLines := strings.Split(claudeMDTemplate, "\n")
	outLines := make([]string, 0, len(srcLines))
	for _, line := range srcLines {
		switch strings.TrimSpace(line) {
		case mindPlaceholder:
			outLines = append(outLines, mind)
		case businessPlaceholder:
			outLines = append(outLines, business)
		default:
			outLines = append(outLines, line)
		}
	}
	return strings.Join(outLines, "\n")
}
