package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"unicode/utf8"

	"github.com/PHPCraftdream/HotamSpec/internal/diagnose"
	"github.com/PHPCraftdream/HotamSpec/internal/loader"
	"github.com/PHPCraftdream/HotamSpec/internal/methodology"
	"github.com/PHPCraftdream/HotamSpec/internal/ontology"
)

// Canon: §Graph — root CLAUDE.md generation (R-claude-md-template-driven).
//
// The root CLAUDE.md.template.txt is a
// fixed header plus exactly two placeholder lines, "<!-- mind -->" and
// "<!-- business -->", substituted with the MIND bucket (domain-agnostic
// "how to think" layer: OPERATOR-ROLE, MEDIATION-LOOP, EMBEDDED-THINKING,
// EMBEDDED-TOOLS, OPERATOR-RECURSION) and the BUSINESS bucket
// (domain-specific "what this claims" layer: LIVE-STATE, DOMAIN-MAP,
// CONSTITUTION, AGENT-MAP, CONCEPT-MAP, RECENTLY-REJECTED) respectively.
// Every individual block still carries its own BEGIN/END sentinel-comment
// pair (WrapBlock); MIND/BUSINESS are concatenations of those blocks.

const mindPlaceholder = "<!-- mind -->"
const businessPlaceholder = "<!-- business -->"

// claudeMDTemplate is embedded verbatim from CLAUDE.md.template.txt.
// Embedding it here — rather than reading an external file — keeps root
// CLAUDE.md generation self-contained within this package and avoids a
// second file-ownership surface at repo root while still producing
// byte-identical output.
const claudeMDTemplate = "# CLAUDE.md — Hotam-Spec framework\n" +
	"\n" +
	"**Hotam-Spec** — executable memory and discipline for a human + LLM-agent fleet: understand, evolve, protect, and support a shared model over time. Contradictory requirements are one of its properties — held open as tension-graph nodes, never silently discarded. License: MIT OR Apache-2.0.\n" +
	"\n" +
	"Boot: Role + Mediation-loop blocks below = operating seed. Deep-dives: `spec/docs/thinking/`.\n" +
	"\n" +
	mindPlaceholder + "\n" +
	"\n" +
	businessPlaceholder + "\n" +
	"\n" +
	"<!-- Anything you write below this line survives every regeneration verbatim. Use this space for durable notes, reminders, or context that the generator should never touch. -->\n"

const generatedHeaderComment = "<!-- (generated by `go run ./cmd/hotam gen-spec` — do not hand-edit) -->"

// RenderOperatorRoleBlock renders the OPERATOR-ROLE block content (without
// sentinels): the resident seed's identity, parametrized by the active
// domain's name and its SETTLED requirement count.
func RenderOperatorRoleBlock(g *ontology.Graph, scopeLabel string) string {
	if scopeLabel == "" {
		scopeLabel = "(no domain yet)"
	}
	atomCount := 0
	for _, r := range g.Requirements {
		if r.Status == ontology.StatusSETTLED {
			atomCount++
		}
	}
	lines := []string{
		generatedHeaderComment,
		"",
		"### Role (the resident seed)",
		"",
		fmt.Sprintf(
			"Operator of `%s` (%d SETTLED). Guardian: **spec** (`domains/%s/graph.json`) ↔ **tests** (`check_*`/`Test_*`) ↔ **business** (steward decisions). Drift between layers = top signal.",
			scopeLabel, atomCount, scopeLabel,
		),
		"",
		"Confront every input against graph reality BEFORE writing. Cite anchors (`R-…`/`C-…`/`A-…`/`OP-…`), never vibes (R-speak-by-reference). Present, never decide — steward decides; never close a Conflict silently (R-ai-presents-not-decides, R-decided-needs-human-signoff).",
		"",
		"**Generative law:** important-yet-invisible → typed anchored node under a named steward; tension held open as a Conflict node, never quietly extinguished (R-anchor-everything · R-conflict-is-connector-node · R-steward-distinct-from-owners). Every RULE below is a projection of this law.",
	}
	return strings.TrimRight(strings.Join(lines, "\n"), " \t\r\n")
}

// RenderMediationLoopBlock renders the MEDIATION-LOOP block content (without
// sentinels): a static six-step input-processing loop, no graph/filesystem
// dependency.
func RenderMediationLoopBlock() string {
	return mediationLoopText
}

// RenderEmbeddedThinkingBlock renders the EMBEDDED-THINKING block content
// (without sentinels): a compact index of the framework's thinking-topics,
// one linkable line per §-section, derived from methodology.Sections
// (internal/methodology/sections_data.go). The full RULE/Canon/Narrative/Why
// text lives in domains/<domainName>/docs/gen/thinking/<slug>.md (generated
// by BuildThinkingDocs, written by cmd/hotam/gen_spec.go's genSpec), so
// duplicating it inline here was pure context-debt — the resident seed only
// needs the index to know a topic exists and where to read it.
//
// This used to be the hand-baked embeddedThinkingText constant in
// claudemd_static.go; that constant had drifted to 23 alphabetical entries
// while the registry grew to 29 (§Loop/§Ticket/§Tick/§Constitution/§Context/
// §Atoms had silently dropped out). Deriving from the registry fixes that drift
// the same way RenderEmbeddedToolsBlock does for tools.
func RenderEmbeddedThinkingBlock(domainName string) string {
	if domainName == "" {
		domainName = "hotam-spec-self"
	}
	sections := methodology.Sections.All()
	names := make([]string, len(sections))
	for i, s := range sections {
		names[i] = s.Slug
	}
	lines := []string{
		generatedHeaderComment,
		"",
		"### Methodology — how to think",
		"",
		"One RULE per §-section; full Canon/Narrative/Why at `domains/" + domainName + "/docs/gen/thinking/<slug>.md` (slug = lowercased §-name): " + strings.Join(names, " · ") + ".",
	}
	return strings.Join(lines, "\n")
}

// RenderEmbeddedToolsBlock renders the EMBEDDED-TOOLS block content
// (without sentinels). Unlike RenderEmbeddedThinkingBlock, this is NOT
// static text: it is a projection of methodology.Tools (internal/methodology/
// tools_data.go), sorted by Command. Implemented tools get one full line each
// (name + Purpose + Implemented marker) — those are the commands an operator
// actually runs day-to-day. Planned (not-yet-implemented) tools are collapsed
// into a single summary line pointing at docs/gen/tools/ and the registry:
// their per-tool Purpose is historical prose with no runnable command behind
// it, so listing all of them inline was pure context-debt (P1-1/Wave 4 cut
// the block from ~6.7KB to ~2.5KB this way).
//
// It used to be the hand-maintained embeddedToolsText constant in
// claudemd_static.go; that constant silently drifted out of sync every time a
// planned tool got a real Go command (P1-6 / TaskList #19 found
// it still calling `req`/`due`/`inspect`/`land` "not yet implemented" after all four
// had working cmd/hotam commands). Deriving the block from the registry
// instead makes that class of drift structurally impossible, the same way
// gen-spec's whole existence does for docs/gen/*.md (R-... generative law: an
// important-yet-invisible fact goes into a typed node, not prose someone
// forgets to update).
func RenderEmbeddedToolsBlock() string {
	tools := methodology.Tools.All()
	sorted := make([]methodology.Tool, len(tools))
	copy(sorted, tools)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Command < sorted[j].Command })

	lines := []string{
		generatedHeaderComment,
		"",
		"### Tool reference (Go CLI: `hotam <command>` / `go run ./cmd/hotam <command>`)",
		"",
	}
	plannedCount := 0
	for _, t := range sorted {
		displayName := strings.ReplaceAll(t.Command, "_", "-")
		if t.Status == methodology.Implemented {
			lines = append(lines, "- **"+displayName+"** — "+t.Purpose+" Implemented (`hotam "+displayName+"`).")
			continue
		}
		plannedCount++
	}
	if plannedCount > 0 {
		lines = append(lines, fmt.Sprintf(
			"- %d additional tools registered in the methodology but not yet implemented as Go commands — full list + per-tool purpose: `docs/gen/tools/` (one .md per tool) or `internal/methodology/tools_data.go`.",
			plannedCount,
		))
	}
	return strings.Join(lines, "\n")
}

// RenderOperatorRecursionBlock renders the OPERATOR-RECURSION block content
// (without sentinels): sub-operator spawning as a capability, parametrized
// by the active domain name (used in the spawn-path example command).
func RenderOperatorRecursionBlock(domainName string) string {
	if domainName == "" {
		domainName = "hotam-spec-self"
	}
	return strings.Replace(operatorRecursionTemplate, "domains/hotam-spec-self/agents", "domains/"+domainName+"/agents", 1)
}

// RenderMindContent renders the MIND bucket: the domain-agnostic "how to
// think" layer. Order: OPERATOR-ROLE, MEDIATION-LOOP, EMBEDDED-THINKING,
// EMBEDDED-TOOLS, OPERATOR-RECURSION.
func RenderMindContent(g *ontology.Graph, domainName string) string {
	parts := []string{
		WrapBlock("OPERATOR-ROLE", RenderOperatorRoleBlock(g, domainName)),
		WrapBlock("MEDIATION-LOOP", RenderMediationLoopBlock()),
		WrapBlock("EMBEDDED-THINKING", RenderEmbeddedThinkingBlock(domainName)),
		WrapBlock("EMBEDDED-TOOLS", RenderEmbeddedToolsBlock()),
		WrapBlock("OPERATOR-RECURSION", RenderOperatorRecursionBlock(domainName)),
	}
	return strings.Join(parts, "\n")
}

// domainManifest carries the DOMAIN-MAP presentation fields. The on-disk
// manifest.json schema (internal/loader) carries only self_hosting; the
// ID/DESCRIPTION/GOALS/DIRECTOR fields are not yet represented on disk for
// any domain, so they are looked up here by domain directory name. Domains
// absent from this table (a new domain scaffolded without CLAUDE.md-generator
// awareness) fall back to em-dash placeholders.
type domainManifest struct {
	ID          string
	Description string
	Goals       []string
	Director    string
}

var knownDomainManifests = map[string]domainManifest{
	"hotam-spec-self": {
		ID:          "hotam-spec-self",
		Description: "The methodology modeling itself — Hotam-Spec about itself as a tension graph.",
		Goals: []string{
			"burn down SETTLED-unenforced to zero",
			"atomize all compound check_*",
			"every CLAUDE.md section auto-generated from substrate",
		},
		Director: "director",
	},
	"hotam-dev": {
		ID:          "hotam-dev",
		Description: "a model of developing the Hotam-Spec repository itself: waves, commits, spawns, verification gates",
		Goals: []string{
			"waves land atomically with a green T2 at the boundary",
			"every spawn and every apply leaves a trace in the .runtime logs",
			"push only on the steward's explicit word",
		},
		Director: "director",
	},
}

// runeTruncate truncates s to at most n runes (never mid-rune), appending
// "..." when truncation occurred. The cutoff mirrors imperative[:137] +
// "..." for len(imperative) > 140 — rune-based (not byte-based) because the
// graph carries Cyrillic text whose codepoint count differs from its byte
// count.
func runeTruncate(s string, keep int) string {
	if utf8.RuneCountInString(s) <= keep+3 {
		return s
	}
	r := []rune(s)
	if len(r) <= keep {
		return s
	}
	return string(r[:keep]) + "..."
}

// domainPulse mirrors _domain_pulse: a domain's open-action count plus a
// one-line rendering of its top-priority action, via the same
// DiagnoseSignals used for the root LIVE-STATE cipher. Returns (0, "") on a
// clean graph.
func domainPulse(dg *ontology.Graph, today string) (int, string) {
	signals := diagnose.DiagnoseSignals(dg, today)
	if len(signals) == 0 {
		return 0, ""
	}
	top := signals[0]
	imperative := strings.Join(strings.Fields(top.Message), " ")
	if utf8.RuneCountInString(imperative) > 140 {
		imperative = runeTruncate(imperative, 137)
	}
	return len(signals), fmt.Sprintf("[P%d] %s: %s", top.Priority, top.Target, imperative)
}

// RenderDomainMapBlock renders the DOMAIN-MAP block content (without
// sentinels): every domains/<name>/ directory (sorted, excluding those
// starting with "_"), its manifest presentation fields, SETTLED atom count,
// and open-action pulse (R-domain-map-shows-pulse).
//
// repoRoot is the repository root (the parent of domains/); domainGraphs
// optionally pre-supplies already-loaded graphs keyed by domain directory
// name (dedup with the caller's own load), falling back to loading
// domains/<name>/graph.json from disk when absent.
func RenderDomainMapBlock(repoRoot string, domainGraphs map[string]*ontology.Graph, today string) string {
	lines := []string{
		generatedHeaderComment,
		"",
		"### Domain Map",
		"",
	}

	domainsRoot := filepath.Join(repoRoot, "domains")
	entries, err := os.ReadDir(domainsRoot)
	if err != nil {
		lines = append(lines, "_(no domains yet — domains/ directory absent)_")
		return strings.TrimRight(strings.Join(lines, "\n"), " \t\r\n")
	}

	var domainDirs []string
	for _, e := range entries {
		if !e.IsDir() || strings.HasPrefix(e.Name(), "_") {
			continue
		}
		domainDirs = append(domainDirs, e.Name())
	}
	sort.Strings(domainDirs)

	if len(domainDirs) == 0 {
		lines = append(lines, "_(no domains yet)_")
		return strings.TrimRight(strings.Join(lines, "\n"), " \t\r\n")
	}

	for _, name := range domainDirs {
		m, known := knownDomainManifests[name]
		domainID := name
		description := ""
		goalsText := ""
		director := ""
		if known {
			domainID = m.ID
			description = m.Description
			if len(m.Goals) > 0 {
				goalsText = strings.Join(m.Goals, ", ")
			}
			director = m.Director
		}
		if description == "" {
			description = "—"
		}
		if goalsText == "" {
			goalsText = "—"
		}
		if director == "" {
			director = "—"
		}

		atomsCount := 0
		openActions := 0
		topActionLine := ""

		dg := domainGraphs[name]
		if dg == nil {
			gp := filepath.Join(domainsRoot, name, "graph.json")
			if loaded, err := loader.LoadGraph(gp); err == nil {
				dg = loaded
			}
		}
		if dg != nil {
			for _, r := range dg.Requirements {
				if r.Status == ontology.StatusSETTLED {
					atomsCount++
				}
			}
			openActions, topActionLine = domainPulse(dg, today)
		}

		lines = append(lines, "### "+domainID)
		lines = append(lines, "- **purpose** — "+description)
		lines = append(lines, "- **goals** — "+goalsText)
		lines = append(lines, "- **director** — "+director)
		lines = append(lines, "- **path** — `domains/"+name+"/`")
		lines = append(lines, fmt.Sprintf("- **atoms-count** — %d SETTLED", atomsCount))
		if openActions > 0 {
			lines = append(lines, fmt.Sprintf("- **open actions** — %d (top: %s)", openActions, topActionLine))
		} else {
			lines = append(lines, "- **open actions** — 0 (graph clean)")
		}
		lines = append(lines, "")
	}

	return strings.TrimRight(strings.Join(lines, "\n"), " \t\r\n")
}

// RenderAgentMapBlock renders the AGENT-MAP block content (without
// sentinels). Static: no spec/agents/<name>/ directories exist
// (R-claude-md-consolidates-when-single-agent — sub-agent crystals
// materialize only at real spawn time), so the placeholder is the only
// reachable output; baked in claudemd_static.go alongside the other
// no-filesystem-equivalent blocks.
func RenderAgentMapBlock() string {
	return agentMapText
}

// RenderConceptMapBlock renders the CONCEPT-MAP block content (without
// sentinels). Static: the concept map projects glossary §-section terms
// against the framework's source tree, with no live AST scan wired up (see
// claudemd_static.go doc comment); the function carries no graph dependency.
func RenderConceptMapBlock() string {
	return conceptMapText
}

// recentlyRejectedCap caps the CLAUDE.md RECENTLY-REJECTED block at a small
// taste of the anti-relitigation list (P2-1 compaction — the full list with
// full summaries lives in docs/gen/HISTORY.md, not duplicated into every
// regeneration of the root crystal).
const recentlyRejectedCap = 3

// rejectedReplacesRE matches the "REJECTED <dash> REPLACES" marker across
// em-dash, en-dash, double-dash, and single-hyphen variants.
var rejectedReplacesRE = regexp.MustCompile(`REJECTED\s*(?:—|–|--|-)\s*REPLACES`)

func hasRejectedReplacesMarker(why string) bool {
	return rejectedReplacesRE.MatchString(why)
}

// replacesMap mirrors graph.replaces_map: REJECTED-id -> ordered tuple of
// successor (carrier) ids, built from every Requirement's "replaces"
// relations, in graph declaration order (NOT raw JSON array order). The
// Go loader preserves source-file textual declaration order only via
// DeclOrder (see NarrativeOrder, the same pattern every other
// order-sensitive builder in this package uses).
func replacesMap(g *ontology.Graph) map[string][]string {
	out := make(map[string][]string)
	for _, r := range NarrativeOrder(g.Requirements, func(r ontology.Requirement) int { return r.DeclOrder }) {
		for _, rel := range r.Relations {
			if rel.Kind == "replaces" {
				out[rel.Target] = append(out[rel.Target], r.ID)
			}
		}
	}
	return out
}

// RenderRecentlyRejectedBlock renders the RECENTLY-REJECTED block content
// (without sentinels): REJECTED requirements with a known replacement
// (structural `replaces` edge OR legacy prose "REJECTED — REPLACES"
// marker), capped at recentlyRejectedCap entries (a small taste, P2-1
// compaction) in alphabetical-by-id order, with a pointer to the full
// history (docs/gen/HISTORY.md) beyond the cap.
func RenderRecentlyRejectedBlock(g *ontology.Graph) string {
	lines := []string{
		generatedHeaderComment,
		"",
		"### Recently rejected (anti-relitigation — summary)",
		"",
		"Before proposing an architectural change, check this isn't already REJECTED with a REPLACES successor — cite the replacement instead of re-deriving. Full list: `docs/gen/HISTORY.md`.",
		"",
	}

	rmap := replacesMap(g)

	var rejected []ontology.Requirement
	for _, r := range g.Requirements {
		if r.Status != ontology.StatusREJECTED {
			continue
		}
		_, hasEdge := rmap[r.ID]
		if hasEdge || hasRejectedReplacesMarker(r.Why) {
			rejected = append(rejected, r)
		}
	}
	sort.Slice(rejected, func(i, j int) bool { return rejected[i].ID < rejected[j].ID })

	if len(rejected) == 0 {
		lines = append(lines, "_(no anti-relitigation entries — nothing recently rejected.)_")
		return strings.TrimRight(strings.Join(lines, "\n"), " \t\r\n")
	}

	total := len(rejected)
	shown := rejected
	if len(shown) > recentlyRejectedCap {
		shown = shown[:recentlyRejectedCap]
	}

	// P2-1 compaction: id-only (no WHY-derived summary text — that detail
	// lives in docs/gen/HISTORY.md, `hotam req show <id>`, and
	// AGENT-CONTEXT.md's pointer to it) to keep this root-crystal block
	// small regardless of how verbose an individual rejection's WHY prose
	// is.
	ids := make([]string, len(shown))
	for i, r := range shown {
		ids[i] = r.ID
	}
	lines = append(lines, fmt.Sprintf("**REJECTED (REPLACES known)** (%d) — %s", total, strings.Join(ids, " · ")))

	if total > recentlyRejectedCap {
		lines = append(lines, "")
		lines = append(lines, fmt.Sprintf(
			"_(showing %d of %d, alphabetical by id — full history + WHY: docs/gen/HISTORY.md, `hotam req show <id>`)_",
			len(shown), total,
		))
	}

	return strings.TrimRight(strings.Join(lines, "\n"), " \t\r\n")
}

// runeTruncateEllipsis truncates s to keep runes and appends the single
// Unicode ellipsis character "…".
func runeTruncateEllipsis(s string, keep int) string {
	r := []rune(s)
	if len(r) <= keep {
		return s
	}
	return strings.TrimRight(string(r[:keep]), " \t\r\n") + "…"
}

// RenderBusinessContent renders the BUSINESS bucket: the domain-specific
// "what this claims" layer. Order: LIVE-STATE, DOMAIN-MAP, CONSTITUTION,
// AGENT-MAP, CONCEPT-MAP, RECENTLY-REJECTED.
func RenderBusinessContent(g *ontology.Graph, domainName, repoRoot string, claudeMDCharCount int, domainGraphs map[string]*ontology.Graph, today string) string {
	parts := []string{
		WrapBlock("LIVE-STATE", BuildLiveState(g, claudeMDCharCount, today)),
		WrapBlock("DOMAIN-MAP", RenderDomainMapBlock(repoRoot, domainGraphs, today)),
		WrapBlock("CONSTITUTION", BuildConstitutionBlock(g, domainName)),
		WrapBlock("AGENT-MAP", RenderAgentMapBlock()),
		WrapBlock("CONCEPT-MAP", RenderConceptMapBlock()),
		WrapBlock("RECENTLY-REJECTED", RenderRecentlyRejectedBlock(g)),
	}
	return strings.Join(parts, "\n")
}

// RenderClaudeMDFromTemplate renders root CLAUDE.md by substituting the two
// template placeholder lines ("<!-- mind -->" / "<!-- business -->") in
// claudeMDTemplate with the rendered MIND and BUSINESS content
// respectively. Every other line of the template — including the trailing
// human-notes marker comment — is preserved byte-for-byte.
//
// claudeMDCharCount feeds the LIVE-STATE CRYSTAL_CHARS budget line (the
// resident crystal's own character count — supplied by the caller to avoid
// the fixpoint hazard of CLAUDE.md measuring its own about-to-be-written
// size; see BuildLiveState / livestate.go).
//
// today (YYYY-MM-DD) is threaded through explicitly rather than computed
// internally via time.Now(), so `hotam gen-spec --today <date>` (or any
// caller) can render a byte-reproducible crystal independent of wall-clock
// date — the property CI's regen-idempotency check needs.
func RenderClaudeMDFromTemplate(g *ontology.Graph, domainName, repoRoot string, claudeMDCharCount int, domainGraphs map[string]*ontology.Graph, today string) string {
	effectiveDomain := domainName
	if effectiveDomain == "" {
		effectiveDomain = "hotam-spec-self"
	}
	mind := RenderMindContent(g, domainName)
	business := RenderBusinessContent(g, domainName, repoRoot, claudeMDCharCount, domainGraphs, today)

	srcLines := strings.Split(claudeMDTemplate, "\n")
	outLines := make([]string, 0, len(srcLines))
	for _, line := range srcLines {
		switch strings.TrimSpace(line) {
		case mindPlaceholder:
			outLines = append(outLines, mind)
		case businessPlaceholder:
			outLines = append(outLines, business)
		default:
			outLines = append(outLines, line)
		}
	}
	// The boot line's deep-dive pointer is a fixed template string (it can't
	// carry a %s placeholder without complicating claudeMDTemplate's
	// mind/business substitution above), so the domain-qualified path is
	// filled in with one targeted replace here instead -- same pattern as
	// RenderOperatorRecursionBlock's domain substitution.
	return strings.ReplaceAll(strings.Join(outLines, "\n"), "`spec/docs/thinking/`", "`domains/"+effectiveDomain+"/docs/gen/thinking/`")
}

// maxCrystalFixpointIterations caps the render→measure→re-render loop that
// converges the resident crystal's self-referential CRYSTAL_CHARS measurement.
// The ONLY way the embedded number can shift the rendered length is a
// digit-count change (e.g. "9999"→"10000" is +1 char); convergence in ≤3
// iterations is guaranteed for any realistic crystal size, so 5 is a generous
// guard against a non-convergent (oscillating) measurement that should never
// occur in practice.
const maxCrystalFixpointIterations = 5

// ComputeCrystalCharCountFixpoint computes the fixpoint rune-count of the
// rendered root crystal. The resident crystal's LIVE-STATE block embeds its
// OWN character count (the CRYSTAL_CHARS budget line, R-context-budget-rule),
// so the measurement is self-referential: embedding a different count can
// shift the rendered length (a digit-count change like "9999"→"10000" adds
// one char), which changes the very number being embedded. The fixpoint is
// the count that, when embedded, produces a crystal whose rune count equals
// that count.
//
// It iterates render→measure (rune count via utf8.RuneCountInString, the
// convention every other CRYSTAL_CHARS call site uses)→re-render until the
// embedded number stops changing, capped at maxCrystalFixpointIterations; a
// non-convergence returns an error (oscillation should be impossible since
// only a small number's digit count can shift, but it is guarded anyway).
//
// The returned fixpoint is what every LIVE-STATE carrier (the root crystal
// AND docs/gen/AGENT-CONTEXT.md + live-state.md, which reuse BuildLiveState)
// must embed so the two artifacts agree regardless of the --claude-md flag
// (which gates only the crystal's DISK WRITE, not whether the measurement is
// computed). This replaces the former buggy mechanism that read the size of a
// stale pre-existing CLAUDE.md from the previous run — a read that made two
// consecutive gen-spec passes never converge and left AGENT-CONTEXT.md stuck
// at "0 chars" whenever --claude-md was omitted.
func ComputeCrystalCharCountFixpoint(g *ontology.Graph, domainName, repoRoot string, domainGraphs map[string]*ontology.Graph, today string) (int, error) {
	count := 0
	for i := 0; i < maxCrystalFixpointIterations; i++ {
		rendered := RenderClaudeMDFromTemplate(g, domainName, repoRoot, count, domainGraphs, today)
		measured := utf8.RuneCountInString(rendered)
		if measured == count {
			return count, nil
		}
		count = measured
	}
	return count, fmt.Errorf("crystal char-count fixpoint did not converge after %d iterations (last measurement %d) — the resident crystal's self-referential size measurement is oscillating, which should be impossible since only a digit-count shift can change the rendered length", maxCrystalFixpointIterations, count)
}
