package generator

import (
	"sort"
	"strings"

	"github.com/PHPCraftdream/HotamSpec/internal/docbundle"
	"github.com/PHPCraftdream/HotamSpec/internal/localization"
	"github.com/PHPCraftdream/HotamSpec/internal/ontology"
)

func NarrativeOrder[T any](items []T, order func(T) int) []T {
	cp := make([]T, len(items))
	copy(cp, items)
	sort.SliceStable(cp, func(i, j int) bool {
		return order(cp[i]) < order(cp[j])
	})
	return cp
}

const Banner = "<!-- AUTOGENERATED from the domain graph.json — do not edit by hand. Edits: methodology/graph -> hotam gen-spec -->"

const EmptyNotice = "_No domain content loaded — no `domains/<name>/graph.json` found. Run `hotam init <dir>` to scaffold a new domain, then `hotam gen-spec --domain <dir>` to populate docs/gen/. The methodology narrative below is the framework itself and is always present._"

const UnresolvedReader = "(unresolved-reader)"

const RoleOperator = "operator"

const RoleDomainResolver = "domain-resolver"

const RoleFrameworkMaintainer = "framework-maintainer"

var DocReaderRoles = map[string]string{
	"CONSTITUTION":         RoleOperator,
	"OPEN":                 RoleOperator,
	"UNENFORCED":           RoleOperator,
	"ATOMS_OPERATOR":       RoleOperator,
	"ATOMS_SUBSTRATE":      RoleOperator,
	"ATOMS_DISCIPLINE":     RoleOperator,
	"ATOMS_CHECK":          RoleOperator,
	"SHARED_THINKING":      RoleOperator,
	"SHARED_TOOL":          RoleOperator,
	"REQUIREMENTS":         RoleDomainResolver,
	"SPEC":                 RoleDomainResolver,
	"TENSIONS":             RoleDomainResolver,
	"DECISIONS":            RoleDomainResolver,
	"HISTORY":              RoleDomainResolver,
	"ENTITIES":             RoleDomainResolver,
	"FRAMEWORK_INVARIANTS": RoleFrameworkMaintainer,
	"GLOSSARY":             RoleFrameworkMaintainer,
	"AUDIT":                RoleFrameworkMaintainer,
	"REPO_MAP":             RoleOperator,
	"MODELS":               RoleDomainResolver,
	"COVERAGE":             RoleDomainResolver,
}

var DomainDocReaders = map[string]string{
	RoleOperator:            "ai-agent",
	RoleDomainResolver:      "domain-user",
	RoleFrameworkMaintainer: "framework-author",
}

func ResolveReader(docKind string, stakeholderIDs map[string]struct{}, roleBindings map[string]string) string {
	role, ok := DocReaderRoles[docKind]
	if !ok {
		return UnresolvedReader
	}
	if roleBindings == nil {
		return UnresolvedReader
	}
	boundID, ok := roleBindings[role]
	if !ok {
		return UnresolvedReader
	}
	if _, exists := stakeholderIDs[boundID]; !exists {
		return UnresolvedReader
	}
	return boundID
}

func renderLanguage(g *ontology.Graph) string {
	if g == nil {
		return ""
	}
	if g.RenderLanguage != "" {
		return g.RenderLanguage
	}
	if g.DefaultLanguage != "" {
		return g.DefaultLanguage
	}
	if len(g.Languages) == 1 {
		return g.Languages[0]
	}
	return ""
}

// serviceText selects a fixed, author-authored service template for this
// invocation's graph view. It must never be used for graph/user-authored text.
func serviceText(g *ontology.Graph, sourceTemplate string, args ...any) string {
	return localization.Text(renderLanguage(g), sourceTemplate, args...)
}

// requirementClaim selects an authored claim translation for the active view.
// It never rewrites claim data; non-default locales require an explicit entry.
func requirementClaim(g *ontology.Graph, r ontology.Requirement) string {
	language := renderLanguage(g)
	if g == nil || len(g.Languages) < 2 || language == g.DefaultLanguage {
		return r.Claim
	}
	if claim, ok := r.ClaimTexts[language]; ok && strings.TrimSpace(claim) != "" {
		return claim
	}
	// REJECTED history shows the historical wording as is — no substitution,
	// no missing-translation failure when only some languages were authored.
	if r.Status == ontology.StatusREJECTED {
		if strings.TrimSpace(r.Claim) != "" {
			return r.Claim
		}
		if claim, ok := r.ClaimTexts[g.DefaultLanguage]; ok && strings.TrimSpace(claim) != "" {
			return claim
		}
		return ""
	}
	panic(&localization.MissingTranslation{
		Language: language,
		Template: "Requirement.ClaimTexts",
	})
}

// localizedStatus translates only the fixed status token, retaining any
// authored detail carried by OPEN(...).
func localizedStatus(g *ontology.Graph, status string) string {
	if status == "OPEN" || strings.HasPrefix(status, "OPEN(") {
		return serviceText(g, "OPEN") + strings.TrimPrefix(status, "OPEN")
	}
	return serviceText(g, status)
}

func localizedBanner(g *ontology.Graph) string {
	return serviceText(g, Banner)
}

func localizedEmptyNotice(g *ontology.Graph) string {
	return serviceText(g, EmptyNotice)
}

func ReaderHeaderLine(docKind string, g *ontology.Graph) string {
	reader := ResolveReader(docKind, ontology.StakeholderIDs(g), DomainDocReaders)
	if reader == UnresolvedReader {
		// No named reader for this graph (e.g. consumer domains without a
		// "domain-user" stakeholder): omit the line entirely instead of
		// printing an "(unresolved-reader)" placeholder.
		return ""
	}
	return serviceText(g, "reader: %s", reader)
}

// docHeaderLines renders the shared document opening: the localized banner,
// an optional resolved reader line (omitted when unresolved), and the blank
// separator before the title.
func docHeaderLines(docKind string, g *ontology.Graph) []string {
	lines := []string{localizedBanner(g)}
	if reader := ReaderHeaderLine(docKind, g); reader != "" {
		lines = append(lines, reader)
	}
	return append(lines, "")
}

func localizedDocumentPath(g *ontology.Graph, path string) string {
	if g == nil || len(g.Languages) == 0 {
		return path
	}
	layout, err := docbundle.NewLayout(g.Languages, g.DefaultLanguage)
	if err != nil {
		panic(err)
	}
	localized, err := layout.DocumentPath(path, renderLanguage(g))
	if err != nil {
		panic(err)
	}
	return localized
}

// IsGeneratedLocalizedDocument recognizes exact generated first-line markers.
func IsGeneratedLocalizedDocument(language, content string) bool {
	if !localization.Supported(language) {
		return false
	}
	for _, markerLanguage := range []string{"", "ru", "zh"} {
		for _, source := range []string{Banner, generatedHeaderComment, "### Live state (autogenerated by `hotam gen-spec` — do not hand-edit)"} {
			marker, err := localization.Lookup(markerLanguage, source)
			if err != nil || !strings.HasPrefix(content, marker) {
				continue
			}
			remainder := strings.TrimPrefix(content, marker)
			if strings.HasPrefix(remainder, "\n") || strings.HasPrefix(remainder, "\r\n") {
				return true
			}
		}
	}
	return false
}

func Cell(text string) string {
	t := strings.ReplaceAll(text, "\n", " ")
	t = strings.ReplaceAll(t, "|", "\\|")
	return t
}

func MermaidID(nodeID string) string {
	t := strings.ReplaceAll(nodeID, "-", "_")
	t = strings.ReplaceAll(t, "~", "_")
	t = strings.ReplaceAll(t, ".", "_")
	return t
}
