package generator

import (
	"sort"
	"strings"

	"github.com/PHPCraftdream/HotamSpec/internal/ontology"
)

func NarrativeOrder[T any](items []T, order func(T) int) []T {
	cp := make([]T, len(items))
	copy(cp, items)
	sort.SliceStable(cp, func(i, j int) bool {
		return order(cp[i]) < order(cp[j])
	})
	return cp
}

const Banner = "<!-- AUTOGENERATED from the domain graph.json — do not edit by hand. Edits: methodology/graph -> hotam gen-spec -->"

const EmptyNotice = "_No domain content loaded — no `domains/<name>/graph.json` found. Run `hotam init <dir>` to scaffold a new domain, then `hotam gen-spec --domain <dir>` to populate docs/gen/. The methodology narrative below is the framework itself and is always present._"

const UnresolvedReader = "(unresolved-reader)"

const RoleOperator = "operator"

const RoleDomainSteward = "domain-steward"

const RoleFrameworkMaintainer = "framework-maintainer"

var DocReaderRoles = map[string]string{
	"CONSTITUTION":         RoleOperator,
	"OPEN":                 RoleOperator,
	"UNENFORCED":           RoleOperator,
	"ATOMS_OPERATOR":       RoleOperator,
	"ATOMS_SUBSTRATE":      RoleOperator,
	"ATOMS_DISCIPLINE":     RoleOperator,
	"ATOMS_CHECK":          RoleOperator,
	"SHARED_THINKING":      RoleOperator,
	"SHARED_TOOL":          RoleOperator,
	"REQUIREMENTS":         RoleDomainSteward,
	"TENSIONS":             RoleDomainSteward,
	"DECISIONS":            RoleDomainSteward,
	"HISTORY":              RoleDomainSteward,
	"ENTITIES":             RoleDomainSteward,
	"FRAMEWORK_INVARIANTS": RoleFrameworkMaintainer,
	"GLOSSARY":             RoleFrameworkMaintainer,
	"AUDIT":                RoleFrameworkMaintainer,
	"REPO_MAP":             RoleOperator,
}

var DomainDocReaders = map[string]string{
	RoleOperator:            "ai-agent",
	RoleDomainSteward:       "domain-user",
	RoleFrameworkMaintainer: "framework-author",
}

func ResolveReader(docKind string, stakeholderIDs map[string]struct{}, roleBindings map[string]string) string {
	role, ok := DocReaderRoles[docKind]
	if !ok {
		return UnresolvedReader
	}
	if roleBindings == nil {
		return UnresolvedReader
	}
	boundID, ok := roleBindings[role]
	if !ok {
		return UnresolvedReader
	}
	if _, exists := stakeholderIDs[boundID]; !exists {
		return UnresolvedReader
	}
	return boundID
}

func ReaderHeaderLine(docKind string, g *ontology.Graph) string {
	return "reader: " + ResolveReader(docKind, ontology.StakeholderIDs(g), DomainDocReaders)
}

func Cell(text string) string {
	t := strings.ReplaceAll(text, "\n", " ")
	t = strings.ReplaceAll(t, "|", "\\|")
	return t
}

func MermaidID(nodeID string) string {
	t := strings.ReplaceAll(nodeID, "-", "_")
	t = strings.ReplaceAll(t, "~", "_")
	t = strings.ReplaceAll(t, ".", "_")
	return t
}
