package generator

import (
	"html"
	"path/filepath"
	"strings"
	"unicode"

	"github.com/PHPCraftdream/HotamSpec/internal/evidence"
	"github.com/PHPCraftdream/HotamSpec/internal/gate"
	"github.com/PHPCraftdream/HotamSpec/internal/ontology"
)

// BuildEvidence renders the current, freshly collected evidence packet. It is
// deliberately descriptive: coverage declarations, executed verdicts, and
// structural source checks remain separate so none can be mistaken for
// another.
func BuildEvidence(g *ontology.Graph, report evidence.Report) string {
	contents, err := BuildEvidenceLocalized(g, report, selectedReportLanguage(g, ""))
	if err != nil {
		panic(err)
	}
	return contents
}

// BuildEvidenceLocalized renders one view of the shared evidence snapshot.
// It returns before any caller writes output if a fixed translation is absent.
func BuildEvidenceLocalized(g *ontology.Graph, report evidence.Report, language string) (string, error) {
	language = selectedReportLanguage(g, language)
	var claimErr error
	contents, err := renderLocalizedReport(language, func(text reportText) string {
		rendered, err := renderEvidence(g, report, language, text)
		claimErr = err
		return rendered
	})
	if err != nil {
		return "", err
	}
	if claimErr != nil {
		return "", claimErr
	}
	return contents, nil
}

func renderEvidence(g *ontology.Graph, report evidence.Report, language string, text reportText) (string, error) {
	lines := []string{
		text("# EVIDENCE.md — Current verification evidence"),
		"",
		text("> Generated by `hotam evidence`. This report records observed checks; it is not a normative specification and does not assign semantic blame."),
		"",
		text("## Coverage overview"),
		"",
	}
	if len(report.Requirements) == 0 {
		lines = append(lines, text("_No requirements were collected._"), "")
	} else {
		lines = append(lines,
			text("| Requirement | Report coverage status | Authored declaration | Tests | Cases |"),
			"|---|---|---|---:|---:|")
		for _, req := range report.Requirements {
			qualification := authoredCoverageLocalized(g, req.ID, req.Rationale, req.Profile, text)
			lines = append(lines, "| ["+Cell(req.ID)+"](#requirement-"+html.EscapeString(req.ID)+") | "+
				Cell(reportStatus(text, req.CoverageStatus))+" | "+Cell(qualification)+" | "+
				itoa(len(req.Tests))+" | "+itoa(len(req.Cases))+" |")
		}
		lines = append(lines, "")
	}

	lines = append(lines, text("## Specification source checks"), "")
	if len(report.Sources) == 0 {
		lines = append(lines, text("_No specification sources were declared._"), "")
	} else {
		lines = append(lines,
			text("| Source | Anchor | Path | Version | Integrity | SHA-256 (expected / actual) |"),
			"|---|---|---|---|---|---|")
		for _, check := range report.Sources {
			pathCell := "—"
			if check.Path != "" {
				pathCell = "[" + Cell(check.Path) + "](" + sourceLink(g, check.Path, check.Anchor) + ")"
			}
			lines = append(lines, "| `"+Cell(check.SourceID)+"` | `"+Cell(check.Anchor)+"` | "+pathCell+
				" | "+Cell(check.Version)+" | "+Cell(reportStatus(text, check.Status))+" | `"+
				Cell(check.ExpectedSHA256)+"` / `"+Cell(check.ActualSHA256)+"` |")
			if check.Message != "" {
				lines = append(lines, "|  |  | "+text("_Check detail_")+" |  |  | "+Cell(check.Message)+" |")
			}
		}
		lines = append(lines, "")
	}

	if hasConformanceData(report.Conformance) {
		lines = append(lines, text("## Conformance audit"), "")
		lines = append(lines, text("> This audit is structural relative to the declared inventory. It does not establish semantic completeness or exhaustive input coverage."), "")
		lines = append(lines,
			text("| Metric | Count |"),
			"|---|---:|",
			"| "+text("Source clauses declared")+" | "+itoa(report.Conformance.InventoryDeclared)+" |",
			"| "+text("Source clauses linked")+" | "+itoa(report.Conformance.InventoryLinked)+" |",
			"| "+text("Atoms linked")+" | "+itoa(report.Conformance.AtomsLinked)+" |",
			"| "+text("Atoms with methods")+" | "+itoa(report.Conformance.AtomsWithMethods)+" |",
			"| "+text("Cases declared")+" | "+itoa(report.Conformance.CasesDeclared)+" |",
			"| "+text("Cases observed")+" | "+itoa(report.Conformance.CasesObserved)+" |",
			"| "+text("Cases executed")+" | "+itoa(report.Conformance.CasesExecuted)+" |",
			"| "+text("Comparisons executed")+" | "+itoa(report.Conformance.ComparisonsExecuted)+" |",
			"| "+text("Observed discrepancies")+" | "+itoa(report.Conformance.Discrepancies)+" |",
			"| "+text("Profile qualifications")+" | "+itoa(report.Conformance.ProfileQualifications)+" |",
			"")

		if len(report.Conformance.Clauses) > 0 {
			lines = append(lines, text("## Source clause inventory"), "",
				text("| Clause | Strength | Source links | Atoms | Missing sides | Status |"),
				"|---|---|---|---|---|---|")
			for _, clause := range report.Conformance.Clauses {
				var links []string
				for _, link := range clause.SourceLinks {
					check, ok := sourceCheckForAnchor(report.Sources, link.SourceID, link.Anchor)
					if ok && check.Path != "" {
						links = append(links, "["+Cell(link.SourceID+"#"+link.Anchor)+"]("+sourceLink(g, check.Path, link.Anchor)+")")
					} else {
						links = append(links, "`"+Cell(link.SourceID+"#"+link.Anchor)+"`")
					}
				}
				lines = append(lines, "| `"+Cell(clause.ID)+"` | "+Cell(clause.Strength)+" | "+
					strings.Join(links, ", ")+" | `"+Cell(strings.Join(clause.AtomIDs, ", "))+"` | `"+
					Cell(strings.Join(clause.MissingSides, ", "))+"` | "+
					Cell(reportStatus(text, clause.Status))+" |")
			}
			lines = append(lines, "")
		}

		if len(report.Conformance.Cases) > 0 {
			lines = append(lines, text("## Declared cases and observations"), "",
				text("| Case | Atom | Test | Profile | Operation | Target | Producer | Sides | Fixtures | Status | Qualification | Input (typed) | Expected (typed) |"),
				"|---|---|---|---|---|---|---|---|---|---|---|---|---|")
			for _, item := range report.Conformance.Cases {
				lines = append(lines, "| `"+Cell(item.ID)+"` | `"+Cell(item.AtomID)+"` | "+
					testLink(g, item.Test)+" | `"+Cell(item.Profile)+"` | `"+Cell(item.Operation)+"` | `"+
					Cell(item.Target)+"` | `"+Cell(item.Producer)+"` | `"+Cell(strings.Join(item.Sides, ", "))+
					"` | `"+Cell(reportJSON(item.Fixtures, text))+"` | "+Cell(reportStatus(text, item.Status))+
					" | "+Cell(reportStatus(text, item.Qualification))+" | `"+Cell(reportRawValue(item.Input, text))+
					"` | `"+Cell(reportRawValue(item.Expected, text))+"` |")
			}
			lines = append(lines, "")
			for _, item := range report.Conformance.Cases {
				for _, execution := range item.Executions {
					if len(execution.Comparisons) == 0 {
						continue
					}
					lines = append(lines,
						text("### Case `%s` — atom `%s`", Cell(item.ID), Cell(item.AtomID)), "",
						text("| Comparison | Test | Profile | Operation | Target | Producer | Conditions / selection | Input | Raw input | Actual | Raw actual | Expected | Raw expected | Verdict |"),
						"|---|---|---|---|---|---|---|---|---|---|---|---|---|---|")
					for _, comparison := range execution.Comparisons {
						verdict := "pass"
						if !comparison.Passed {
							verdict = "fail"
						}
						profile := execution.Profile
						if execution.ObservedProfile != "" && execution.ObservedProfile != profile {
							profile += " / " + execution.ObservedProfile
						}
						lines = append(lines, "| `"+Cell(comparison.Name)+"` | "+testLink(g, execution.Test)+
							" | `"+Cell(profile)+"` | `"+Cell(execution.Operation)+"` | `"+
							Cell(execution.Target)+"` | `"+Cell(execution.Producer)+"` | `"+
							Cell(reportJSON(execution.Conditions, text)+" / "+reportJSON(execution.Selection, text))+
							"` | "+Cell(comparison.InputText)+" | `"+Cell(reportRawValue(comparison.Input, text))+
							"` | "+Cell(comparison.ActualText)+" | `"+Cell(reportRawValue(comparison.Actual, text))+
							"` | "+Cell(comparison.ExpectedText)+" | `"+Cell(reportRawValue(comparison.Expected, text))+"` | "+
							Cell(reportStatus(text, verdict))+" |")
					}
					lines = append(lines, "")
				}
			}
		}

		if len(report.Conformance.Profiles) > 0 {
			lines = append(lines, text("## Implementation profiles"), "",
				text("| Profile | Operations | Features | Capabilities | Status |"),
				"|---|---|---|---|---|")
			for _, profile := range report.Conformance.Profiles {
				operations, features, capabilities := "—", "—", "—"
				if profile.Definition != nil {
					operations = strings.Join(profile.Definition.Operations, ", ")
					features = strings.Join(profile.Definition.Features, ", ")
					capabilities = reportJSON(profile.Definition, text)
				}
				lines = append(lines, "| `"+Cell(profile.ID)+"` | `"+Cell(operations)+"` | `"+
					Cell(features)+"` | `"+Cell(capabilities)+"` | "+
					Cell(reportStatus(text, profile.Status))+" |")
			}
			lines = append(lines, "")
		}

		if len(report.Conformance.Precedence) > 0 {
			lines = append(lines, text("## Scoped precedence"), "",
				text("| Atom | Target | Scope | Profile | Operation | Status |"),
				"|---|---|---|---|---|---|")
			for _, precedence := range report.Conformance.Precedence {
				lines = append(lines, "| `"+Cell(precedence.AtomID)+"` | `"+Cell(precedence.Target)+
					"` | `"+Cell(precedence.Scope)+"` | `"+Cell(precedence.Profile)+"` | `"+
					Cell(precedence.Operation)+"` | "+Cell(reportStatus(text, precedence.Status))+" |")
			}
			lines = append(lines, "")
		}

		if len(report.Conformance.Compositions) > 0 {
			lines = append(lines, text("## Implementation compositions"), "",
				text("| Composition | Declared components | Measured components | Declared fingerprint | Measured fingerprint | Status |"),
				"|---|---|---|---|---|---|")
			for _, composition := range report.Conformance.Compositions {
				lines = append(lines, "| `"+Cell(composition.ID)+"` | `"+
					Cell(reportJSON(composition.Components, text))+"` | `"+
					Cell(reportJSON(composition.ObservedComponents, text))+"` | `"+
					Cell(composition.DeclaredFingerprint)+"` | `"+Cell(composition.MeasuredFingerprint)+"` | "+
					Cell(reportStatus(text, composition.Status))+" |")
			}
			lines = append(lines, "")
		}

		if len(report.Conformance.Issues) > 0 {
			lines = append(lines, text("## Audit issues"), "",
				text("| Issue | Disposition | Clause | Atom | Case | Profile | Target | Producer | Operation | Detail |"),
				"|---|---|---|---|---|---|---|---|---|---|")
			for _, issue := range report.Conformance.Issues {
				lines = append(lines, "| `"+Cell(issue.Code)+"` | "+Cell(reportStatus(text, issue.Disposition))+
					" | `"+Cell(issue.ClauseID)+"` | `"+Cell(issue.AtomID)+"` | `"+Cell(issue.CaseID)+
					"` | `"+Cell(issue.Profile)+"` | `"+Cell(issue.Target)+"` | `"+Cell(issue.Producer)+
					"` | `"+Cell(issue.Operation)+"` | "+Cell(issue.Message)+" |")
			}
			lines = append(lines, "")
		}
	}

	for _, req := range report.Requirements {
		claim, err := reportClaim(g, language, req.ID, req.Claim, req.ClaimTexts)
		if err != nil {
			return "", err
		}
		lines = append(lines, "<a id=\"requirement-"+html.EscapeString(req.ID)+"\"></a>",
			text("## Requirement `%s`", Cell(req.ID)), "", Cell(claim), "")
		lines = append(lines,
			"- **"+text("Coverage status (report)")+":** `"+Cell(reportStatus(text, req.CoverageStatus))+"`",
			"- **"+text("Authored declaration")+":** "+Cell(authoredCoverageLocalized(g, req.ID, req.Rationale, req.Profile, text)))
		var requirementFindings []evidence.Finding
		for _, finding := range report.Findings {
			if finding.RequirementID == req.ID {
				requirementFindings = append(requirementFindings, finding)
			}
		}
		if len(requirementFindings) > 0 {
			lines = append(lines, "- **"+text("Observed finding records")+":**")
			for _, finding := range requirementFindings {
				findingsDoc := localizedReportName(g, "FINDINGS", language)
				lines = append(lines, "  - [`"+Cell(finding.ID)+"` — `"+
					Cell(reportStatus(text, finding.Kind))+"`]("+findingsDoc+"#finding-"+html.EscapeString(finding.ID)+")")
			}
		}
		if len(req.Cases) > 0 {
			caseIDs := make([]string, 0, len(req.Cases))
			for _, definition := range req.Cases {
				caseIDs = append(caseIDs, definition.ID)
			}
			lines = append(lines, "- **"+text("Cases")+":** `"+Cell(strings.Join(caseIDs, ", "))+"`")
		}
		if len(req.SourceLinks) > 0 {
			lines = append(lines, "- **"+text("Normative/source links")+":**")
			for _, link := range req.SourceLinks {
				check, ok := sourceCheckForAnchor(report.Sources, link.SourceID, link.Anchor)
				label := link.SourceID + "#" + link.Anchor
				href := ""
				if ok {
					label = link.SourceID + " — " + check.Path + "#" + link.Anchor
					href = sourceLink(g, check.Path, link.Anchor)
				}
				if href == "" {
					lines = append(lines, "  - `"+Cell(label)+"` ("+text("source reference unresolved")+")")
				} else {
					lines = append(lines, "  - ["+Cell(label)+"]("+href+")"+anchorSuffix(link.Anchor))
				}
			}
		}
		if len(req.Methods) > 0 {
			lines = append(lines, "- **"+text("Implementation methods")+":**")
			for _, method := range req.Methods {
				lines = append(lines, "  - "+methodLink(g, method))
			}
		}
		if req.CoverageStatus == evidence.CoverageRetired {
			lines = append(lines, "", text("_Retired requirement; no live test obligation is collected._"))
		} else if len(req.Tests) == 0 {
			lines = append(lines, "", text("_No test execution evidence was collected for this requirement._"))
		} else {
			lines = append(lines, "", text("### Test executions"), "")
			for _, test := range req.Tests {
				lines = append(lines, "#### "+testLink(g, test.Reference)+" — `"+
					Cell(reportStatus(text, test.Verdict))+"`", "")
				if test.Problem != "" {
					lines = append(lines, "- **"+text("Execution detail")+":** "+Cell(test.Problem), "")
				}
				if len(test.Artifacts) == 0 {
					lines = append(lines, text("_No per-test artifact was recorded._"), "")
					continue
				}
				for _, artifact := range test.Artifacts {
					lines = append(lines, "**"+text("Artifact")+":** "+testLink(g, artifact.Test)+
						" — "+text("Case ID")+": `"+Cell(artifact.CaseID)+"`, "+text("Subject")+
						" `"+Cell(artifact.Subject)+"`, "+text("Verdict")+" `"+
						Cell(reportStatus(text, artifact.Verdict))+"`", "")
					lines = append(lines, text("| Context | Value |"), "|---|---|")
					lines = append(lines,
						"| "+text("Implementation")+" | "+Cell(artifact.Context.Implementation)+" |",
						"| "+text("Implementation version")+" | "+Cell(artifact.Context.ImplementationVersion)+" |",
						"| "+text("Specification version")+" | "+Cell(artifact.Context.SpecVersion)+" |",
						"| "+text("Profile")+" | "+Cell(artifact.Context.Profile)+" |",
						"| "+text("Operation")+" | "+Cell(artifact.Context.Operation)+" |",
						"| "+text("Target")+" | "+Cell(artifact.Target)+" / "+Cell(artifact.Context.Target)+" |",
						"| "+text("Producer")+" | "+Cell(artifact.Producer)+" / "+Cell(artifact.Context.Producer)+" |",
						"| "+text("Profile selection fingerprint")+" | `"+Cell(artifact.Context.ProfileFingerprint)+"` |",
						"| "+text("Producer fingerprint")+" | `"+Cell(artifact.Context.ProducerFingerprint)+"` |",
						"| "+text("Case fingerprint")+" | `"+Cell(artifact.Context.CaseFingerprint)+"` |",
						"| "+text("Recorded case fingerprint")+" | `"+Cell(artifact.Context.RecordedCaseFingerprint)+"` |",
						"| "+text("Declared case fingerprint")+" | `"+Cell(artifact.Context.DeclaredCaseFingerprint)+"` |",
						"| "+text("Declared composition")+" | `"+Cell(reportJSON(artifact.Context.Composition, text))+"` |",
						"| "+text("Measured components")+" | `"+Cell(reportJSON(artifact.Context.MeasuredComponents, text))+"` |", "")
					if len(artifact.Observations) == 0 {
						lines = append(lines, text("_No detailed observations were recorded._"), "")
						continue
					}
					lines = append(lines,
						text("| Observation | Input | Raw input | Actual | Raw actual | Expected | Raw expected | Verdict |"),
						"|---|---|---|---|---|---|---|---|")
					for _, observation := range artifact.Observations {
						verdict := "pass"
						if !observation.Passed {
							verdict = "fail"
						}
						lines = append(lines, "| "+Cell(observation.Name)+" | "+Cell(observation.Input)+" | `"+
							Cell(reportRawValue(observation.RawInput, text))+"` | "+Cell(observation.Actual)+" | `"+
							Cell(reportRawValue(observation.RawActual, text))+"` | "+Cell(observation.Expected)+" | `"+
							Cell(reportRawValue(observation.RawExpected, text))+"` | "+Cell(reportStatus(text, verdict))+" |")
					}
					lines = append(lines, "")
				}
			}
		}
		lines = append(lines, "---", "")
	}

	if len(report.Limitations) > 0 {
		lines = append(lines, text("## Collection limitations"), "")
		for _, limitation := range report.Limitations {
			lines = append(lines, "- "+Cell(limitation))
		}
		lines = append(lines, "")
	}
	return strings.TrimRight(strings.Join(lines, "\n"), " \t\r\n") + "\n", nil
}

func sourceLink(g *ontology.Graph, file, anchor string) string {
	href := relativeSourcePath(g, file)
	if fragment := sourceAnchorFragment(anchor); fragment != "" {
		href += "#" + fragment
	}
	return href
}

func methodLink(g *ontology.Graph, method string) string {
	if method == "" {
		return "—"
	}
	file, _ := splitFileSymbol(method)
	if file == "" {
		return "`" + Cell(method) + "`"
	}
	return "[" + Cell(method) + "](" + relativeSourcePath(g, file) + ")"
}

func testLink(g *ontology.Graph, test string) string {
	if test == "" {
		return "—"
	}
	file, _ := splitFileSymbol(test)
	if file == "" {
		return "`" + Cell(test) + "`"
	}
	return "[" + Cell(test) + "](" + relativeSourcePath(g, file) + ")"
}

func splitFileSymbol(value string) (string, string) {
	at := strings.LastIndex(value, ":")
	if at <= 0 || at == len(value)-1 {
		return "", ""
	}
	return value[:at], value[at+1:]
}

func relativeSourcePath(g *ontology.Graph, file string) string {
	if g == nil {
		return strings.ReplaceAll(filepath.ToSlash(file), " ", "%20")
	}
	path := filepath.FromSlash(file)
	if !filepath.IsAbs(path) {
		path = filepath.Join(gate.SpecRootForGraph(g), path)
	}
	base := filepath.Join(g.DomainDir, "docs", "gen")
	rel, err := filepath.Rel(base, path)
	if err != nil {
		rel = file
	}
	return strings.ReplaceAll(filepath.ToSlash(rel), " ", "%20")
}

func anchorSuffix(anchor string) string {
	if anchor == "" {
		return ""
	}
	return " (`" + Cell(anchor) + "`)"
}

func sourceAnchorFragment(anchor string) string {
	anchor = strings.TrimPrefix(strings.TrimSpace(anchor), "#")
	if anchor == "" {
		return ""
	}
	if isSourceLineAnchor(anchor) {
		return anchor
	}
	var slug strings.Builder
	lastDash := false
	for _, r := range strings.ToLower(anchor) {
		switch {
		case unicode.IsLetter(r), unicode.IsNumber(r), r == '_':
			slug.WriteRune(r)
			lastDash = false
		case unicode.IsSpace(r) || r == '-':
			if slug.Len() > 0 && !lastDash {
				slug.WriteByte('-')
				lastDash = true
			}
		}
	}
	return strings.Trim(slug.String(), "-")
}

func isSourceLineAnchor(anchor string) bool {
	if !strings.HasPrefix(anchor, "L") {
		return false
	}
	parts := strings.Split(strings.TrimPrefix(anchor, "L"), "-L")
	if len(parts) < 1 || len(parts) > 2 {
		return false
	}
	for _, part := range parts {
		if part == "" {
			return false
		}
		for _, r := range part {
			if r < '0' || r > '9' {
				return false
			}
		}
	}
	return true
}
