package generator

import (
	"html"
	"strings"

	"github.com/PHPCraftdream/HotamSpec/internal/evidence"
	"github.com/PHPCraftdream/HotamSpec/internal/ontology"
)

// BuildFindings renders only findings produced by the current evidence
// collection. Human review records are stored separately and are never folded
// into this derived report.
func BuildFindings(g *ontology.Graph, report evidence.Report) string {
	contents, err := BuildFindingsLocalized(g, report, selectedReportLanguage(g, ""))
	if err != nil {
		panic(err)
	}
	return contents
}

// BuildFindingsLocalized creates a locale view from the shared findings and
// review identities. Locale choice never participates in finding identity.
func BuildFindingsLocalized(g *ontology.Graph, report evidence.Report, language string) (string, error) {
	language = selectedReportLanguage(g, language)
	var claimErr error
	contents, err := renderLocalizedReport(language, func(text reportText) string {
		rendered, err := renderFindings(g, report, language, text)
		claimErr = err
		return rendered
	})
	if err != nil {
		return "", err
	}
	if claimErr != nil {
		return "", claimErr
	}
	return contents, nil
}

func renderFindings(g *ontology.Graph, report evidence.Report, language string, text reportText) (string, error) {
	lines := []string{
		text("# FINDINGS.md — Observed evidence requiring attention"),
		"",
		text("> Generated by `hotam evidence`. Finding kinds describe observed discrepancies or execution/source conditions; they do not infer semantic blame or decide a resolver outcome."),
		"",
	}
	if len(report.Findings) == 0 {
		lines = append(lines, text("_This collection produced no findings. That is not a claim of complete coverage; consult EVIDENCE.md for the recorded coverage and limitations._"), "")
	} else {
		lines = append(lines,
			text("| Finding | Kind | Disposition | Review | Requirement | Clause | Case | Test / subject | Target | Producer |"),
			"|---|---|---|---|---|---|---|---|---|---|")
		for _, finding := range report.Findings {
			requirement := requirementFindingLink(g, language, text, finding.RequirementID)
			target := finding.Test
			if target == "" {
				target = finding.Subject
			} else if finding.Subject != "" {
				target += " / " + finding.Subject
			}
			lines = append(lines, "| [`"+Cell(finding.ID)+"`](#finding-"+html.EscapeString(finding.ID)+") | `"+
				Cell(reportStatus(text, finding.Kind))+"` | "+Cell(reportStatus(text, finding.Disposition))+" | `"+
				Cell(reportStatus(text, finding.ReviewStatus))+"` | "+requirement+" | `"+Cell(finding.ClauseID)+
				"` | `"+Cell(finding.CaseID)+"` | "+Cell(target)+" | `"+Cell(finding.Target)+"` | `"+
				Cell(finding.Producer)+"` |")
		}
		lines = append(lines, "")
		for _, finding := range report.Findings {
			claim, err := reportClaim(g, language, finding.RequirementID, finding.Claim, finding.ClaimTexts)
			if err != nil {
				return "", err
			}
			lines = append(lines, "<a id=\"finding-"+html.EscapeString(finding.ID)+"\"></a>",
				text("## Finding `%s`", Cell(finding.ID)), "")
			lines = append(lines,
				"- **"+text("Observed kind")+":** `"+Cell(reportStatus(text, finding.Kind))+"`",
				"- **"+text("Disposition")+":** "+Cell(reportStatus(text, finding.Disposition)),
				"- **"+text("Review status")+":** `"+Cell(reportStatus(text, finding.ReviewStatus))+"`",
				"- **"+text("Requirement")+":** "+requirementFindingLink(g, language, text, finding.RequirementID),
				"- **"+text("Case ID")+":** `"+Cell(finding.CaseID)+"`",
				"- **"+text("Clause ID")+":** `"+Cell(finding.ClauseID)+"`",
				"- **"+text("Test")+":** "+testLink(g, finding.Test),
				"- **"+text("Subject")+":** `"+Cell(finding.Subject)+"`",
				"- **"+text("Target")+":** `"+Cell(finding.Target)+"`",
				"- **"+text("Operation")+":** `"+Cell(finding.Operation)+"`",
				"- **"+text("Producer")+":** `"+Cell(finding.Producer)+"`",
				"- **"+text("Claim")+":** "+Cell(claim))
			for i := range report.Requirements {
				requirement := &report.Requirements[i]
				if requirement.ID != finding.RequirementID {
					continue
				}
				qualification := authoredCoverageLocalized(g, finding.RequirementID, requirement.Rationale, requirement.Profile, text)
				if qualification != text("none declared") {
					lines = append(lines, "- **"+text("Authored coverage declaration")+":** "+Cell(qualification))
				}
				break
			}
			if len(finding.SourceLinks) > 0 {
				lines = append(lines, "- **"+text("Source links")+":**")
				for _, link := range finding.SourceLinks {
					check, ok := sourceCheckForAnchor(report.Sources, link.SourceID, link.Anchor)
					href := ""
					if ok && check.Path != "" {
						href = sourceLink(g, check.Path, link.Anchor)
					}
					if href == "" {
						lines = append(lines, "  - `"+Cell(link.SourceID+"#"+link.Anchor)+"` ("+text("source reference unresolved")+")")
						continue
					}
					lines = append(lines, "  - ["+Cell(link.SourceID+" — "+check.Path+"#"+link.Anchor)+"]("+
						href+")"+anchorSuffix(link.Anchor))
				}
			}
			if len(finding.Observations) == 0 {
				lines = append(lines, "", text("_No detailed observation was attached._"))
			} else {
				lines = append(lines, "",
					text("| Observation | Input | Raw input | Actual | Raw actual | Expected | Raw expected | Verdict |"),
					"|---|---|---|---|---|---|---|---|")
				for _, observation := range finding.Observations {
					verdict := "pass"
					if !observation.Passed {
						verdict = "fail"
					}
					lines = append(lines, "| "+Cell(observation.Name)+" | "+Cell(observation.Input)+" | `"+
						Cell(reportRawValue(observation.RawInput, text))+"` | "+Cell(observation.Actual)+" | `"+
						Cell(reportRawValue(observation.RawActual, text))+"` | "+Cell(observation.Expected)+" | `"+
						Cell(reportRawValue(observation.RawExpected, text))+"` | "+Cell(reportStatus(text, verdict))+" |")
				}
			}
			lines = append(lines, "", text("### Version and execution context"), "",
				text("| Field | Value |"), "|---|---|",
				"| "+text("Implementation")+" | "+Cell(finding.Context.Implementation)+" |",
				"| "+text("Implementation version")+" | "+Cell(finding.Context.ImplementationVersion)+" |",
				"| "+text("Specification version")+" | "+Cell(finding.Context.SpecVersion)+" |",
				"| "+text("Profile")+" | "+Cell(finding.Context.Profile)+" |",
				"| "+text("Operation")+" | "+Cell(finding.Context.Operation)+" |",
				"| "+text("Target")+" | "+Cell(finding.Context.Target)+" |",
				"| "+text("Producer")+" | "+Cell(finding.Context.Producer)+" |",
				"| "+text("Profile selection fingerprint")+" | `"+Cell(finding.Context.ProfileFingerprint)+"` |",
				"| "+text("Producer fingerprint")+" | `"+Cell(finding.Context.ProducerFingerprint)+"` |",
				"| "+text("Case fingerprint")+" | `"+Cell(finding.Context.CaseFingerprint)+"` |",
				"| "+text("Recorded case fingerprint")+" | `"+Cell(finding.Context.RecordedCaseFingerprint)+"` |",
				"| "+text("Declared case fingerprint")+" | `"+Cell(finding.Context.DeclaredCaseFingerprint)+"` |",
				"| "+text("Declared composition")+" | `"+Cell(reportJSON(finding.Context.Composition, text))+"` |",
				"| "+text("Measured components")+" | `"+Cell(reportJSON(finding.Context.MeasuredComponents, text))+"` |",
				"", "---", "")
		}
	}
	return strings.TrimRight(strings.Join(lines, "\n"), " \t\r\n") + "\n", nil
}

func requirementFindingLink(g *ontology.Graph, language string, text reportText, id string) string {
	if id == "" {
		return text("_not associated with a requirement_")
	}
	return "[" + Cell(id) + "](" + localizedReportName(g, "EVIDENCE", language) +
		"#requirement-" + html.EscapeString(id) + ")"
}
