package generator

type glossaryTerm struct {
	Slug       string
	Kind       string
	Definition string
}

var glossaryTerms = []glossaryTerm{
	{Slug: "§Requirement", Kind: "SECTION", Definition: "The requirement node — a claim the system shall satisfy."},
	{Slug: "§Conflict", Kind: "SECTION", Definition: "The first-class connector NODE between requirements, carrying axis+context+resolver."},
	{Slug: "§Assumption", Kind: "SECTION", Definition: "A belief with its own lifecycle (HOLDS/UNCERTAIN/DEAD)."},
	{Slug: "§Axis", Kind: "SECTION", Definition: "A controlled-vocabulary entry naming a tension dimension."},
	{Slug: "§Stakeholder", Kind: "SECTION", Definition: "Accountability facet: who owns a requirement or resolvers a conflict."},
	{Slug: "§Invariants", Kind: "SECTION", Definition: "Structural form of the tension graph (check_* functions)."},
	{Slug: "§Graph", Kind: "SECTION", Definition: "The TensionGraph container + traversal + loader."},
	{Slug: "§Lifecycle", Kind: "SECTION", Definition: "The generic state-machine value-type — keystone for Requirement.status / Conflict.lifecycle / future Operator/Process lifecycles."},
	{Slug: "§Operator", Kind: "SECTION", Definition: "The acting facet of a Stakeholder — owns a sub-domain, carries a context budget, and runs the closed loop."},
	{Slug: "§ContextBudget", Kind: "SECTION", Definition: "The working-store ceiling of an Operator; the substrate is free."},
	{Slug: "§Loop", Kind: "SECTION", Definition: "The closed loop: State→Diagnosis→Next-action→Action→regenerate→State."},
	{Slug: "§Glossary", Kind: "SECTION", Definition: "The methodology's controlled vocabulary (this module)."},
	{Slug: "§Scope", Kind: "SECTION", Definition: "An operator's sub-domain as a PROJECTION (id-set view) over the shared graph, not a copy; overlaps with another operator's projection are computed and rendered, never hidden."},
	{Slug: "§Ticket", Kind: "SECTION", Definition: "A durable on-disk work item (tickets/<status>/T-<n>.md): frontmatter header + Markdown body, mutated only through the ticket_* tools which auto-maintain its status-and-text History."},
	{Slug: "DETECTED", Kind: "LIFECYCLE_STATE", Definition: "A conflict has been surfaced but no resolver action yet."},
	{Slug: "ACKNOWLEDGED", Kind: "LIFECYCLE_STATE", Definition: "Resolver accepts the conflict is real and owns it."},
	{Slug: "DECIDED", Kind: "LIFECYCLE_STATE", Definition: "Resolved with recorded rationale and/or a derived requirement."},
	{Slug: "REVISIT_WHEN", Kind: "LIFECYCLE_STATE", Definition: "Parked with an explicit revisit condition (anti-relitigation)."},
	{Slug: "DRAFT", Kind: "STATUS", Definition: "Proposed, not yet accepted into the canon."},
	{Slug: "SETTLED", Kind: "STATUS", Definition: "Accepted and currently held."},
	{Slug: "OPEN", Kind: "STATUS", Definition: "Accepted-with-a-hole; carries a non-empty question."},
	{Slug: "REJECTED", Kind: "STATUS", Definition: "Withdrawn; kept for history (anti-relitigation)."},
	{Slug: "HOLDS", Kind: "STATUS", Definition: "Assumption currently believed true."},
	{Slug: "UNCERTAIN", Kind: "STATUS", Definition: "Assumption whose truth is unconfirmed."},
	{Slug: "DEAD", Kind: "STATUS", Definition: "Assumption known false — dependents are surfaced as DRIFT_FALLOUT."},
	{Slug: "PROSE", Kind: "STATUS", Definition: "Enforcement level: recorded only, unenforced (soft context-debt)."},
	{Slug: "STRUCTURAL", Kind: "STATUS", Definition: "Enforcement level: visible/addressable but no predicate fires."},
	{Slug: "ENFORCED", Kind: "STATUS", Definition: "Enforcement level: a check_* invariant or test fires on violation."},
	{Slug: "resolver", Kind: "ROLE", Definition: "Holds a conflict; by construction NOT the owner of any of its members."},
	{Slug: "owner", Kind: "ROLE", Definition: "Stakeholder who defends a requirement or an assumption."},
	{Slug: "operator", Kind: "ROLE", Definition: "An acting agent that owns a bounded sub-domain of the graph."},
	{Slug: "latent connector", Kind: "CONCEPT", Definition: "A requirement pair that SHOULD have a Conflict node but doesn't — a heuristic suspicion."},
	{Slug: "DRIFT_FALLOUT", Kind: "CONCEPT", Definition: "A DEAD assumption with live dependents — they must be revisited."},
	{Slug: "crystallize", Kind: "CONCEPT", Definition: "Move knowledge from working context into the durable substrate (graph + invariants + docs)."},
	{Slug: "anchor", Kind: "CONCEPT", Definition: "A stable, short, typed identifier (R-/C-/A-/§) the operator references rather than re-carries."},
	{Slug: "substrate", Kind: "CONCEPT", Definition: "The durable, enforced/regenerable/addressable store — free of context cost."},
	{Slug: "burn-down", Kind: "CONCEPT", Definition: "Promotion of DRAFT requirements to ENFORCED; the methodology's honesty governor."},
	{Slug: "§Proposal", Kind: "SECTION", Definition: "Structured operator-→-resolver change proposals: the closed loop's ACT half."},
	{Slug: "playbook", Kind: "CONCEPT", Definition: "A band-specific procedure the AI operator follows to convert a what_now action into a structured proposal for resolver approval."},
	{Slug: "apply_proposal", Kind: "CONCEPT", Definition: "The mechanical writer (`hotam apply-proposal`) that lands a resolver-approved proposal into the domain's graph.json; the AI never edits the graph by hand."},
	{Slug: "§Closure", Kind: "SECTION", Definition: "Per-action verify: after apply-proposal writes + regens + tests-green, asserts the triggering diagnosis was actually removed."},
	{Slug: "§Tick", Kind: "SECTION", Definition: "The closed-loop diagnostic driver (advisory, M32 conservative): one cycle loads the graph, diagnoses, and emits a TickReport for resolver attention."},
	{Slug: "§Conscience", Kind: "SECTION", Definition: "The Hypothesis property-test sweep over the critical-core invariants (M7) — does my OWN edit introduce a contradiction?"},
	{Slug: "critical core", Kind: "CONCEPT", Definition: "The set of invariants whose violation would silently break the hard boundary or anti-drift — the conscience's narrow scope (M7)."},
	{Slug: "§Constitution", Kind: "SECTION", Definition: "The operator's boot sequence — the generated reconstitution from the substrate's SETTLED laws."},
	{Slug: "§Reflection", Kind: "SECTION", Definition: "The operator self-diagnosis band (P0) — diagnoses the operator's OWN readiness: DRAFT-overhang, UNENFORCED-SETTLED debt, over-budget operators, dead-assumption-on-enforcer, derived-but-unbuilt."},
	{Slug: "§Process", Kind: "SECTION", Definition: "The opt-in behavioral aspect (M12): a Lifecycle + ordered Steps + roles_required + drives_entities — the richest contradiction surface."},
	{Slug: "§Goal", Kind: "SECTION", Definition: "A first-class target-state type (M19): distinct from a static Requirement because it carries a MOVING TARGET that yields a Gap driving a Process."},
	{Slug: "Step", Kind: "CONCEPT", Definition: "One step in a Process — a verb requiring a declared role (requires_role must be in Process.roles_required)."},
	{Slug: "Gap", Kind: "CONCEPT", Definition: "The distance between a Goal's target_state and the current state — drives Process execution and is the measurable work remaining."},
	{Slug: "Target state", Kind: "CONCEPT", Definition: "The desired-state predicate carried by a Goal (kind in TARGET_KINDS: GRAPH_PROPERTY | BUSINESS_STATE | ENTITY_STATE)."},
	{Slug: "three-cipher pulse", Kind: "CONCEPT", Definition: "The operator's per-turn vital-signs: context % + top what_now action + unenforced-SETTLED+DRAFT debt count."},
	{Slug: "boot ritual", Kind: "CONCEPT", Definition: "The per-turn sequence that re-loads the operator from the substrate (go test → what_now → tick → skim UNENFORCED/DECISIONS)."},
	{Slug: "§Context", Kind: "SECTION", Definition: "The operator's working-context fullness measurement — MEASURED from a runtime stamp, never guessed (R-measure-context-size)."},
	{Slug: "§Atoms", Kind: "SECTION", Definition: "The atomized methodology docs generated under docs/methodology/atoms/ from SETTLED requirements grouped by topic."},
	{Slug: "§Agent", Kind: "SECTION", Definition: "A scoped sub-operator directory (domains/<domain>/agents/<name>/) with a scope definition, CLAUDE.md, tools/, agents/, and docs/ subdirectories."},
	{Slug: "§Domain", Kind: "SECTION", Definition: "A self-contained business domain directory (domains/<name>/) with manifest.json, graph.json, tools/, agents/director/, docs/gen/, and CLAUDE.md."},
	{Slug: "§Entity", Kind: "SECTION", Definition: "Domain-declared business concept with its own lifecycle (M12 opt-in aspect): EntityType + EntityField + EntityInstance; check_entity_* covers every declared type by iteration."},
	{Slug: "§Signoff", Kind: "SECTION", Definition: "The frozen provenance payload (decided_by + date + verbatim + instrument + chosen_variant) attached to a node a human resolver decided on; not a node type, a payload like Variant."},
	{Slug: "§Attention", Kind: "SECTION", Definition: "The agent-agnostic registry of attention-codes (ATTENTION_SOURCES): collect() runs the sources and returns typed AttentionSignals. Graph sources are deterministic (the diagnose subset the substrate consumes); runtime-fs sources are injected by the live consumer to form the agent superset."},
}
