package generator

import (
	"fmt"
	"strings"

	"github.com/PHPCraftdream/HotamSpec/internal/diagnose"
	"github.com/PHPCraftdream/HotamSpec/internal/ontology"
)

const hostCharWarn = 130000
const hostCharCap = 150000

var bandLabel = map[int]string{
	0: "REFLECTION",
	1: "STRUCTURE",
	2: "DRIFT_FALLOUT",
	3: "CONFLICT_STALLED",
	4: "OPEN_ITEM",
	5: "LATENT_CONNECTOR",
	6: "PENDING_PROPOSAL",
	7: "ADVISORY",
}

const ctxLineStatic = "context: UNMEASURED — measuring working-context requires host cooperation the framework will not touch (R-work-within-launch-dir); it measures only if the local stdin payload honestly carries ctx_pct — R-unmeasured-cipher-names-host-boundary"

func BuildLiveState(g *ontology.Graph, domainName string, claudeMDCharCount int, today string) string {
	if domainName == "" {
		domainName = "hotam-spec-self"
	}
	signals := diagnose.DiagnoseSignals(g, today)
	var topLine string
	if len(signals) > 0 {
		sig := signals[0]
		// diagnose.Finding.Imperative is domain-agnostic (the diagnose package
		// never carries a domain name — see internal/diagnose/signal.go); a
		// bare "docs/gen/UNENFORCED.md" pointer embedded in a Finding message
		// (internal/diagnose/finding.go ReflectUnenforcedSettled) would resolve
		// to a nonexistent repo-root path once rendered here (every domain's
		// generated docs live under domains/<name>/docs/gen/, never at the repo
		// root — see RenderEmbeddedThinkingBlock / BuildAgentContext's own
		// domainName-qualification of the same pointer pattern). Qualify it at
		// the one point domainName is actually known, the same fix pattern
		// task #103 already applied to this exact call site's sibling
		// (domainPulse's mid-word truncation bug).
		msg := strings.ReplaceAll(sig.Message, "docs/gen/UNENFORCED.md", "domains/"+domainName+"/docs/gen/UNENFORCED.md")
		topLine = fmt.Sprintf("[P%d] %s on `%s` — %s", sig.Priority, bandLabel[sig.Priority], sig.Target, msg)
	} else {
		topLine = "none — graph clean"
	}

	var settledTotal, settledEnforced, draft, openReqs, unenforced int
	for _, r := range g.Requirements {
		if r.Status == ontology.StatusSETTLED {
			settledTotal++
			if r.Enforcement == ontology.EnforcementENFORCED {
				settledEnforced++
			}
			if r.IsCloseableDebt() {
				unenforced++
			}
		}
		if r.Status == ontology.StatusDRAFT {
			draft++
		}
		if r.IsOpen() {
			openReqs++
		}
	}
	debtLine := fmt.Sprintf("%d/%d SETTLED ENFORCED · %d DRAFT · %d OPEN · %d closeable debt (ENFORCEABLE, still PROSE/STRUCTURAL)", settledEnforced, settledTotal, draft, openReqs, unenforced)

	nodes := len(g.Requirements) + len(g.Conflicts) + len(g.Assumptions)
	opBudget := 0
	opMeasure := ontology.BudgetMeasureNODE_COUNT
	if len(g.Operators) > 0 {
		opBudget = g.Operators[0].ContextBudget.Limit
		opMeasure = g.Operators[0].ContextBudget.Measure
	}

	var budgetLine string
	if opMeasure == ontology.BudgetMeasureCRYSTAL_CHARS {
		used := claudeMDCharCount
		budgetLine = fmt.Sprintf("- **graph:** %d nodes (req+conflict+assumption); OP-director budget %d chars (CRYSTAL_CHARS measure) — resident crystal %d chars (headroom %d)", nodes, opBudget, used, opBudget-used)
	} else {
		budgetLine = fmt.Sprintf("- **graph:** %d nodes (req+conflict+assumption); OP-director budget %d nodes (NODE_COUNT measure) (headroom %d)", nodes, opBudget, opBudget-nodes)
	}

	approxSize := claudeMDCharCount
	var crystalLine string
	if approxSize >= hostCharCap {
		crystalLine = fmt.Sprintf("OVER host cap %d chars — split/distill required", hostCharCap)
	} else if approxSize >= hostCharWarn {
		crystalLine = fmt.Sprintf("NEAR — approaching %d char warn threshold (host cap %d)", hostCharWarn, hostCharCap)
	} else {
		crystalLine = fmt.Sprintf("OK — under %d char warn threshold (host cap %d)", hostCharWarn, hostCharCap)
	}

	lines := []string{
		"### Live state (autogenerated by `hotam gen-spec` — do not hand-edit)",
		"",
		fmt.Sprintf("- **top action:** %s", topLine),
		fmt.Sprintf("- **debt:** %s", debtLine),
		budgetLine,
		fmt.Sprintf("- **crystal:** %s", crystalLine),
		fmt.Sprintf("- %s", ctxLineStatic),
	}
	return strings.Join(lines, "\n")
}
