package generator

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/PHPCraftdream/HotamSpec/internal/conformance"
	"github.com/PHPCraftdream/HotamSpec/internal/localization"
	"github.com/PHPCraftdream/HotamSpec/internal/ontology"
	"github.com/PHPCraftdream/HotamSpec/internal/source"
)

type reportText func(sourceTemplate string, args ...any) string

func renderLocalizedReport(language string, render func(reportText) string) (string, error) {
	var contents string
	text := reportText(func(sourceTemplate string, args ...any) string {
		return localization.Text(language, sourceTemplate, args...)
	})
	err := localization.SafeRender(func() error {
		contents = render(text)
		return nil
	})
	if err != nil {
		return "", err
	}
	return contents, nil
}

func selectedReportLanguage(g *ontology.Graph, language string) string {
	if language != "" || g == nil {
		return language
	}
	if g.RenderLanguage != "" {
		return g.RenderLanguage
	}
	if g.DefaultLanguage != "" {
		return g.DefaultLanguage
	}
	if len(g.Languages) == 1 {
		return g.Languages[0]
	}
	return ""

}

const (
	evidenceBannerTitle      = "# EVIDENCE.md — Current verification evidence"
	evidenceBannerProvenance = "> Generated by `hotam evidence`. This report records observed checks; it is not a normative specification and does not assign semantic blame."
	findingsBannerTitle      = "# FINDINGS.md — Observed evidence requiring attention"
	findingsBannerProvenance = "> Generated by `hotam evidence`. Finding kinds describe observed discrepancies or execution/source conditions; they do not infer semantic blame or decide a resolver outcome."
)

// IsGeneratedEvidence recognizes only this generator's exact localized title
// and provenance banner, so publication never claims an unrelated document.
func IsGeneratedEvidence(contents string) bool {
	if strings.HasPrefix(contents, evidenceCaseMarker) {
		if _, err := readEvidenceCaseIntegrity(contents); err != nil {
			return false
		}
		_, contents, _ = strings.Cut(contents, "\n")
	}
	return generatedReportBannerMatches(contents, evidenceBannerTitle, evidenceBannerProvenance)
}

// IsGeneratedFindings recognizes only this generator's exact localized title
// and provenance banner, so publication never claims an unrelated document.
func IsGeneratedFindings(contents string) bool {
	return generatedReportBannerMatches(contents, findingsBannerTitle, findingsBannerProvenance)
}

func generatedReportBannerMatches(contents, titleTemplate, provenanceTemplate string) bool {
	lines := strings.SplitN(contents, "\n", 4)
	if len(lines) < 3 || lines[1] != "" {
		return false
	}
	for _, language := range []string{"", "en", "ru", "zh"} {
		title, titleErr := localization.Lookup(language, titleTemplate)
		provenance, provenanceErr := localization.Lookup(language, provenanceTemplate)
		if titleErr == nil && provenanceErr == nil && lines[0] == title && lines[2] == provenance {
			return true
		}
	}
	return false
}

func reportClaim(g *ontology.Graph, language, requirementID, claim string, claims ontology.LocalizedText) (string, error) {
	if requirementID == "" {
		return claim, nil
	}
	if len(claims) > 0 {
		if text, ok := claims[language]; ok && strings.TrimSpace(text) != "" {
			return text, nil
		}
		return "", fmt.Errorf("requirement %q has no authored claim text for language %q", requirementID, language)
	}
	if g != nil && len(g.Languages) > 1 {
		return "", fmt.Errorf("requirement %q has no localized claim text for multilingual evidence view %q", requirementID, language)
	}
	return claim, nil
}

func reportStatus(text reportText, value string) string {
	switch value {
	case "verified", "retired", "discrepancy", "unsupported_recommendation", "unreachable", "unverified",
		"missing", "drift", "invalid", "pass", "fail", "skip", "violation", "qualification",
		"decomposed", "missing_decomposition", "incomplete_sides", "report_only", "report_only_discrepancy",
		"not_applicable", "unsupported", "optional", "verified_case", "applicable", "declared_unselected",
		"witnessed", "unwitnessed", "declared", "unselected", "unmeasured", "changed", "measured_match",
		"unreviewed", "test_failure", "execution_unavailable", "source_drift", "conformance_audit", "unproved":
		return text(value)
	case "not_declared":
		return text("not declared")
	default:
		return value
	}
}

func authoredQualificationLocalized(text reportText, rationale, profile string) string {
	parts := make([]string, 0, 2)
	if strings.TrimSpace(rationale) != "" {
		parts = append(parts, text("rationale: %s", rationale))
	}
	if strings.TrimSpace(profile) != "" {
		parts = append(parts, text("profile: %s", profile))
	}
	if len(parts) == 0 {
		return text("none declared")
	}
	return strings.Join(parts, "; ")
}

func authoredCoverageLocalized(g *ontology.Graph, id, rationale, profile string, text reportText) string {
	var status string
	if g != nil {
		for _, requirement := range g.Requirements {
			if requirement.ID == id && requirement.Coverage != nil {
				status = requirement.Coverage.Status
				break
			}
		}
	}
	if status == "" {
		return authoredQualificationLocalized(text, rationale, profile)
	}
	parts := []string{text("status: %s", reportStatus(text, status))}
	if strings.TrimSpace(rationale) != "" {
		parts = append(parts, text("rationale: %s", rationale))
	}
	if strings.TrimSpace(profile) != "" {
		parts = append(parts, text("profile: %s", profile))
	}
	return strings.Join(parts, "; ")
}

func sourceCheckForAnchor(checks []source.Check, sourceID, anchor string) (source.Check, bool) {
	var fallback source.Check
	foundFallback := false
	for _, check := range checks {
		if check.SourceID != sourceID {
			continue
		}
		if check.Anchor == anchor {
			return check, true
		}
		if check.Anchor == "" && !foundFallback {
			fallback = check
			foundFallback = true
		}
	}
	return fallback, foundFallback
}

func hasConformanceData(report conformance.Report) bool {
	return report.InventoryDeclared != 0 || len(report.Clauses) != 0 || len(report.Cases) != 0 ||
		len(report.Profiles) != 0 || len(report.Precedence) != 0 || len(report.Compositions) != 0 ||
		len(report.Issues) != 0
}

func localizedReportName(g *ontology.Graph, base, language string) string {
	if g != nil && len(g.Languages) > 1 {
		return base + "." + language + ".md"
	}
	return base + ".md"
}
func reportRawValue(value *ontology.ObservedValue, text reportText) string {
	if value == nil {
		return text("absent")
	}
	data, err := json.Marshal(value)
	if err != nil {
		return text("unavailable")
	}
	return string(data)
}

func reportJSON(value any, text reportText) string {
	data, err := json.Marshal(value)
	if err != nil {
		return text("unavailable")
	}
	return string(data)
}
