// models.go renders docs/gen/MODELS.md: the generated navigational overview
// PLAN-authored-spec-discipline.md §7 names for a domain's authored object
// model -- "обзор authored-моделей (структуры/поля/методы/инварианты,
// извлечённые из spec/model через go/ast)". It exists so an agent or human
// can see, at a glance, WHAT objects a domain's hand-written spec/ tree
// declares -- their fields, their methods, and their typed sentinel errors
// -- without opening every file under spec/model by hand.
//
// LAYERING (W2.4): the AST model SCAN itself (which files to parse, how to
// extract objects/fields/methods, the vendored-recorder exclusion) moved to
// internal/gate/model_scan.go -- see that file's own LAYERING doc comment
// for the full reasoning (same W2.3 spec_build.go precedent: the scan is
// shared with internal/invariants' new check_model_complete gate, W2.4, and
// internal/invariants must never import internal/generator). This file now
// holds ONLY the RENDERING of MODELS.md plus the public count wrapper
// (ScanModelLayerCounts) coverage.go consumes: thin type aliases over
// gate's scan types and a thin re-export of IsVendoredRecorderFile (kept so
// internal/generator's own models_vendor_exclusion_test.go, package
// generator, can still call it by its lowercase name without reaching
// across the package boundary). Behavior is byte-identical to before the
// move -- internal/generator/models_vendor_exclusion_test.go and
// byteidentical_test.go's MODELS.md golden are the mechanical proof.
//
// This file is read-only over both the graph and the filesystem: it renders
// what gate.ScanAuthoredModels inventories. It never executes, type-checks,
// or mutates anything it reads, and it is not an enforcement gate -- that
// role belongs to the mechanical checks in internal/invariants; this doc is
// display-only.
package generator

import (
	"strings"

	"github.com/PHPCraftdream/HotamSpec/internal/gate"
	"github.com/PHPCraftdream/HotamSpec/internal/ontology"
)

// The scan-inventory types are thin aliases over gate's exported types so
// BuildModels's rendering body (and any in-package caller) reads the exact
// same shape the scan produces, with zero conversion at the call site. They
// stay lowercase to preserve this file's pre-move public surface (no
// external package referenced them; only BuildModels/ScanModelLayerCounts
// are part of generator's public API).
type modelObject = gate.ModelObject
type modelField = gate.ModelField
type modelMethod = gate.ModelMethod
type modelError = gate.ModelError
type modelFile = gate.ModelFile

// isVendoredRecorderFile re-exports gate.IsVendoredRecorderFile under the
// lowercase name internal/generator/models_vendor_exclusion_test.go already
// calls it by (that test is package generator, so it reaches unexported
// names directly -- the rename keeps the test unchanged). The canonical,
// shared implementation lives in gate (single choke point both
// generator and invariants funnel through); this wrapper is a zero-cost
// re-export, not a second copy.
func isVendoredRecorderFile(path string) bool {
	return gate.IsVendoredRecorderFile(path)
}

// BuildModels renders docs/gen/MODELS.md: an object model overview --
// objects (structs/types) -> their fields -> their methods -> their typed
// sentinel errors -- extracted via go/ast from a domain's authored spec/
// tree (PLAN-authored-spec-discipline.md §7).
//
// Source selection differs by domain kind:
//
//   - An ORDINARY (non-self-hosting) domain is scanned by walking
//     SpecRootForGraph(g)/spec/ on disk (the domain's own authored model
//     code, e.g. domains/prat/spec/model/*.go) -- every *.go file under
//     spec/ EXCEPT *_test.go.
//   - A SELF-HOSTING domain (g.SelfHosting == true, e.g. hotam-spec-self)
//     has no authored spec/ tree of its own -- its "code" IS the engine.
//     Dumping the whole internal/ tree would bury the navigation value this
//     doc exists for, so only the FILES NAMED BY implemented_by/verified_by
//     entries on this domain's own requirements are parsed -- a focused
//     slice of engine types the discipline itself points at, resolved
//     against gate.SpecRootForGraph(g) exactly as the mechanical gate does.
//
// Output is fully deterministic (files, objects, fields, methods, and
// errors are all sorted) so re-running against an unchanged spec/ tree
// yields byte-identical output.
func BuildModels(g *ontology.Graph) string {
	lines := []string{Banner, ReaderHeaderLine("MODELS", g), ""}
	lines = append(lines, "# MODELS.md — authored object model overview (Hotam-Spec)")
	lines = append(lines, "")
	lines = append(lines,
		"Generated by parsing this domain's authored `spec/` tree with `go/ast` "+
			"(PLAN-authored-spec-discipline.md §7): objects (structs/types), their "+
			"fields, their methods, and their typed sentinel errors, in general -> "+
			"specific order. Read-only overview -- it does not execute or "+
			"type-check the source, only inventories declarations.")
	lines = append(lines, "")

	if g.IsEmpty() {
		lines = append(lines, EmptyNotice)
		lines = append(lines, "")
		return strings.TrimRight(strings.Join(lines, "\n"), " \t\r\n") + "\n"
	}

	files, scanErr := gate.ScanAuthoredModels(g)

	if scanErr != nil {
		lines = append(lines, "_MODELS.md could not be generated: "+scanErr.Error()+"_")
		lines = append(lines, "")
		return strings.TrimRight(strings.Join(lines, "\n"), " \t\r\n") + "\n"
	}

	if len(files) == 0 {
		if g.SelfHosting {
			lines = append(lines, "_No requirement in this domain names an `implemented_by`/`verified_by` engine file yet -- the self-hosting object-model slice (PLAN-authored-spec-discipline.md §9) has nothing to show until authored links exist._")
		} else {
			lines = append(lines, "_No authored `spec/` model files found for this domain yet (PLAN-authored-spec-discipline.md §3/§8 step 3) -- this doc will populate once `spec/model/*.go` exists._")
		}
		lines = append(lines, "")
		return strings.TrimRight(strings.Join(lines, "\n"), " \t\r\n") + "\n"
	}

	totalObjects, totalErrors := 0, 0
	for _, f := range files {
		totalObjects += len(f.Objects)
		totalErrors += len(f.Errors)
	}
	lines = append(lines,
		"**"+itoa(len(files))+" file(s) scanned; "+itoa(totalObjects)+" object(s); "+itoa(totalErrors)+" typed error(s).**")
	lines = append(lines, "")
	lines = append(lines, "---")
	lines = append(lines, "")

	for _, f := range files {
		lines = append(lines, "## `"+f.RelPath+"`")
		lines = append(lines, "")
		if f.Pkg != "" {
			lines = append(lines, "package `"+f.Pkg+"`")
			lines = append(lines, "")
		}

		if len(f.Objects) == 0 && len(f.Errors) == 0 {
			lines = append(lines, "_No exported objects or typed errors in this file._")
			lines = append(lines, "")
			continue
		}

		for _, obj := range f.Objects {
			lines = append(lines, "### `"+obj.Name+"` ("+obj.Kind+")")
			lines = append(lines, "")
			if obj.Doc != "" {
				lines = append(lines, Cell(obj.Doc))
				lines = append(lines, "")
			}
			if len(obj.Fields) > 0 {
				lines = append(lines, "**Fields:**")
				lines = append(lines, "")
				lines = append(lines, "| field | type |")
				lines = append(lines, "|---|---|")
				for _, fld := range obj.Fields {
					lines = append(lines, "| `"+fld.Name+"` | `"+fld.Typ+"` |")
				}
				lines = append(lines, "")
			}
			if len(obj.Methods) > 0 {
				lines = append(lines, "**Methods:**")
				lines = append(lines, "")
				for _, m := range obj.Methods {
					lines = append(lines, "- `"+m.Signature+"`")
					if m.Doc != "" {
						lines = append(lines, "  "+Cell(m.Doc))
					}
				}
				lines = append(lines, "")
			}
		}

		if len(f.Errors) > 0 {
			lines = append(lines, "**Typed errors:**")
			lines = append(lines, "")
			lines = append(lines, "| name | doc |")
			lines = append(lines, "|---|---|")
			for _, e := range f.Errors {
				lines = append(lines, "| `"+e.Name+"` | "+Cell(e.Doc)+" |")
			}
			lines = append(lines, "")
		}
	}

	return strings.TrimRight(strings.Join(lines, "\n"), " \t\r\n") + "\n"
}

// ModelLayerCounts is the structural inventory COVERAGE.md (§4's layer
// progression: models -> fields -> methods -> tests) reads from the SAME
// go/ast scan BuildModels performs (now gate.ScanAuthoredModels), so the two
// projections never disagree about how many objects/fields/methods a
// domain's authored spec/ tree declares. Purely a count -- no rendering
// concern lives here.
type ModelLayerCounts struct {
	Files   int
	Objects int
	Fields  int
	Methods int
	Errors  int
}

// ScanModelLayerCounts runs the same source selection BuildModels uses
// (gate.ScanAuthoredModels: ordinary domain -> spec/ on disk; self-hosting
// domain -> the focused implemented_by/verified_by-named engine file slice)
// and reduces it to counts only. Returns the zero value, not an error, when
// spec/ does not exist yet or no authored links name engine files yet --
// mirroring BuildModels's own "nothing to show" branches (a calm, expected
// state, not a scan failure).
func ScanModelLayerCounts(g *ontology.Graph) (ModelLayerCounts, error) {
	files, err := gate.ScanAuthoredModels(g)
	if err != nil {
		return ModelLayerCounts{}, err
	}

	var c ModelLayerCounts
	c.Files = len(files)
	for _, f := range files {
		c.Errors += len(f.Errors)
		for _, obj := range f.Objects {
			c.Objects++
			c.Fields += len(obj.Fields)
			c.Methods += len(obj.Methods)
		}
	}
	return c, nil
}

// itoa is a tiny local wrapper so this file does not need to import
// strconv solely for one-off int-to-string conversions in the summary line.
func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	neg := n < 0
	if neg {
		n = -n
	}
	var buf [20]byte
	i := len(buf)
	for n > 0 {
		i--
		buf[i] = byte('0' + n%10)
		n /= 10
	}
	if neg {
		i--
		buf[i] = '-'
	}
	return string(buf[i:])
}
